import { approval, area, date, docs, f, leaf, money, multi, num, ref, register, select, status, text } from '../dsl';
import type { AppConfig } from '../types';

const P8 = ['Skyline', 'Riverside', 'Greenfield', 'Metro Tower', 'Lakeview', 'Orbit TP', 'Harbour View', 'Sunrise'];
const CLAIM_TYPES = ['Delay', 'Extension of Time', 'Variation-related', 'Additional Cost', 'Disruption', 'Acceleration', 'Client Default', 'Force Majeure'];
const EVIDENCE = ['Correspondence', 'Site Records', 'Photos', 'Progress Records', 'Cost Records'];
const REASONS = [
  'Delayed drawings / approvals',
  'Late handover of site',
  'Client-instructed scope change',
  'Suspension of work by client',
  'Price escalation beyond PVC cap',
  'Acceleration instructed by client',
  'Delayed payment by client',
  'Exceptional rainfall / cyclone',
  'Unforeseen ground conditions',
  'Statutory authority delay',
  'Access restrictions',
  'Utility shifting delay',
];

/* ── claims (index-aligned so CLM-001 … CLM-014 read consistently across pages) ── */
const CLM_TITLES = [
  'Prolongation costs — late structural drawings, Tower B',
  'EOT for delayed site handover — Phase 2',
  'Additional cost — client-instructed clubhouse redesign',
  'Idle labour & plant — work suspension by client',
  'Steel price escalation beyond PVC cap',
  'Acceleration to meet revised handover date',
  'Interest on delayed RA bill payments',
  'Cyclone — site shutdown and damage to works',
  'Unforeseen rock strata — foundation redesign',
  'Delay in fire NOC and statutory approvals',
  'Disruption due to restricted site access hours',
  'Utility shifting delay — HT line relocation',
  'Loss of productivity — out-of-sequence works',
  'Variation-linked EOT — façade specification change',
];
const CLM_TYPE = ['Delay', 'Extension of Time', 'Variation-related', 'Disruption', 'Additional Cost', 'Acceleration', 'Client Default', 'Force Majeure', 'Additional Cost', 'Extension of Time', 'Disruption', 'Delay', 'Disruption', 'Variation-related'];
const CLM_REASON = [REASONS[0], REASONS[1], REASONS[2], REASONS[3], REASONS[4], REASONS[5], REASONS[6], REASONS[7], REASONS[8], REASONS[9], REASONS[10], REASONS[11], REASONS[0], REASONS[2]];
// 6 open (2 Submitted, 2 Under Review, 2 Negotiation) · 3 Settled · 2 Approved · 1 Partially Approved · 1 Rejected · 1 Draft
const CLM_STATUS = ['Negotiation', 'Under Review', 'Settled', 'Submitted', 'Approved', 'Negotiation', 'Settled', 'Partially Approved', 'Under Review', 'Submitted', 'Rejected', 'Approved', 'Draft', 'Settled'];
const code = (i: number) => `CLM-${String(i + 1).padStart(3, '0')}`;

/* EOT per claim (days) — only claims with a time component */
const EOT_IDX = [0, 1, 2, 3, 7, 8, 9, 10, 11, 12, 13];
const EOT_CLAIMED = [64, 45, 28, 21, 18, 35, 30, 14, 26, 12, 25]; // 318
const EOT_GRANTED = [38, 24, 21, 0, 12, 0, 0, 0, 26, 0, 25]; // 146
const CLAIMED = [8.4, 2.6, 6.9, 5.2, 2.1, 1.8, 3.4, 1.4]; // 31.8
const APPROVED = [3.1, 1.2, 1.4, 2.0, 0.4, 0.9, 0.4, 0.2]; // 9.6

export const claimsApp: AppConfig = {
  id: 'claims',
  name: 'Claims',
  icon: 'ti-scale',
  description: 'Contractual claims — registration, evidence, cost & time impact, submission, negotiation, approval and settlement',
  menus: [
    leaf('Claim Registration', 'ti-file-description', register('clmClaim', { views: ['table', 'board'], tabs: { field: 'status', values: ['Draft', 'Submitted', 'Under Review', 'Negotiation', 'Approved', 'Settled', 'Rejected'] } })),
    leaf('Claim Type', 'ti-category', register('clmType')),
    leaf('Claim Reason', 'ti-message-question', register('clmReason')),
    leaf('Supporting Documents', 'ti-files', docs(['Notices', 'Contract Clauses', 'Drawings & Instructions', 'Claim Submissions', 'Expert Reports'], undefined, 'Claim Supporting Documents')),
    leaf('Cost Impact', 'ti-coins', {
      type: 'analysis',
      title: 'Cost Impact of Claims',
      kpis: [
        { label: 'Total claimed (FY)', value: '₹ 31.8 Cr', icon: 'ti-scale', sub: '14 claims registered' },
        { label: 'Open claims value', value: '₹ 14.2 Cr', icon: 'ti-hourglass', sub: '6 open · 2 under negotiation' },
        { label: 'Approved / settled', value: '₹ 9.6 Cr', progress: 30, icon: 'ti-circle-check' },
        { label: 'Rejected / written off', value: '₹ 6.1 Cr', icon: 'ti-circle-x', sub: 'Incl. partial disallowances' },
        { label: 'Recovery rate (closed)', value: '61%', delta: '+7 pts vs FY 25-26', up: true, icon: 'ti-percentage' },
      ],
      charts: [
        { title: 'Claimed vs Approved by Project (₹ Cr)', kind: 'bar', categories: P8, series: [{ name: 'Claimed', data: CLAIMED }, { name: 'Approved', data: APPROVED }], unit: '₹Cr', span: 2 },
        { title: 'Claimed Value by Cost Head', kind: 'donut', categories: ['Site overheads (prolongation)', 'Idle labour & plant', 'Material escalation', 'Additional works', 'HO overheads', 'Finance charges'], series: [{ name: '₹ Cr', data: [9.4, 6.8, 5.9, 4.6, 3.1, 2.0] }], unit: '₹Cr' },
        { title: 'Claim Build-up — CLM-001 Prolongation (₹ L)', kind: 'waterfall', categories: ['Site overheads', 'Idle plant', 'Idle labour', 'HO overheads', 'Finance charges', 'Profit', 'Total claim'], series: [{ name: 'Claim', data: [184, 96, 72, 88, 26, 20, 0] }], unit: '₹L', span: 2 },
        { title: 'Claims Value by Type (₹ Cr)', kind: 'hbar', categories: CLAIM_TYPES, series: [{ name: 'Claimed', data: [5.8, 3.2, 6.1, 6.4, 4.7, 2.3, 1.2, 2.1] }], unit: '₹Cr' },
      ],
      table: {
        title: 'Claim Cost Summary',
        columns: [
          { key: 'claim', label: 'Claim No.', type: 'code' },
          { key: 'title', label: 'Claim' },
          { key: 'type', label: 'Type' },
          { key: 'claimed', label: 'Claimed', type: 'currency' },
          { key: 'certified', label: 'Consultant Certified', type: 'currency' },
          { key: 'approved', label: 'Approved', type: 'currency' },
          { key: 'status', label: 'Status', type: 'status' },
        ],
        rows: [0, 2, 4, 3, 8, 5, 7, 11].map((i, k) => ({
          claim: code(i),
          title: CLM_TITLES[i],
          type: CLM_TYPE[i],
          claimed: [48600000, 42800000, 38200000, 31400000, 26500000, 22600000, 18900000, 14200000][k],
          certified: [36200000, 31500000, 29800000, 0, 0, 16400000, 11200000, 14200000][k],
          approved: [0, 29000000, 27400000, 0, 0, 0, 9800000, 12600000][k],
          status: CLM_STATUS[i],
        })),
      },
    }),
    leaf('Time Impact', 'ti-hourglass', {
      type: 'analysis',
      title: 'Time Impact — Extension of Time',
      kpis: [
        { label: 'EOT claimed', value: '318 days', icon: 'ti-calendar-plus', sub: 'Across 11 claims' },
        { label: 'EOT granted', value: '146 days', progress: 46, icon: 'ti-calendar-check' },
        { label: 'EOT pending decision', value: '145 days', icon: 'ti-hourglass', sub: '6 claims' },
        { label: 'EOT disallowed', value: '27 days', icon: 'ti-calendar-x' },
        { label: 'LD exposure mitigated', value: '₹ 4.2 Cr', delta: '+₹ 1.1 Cr', up: true, icon: 'ti-shield-check' },
      ],
      charts: [
        { title: 'EOT Days by Claim — Claimed vs Granted', kind: 'hbar', categories: EOT_IDX.map((i) => code(i)), series: [{ name: 'Claimed', data: EOT_CLAIMED }, { name: 'Granted', data: EOT_GRANTED }], unit: 'days', span: 2, height: 300 },
        { title: 'Delay Responsibility (days claimed)', kind: 'donut', categories: ['Client', 'Consultant', 'Statutory authority', 'Neutral (weather)'], series: [{ name: 'Days', data: [162, 64, 56, 36] }], unit: 'days' },
        { title: 'Cumulative EOT — Claimed vs Granted (days)', kind: 'line', categories: ['Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep'], series: [{ name: 'Claimed', data: [96, 142, 188, 236, 281, 318] }, { name: 'Granted', data: [21, 45, 71, 97, 122, 146] }], unit: 'days', span: 3 },
      ],
      table: {
        title: 'Extension of Time Register',
        columns: [
          { key: 'claim', label: 'Claim No.', type: 'code' },
          { key: 'title', label: 'Delay Event' },
          { key: 'claimed', label: 'EOT Claimed (days)', type: 'number' },
          { key: 'granted', label: 'EOT Granted (days)', type: 'number' },
          { key: 'critical', label: 'Critical Path' },
          { key: 'notice', label: 'Notice Issued', type: 'date' },
          { key: 'status', label: 'Status', type: 'status' },
        ],
        rows: EOT_IDX.map((i, k) => ({
          claim: code(i),
          title: CLM_TITLES[i],
          claimed: EOT_CLAIMED[k],
          granted: EOT_GRANTED[k],
          critical: ['Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'Yes'][k],
          notice: ['2026-03-18', '2026-04-02', '2026-02-11', '2026-05-06', '2025-12-09', '2026-06-14', '2026-07-21', '2026-06-30', '2026-01-27', '2026-08-19', '2026-03-05'][k],
          status: CLM_STATUS[i],
        })),
      },
    }),
    leaf('Evidence', 'ti-folder-search', docs(EVIDENCE, undefined, 'Claim Evidence')),
    leaf('Submission', 'ti-send', register('clmSubmission')),
    leaf('Negotiation', 'ti-messages', {
      type: 'timeline',
      title: 'Negotiation History — CLM-001 Prolongation costs, Tower B',
      subject: 'clmClaim',
      events: [
        { date: '2026-04-18', title: 'Claim submitted (Rev 0)', actor: 'Harish V — Commercial Manager', text: 'Prolongation claim for 64 days: site overheads, idle plant & labour, HO overheads (Hudson formula) and finance charges.', status: 'Submitted', amount: 48600000 },
        { date: '2026-05-22', title: 'Client response — partial acceptance', actor: 'Ramesh Iyer — ABC Builders Pvt Ltd', text: 'Client accepts 38 days as excusable delay; disputes HO overhead computation and idle plant hire records.', status: 'Under Review', amount: 21400000 },
        { date: '2026-06-10', title: 'Counterclaim raised by client', actor: 'Ramesh Iyer — ABC Builders Pvt Ltd', text: 'LD counterclaim for 18 days slippage on Tower A slab cycle, ₹ 62 L.', status: 'Disputed', amount: 6200000 },
        { date: '2026-07-02', title: 'Revised claim submitted (Rev 1)', actor: 'Harish V — Commercial Manager', text: 'HO overheads recomputed using Emden formula; idle plant restricted to certified hire logs; counterclaim rebutted with RFI log.', status: 'Submitted', amount: 41200000 },
        { date: '2026-08-05', title: 'Negotiation meeting — Round 1', actor: 'Siddharth Rao / Ramesh Iyer', text: 'Client offer ₹ 2.95 Cr against contractor position ₹ 3.90 Cr. Consultant to verify site overhead records.', status: 'Negotiation', amount: 29500000 },
        { date: '2026-09-12', title: 'Negotiation meeting — Round 2', actor: 'Siddharth Rao / Ramesh Iyer', text: 'Counterclaim withdrawn subject to full & final settlement at ₹ 3.45 Cr and 38 days EOT.', status: 'Negotiation', amount: 34500000 },
        { date: '2026-09-26', title: 'Settlement proposal sent for management approval', actor: 'Arun S — Director Contracts', text: 'Recommended acceptance: recovery 71% of revised claim, LD exposure of ₹ 62 L eliminated.', status: 'Pending Approval' },
      ],
    }),
    leaf('Approval / Rejection', 'ti-gavel', approval('clmClaim', ['Commercial Review', 'Legal Review', 'Management', 'Client Decision'])),
    leaf('Settlement', 'ti-cash', register('clmSettlement')),
  ],
  dashboard: {
    flow: [
      { label: 'Registered', value: '14 claims · ₹ 31.8 Cr' },
      { label: 'Submitted', value: '12 to clients' },
      { label: 'Under Review', value: '2 claims' },
      { label: 'Negotiation', value: '2 · ₹ 7.1 Cr' },
      { label: 'Settled', value: '3 · ₹ 5.8 Cr' },
    ],
    kpis: [
      { label: 'Open Claims', value: '6', sub: '₹ 14.2 Cr under process', icon: 'ti-scale', progress: 43 },
      { label: 'Under Negotiation', value: '2', sub: '₹ 7.1 Cr claimed', icon: 'ti-messages' },
      { label: 'Total Claimed (FY)', value: '₹ 31.8 Cr', delta: '+₹ 4.2 Cr', up: true, icon: 'ti-file-description' },
      { label: 'Approved / Settled', value: '₹ 9.6 Cr', delta: '+₹ 2.3 Cr', up: true, icon: 'ti-circle-check', progress: 30 },
      { label: 'Recovery Rate', value: '61%', delta: '+7 pts', up: true, icon: 'ti-percentage' },
      { label: 'EOT Pending', value: '145 days', sub: '146 days granted', icon: 'ti-hourglass' },
    ],
    charts: [
      { title: 'Claimed vs Approved by Project (₹ Cr)', kind: 'bar', categories: P8, series: [{ name: 'Claimed', data: CLAIMED }, { name: 'Approved', data: APPROVED }], unit: '₹Cr', span: 2 },
      { title: 'Claims by Type', kind: 'donut', categories: CLAIM_TYPES, series: [{ name: 'Claims', data: [2, 2, 2, 2, 3, 1, 1, 1] }], subtitle: '14 claims' },
      { title: 'Claim Pipeline (₹ Cr)', kind: 'funnel', categories: ['Claimed', 'Submitted', 'Consultant certified', 'Approved', 'Paid'], series: [{ name: '₹ Cr', data: [31.8, 29.6, 18.4, 9.6, 5.8] }], unit: '₹Cr' },
    ],
    table: { entity: 'clmClaim', title: 'Claims Register', columns: ['title', 'project', 'claimType', 'claimValue', 'eotDays', 'status'], limit: 6 },
    rail: [
      {
        kind: 'health',
        title: 'Claim Status',
        items: [
          { label: 'Submitted / Under Review', value: 4, tone: 'yellow' },
          { label: 'Negotiation', value: 2, tone: 'blue' },
          { label: 'Approved / Settled', value: 6, tone: 'green' },
          { label: 'Rejected', value: 1, tone: 'red' },
          { label: 'Draft', value: 1, tone: 'gray' },
        ],
      },
      {
        kind: 'list',
        title: 'Under Negotiation',
        items: [
          { title: `${code(0)} — ${CLM_TITLES[0]}`, sub: 'Round 2 held 12 Sep · offer ₹ 3.45 Cr', meta: 'Delay', status: 'Negotiation' },
          { title: `${code(5)} — ${CLM_TITLES[5]}`, sub: 'Client counter-offer awaited', meta: 'Acceleration', status: 'Negotiation' },
        ],
      },
      {
        kind: 'dates',
        title: 'Response Deadlines',
        items: [
          { date: '2026-10-03', title: 'Client response due — CLM-002', sub: 'EOT for delayed site handover' },
          { date: '2026-10-08', title: 'Rev 1 submission — CLM-009', sub: 'Unforeseen rock strata' },
          { date: '2026-10-14', title: 'Negotiation Round 1 — CLM-006', sub: 'Acceleration claim' },
          { date: '2026-10-21', title: 'Notice period expiry — CLM-013', sub: 'Draft claim — file before deadline' },
        ],
      },
    ],
  },
  entities: [
    {
      id: 'clmClaim',
      label: 'Claim',
      plural: 'Claims',
      app: 'claims',
      codePrefix: 'CLM',
      titleField: 'title',
      count: 14,
      form: 'wizard',
      info: 'Claims must be notified within the contractual notice period (GCC Cl. 44). Attach correspondence, site records and cost records as evidence before submission.',
      sections: [
        { id: 'details', title: 'Claim Details', icon: 'ti-file-description' },
        { id: 'type', title: 'Type & Reason', icon: 'ti-category' },
        { id: 'impact', title: 'Cost & Time Impact', icon: 'ti-coins' },
        { id: 'evidence', title: 'Evidence', icon: 'ti-folder-search' },
      ],
      fields: [
        text('title', 'Claim Title', CLM_TITLES, { required: true, section: 'details' }),
        ref('project', 'Project', 'project', { required: true, section: 'details' }),
        text('contractRef', 'Contract Ref.', ['CON-001', 'CON-003', 'CON-004', 'CON-002', 'CON-001', 'CON-004', 'CON-003', 'CON-007', 'CON-005', 'CON-007', 'CON-006', 'CON-003', 'CON-008', 'CON-004'], { section: 'details', list: false }),
        date('eventDate', 'Event Date', [-320, -25], { required: true, section: 'details' }),
        date('noticeDate', 'Notice Date', [-300, -15], { section: 'details', list: false }),
        ref('preparedBy', 'Prepared By', 'employee', { section: 'details', list: false }),
        status(['Draft', 'Submitted', 'Under Review', 'Negotiation', 'Approved', 'Partially Approved', 'Rejected', 'Settled'], { section: 'details', gen: CLM_STATUS }),
        select('claimType', 'Claim Type', CLAIM_TYPES, { required: true, section: 'type', gen: CLM_TYPE }),
        select('reason', 'Claim Reason', REASONS, { required: true, section: 'type', gen: CLM_REASON }),
        text('clause', 'Contract Clause', ['GCC 44.1', 'GCC 28.2', 'GCC 51.1', 'GCC 40.2', 'SCC 47 (PVC)', 'GCC 28.3', 'GCC 60.8', 'GCC 66.1', 'GCC 12.2', 'GCC 44.1(e)', 'GCC 42.1', 'GCC 44.1(h)', 'GCC 44.1', 'GCC 51.2'], { section: 'type', list: false }),
        area('description', 'Claim Narrative', [
          'Structural drawings for Tower B were issued 64 days after the date in the drawing schedule, delaying the superstructure cycle.',
          'Phase 2 site area handed over 45 days late owing to pending land title clearance.',
          'Client instructed redesign of clubhouse; demolition of completed works and re-execution required.',
          'Work suspended by client for 21 days pending funding; labour and plant retained on site.',
          'Steel prices rose 18% against the 10% PVC cap under SCC 47.',
        ], { section: 'type' }),
        money('claimValue', 'Claim Value', [4000000, 45000000], { required: true, section: 'impact' }),
        num('eotDays', 'EOT Claimed', [0, 90], { unit: 'days', section: 'impact' }),
        select('costHead', 'Principal Cost Head', ['Site overheads', 'Idle labour & plant', 'Material escalation', 'Additional works', 'HO overheads', 'Finance charges'], { section: 'impact', list: false }),
        multi('evidence', 'Evidence Attached', EVIDENCE, { section: 'evidence' }),
        area('evidenceNote', 'Evidence Notes', ['RFI log, drawing register and daily progress reports attached.', 'Hindrance register signed by client engineer.', 'Hire invoices and idle-time logs certified by site engineer.'], { section: 'evidence', list: false }),
      ],
    },
    {
      id: 'clmType',
      label: 'Claim Type',
      plural: 'Claim Types',
      app: 'claims',
      codePrefix: 'CT',
      titleField: 'name',
      count: 8,
      fields: [
        text('name', 'Claim Type', CLAIM_TYPES, { required: true }),
        select('category', 'Entitlement', ['Time', 'Cost', 'Time & Cost'], { gen: ['Time & Cost', 'Time', 'Time & Cost', 'Cost', 'Time & Cost', 'Cost', 'Cost', 'Time'] }),
        text('clause', 'Contract Clause', ['GCC 44.1', 'GCC 28.2', 'GCC 51.1', 'SCC 47', 'GCC 42.1', 'GCC 28.3', 'GCC 60.8', 'GCC 66.1']),
        num('noticeDays', 'Notice Period', [14, 28], { unit: 'days' }),
        num('openClaims', 'Open Claims', [0, 3]),
        area('description', 'Description', [
          'Recovery of prolongation costs for employer-caused delay.',
          'Extension of the time for completion without cost entitlement.',
          'Cost and time consequences of instructed variations.',
          'Additional cost incurred beyond the contract price (escalation, unforeseen conditions).',
          'Loss of productivity due to disruption of planned sequence.',
          'Cost of accelerating works at the employer’s instruction.',
          'Interest and costs arising from employer default (e.g. late payment).',
          'Relief for events beyond the parties’ control.',
        ]),
        status(['Active', 'Inactive'], { gen: ['Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active'] }),
      ],
    },
    {
      id: 'clmReason',
      label: 'Claim Reason',
      plural: 'Claim Reasons',
      app: 'claims',
      codePrefix: 'CR',
      titleField: 'reason',
      count: 12,
      fields: [
        text('reason', 'Claim Reason', REASONS, { required: true }),
        select('claimType', 'Typical Claim Type', CLAIM_TYPES, { gen: ['Delay', 'Extension of Time', 'Variation-related', 'Disruption', 'Additional Cost', 'Acceleration', 'Client Default', 'Force Majeure', 'Additional Cost', 'Extension of Time', 'Disruption', 'Delay'] }),
        select('responsibility', 'Responsibility', ['Client', 'Consultant', 'Authority', 'Neutral'], { gen: ['Consultant', 'Client', 'Client', 'Client', 'Neutral', 'Client', 'Client', 'Neutral', 'Neutral', 'Authority', 'Client', 'Authority'] }),
        text('clause', 'Contract Clause', ['GCC 44.1(a)', 'GCC 44.1(b)', 'GCC 51.1', 'GCC 40.2', 'SCC 47', 'GCC 28.3', 'GCC 60.8', 'GCC 66.1', 'GCC 12.2', 'GCC 44.1(e)', 'GCC 42.1', 'GCC 44.1(h)']),
        num('usage', 'Claims Using', [0, 4]),
        status(['Active', 'Inactive'], { gen: ['Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Inactive'] }),
      ],
    },
    {
      id: 'clmSubmission',
      label: 'Claim Submission',
      plural: 'Claim Submissions',
      app: 'claims',
      codePrefix: 'CS',
      titleField: 'title',
      count: 12,
      form: 'page',
      fields: [
        text('title', 'Submission', [
          'Prolongation claim — Rev 0',
          'EOT application — site handover',
          'Clubhouse redesign cost claim',
          'Suspension idle-cost claim',
          'Steel escalation claim — Q1',
          'Acceleration cost claim',
          'Interest on delayed payments',
          'Force majeure notice & claim',
          'Rock strata additional cost claim',
          'EOT application — fire NOC',
          'Prolongation claim — Rev 1',
          'Access restriction disruption claim',
        ], { required: true }),
        ref('claim', 'Claim', 'clmClaim', { required: true }),
        ref('project', 'Project', 'project'),
        select('revision', 'Revision', ['Rev 0', 'Rev 1', 'Rev 2'], { gen: ['Rev 0', 'Rev 0', 'Rev 0', 'Rev 0', 'Rev 0', 'Rev 0', 'Rev 0', 'Rev 0', 'Rev 0', 'Rev 0', 'Rev 1', 'Rev 0'] }),
        date('date', 'Submitted On', [-200, -3], { required: true }),
        money('amount', 'Amount Claimed', [4000000, 45000000]),
        num('eotDays', 'EOT Sought', [0, 64], { unit: 'days' }),
        select('mode', 'Mode', ['Letter', 'Email', 'Client Portal', 'Hand Delivered']),
        date('responseDue', 'Response Due', [-20, 30]),
        status(['Draft', 'Submitted', 'Under Review', 'Query Raised', 'Accepted', 'Rejected'], { gen: ['Accepted', 'Under Review', 'Accepted', 'Submitted', 'Accepted', 'Query Raised', 'Accepted', 'Accepted', 'Under Review', 'Submitted', 'Accepted', 'Rejected'] }),
      ],
    },
    {
      id: 'clmSettlement',
      label: 'Settlement',
      plural: 'Settlements',
      app: 'claims',
      codePrefix: 'STL',
      titleField: 'title',
      count: 10,
      form: 'page',
      fields: [
        text('title', 'Settlement', [
          'Clubhouse redesign — full & final',
          'Steel escalation — Q1 settlement',
          'Interest on delayed payments — settled',
          'Cyclone damage — partial settlement',
          'HT line relocation delay — settled',
          'Façade change EOT & cost — settled',
          'Tower A slab cycle — negotiated',
          'Rainfall disruption — FY 25-26',
          'Access restriction — interim settlement',
          'Mobilisation advance interest — settled',
        ], { required: true }),
        ref('claim', 'Claim', 'clmClaim', { required: true }),
        ref('project', 'Project', 'project'),
        money('claimed', 'Amount Claimed', [9000000, 45000000]),
        money('approved', 'Approved Amount', [5000000, 28000000]),
        money('rejected', 'Rejected Amount', [800000, 9000000]),
        date('settlementDate', 'Settlement Date', [-240, -5], { required: true }),
        select('mode', 'Payment Route', ['RA Bill Adjustment', 'Separate Payment', 'Final Bill', 'Credit Note']),
        f('status', 'Payment Status', 'status', { options: ['Pending', 'Partially Paid', 'Paid'], gen: ['Paid', 'Paid', 'Paid', 'Partially Paid', 'Paid', 'Pending', 'Paid', 'Paid', 'Partially Paid', 'Paid'] }),
      ],
    },
  ],
};
