import { area, date, docs, fieldView, group, leaf, lineItems, money, num, page, pct, ref, register, select, status, text } from '../dsl';
import type { AppConfig, Row } from '../types';

const CR = 1e7;
const pad = (n: number) => String(n).padStart(3, '0');

/* ───────── Client contracts CON-001…008 (one per project) ───────── */
// title, type, value ₹Cr, start, end, months, retention %, advance %, PBG %, billed to date ₹Cr, signed on
const contractData: [string, string, number, string, string, number, number, number, number, number, string][] = [
  ['Skyline Apartments — Civil, Structure & Finishes', 'Item Rate', 85, '2025-01-01', '2026-12-31', 24, 5, 10, 10, 57.8, '2024-12-12'],
  ['Riverside Villas — 64 Villas Turnkey', 'Lump Sum', 42, '2025-02-15', '2026-11-30', 22, 5, 10, 5, 18.9, '2025-01-28'],
  ['Greenfield Township — Phase 1 Infrastructure & Towers', 'Item Rate', 58, '2025-03-01', '2027-02-28', 24, 10, 5, 10, 18.6, '2025-02-10'],
  ['Metro Office Tower — Design & Build', 'Design & Build', 64, '2025-01-20', '2026-12-31', 23, 5, 10, 10, 35.2, '2025-01-06'],
  ['Lakeview Residency — Towers A to C', 'Item Rate', 28, '2025-04-10', '2027-06-30', 27, 10, 5, 5, 7.8, '2025-03-24'],
  ['Orbit Tech Park Phase II — Shell & Core', 'Lump Sum', 18, '2024-06-01', '2026-11-30', 30, 5, 10, 5, 16.6, '2024-05-15'],
  ['Harbour View Hospital — EPC', 'EPC', 15, '2025-01-05', '2026-12-15', 23, 10, 15, 10, 12.6, '2024-12-20'],
  ['Sunrise Business Hotel — Civil & Interiors', 'Lump Sum', 10, '2025-05-01', '2026-12-31', 20, 5, 10, 5, 7.6, '2025-04-18'],
];
const PAYMENT_TERMS = ['Monthly RA — 30 days from certification', 'Monthly RA — 21 days from certification', 'Monthly RA — 30 days from certification', 'Milestone-linked — 30 days', 'Monthly RA — 45 days from certification', 'Monthly RA — 30 days from certification', 'Monthly RA — 30 days from certification', 'Fortnightly RA — 15 days'];
const contractRows: Row[] = contractData.map(([title, type, value, start, end, months, ret, adv, pbg, , signed], i) => ({
  id: `CON-${pad(i + 1)}`,
  code: `CON-${pad(i + 1)}`,
  title,
  project: `PRJ-${pad(i + 1)}`,
  client: `CL-${pad(i + 1)}`,
  type,
  signed,
  value: value * CR,
  start,
  end,
  duration: months,
  retention: ret,
  advance: adv,
  pbg,
  paymentTerms: PAYMENT_TERMS[i],
  dlp: i === 6 ? 24 : 12,
  ld: '0.5% per week, max 5%',
  status: 'Active',
}));

/* ───────── Retention per contract (reconciles to ₹10.7 Cr held) ───────── */
const retentionRows: Row[] = contractData.map(([title, , value, , end, , ret, , , billed], i) => ({
  id: `RET-${pad(i + 1)}`,
  code: `RET-${pad(i + 1)}`,
  contract: `CON-${pad(i + 1)}`,
  project: `PRJ-${pad(i + 1)}`,
  scope: title.split(' — ')[0],
  rate: ret,
  cap: Math.round(value * CR * ret / 100),
  held: Math.round(billed * CR * ret / 100),
  release: ret === 10 ? '50% on completion · 50% after DLP' : '100% after DLP against BG',
  releaseDue: end,
  status: 'Active',
}));

/* ───────── Advances per contract ───────── */
const advanceRows: Row[] = [
  ...contractData.map(([title, , value, start, , , , adv, , billed], i) => {
    const amount = Math.round(value * CR * adv / 100);
    const recovered = Math.round(billed * CR * adv / 100);
    return {
      id: `ADV-${pad(i + 1)}`,
      code: `ADV-${pad(i + 1)}`,
      reference: `MA-${title.split(' ')[0].slice(0, 3).toUpperCase()}-01`,
      contract: `CON-${pad(i + 1)}`,
      type: 'Mobilisation Advance',
      received: start,
      amount,
      recoveryRate: adv,
      recovered,
      balance: amount - recovered,
      status: amount - recovered < 0.02 * amount ? 'Closed' : 'Active',
    };
  }),
  { id: 'ADV-009', code: 'ADV-009', reference: 'SA-SKY-07', contract: 'CON-001', type: 'Secured Advance (materials)', received: '2026-08-28', amount: 18600000, recoveryRate: 100, recovered: 0, balance: 18600000, status: 'Active' },
  { id: 'ADV-010', code: 'ADV-010', reference: 'SA-MOT-04', contract: 'CON-004', type: 'Secured Advance (materials)', received: '2026-07-24', amount: 12400000, recoveryRate: 100, recovered: 12400000, balance: 0, status: 'Closed' },
  { id: 'ADV-011', code: 'ADV-011', reference: 'PM-GFT-01', contract: 'CON-003', type: 'Plant & Machinery Advance', received: '2026-09-22', amount: 9500000, recoveryRate: 5, recovered: 0, balance: 9500000, status: 'Pending' },
];

/* ───────── Bank guarantees (2 expiring within 60 days) ───────── */
const bgData: [string, number, string, string, number, string, string, string][] = [
  ['BG/HDFC/2024/1182', 0, 'Performance Bank Guarantee', 'HDFC Bank', 8.5, '2024-12-20', '2028-03-31', 'Valid'],
  ['BG/ICICI/2025/0217', 1, 'Performance Bank Guarantee', 'ICICI Bank', 2.1, '2025-02-05', '2028-02-29', 'Valid'],
  ['BG/SBI/2025/0344', 2, 'Performance Bank Guarantee', 'State Bank of India', 5.8, '2025-02-20', '2028-05-31', 'Valid'],
  ['BG/AXIS/2025/0109', 3, 'Performance Bank Guarantee', 'Axis Bank', 6.4, '2025-01-15', '2028-03-31', 'Valid'],
  ['BG/CANARA/2025/0421', 4, 'Performance Bank Guarantee', 'Canara Bank', 1.4, '2025-04-02', '2028-09-30', 'Valid'],
  ['BG/HDFC/2024/0688', 5, 'Performance Bank Guarantee', 'HDFC Bank', 0.9, '2024-05-28', '2027-12-31', 'Valid'],
  ['BG/SBI/2024/1290', 6, 'Performance Bank Guarantee', 'State Bank of India', 1.5, '2024-12-28', '2029-03-31', 'Valid'],
  ['BG/ICICI/2025/0512', 7, 'Performance Bank Guarantee', 'ICICI Bank', 0.5, '2025-04-25', '2028-03-31', 'Valid'],
  ['APG/HDFC/2024/0691', 5, 'Advance Payment Guarantee', 'HDFC Bank', 1.8, '2024-05-28', '2026-10-31', 'Expiring Soon'],
  ['APG/ICICI/2025/0513', 7, 'Advance Payment Guarantee', 'ICICI Bank', 1.0, '2025-04-25', '2026-11-20', 'Expiring Soon'],
  ['APG/HDFC/2024/1183', 0, 'Advance Payment Guarantee', 'HDFC Bank', 8.5, '2024-12-20', '2027-03-31', 'Valid'],
  ['APG/AXIS/2025/0110', 3, 'Advance Payment Guarantee', 'Axis Bank', 6.4, '2025-01-15', '2027-03-31', 'Valid'],
  ['SA-BG/AXIS/2026/0077', 3, 'Secured Advance Guarantee', 'Axis Bank', 1.24, '2026-06-30', '2026-09-15', 'Released'],
];
const guaranteeRows: Row[] = bgData.map(([bgNo, ci, type, bank, amtCr, issued, expiry, st], i) => ({
  id: `BG-${pad(i + 1)}`,
  code: `BG-${pad(i + 1)}`,
  bgNo,
  contract: `CON-${pad(ci + 1)}`,
  type,
  bank,
  amount: Math.round(amtCr * CR),
  issued,
  expiry,
  claimPeriod: 6,
  status: st,
}));

/* ───────── Contract BOQ — CON-001 Skyline Apartments (sub-total ≈ ₹72.6 Cr + GST ≈ ₹85.7 Cr) ───────── */
const boqData: [string, string, string, string, number, number][] = [
  ['1.1', 'Earthwork & Substructure', 'Excavation in all soils up to 3 m depth incl. disposal within 5 km', 'Cum', 24000, 420],
  ['1.2', 'Earthwork & Substructure', 'Anti-termite treatment — pre-construction (IS 6313)', 'Sqm', 9800, 65],
  ['1.3', 'Earthwork & Substructure', 'PCC M15 levelling course below raft', 'Cum', 980, 5600],
  ['1.4', 'Earthwork & Substructure', 'RCC M30 raft foundation incl. pumping', 'Cum', 5200, 7450],
  ['1.5', 'Earthwork & Substructure', 'Basement waterproofing — crystalline + membrane', 'Sqm', 11500, 1150],
  ['1.6', 'Earthwork & Substructure', 'Reinforcement steel Fe500D — substructure', 'MT', 620, 72500],
  ['2.1', 'Superstructure', 'RCC M30 columns & shear walls', 'Cum', 4100, 8250],
  ['2.2', 'Superstructure', 'RCC M25 slabs, beams & staircases', 'Cum', 9600, 7650],
  ['2.3', 'Superstructure', 'Reinforcement steel Fe500D — superstructure', 'MT', 1640, 72500],
  ['2.4', 'Superstructure', 'Aluminium system formwork — slabs & walls', 'Sqm', 62000, 480],
  ['3.1', 'Masonry & Finishes', 'AAC block masonry 200 mm in CM 1:4', 'Cum', 5400, 5950],
  ['3.2', 'Masonry & Finishes', 'Internal plaster 12 mm in CM 1:5', 'Sqm', 148000, 260],
  ['3.3', 'Masonry & Finishes', 'External plaster 20 mm with waterproofing admixture', 'Sqm', 36000, 420],
  ['3.4', 'Masonry & Finishes', 'Vitrified tile flooring 600×600 incl. skirting', 'Sqm', 42000, 1250],
  ['3.5', 'Masonry & Finishes', 'Interior acrylic emulsion — 2 coats over putty', 'Sqm', 148000, 145],
  ['3.6', 'Masonry & Finishes', 'uPVC windows with 5 mm clear glass', 'Sqm', 6200, 3650],
  ['4.1', 'MEP Services', 'Electrical wiring, DB & fixtures — per flat', 'Nos', 336, 185000],
  ['4.2', 'MEP Services', 'Plumbing & sanitary installation — per flat', 'Nos', 336, 120000],
  ['4.3', 'MEP Services', 'Fire fighting — wet riser, sprinklers & pumps', 'LS', 1, 24500000],
  ['4.4', 'MEP Services', 'Passenger lifts 13-person, 1.5 m/s', 'Nos', 6, 3850000],
  ['5.1', 'External Works', 'Internal roads — interlocking paver blocks', 'Sqm', 8400, 1250],
  ['5.2', 'External Works', 'Landscaping & hardscape', 'Sqm', 6500, 850],
  ['5.3', 'External Works', 'Sewage treatment plant 150 KLD — supply & commissioning', 'LS', 1, 8500000],
];
const boqRows: Row[] = boqData.map(([itemCode, section, description, unit, qty, rate], i) => ({
  id: `BQ-${pad(i + 1)}`,
  code: `BQ-${pad(i + 1)}`,
  itemCode,
  section,
  description,
  unit,
  qty,
  rate,
  contract: 'CON-001',
}));

export const contractsApp: AppConfig = {
  id: 'contracts',
  name: 'Contracts',
  icon: 'ti-file-certificate',
  description: 'Client contracts, contract BOQ, commercial terms, guarantees, milestones and documents',
  menus: [
    leaf('Contract Master', 'ti-file-certificate', register('contract', { views: ['table', 'board'] })),
    group('Client Contract', 'ti-file-text', [
      page('Contract Value', fieldView('contract', 'value')),
      page('Duration', fieldView('contract', 'duration')),
      page('Terms', register('conTerm')),
      page('Conditions', register('conCondition', { tabs: { field: 'type', values: ['General Condition', 'Special Condition', 'Particular Condition'] } })),
    ]),
    group('Contract BOQ', 'ti-list-numbers', [
      page('Contract Items', lineItems('conBoqItem', 'Contract BOQ — CON-001 Skyline Apartments', ['itemCode'])),
      page('Quantities', fieldView('conBoqItem', 'qty')),
      page('Rates', fieldView('conBoqItem', 'rate')),
    ]),
    group('Commercial Terms', 'ti-briefcase', [
      page('Payment Terms', register('conPaymentTerm')),
      page('Retention', register('conRetention')),
      page('Advance', register('conAdvance')),
      page('Performance Guarantee', register('conGuarantee', { tabs: { field: 'status', values: ['Valid', 'Expiring Soon', 'Expired', 'Released'] }, views: ['table', 'calendar'], dateField: 'expiry' })),
    ]),
    leaf('Milestones', 'ti-flag', register('conMilestone', { views: ['table', 'calendar'], dateField: 'due' })),
    leaf('Contract Documents', 'ti-folders', docs(['Signed Agreements', 'Letters of Award', 'General Conditions', 'Special Conditions', 'BOQ & Specifications', 'Tender Drawings', 'Bank Guarantees', 'Insurance Policies', 'Amendments', 'Correspondence'], 'Signed Agreements', 'Contract Documents')),
  ],
  dashboard: {
    flow: [
      { label: 'Contracts', value: '8 active' },
      { label: 'Contract Value', value: '₹ 320 Cr' },
      { label: 'Billed to Date', value: '₹ 175.1 Cr · 55%' },
      { label: 'Retention Held', value: '₹ 10.7 Cr' },
      { label: 'Guarantees', value: '2 expiring in 60 d' },
    ],
    kpis: [
      { label: 'Active Contracts', value: '8', sub: '₹ 320 Cr total contract value', progress: 100, icon: 'ti-file-certificate' },
      { label: 'Billed to Date', value: '₹ 175.1 Cr', delta: '+₹ 26.1 Cr (Sep)', up: true, progress: 55, icon: 'ti-file-invoice' },
      { label: 'Balance to Bill', value: '₹ 144.9 Cr', progress: 45, icon: 'ti-report-money' },
      { label: 'Retention Held', value: '₹ 10.7 Cr', icon: 'ti-coins', sub: '5–10% per contract' },
      { label: 'Guarantees Expiring (60 d)', value: '2', sub: '₹ 2.8 Cr · Orbit TP, Sunrise', icon: 'ti-shield-check' },
      { label: 'Milestones Due (30 d)', value: '5', icon: 'ti-flag' },
    ],
    charts: [
      { title: 'Contract Value vs Billed to Date (₹ Cr)', kind: 'bar', categories: ['Skyline', 'Riverside', 'Greenfield', 'Metro Tower', 'Lakeview', 'Orbit TP', 'Harbour View', 'Sunrise'], series: [{ name: 'Contract value', data: [85, 42, 58, 64, 28, 18, 15, 10] }, { name: 'Billed to date', data: [57.8, 18.9, 18.6, 35.2, 7.8, 16.6, 12.6, 7.6] }], unit: '₹Cr', span: 2 },
      { title: 'Contracts by Type (₹ Cr)', kind: 'donut', categories: ['Item Rate', 'Lump Sum', 'Design & Build', 'EPC'], series: [{ name: '₹ Cr', data: [171, 70, 64, 15] }], unit: '₹Cr', subtitle: '₹ 320 Cr' },
      { title: 'Contract Completion Dates', kind: 'bar', categories: ['Q3 FY27', 'Q4 FY27', 'Q1 FY28', 'Q2 FY28'], series: [{ name: 'Contracts', data: [5, 1, 1, 1] }] },
      { title: 'Billing Progress vs Time Elapsed (%)', kind: 'hbar', categories: ['Skyline', 'Riverside', 'Greenfield', 'Metro Tower', 'Lakeview', 'Orbit TP', 'Harbour View', 'Sunrise'], series: [{ name: 'Billed %', data: [68, 45, 32, 55, 28, 92, 84, 76] }, { name: 'Time elapsed %', data: [88, 88, 79, 89, 64, 94, 91, 85] }], unit: '%', span: 2 },
    ],
    table: { entity: 'contract', title: 'Contract Register', columns: ['title', 'client', 'value', 'start', 'end', 'status'], limit: 8 },
    rail: [
      {
        kind: 'dates',
        title: 'Key Contract Dates',
        items: [
          { date: '2026-10-31', title: 'APG expiry — HDFC ₹ 1.8 Cr', sub: 'Orbit Tech Park Phase II' },
          { date: '2026-11-20', title: 'APG expiry — ICICI ₹ 1.0 Cr', sub: 'Sunrise Business Hotel' },
          { date: '2026-11-30', title: 'Contract completion', sub: 'Riverside Villas · Orbit Tech Park' },
          { date: '2026-12-15', title: 'Contract completion', sub: 'Harbour View Hospital' },
        ],
      },
      { kind: 'health', title: 'Guarantee Status', items: [{ label: 'Valid', value: 10, tone: 'green' }, { label: 'Expiring Soon', value: 2, tone: 'yellow' }, { label: 'Released', value: 1, tone: 'gray' }] },
      {
        kind: 'list',
        title: 'Recent Contract Activity',
        items: [
          { avatar: 'Siddharth Rao', title: 'Amendment No. 3 uploaded', sub: 'CON-003 Greenfield Township — clubhouse scope', meta: '2 hours ago', status: 'Under Review' },
          { avatar: 'Pooja Reddy', title: 'BG renewal request sent to HDFC', sub: 'APG/HDFC/2024/0691 · Orbit TP', meta: 'Yesterday' },
          { avatar: 'Priya M', title: 'BOQ rates revised — steel PVC', sub: 'CON-001 Skyline Apartments', meta: '2 days ago' },
          { avatar: 'Siddharth Rao', title: 'Payment milestone achieved', sub: 'CON-006 Orbit TP — shell completion', meta: '4 days ago', status: 'Completed' },
        ],
      },
    ],
  },
  entities: [
    {
      id: 'contract',
      label: 'Contract',
      plural: 'Contracts',
      app: 'contracts',
      codePrefix: 'CON',
      titleField: 'title',
      form: 'wizard',
      sections: [
        { id: 'parties', title: 'Parties & Scope', icon: 'ti-users-group' },
        { id: 'value', title: 'Value & Duration', icon: 'ti-currency-rupee' },
        { id: 'terms', title: 'Commercial Terms', icon: 'ti-briefcase' },
      ],
      fields: [
        text('code', 'Contract No.', undefined, { section: 'parties', hint: 'Auto-generated series CON-###' }),
        text('title', 'Contract Title', undefined, { required: true, section: 'parties' }),
        ref('project', 'Project', 'project', { required: true, section: 'parties' }),
        ref('client', 'Client', 'client', { required: true, section: 'parties' }),
        select('type', 'Contract Type', ['Item Rate', 'Lump Sum', 'Design & Build', 'EPC', 'Cost Plus'], { section: 'parties' }),
        date('signed', 'Agreement Date', undefined, { section: 'parties', list: false }),
        money('value', 'Contract Value', undefined, { required: true, section: 'value', hint: 'Excluding GST' }),
        date('start', 'Start Date', undefined, { required: true, section: 'value' }),
        date('end', 'Completion Date', undefined, { required: true, section: 'value' }),
        num('duration', 'Duration', undefined, { unit: 'months', section: 'value' }),
        pct('retention', 'Retention', undefined, { section: 'terms', list: false }),
        pct('advance', 'Mobilisation Advance', undefined, { section: 'terms', list: false }),
        pct('pbg', 'Performance Guarantee', undefined, { section: 'terms', list: false }),
        text('paymentTerms', 'Payment Terms', undefined, { section: 'terms', list: false }),
        num('dlp', 'Defect Liability Period', undefined, { unit: 'months', section: 'terms', list: false }),
        text('ld', 'Liquidated Damages', undefined, { section: 'terms', list: false }),
        status(['Draft', 'Under Review', 'Active', 'On Hold', 'Completed', 'Closed'], { section: 'parties' }),
      ],
      rows: contractRows,
    },
    {
      id: 'conTerm',
      label: 'Contract Term',
      plural: 'Contract Terms',
      app: 'contracts',
      codePrefix: 'CT',
      titleField: 'title',
      count: 16,
      form: 'page',
      fields: [
        text('title', 'Term', ['Scope of work & exclusions', 'Time for completion', 'Extension of time', 'Liquidated damages', 'Price variation — steel & cement', 'Variations & extra items', 'Measurement & billing', 'Payment & interest on delay', 'Retention money', 'Mobilisation advance', 'Defect liability period', 'Insurance — CAR & WC', 'Termination by employer', 'Dispute resolution — arbitration', 'Force majeure', 'Taxes & duties'], { required: true }),
        text('clause', 'Clause', ['Cl. 2.1', 'Cl. 8.2', 'Cl. 8.4', 'Cl. 8.7', 'Cl. 13.8', 'Cl. 13.1', 'Cl. 12.1', 'Cl. 14.7', 'Cl. 14.3', 'Cl. 14.2', 'Cl. 11.1', 'Cl. 18.1', 'Cl. 15.2', 'Cl. 20.6', 'Cl. 19.1', 'Cl. 14.1']),
        ref('contract', 'Contract', 'contract', { required: true }),
        select('category', 'Category', ['Scope', 'Time', 'Commercial', 'Legal', 'Risk'], { gen: ['Scope', 'Time', 'Time', 'Time', 'Commercial', 'Commercial', 'Commercial', 'Commercial', 'Commercial', 'Commercial', 'Risk', 'Risk', 'Legal', 'Legal', 'Risk', 'Commercial'] }),
        area('summary', 'Summary', ['Contractor to complete all works as per BOQ, drawings and specifications; client-supplied items excluded.', 'Completion within 24 months from the date of site handover.', 'EOT admissible for client-caused delays and force majeure events with notice within 14 days.', 'LD at 0.5% of contract value per week of delay, capped at 5%.', 'Steel and cement variation payable beyond ±5% of base price as per RBI WPI.', 'Variations valued at BOQ rates; new items at derived rates plus 15% overhead & profit.', 'Monthly joint measurement; RA bill submitted by the 28th of each month.', 'Payment within 30 days of certification; interest at 12% p.a. on delayed payment.']),
        ref('owner', 'Responsible Person', 'employee'),
        status(['Active', 'Under Review', 'Revised'], { gen: ['Active', 'Active', 'Active', 'Active', 'Revised', 'Active', 'Active', 'Under Review', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active'] }),
      ],
    },
    {
      id: 'conCondition',
      label: 'Contract Condition',
      plural: 'Contract Conditions',
      app: 'contracts',
      codePrefix: 'CC',
      titleField: 'condition',
      count: 15,
      fields: [
        text('condition', 'Condition', ['Contractor All Risk insurance for full contract value', 'Workmen compensation policy for all labour', 'Labour licence under CLRA Act before mobilisation', 'BOCW cess @ 1% deducted from each bill', 'Safety plan approval before start of work', 'Monthly progress report by 5th of each month', 'Third-party quality audit every quarter', 'Client-supplied cement & steel reconciliation', 'Night work only with prior written approval', 'Green building (IGBC) compliance', 'Minimum wage compliance for all workers', 'Key personnel not to be replaced without consent', 'Hoarding & dust control within 50 m of boundary', 'Performance guarantee valid till DLP + 3 months', 'As-built drawings before final bill'], { required: true }),
        select('type', 'Condition Type', ['General Condition', 'Special Condition', 'Particular Condition'], { gen: ['General Condition', 'General Condition', 'General Condition', 'Special Condition', 'General Condition', 'Particular Condition', 'Special Condition', 'Special Condition', 'Particular Condition', 'Special Condition', 'General Condition', 'Particular Condition', 'Particular Condition', 'Special Condition', 'General Condition'] }),
        ref('contract', 'Contract', 'contract', { required: true }),
        text('clause', 'Clause Ref', ['GCC 18.1', 'GCC 18.3', 'GCC 6.4', 'SCC 4.2', 'GCC 6.7', 'PCC 2.1', 'SCC 7.3', 'SCC 5.1', 'PCC 3.4', 'SCC 9.2', 'GCC 6.2', 'PCC 1.6', 'PCC 4.1', 'SCC 4.8', 'GCC 16.2']),
        date('reviewOn', 'Next Review', [-10, 60]),
        ref('owner', 'Compliance Owner', 'employee'),
        status(['Compliant', 'Pending', 'Under Review', 'Non-Compliant'], { gen: ['Compliant', 'Compliant', 'Compliant', 'Compliant', 'Compliant', 'Pending', 'Under Review', 'Compliant', 'Compliant', 'Pending', 'Compliant', 'Compliant', 'Non-Compliant', 'Compliant', 'Pending'] }),
      ],
    },
    {
      id: 'conBoqItem',
      label: 'Contract BOQ Item',
      plural: 'Contract BOQ Items',
      app: 'contracts',
      codePrefix: 'BQ',
      titleField: 'description',
      fields: [
        text('itemCode', 'BOQ Ref'),
        text('description', 'Description', undefined, { required: true }),
        select('section', 'Section', ['Earthwork & Substructure', 'Superstructure', 'Masonry & Finishes', 'MEP Services', 'External Works']),
        text('unit', 'Unit'),
        num('qty', 'Contract Quantity'),
        money('rate', 'Contract Rate'),
        ref('contract', 'Contract', 'contract', { list: false }),
      ],
      rows: boqRows,
    },
    {
      id: 'conPaymentTerm',
      label: 'Payment Term',
      plural: 'Payment Terms',
      app: 'contracts',
      codePrefix: 'PAY',
      titleField: 'term',
      count: 14,
      fields: [
        text('term', 'Payment Term', ['Monthly RA bill — payment within 30 days of certification', 'Mobilisation advance 10% against bank guarantee', 'Secured advance 75% on materials brought to site', 'Price variation — steel & cement (RBI WPI)', 'Final bill within 90 days of completion certificate', 'Retention release 50% on completion', 'Retention release 50% after DLP', 'Interest @ 12% p.a. on delayed payments', 'GST extra at applicable rates', 'Milestone payment — structure completion', 'Escalation capped at 5% of contract value', 'TDS u/s 194C deducted at source', 'Fortnightly RA bills — 15 days credit', 'Advance recovery @ 10% of each RA bill'], { required: true }),
        ref('contract', 'Contract', 'contract', { required: true }),
        select('category', 'Category', ['Billing', 'Advance', 'Escalation', 'Retention', 'Taxes', 'Final Bill'], { gen: ['Billing', 'Advance', 'Advance', 'Escalation', 'Final Bill', 'Retention', 'Retention', 'Billing', 'Taxes', 'Billing', 'Escalation', 'Taxes', 'Billing', 'Advance'] }),
        num('creditDays', 'Credit Period', [0, 90], { unit: 'days' }),
        pct('share', 'Value / Rate', [0, 75]),
        text('clause', 'Clause Ref', ['Cl. 14.7', 'Cl. 14.2', 'Cl. 14.5', 'Cl. 13.8', 'Cl. 14.11', 'Cl. 14.9', 'Cl. 14.9', 'Cl. 14.8', 'Cl. 14.1', 'Sch. F', 'Cl. 13.8', 'Cl. 14.1', 'Cl. 14.7', 'Cl. 14.2']),
        status(['Active', 'Under Review'], { gen: ['Active', 'Active', 'Active', 'Under Review', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Under Review', 'Active', 'Active', 'Active'] }),
      ],
    },
    {
      id: 'conRetention',
      label: 'Retention',
      plural: 'Retention',
      app: 'contracts',
      codePrefix: 'RET',
      titleField: 'scope',
      info: 'Retention held across 8 client contracts: ₹ 10.7 Cr. Release as per contract clause 14.9.',
      fields: [
        text('scope', 'Contract Scope', undefined, { required: true }),
        ref('contract', 'Contract', 'contract', { required: true }),
        ref('project', 'Project', 'project', { list: false }),
        pct('rate', 'Retention %'),
        money('cap', 'Retention Cap'),
        money('held', 'Held to Date'),
        text('release', 'Release Terms'),
        date('releaseDue', 'Release Due'),
        status(['Active', 'Due', 'Released'], { gen: ['Active'] }),
      ],
      rows: retentionRows,
    },
    {
      id: 'conAdvance',
      label: 'Advance',
      plural: 'Advances',
      app: 'contracts',
      codePrefix: 'ADV',
      titleField: 'reference',
      fields: [
        text('reference', 'Advance Ref', undefined, { required: true }),
        ref('contract', 'Contract', 'contract', { required: true }),
        select('type', 'Advance Type', ['Mobilisation Advance', 'Secured Advance (materials)', 'Plant & Machinery Advance']),
        date('received', 'Received On'),
        money('amount', 'Advance Amount'),
        pct('recoveryRate', 'Recovery % per Bill'),
        money('recovered', 'Recovered to Date'),
        money('balance', 'Balance to Recover'),
        status(['Pending', 'Active', 'Closed']),
      ],
      rows: advanceRows,
    },
    {
      id: 'conGuarantee',
      label: 'Bank Guarantee',
      plural: 'Bank Guarantees',
      app: 'contracts',
      codePrefix: 'BG',
      titleField: 'bgNo',
      info: '2 guarantees expire within 60 days — renewal requests to be raised 30 days before expiry.',
      fields: [
        text('bgNo', 'BG Number', undefined, { required: true }),
        ref('contract', 'Contract', 'contract', { required: true }),
        select('type', 'Guarantee Type', ['Performance Bank Guarantee', 'Advance Payment Guarantee', 'Secured Advance Guarantee', 'Retention Bond']),
        select('bank', 'Issuing Bank', ['HDFC Bank', 'ICICI Bank', 'State Bank of India', 'Axis Bank', 'Canara Bank']),
        money('amount', 'Guarantee Amount'),
        date('issued', 'Issued On'),
        date('expiry', 'Expiry Date', undefined, { required: true }),
        num('claimPeriod', 'Claim Period', undefined, { unit: 'months', list: false }),
        status(['Valid', 'Expiring Soon', 'Expired', 'Released']),
      ],
      rows: guaranteeRows,
    },
    {
      id: 'conMilestone',
      label: 'Contract Milestone',
      plural: 'Contract Milestones',
      app: 'contracts',
      codePrefix: 'CM',
      titleField: 'name',
      count: 18,
      fields: [
        text('name', 'Milestone', ['Structure completion — Tower A', 'Shell & core completion', 'Topping out — Tower B', 'Handover of 32 villas', 'MEP first fix complete', 'Façade completion', 'Occupancy certificate', 'Raft completion — Tower C', 'Clubhouse structure', 'OT & ICU block handover', 'Lift commissioning', 'Hotel soft opening', 'Final completion', 'Basement completion', 'Infrastructure — Phase 1 roads', 'Fire NOC', 'Retention release — 50%', 'Mobilisation complete'], { required: true }),
        ref('contract', 'Contract', 'contract', { required: true }),
        select('type', 'Milestone Type', ['Contract', 'Payment', 'Completion'], { gen: ['Completion', 'Payment', 'Contract', 'Payment', 'Contract', 'Contract', 'Completion', 'Contract', 'Contract', 'Payment', 'Contract', 'Completion', 'Completion', 'Contract', 'Payment', 'Contract', 'Payment', 'Contract'] }),
        date('due', 'Due Date', [-90, 150], { required: true }),
        pct('share', 'Payment Share', [0, 15]),
        money('amount', 'Payment Value', [0, 85000000]),
        ref('owner', 'Responsible', 'employee'),
        status(['Planned', 'Due', 'Completed', 'At Risk', 'Delayed'], { gen: ['Due', 'Completed', 'Planned', 'At Risk', 'Completed', 'Planned', 'Planned', 'Completed', 'Delayed', 'Due', 'Planned', 'At Risk', 'Planned', 'Completed', 'Due', 'Planned', 'Planned', 'Completed'] }),
      ],
    },
  ],
};
