import { area, board, date, docs, f, fieldView, group, money, multi, num, page, pct, ref, register, select, status, text } from '../dsl';
import type { AppConfig } from '../types';

const SOURCES = ['Website', 'Referral', 'Direct Enquiry', 'Tender Portal', 'Existing Client', 'Campaign', 'Other'];
const PROJECT_TYPES = ['Residential', 'Commercial', 'Industrial', 'Institutional', 'Hospitality', 'Infrastructure'];

export const crmApp: AppConfig = {
  id: 'crm',
  name: 'CRM',
  icon: 'ti-address-book',
  description: 'Leads, clients, opportunities, pipeline and client communication',
  menus: [
    group('Lead Management', 'ti-user-plus', [
      page('Lead Registration', register('crmLead', { views: ['table', 'board'] })),
      page('Lead Source', register('crmLeadSource')),
      page('Lead Qualification', board('crmLead', 'status', ['company', 'value', 'owner'])),
      page('Lead Conversion', {
        type: 'wizard',
        title: 'Lead Conversion',
        submitLabel: 'Convert Lead',
        steps: [
          {
            title: 'Lead & Qualification',
            icon: 'ti-user-check',
            note: 'Select a qualified lead. Only leads with status “Qualified” and a completed qualification score can be converted.',
            fields: [
              ref('lead', 'Lead', 'crmLead', { required: true }),
              select('rating', 'Lead Rating', ['Hot', 'Warm', 'Cold'], { required: true }),
              pct('score', 'Qualification Score', undefined, { hint: 'BANT score out of 100' }),
              select('budgetConfirmed', 'Budget Confirmed', ['Yes', 'No', 'Partially']),
            ],
            checklist: [
              'Budget / funding source confirmed by client',
              'Decision maker identified and met',
              'Land / site available and title verified',
              'Project timeline within the next 12 months',
              'Scope fits our capability and bid capacity',
            ],
          },
          {
            title: 'Client Details',
            icon: 'ti-building-community',
            note: 'Link the lead to an existing client or create a new client master record.',
            fields: [
              select('clientMode', 'Client', ['Link existing client', 'Create new client'], { required: true }),
              ref('client', 'Existing Client', 'client'),
              text('clientName', 'New Client Name', undefined, { placeholder: 'e.g. Navalur Realty LLP' }),
              select('clientType', 'Client Type', ['Developer', 'Corporate', 'Government', 'Institution']),
              text('gstin', 'GSTIN', undefined, { placeholder: '33AAAAA0000A1Z5' }),
              text('contact', 'Primary Contact', undefined, { required: true }),
              f('phone', 'Phone', 'phone'),
              f('email', 'Email', 'email'),
            ],
          },
          {
            title: 'Opportunity Details',
            icon: 'ti-target-arrow',
            fields: [
              text('opportunity', 'Opportunity Name', undefined, { required: true }),
              select('projectType', 'Project Type', PROJECT_TYPES, { required: true }),
              money('value', 'Estimated Value', undefined, { required: true }),
              pct('probability', 'Probability'),
              date('expectedStart', 'Expected Start'),
              date('expectedClose', 'Expected Close', undefined, { required: true }),
              ref('owner', 'Opportunity Owner', 'employee', { required: true }),
              multi('team', 'Assigned Team', ['Business Development', 'Estimation', 'Tender', 'Design', 'Legal']),
              area('requirement', 'Project Requirement'),
            ],
            upload: ['Enquiry letter / RFP', 'Site plan or KML', 'Client KYC (PAN, GST certificate)'],
          },
        ],
      }),
    ]),
    group('Client Management', 'ti-building-community', [
      page('Client Master', register('client')),
      page('Client Contacts', register('crmContact')),
      page('Client Addresses', register('crmAddress')),
      page('Client Documents', docs(['KYC & Registration', 'GST Certificates', 'Agreements & MoUs', 'Letters of Intent', 'Work Orders', 'Correspondence', 'Financial Statements'], undefined, 'Client Documents')),
      page('Client History', {
        type: 'timeline',
        title: 'Client History',
        subject: 'client',
        events: [
          { date: '2016-01-15', title: 'Client onboarded', actor: 'Ramya K', text: 'KYC completed; credit limit ₹ 5 Cr approved by Finance.', status: 'Completed' },
          { date: '2019-06-10', title: 'Pearl Residency (G+9) handed over', actor: 'Arun S', text: 'Completed 3 weeks ahead of schedule; client satisfaction score 4.6 / 5.', status: 'Completed' },
          { date: '2024-11-04', title: 'Enquiry received — Skyline Apartments', actor: 'Ramya K', text: 'Twin tower residential project at Sholinganallur, 4.2 acres.', status: 'Closed' },
          { date: '2024-12-18', title: 'Proposal & estimate submitted', actor: 'Kavya R', text: 'Estimate R2 of ₹ 88.4 Cr submitted with methodology and schedule.', status: 'Submitted' },
          { date: '2025-01-01', title: 'Contract signed — Skyline Apartments (₹ 85 Cr)', actor: 'Siddharth Rao', text: 'Item-rate contract CON-001; 24-month duration, 5% retention.', status: 'Approved' },
          { date: '2026-03-12', title: 'Quarterly review meeting', actor: 'Arun S', text: 'Progress 48%; client requested façade upgrade to ACP + glass.', status: 'Completed' },
          { date: '2026-07-22', title: 'Variation VO-004 approved', actor: 'Siddharth Rao', text: 'Clubhouse interiors added — ₹ 1.8 Cr.', status: 'Approved' },
          { date: '2026-09-10', title: 'New enquiry — ABC Grand, Adyar', actor: 'Ramya K', text: 'Luxury apartments, 1.85 lakh sq ft; converted to opportunity OPP-009.', status: 'Open' },
          { date: '2026-09-24', title: 'RA Bill 18 payment received — ₹ 3.2 Cr', actor: 'Lakshmi N', text: 'Received within 21 days of certification.', status: 'Received' },
          { date: '2026-09-27', title: 'Site visit — ABC Grand, Adyar', actor: 'Naveen P', text: 'Joint site inspection with client architect; soil report requested.', status: 'Completed' },
        ],
      }),
    ]),
    group('Opportunity Management', 'ti-target-arrow', [
      page('Opportunity', register('crmOpportunity', { views: ['table', 'board'], boardField: 'stage' })),
      page('Project Requirement', fieldView('crmOpportunity', 'requirement')),
      page('Estimated Value', fieldView('crmOpportunity', 'value')),
      page('Expected Start', fieldView('crmOpportunity', 'expectedStart')),
      page('Probability', fieldView('crmOpportunity', 'probability')),
    ]),
    group('Communication', 'ti-messages', [
      page('Meetings', register('crmMeeting', { views: ['table', 'calendar'], dateField: 'date' })),
      page('Calls', register('crmCall')),
      page('Emails', register('crmEmail')),
      page('Follow-ups', register('crmFollowUp', { tabs: { field: 'bucket', values: ['Today', 'Upcoming', 'Overdue', 'Completed'] } })),
    ]),
  ],
  dashboard: {
    flow: [
      { label: 'Leads', value: '184 FY · 38 new' },
      { label: 'Pipeline', value: '₹ 412 Cr' },
      { label: 'Opportunities', value: '26 open · 9 won' },
      { label: 'Conversion', value: '21.7% lead → opportunity' },
    ],
    kpis: [
      { label: 'Total Leads (FY)', value: '184', delta: '+12%', up: true, progress: 61, icon: 'ti-users', sub: '38 new this month' },
      { label: 'Qualified Leads', value: '44', delta: '+6', up: true, progress: 24, icon: 'ti-user-check', sub: '40 already converted' },
      { label: 'Open Opportunities', value: '26', delta: '+3', up: true, progress: 52, icon: 'ti-target-arrow' },
      { label: 'Pipeline Value', value: '₹ 412 Cr', delta: '+9%', up: true, progress: 68, icon: 'ti-currency-rupee', sub: 'Weighted ₹ 168 Cr' },
      { label: 'Won / Lost (FY)', value: '9 / 17', delta: 'Win rate 34%', up: true, progress: 34, icon: 'ti-trophy' },
      { label: 'Follow-ups Due', value: '14', delta: '4 overdue', up: true, good: false, icon: 'ti-bell-ringing' },
    ],
    charts: [
      {
        title: 'Leads vs Conversions',
        kind: 'barline',
        categories: ['Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep'],
        series: [
          { name: 'Leads', data: [26, 31, 28, 35, 33, 31], type: 'bar' },
          { name: 'Converted', data: [5, 7, 6, 8, 7, 7], type: 'bar' },
          { name: 'Qualified', data: [12, 14, 13, 16, 15, 14], type: 'line' },
        ],
        span: 2,
      },
      { title: 'Lead Source', kind: 'donut', categories: SOURCES, series: [{ name: 'Leads', data: [42, 36, 28, 34, 26, 12, 6] }], subtitle: '184 leads FY 26-27' },
      { title: 'Opportunity Pipeline (₹ Cr)', kind: 'funnel', categories: ['Prospecting', 'Qualification', 'Proposal', 'Negotiation'], series: [{ name: 'Value', data: [148, 112, 86, 66] }], unit: '₹Cr' },
      { title: 'Pipeline by Opportunity Owner (₹ Cr)', kind: 'hbar', categories: ['Naveen P', 'Ramya K', 'Karthik R', 'Arun S', 'Siddharth Rao'], series: [{ name: 'Pipeline', data: [118, 96, 84, 64, 50] }], unit: '₹Cr', span: 2 },
    ],
    table: { entity: 'crmOpportunity', title: 'Open Opportunities', columns: ['name', 'client', 'value', 'probability', 'expectedStart', 'stage'], limit: 8 },
    rail: [
      { kind: 'health', title: 'Lead Status (FY)', items: [{ label: 'New', value: 38, tone: 'blue' }, { label: 'Contacted', value: 22, tone: 'blue' }, { label: 'Qualified', value: 44, tone: 'green' }, { label: 'Converted', value: 40, tone: 'green' }, { label: 'Unqualified', value: 24, tone: 'gray' }, { label: 'Lost', value: 16, tone: 'red' }] },
      {
        kind: 'dates',
        title: 'Follow-ups Due',
        items: [
          { date: '2026-09-29', title: 'Share revised proposal', sub: 'Navalur Realty LLP · Ramya K' },
          { date: '2026-09-30', title: 'Site visit — Oragadam warehouse', sub: 'Meridian Industrial Parks · Naveen P' },
          { date: '2026-10-02', title: 'Technical presentation', sub: 'Coastal Healthcare Trust · Karthik R' },
          { date: '2026-10-06', title: 'Negotiation meeting', sub: 'Orbit Tech Parks · Arun S' },
        ],
      },
      {
        kind: 'list',
        title: 'Recent Activities',
        items: [
          { avatar: 'Ramya K', title: 'Ramya K logged a call', sub: 'Kovai Retail Ventures — mall enquiry', meta: '35 min ago' },
          { avatar: 'Naveen P', title: 'Naveen P moved OPP-004 to Negotiation', sub: 'IT park Phase III — Perungudi', meta: '2 hours ago' },
          { avatar: 'Karthik R', title: 'Karthik R scheduled a meeting', sub: 'Coastal Healthcare Trust', meta: '4 hours ago' },
          { avatar: 'Arun S', title: 'Arun S converted lead LD-009', sub: 'Luxury apartments — Adyar', meta: 'Yesterday' },
        ],
      },
    ],
  },
  entities: [
    {
      id: 'crmLead',
      label: 'Lead',
      plural: 'Leads',
      app: 'crm',
      codePrefix: 'LD',
      titleField: 'name',
      count: 22,
      form: 'page',
      import: true,
      sections: [
        { id: 'basic', title: 'Lead Details', icon: 'ti-user-plus' },
        { id: 'contact', title: 'Contact Information', icon: 'ti-address-book' },
        { id: 'requirement', title: 'Requirement & Value', icon: 'ti-clipboard-list' },
        { id: 'assign', title: 'Qualification & Assignment', icon: 'ti-user-check' },
      ],
      fields: [
        text('name', 'Lead / Enquiry', ['G+14 residential tower — Navalur, OMR', 'Warehouse & logistics park — Oragadam', 'Villa community (86 units) — Saravanampatti', 'Corporate office campus — Whitefield', 'Multi-specialty hospital (250 beds) — Madurai', 'IT park Phase III — Perungudi', 'Affordable housing (480 units) — Coimbatore', 'Business hotel (140 keys) — Trichy', 'Luxury apartments — Adyar', 'School campus — Hosur', 'Cold storage facility — Sriperumbudur', 'Shopping mall — Avinashi Road', 'Data centre civil works — Siruseri', 'Nursing college & hostel — Visakhapatnam', 'Plotted development infrastructure — Kelambakkam', 'Factory shed & admin block — Mahindra World City', 'Residential towers — Gachibowli', 'Resort & convention centre — Kodaikanal', 'Commercial complex — T. Nagar', 'Senior living community — Coimbatore', 'Multi-level car park — Guindy', 'Student hostel block — Hinjewadi, Pune'], { required: true, section: 'basic' }),
        text('company', 'Company', ['Navalur Realty LLP', 'Meridian Industrial Parks', 'XYZ Developers', 'Metro Constructions', 'Coastal Healthcare Trust', 'Orbit Tech Parks', 'TN Housing Partners', 'Sunrise Hospitality', 'ABC Builders Pvt Ltd', 'Greenfield Infra Ltd', 'Arctic Cold Chain Pvt Ltd', 'Kovai Retail Ventures', 'Orbit Tech Parks', 'Coastal Healthcare Trust', 'Pinnacle Realty', 'Kaveri Auto Components', 'Lakeview Estates', 'Sunrise Hospitality', 'ABC Builders Pvt Ltd', 'Serene Living Pvt Ltd', 'Chennai Metro Parking Co.', 'Pinnacle Realty'], { required: true, section: 'basic' }),
        select('source', 'Lead Source', SOURCES, { required: true, section: 'basic', gen: ['Website', 'Existing Client', 'Existing Client', 'Referral', 'Existing Client', 'Existing Client', 'Tender Portal', 'Referral', 'Existing Client', 'Tender Portal', 'Website', 'Direct Enquiry', 'Existing Client', 'Tender Portal', 'Referral', 'Direct Enquiry', 'Existing Client', 'Campaign', 'Existing Client', 'Website', 'Tender Portal', 'Referral'] }),
        select('type', 'Lead Type', PROJECT_TYPES, { section: 'basic', list: false, gen: ['Residential', 'Industrial', 'Residential', 'Commercial', 'Institutional', 'Commercial', 'Residential', 'Hospitality', 'Residential', 'Institutional', 'Industrial', 'Commercial', 'Industrial', 'Institutional', 'Infrastructure', 'Industrial', 'Residential', 'Hospitality', 'Commercial', 'Residential', 'Infrastructure', 'Institutional'] }),
        text('contact', 'Contact Person', ['Vijay Raghavan', 'Neha Kapoor', 'Anand Krishnan', 'Kiran Rao', 'Dr. Padma Rao', 'Vivek Menon', 'S. Ilangovan', 'Arvind Pillai', 'Ramesh Iyer', 'Sanjay Mehta', 'Rohan Shetty', 'P. Senthilnathan', 'Vivek Menon', 'Dr. Padma Rao', 'Rohit Deshpande', 'Ashok Kumar', 'Srinivas Reddy', 'Arvind Pillai', 'Ramesh Iyer', 'Meera Natarajan', 'T. Balasubramanian', 'Rohit Deshpande'], { section: 'contact' }),
        f('phone', 'Phone', 'phone', { section: 'contact', list: false, gen: ['+91 98401 22871', '+91 99620 44318', '+91 98430 51276', '+91 98450 77102', '+91 99490 31845', '+91 98410 66290', '+91 94432 18754', '+91 98422 60931'] }),
        f('email', 'Email', 'email', { section: 'contact', list: false, gen: ['vijay@navalurrealty.in', 'neha.kapoor@meridianparks.in', 'anand@xyzdevelopers.in', 'kiran.rao@metroconstructions.in', 'padma.rao@coastalhealth.org', 'vivek.menon@orbittechparks.in'] }),
        text('city', 'City', ['Chennai', 'Sriperumbudur', 'Coimbatore', 'Bengaluru', 'Madurai', 'Chennai', 'Coimbatore', 'Trichy', 'Chennai', 'Hosur', 'Sriperumbudur', 'Coimbatore', 'Chennai', 'Visakhapatnam', 'Chennai', 'Chengalpattu', 'Hyderabad', 'Kodaikanal', 'Chennai', 'Coimbatore', 'Chennai', 'Pune'], { section: 'contact' }),
        area('requirement', 'Requirement', ['G+14 tower, 2.1 lakh sq ft BUA, 2 basements; design by client architect.', 'Six PEB warehouse blocks with RCC admin building, 5.4 lakh sq ft.', '86 independent villas with clubhouse and internal roads.', 'Corporate campus 3.6 lakh sq ft with 3-level basement parking.', '250-bed hospital with OT complex, ICU and medical gas.', 'Two IT towers (G+12) shell & core with podium parking.'], { section: 'requirement' }),
        money('value', 'Estimated Project Value', [80000000, 1800000000], { section: 'requirement' }),
        date('expected', 'Expected Project Date', [30, 300], { section: 'requirement', list: false }),
        select('rating', 'Qualification', ['Hot', 'Warm', 'Cold'], { section: 'assign', list: false }),
        ref('owner', 'Lead Owner', 'employee', { section: 'assign' }),
        status(['New', 'Contacted', 'Qualified', 'Unqualified', 'Converted', 'Lost'], { section: 'assign', gen: ['New', 'Contacted', 'Qualified', 'Qualified', 'Converted', 'Qualified', 'New', 'Contacted', 'Converted', 'Qualified', 'New', 'Contacted', 'Qualified', 'Lost', 'New', 'Unqualified', 'Converted', 'Contacted', 'Qualified', 'New', 'Unqualified', 'Lost'] }),
      ],
    },
    {
      id: 'crmLeadSource',
      label: 'Lead Source',
      plural: 'Lead Sources',
      app: 'crm',
      codePrefix: 'LS',
      titleField: 'name',
      count: 7,
      fields: [
        text('name', 'Lead Source', SOURCES, { required: true }),
        select('channel', 'Channel', ['Digital', 'Network', 'Walk-in', 'Portal', 'Relationship', 'Marketing', 'Other'], { gen: ['Digital', 'Network', 'Walk-in', 'Portal', 'Relationship', 'Marketing', 'Other'] }),
        num('leads', 'Leads (FY)', [6, 42]),
        pct('conversion', 'Conversion Rate', [8, 38]),
        money('cost', 'Cost per Lead', [2500, 45000]),
        ref('owner', 'Source Owner', 'employee'),
        status(['Active', 'Inactive'], { gen: ['Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Inactive'] }),
      ],
    },
    {
      id: 'crmContact',
      label: 'Contact',
      plural: 'Client Contacts',
      app: 'crm',
      codePrefix: 'CT',
      titleField: 'name',
      count: 20,
      fields: [
        text('name', 'Contact Name', ['Ramesh Iyer', 'Anand Krishnan', 'Sanjay Mehta', 'Kiran Rao', 'Srinivas Reddy', 'Vivek Menon', 'Dr. Padma Rao', 'Arvind Pillai', 'Rohit Deshpande', 'Neha Kapoor', 'Lakshmi Venkatesh', 'Prabhu Shankar', 'Harini Sundar', 'Mohan Das', 'Sujatha R', 'Karthikeyan M', 'Deepa Nair', 'Ganesh Iyer', 'Anjali Kulkarni', 'Faizal Rahman'], { required: true }),
        ref('client', 'Client', 'client', { required: true }),
        text('designation', 'Designation', ['Managing Director', 'Director — Projects', 'CEO', 'VP — Construction', 'Director', 'Head — Real Estate', 'Trustee', 'GM — Projects', 'Director', 'Head — Development', 'Procurement Head', 'Chief Architect', 'Finance Controller', 'Project Manager', 'Legal Counsel', 'Senior Engineer', 'Procurement Manager', 'CFO', 'Design Manager', 'Site Coordinator']),
        select('role', 'Decision Role', ['Decision Maker', 'Influencer', 'Technical Evaluator', 'Procurement', 'Finance'], { gen: ['Decision Maker', 'Decision Maker', 'Decision Maker', 'Decision Maker', 'Decision Maker', 'Decision Maker', 'Decision Maker', 'Decision Maker', 'Decision Maker', 'Decision Maker', 'Procurement', 'Technical Evaluator', 'Finance', 'Influencer', 'Influencer', 'Technical Evaluator', 'Procurement', 'Finance', 'Technical Evaluator', 'Influencer'] }),
        f('phone', 'Mobile', 'phone', { gen: ['+91 98401 11234', '+91 98430 22871', '+91 99430 18204', '+91 98450 33190', '+91 99490 27451', '+91 98410 70266', '+91 98490 12788', '+91 98422 45310', '+91 98220 61877', '+91 99620 33012'] }),
        f('email', 'Email', 'email', { list: false, gen: ['ramesh.iyer@abcbuilders.in', 'anand@xyzdevelopers.in', 'sanjay.mehta@greenfieldinfra.in', 'kiran.rao@metroconstructions.in', 'srinivas@lakeviewestates.in', 'vivek.menon@orbittechparks.in', 'padma.rao@coastalhealth.org', 'arvind@sunrisehospitality.in'] }),
        select('primary', 'Primary Contact', ['Yes', 'No'], { gen: ['Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No'] }),
        status(['Active', 'Inactive'], { gen: ['Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Inactive', 'Active', 'Active', 'Active', 'Active', 'Inactive'] }),
      ],
    },
    {
      id: 'crmAddress',
      label: 'Client Address',
      plural: 'Client Addresses',
      app: 'crm',
      codePrefix: 'ADR',
      titleField: 'address',
      count: 16,
      fields: [
        text('address', 'Address', ['No. 14, Cathedral Road, Gopalapuram', '221, Avinashi Road, Peelamedu', 'Plot 7, SIPCOT Phase II, Bagalur Road', '5th Floor, Prestige Tech Park, Outer Ring Road', 'Plot 32, Financial District, Nanakramguda', '200 Feet Radial Road, Pallikaranai', 'Beach Road, Siripuram Junction', '18, Bypass Road, Anna Nagar', 'Survey 112, Baner–Pashan Link Road', 'Oragadam Industrial Corridor, Vallam', 'Old Mahabalipuram Road, Sholinganallur', 'Saravanampatti–Thudiyalur Road', 'Whitefield Main Road, ITPL', 'Gachibowli–Miyapur Road, Kondapur', 'Rajiv Gandhi Salai, Perungudi', 'Kurukku Salai, KK Nagar'], { required: true }),
        ref('client', 'Client', 'client', { required: true }),
        select('type', 'Address Type', ['Registered Office', 'Corporate Office', 'Billing', 'Site', 'Branch'], { gen: ['Registered Office', 'Registered Office', 'Registered Office', 'Corporate Office', 'Corporate Office', 'Registered Office', 'Registered Office', 'Registered Office', 'Corporate Office', 'Registered Office', 'Site', 'Site', 'Site', 'Site', 'Site', 'Billing'] }),
        text('city', 'City', ['Chennai', 'Coimbatore', 'Hosur', 'Bengaluru', 'Hyderabad', 'Chennai', 'Visakhapatnam', 'Madurai', 'Pune', 'Sriperumbudur', 'Chennai', 'Coimbatore', 'Bengaluru', 'Hyderabad', 'Chennai', 'Madurai']),
        text('state', 'State', ['Tamil Nadu', 'Tamil Nadu', 'Tamil Nadu', 'Karnataka', 'Telangana', 'Tamil Nadu', 'Andhra Pradesh', 'Tamil Nadu', 'Maharashtra', 'Tamil Nadu', 'Tamil Nadu', 'Tamil Nadu', 'Karnataka', 'Telangana', 'Tamil Nadu', 'Tamil Nadu']),
        text('pincode', 'PIN Code', ['600086', '641004', '635109', '560103', '500032', '600100', '530003', '625020', '411045', '602105', '600119', '641035', '560066', '500084', '600096', '625002']),
        select('gstAddress', 'GST Registered Address', ['Yes', 'No']),
        status(['Active', 'Inactive'], { gen: ['Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Inactive'] }),
      ],
    },
    {
      id: 'crmOpportunity',
      label: 'Opportunity',
      plural: 'Opportunities',
      app: 'crm',
      codePrefix: 'OPP',
      titleField: 'name',
      count: 18,
      form: 'page',
      sections: [
        { id: 'basic', title: 'Opportunity Details', icon: 'ti-target-arrow' },
        { id: 'value', title: 'Value & Timeline', icon: 'ti-currency-rupee' },
        { id: 'team', title: 'Team & Competition', icon: 'ti-users' },
      ],
      fields: [
        text('name', 'Opportunity', ['Twin residential towers — Navalur', 'Logistics park Phase 1 — Oragadam', 'Villa community — Saravanampatti', 'IT park Phase III — Perungudi', 'Corporate campus — Whitefield', 'Hospital block — Madurai', 'Affordable housing — Coimbatore', 'Business hotel — Trichy', 'Luxury apartments — Adyar', 'School campus — Hosur', 'Data centre civil works — Siruseri', 'Shopping mall — Avinashi Road', 'Nursing college — Visakhapatnam', 'Residential towers — Gachibowli', 'Resort & convention centre — Kodaikanal', 'Factory & admin block — Mahindra World City', 'Commercial complex — T. Nagar', 'Senior living community — Coimbatore'], { required: true, section: 'basic' }),
        ref('client', 'Client', 'client', { required: true, section: 'basic' }),
        ref('lead', 'Source Lead', 'crmLead', { section: 'basic', list: false }),
        text('requirement', 'Project Requirement', ['G+18, 2 towers, 3.2 lakh sq ft BUA', '6 PEB warehouses, 5.4 lakh sq ft', '120 villas + clubhouse, 12.5 acres', '2 towers G+12 shell & core, 6.2 lakh sq ft', 'Office campus 3.6 lakh sq ft, 3 basements', '250-bed hospital, 3.4 lakh sq ft', '480 EWS/LIG units, G+4 blocks', '140-key hotel with banquet, 1.1 lakh sq ft', 'G+16 luxury tower, 1.85 lakh sq ft', 'K-12 campus, 1.4 lakh sq ft', 'Tier-III data hall civil, 4.2 lakh sq ft', 'Retail mall G+4, 5.1 lakh sq ft', 'College + hostel, 1.65 lakh sq ft', '4 towers G+24, 7.8 lakh sq ft', 'Resort 90 keys + convention hall', 'Factory shed 2.2 lakh sq ft + admin', 'Commercial G+8, 2.4 lakh sq ft', 'Senior living 220 units'], { section: 'basic' }),
        select('projectType', 'Project Type', PROJECT_TYPES, { section: 'basic', list: false, gen: ['Residential', 'Industrial', 'Residential', 'Commercial', 'Commercial', 'Institutional', 'Residential', 'Hospitality', 'Residential', 'Institutional', 'Industrial', 'Commercial', 'Institutional', 'Residential', 'Hospitality', 'Industrial', 'Commercial', 'Residential'] }),
        money('value', 'Estimated Value', [180000000, 380000000], { required: true, section: 'value' }),
        pct('probability', 'Probability', [15, 85], { section: 'value' }),
        date('expectedStart', 'Expected Start', [45, 300], { section: 'value' }),
        date('expectedClose', 'Expected Close', [5, 120], { section: 'value', list: false }),
        select('stage', 'Stage', ['Prospecting', 'Qualification', 'Proposal', 'Negotiation', 'Won', 'Lost'], { required: true, section: 'basic', gen: ['Proposal', 'Qualification', 'Negotiation', 'Negotiation', 'Prospecting', 'Proposal', 'Qualification', 'Prospecting', 'Won', 'Qualification', 'Prospecting', 'Proposal', 'Lost', 'Negotiation', 'Prospecting', 'Won', 'Qualification', 'Lost'] }),
        ref('owner', 'Opportunity Owner', 'employee', { section: 'team' }),
        multi('team', 'Assigned Team', ['Business Development', 'Estimation', 'Tender', 'Design', 'Legal'], { section: 'team', list: false }),
        text('competitors', 'Competitors', ['L&T Construction, Shapoorji Pallonji', 'Ahluwalia Contracts', 'URC Construction, KEC', 'Tata Projects', 'Shapoorji Pallonji', 'L&T Construction', 'Local contractors (3)', 'NCC Ltd'], { section: 'team', list: false }),
        status(['Open', 'On Hold', 'Won', 'Lost'], { section: 'basic', gen: ['Open', 'Open', 'Open', 'Open', 'Open', 'Open', 'Open', 'On Hold', 'Won', 'Open', 'Open', 'Open', 'Lost', 'Open', 'On Hold', 'Won', 'Open', 'Lost'] }),
      ],
    },
    {
      id: 'crmMeeting',
      label: 'Meeting',
      plural: 'Meetings',
      app: 'crm',
      codePrefix: 'MTG',
      titleField: 'subject',
      count: 18,
      fields: [
        text('subject', 'Meeting Subject', ['Kick-off — requirement discussion', 'Technical presentation — methodology', 'Site visit with client architect', 'Commercial negotiation — round 2', 'Design review — concept options', 'Proposal walkthrough', 'Quarterly business review', 'Payment terms discussion', 'Pre-bid clarification meeting', 'Value engineering workshop', 'Contract signing', 'Client leadership introduction', 'Schedule & phasing review', 'Scope freeze meeting', 'Joint site inspection', 'Estimate clarification', 'Negotiation — final offer', 'Relationship review']),
        ref('client', 'Client', 'client', { required: true }),
        ref('opportunity', 'Opportunity', 'crmOpportunity'),
        date('date', 'Meeting Date', [-25, 30], { required: true }),
        select('time', 'Time', ['10:00 AM', '11:30 AM', '2:30 PM', '4:00 PM']),
        select('mode', 'Mode', ['In-person', 'Site Visit', 'Video Call']),
        ref('organiser', 'Organiser', 'employee'),
        area('minutes', 'Minutes / Outcome', ['Client shared revised area statement; estimate to be updated.', 'Methodology accepted; client asked for phasing plan.', 'Soil report requested before final pricing.', 'Agreed to 10% mobilisation advance against BG.']),
        status(['Scheduled', 'Completed', 'Cancelled'], { gen: ['Completed', 'Completed', 'Scheduled', 'Scheduled', 'Completed', 'Scheduled', 'Completed', 'Completed', 'Scheduled', 'Completed', 'Completed', 'Cancelled', 'Scheduled', 'Completed', 'Scheduled', 'Completed', 'Scheduled', 'Completed'] }),
      ],
    },
    {
      id: 'crmCall',
      label: 'Call',
      plural: 'Calls',
      app: 'crm',
      codePrefix: 'CALL',
      titleField: 'subject',
      count: 20,
      fields: [
        text('subject', 'Call Subject', ['Introductory call — new enquiry', 'Follow-up on proposal', 'Clarification on BOQ quantities', 'Meeting confirmation', 'Payment terms query', 'Site visit scheduling', 'Revised estimate discussion', 'Feedback on presentation', 'Tender addendum query', 'Reference check', 'Client callback — pricing', 'Requirement update', 'Drawing status check', 'LOI follow-up', 'Advance payment query', 'Competitor pricing insight', 'Schedule clarification', 'Contract draft comments', 'Handover of enquiry to estimation', 'Relationship check-in']),
        ref('contact', 'Contact', 'crmContact'),
        ref('client', 'Client', 'client'),
        select('direction', 'Direction', ['Outgoing', 'Incoming']),
        date('date', 'Call Date', [-20, 5]),
        num('duration', 'Duration', [3, 42], { unit: 'min' }),
        ref('by', 'Logged By', 'employee'),
        select('outcome', 'Outcome', ['Interested', 'Call Back', 'Requested Proposal', 'Meeting Fixed', 'Not Reachable', 'Not Interested'], { list: false }),
        status(['Completed', 'Scheduled', 'Follow-up Due'], { gen: ['Completed', 'Completed', 'Follow-up Due', 'Completed', 'Scheduled', 'Completed', 'Follow-up Due', 'Completed', 'Completed', 'Scheduled'] }),
      ],
    },
    {
      id: 'crmEmail',
      label: 'Email',
      plural: 'Emails',
      app: 'crm',
      codePrefix: 'EML',
      titleField: 'subject',
      count: 18,
      fields: [
        text('subject', 'Subject', ['Proposal — Twin residential towers, Navalur', 'Revised estimate R2 — IT park Phase III', 'Minutes of meeting — 18 Sep 2026', 'Request for soil investigation report', 'Company profile & past projects', 'Clarifications on tender BOQ', 'Methodology statement — hospital block', 'Meeting request — commercial negotiation', 'Pre-qualification documents', 'Updated project schedule', 'Payment terms — counter proposal', 'Letter of Intent — acknowledgement', 'Site visit confirmation — Oragadam', 'Quotation — clubhouse interiors', 'Introduction — Business Development team', 'Drawing set received — Rev C', 'Bank guarantee format', 'Thank you — contract award']),
        ref('client', 'Client', 'client'),
        text('to', 'To', ['ramesh.iyer@abcbuilders.in', 'anand@xyzdevelopers.in', 'sanjay.mehta@greenfieldinfra.in', 'kiran.rao@metroconstructions.in', 'srinivas@lakeviewestates.in', 'vivek.menon@orbittechparks.in', 'padma.rao@coastalhealth.org', 'arvind@sunrisehospitality.in']),
        ref('from', 'Sent By', 'employee'),
        select('direction', 'Direction', ['Sent', 'Received']),
        select('type', 'Email Type', ['Proposal', 'Clarification', 'Follow-up', 'Introduction', 'Meeting Request', 'Quotation']),
        date('date', 'Date', [-30, 0]),
        num('attachments', 'Attachments', [0, 5]),
        status(['Draft', 'Scheduled', 'Awaiting Reply', 'Closed'], { gen: ['Awaiting Reply', 'Awaiting Reply', 'Closed', 'Closed', 'Closed', 'Awaiting Reply', 'Closed', 'Scheduled', 'Closed', 'Draft', 'Awaiting Reply', 'Closed', 'Closed', 'Awaiting Reply', 'Closed', 'Closed', 'Draft', 'Closed'] }),
      ],
    },
    {
      id: 'crmFollowUp',
      label: 'Follow-up',
      plural: 'Follow-ups',
      app: 'crm',
      codePrefix: 'FU',
      titleField: 'subject',
      count: 20,
      info: 'Follow-ups are bucketed as Today, Upcoming, Overdue and Completed. Overdue items are escalated to the lead owner’s manager after 3 days.',
      fields: [
        text('subject', 'Follow-up', ['Share revised proposal', 'Confirm site visit date', 'Send company profile', 'Collect soil report', 'Negotiation meeting', 'Call back on pricing', 'Send pre-qualification documents', 'Technical presentation', 'Share schedule & phasing plan', 'Confirm budget approval', 'Obtain drawings Rev C', 'LOI follow-up', 'Reference visit — Skyline Apartments', 'Send quotation for clubhouse', 'Check tender addendum', 'Share BG format', 'Arrange MD meeting', 'Confirm award decision', 'Collect KYC documents', 'Share methodology statement']),
        ref('lead', 'Lead', 'crmLead'),
        ref('owner', 'Owner', 'employee'),
        date('due', 'Due Date', [-12, 14]),
        select('mode', 'Mode', ['Call', 'Email', 'Meeting', 'Site Visit']),
        select('priority', 'Priority', ['Low', 'Medium', 'High']),
        select('bucket', 'Follow-up Bucket', ['Today', 'Upcoming', 'Overdue', 'Completed'], { gen: ['Today', 'Today', 'Upcoming', 'Overdue', 'Upcoming', 'Completed', 'Today', 'Upcoming', 'Overdue', 'Completed', 'Upcoming', 'Overdue', 'Completed', 'Upcoming', 'Today', 'Completed', 'Upcoming', 'Overdue', 'Completed', 'Upcoming'] }),
        area('notes', 'Notes', ['Client expects the revised figure before the board meeting.', 'Architect to join the call.', 'Escalated to Business Development head.', 'Awaiting client confirmation.']),
        status(['Pending', 'Overdue', 'Completed'], { gen: ['Pending', 'Pending', 'Pending', 'Overdue', 'Pending', 'Completed', 'Pending', 'Pending', 'Overdue', 'Completed', 'Pending', 'Overdue', 'Completed', 'Pending', 'Pending', 'Completed', 'Pending', 'Overdue', 'Completed', 'Pending'] }),
      ],
    },
  ],
};
