import { area, date, group, money, monthCalendar, num, page, ref, register, select, status, statusView, text } from '../dsl';
import type { AppConfig } from '../types';

/* Equipment master EQ-001…016 — September 2026 usage figures (hours) */
const EQ = [
  'Tower Crane TC-5013', 'Excavator JCB 3DX', 'Excavator Hitachi EX200', 'Transit Mixer 7 cum', 'Concrete Boom Pump', 'Batching Plant CP30',
  'DG Set 250 kVA', 'DG Set 125 kVA', 'Tipper Tata Signa 2823', 'Hydra Crane 14 T', 'Mobile Crane 50 T', 'Material Hoist',
  'Vibratory Roller', 'Bar Bending Machine', 'Bar Cutting Machine', 'Pickup Mahindra Bolero',
];
const OP_HRS = [248, 212, 186, 224, 142, 236, 402, 96, 198, 164, 58, 232, 118, 176, 170, 42];
const IDLE_HRS = [42, 58, 64, 36, 88, 34, 28, 60, 52, 76, 6, 38, 80, 64, 70, 120];
const EQ_PROJECT = ['Skyline Apartments', 'Riverside Villas', 'Greenfield Township', 'Metro Office Tower', 'Lakeview Residency', 'Orbit Tech Park Phase II', 'Harbour View Hospital', 'Sunrise Business Hotel'];
const IDLE_REASON = ['Awaiting front', 'Operator shortage', 'Awaiting front', 'RMC plant shutdown', 'Pour rescheduled', 'Rain stoppage', 'Grid power available', 'Under maintenance', 'Awaiting loading', 'Awaiting front', 'Breakdown', 'Rain stoppage', 'No compaction front', 'Steel not received', 'Steel not received', 'Standby vehicle'];

export const equipmentApp: AppConfig = {
  id: 'equipment',
  name: 'Equipment',
  icon: 'ti-bulldozer',
  description: 'Plant & machinery register, ownership, allocation, usage, fuel and maintenance',
  menus: [
    group('Equipment Master', 'ti-crane', [
      page('Machinery', statusView('equipment', 'Machinery', 'category')),
      page('Vehicles', statusView('equipment', 'Vehicles', 'category')),
      page('Equipment', statusView('equipment', 'Equipment', 'category')),
    ]),
    group('Ownership', 'ti-key', [
      page('Owned', statusView('equipment', 'Owned', 'ownership')),
      page('Rented', statusView('equipment', 'Rented', 'ownership')),
      page('Leased', statusView('equipment', 'Leased', 'ownership')),
    ]),
    group('Allocation', 'ti-map-pin', [
      page('Project', register('eqProjectAlloc', { views: ['table', 'calendar'], dateField: 'from' })),
      page('Site', register('eqSiteAlloc', { views: ['table', 'board'] })),
      page('Activity', register('eqActivityAlloc', { views: ['table', 'board', 'calendar'], dateField: 'date' })),
    ]),
    group('Usage', 'ti-clock-hour-4', [
      page('Operating Hours', {
        type: 'analysis',
        title: 'Operating Hours — September 2026',
        kpis: [
          { label: 'Operating hours (Sep)', value: '2,904 hrs', delta: '+6.2%', up: true, icon: 'ti-clock-hour-4', sub: '16 assets · 26 working days' },
          { label: 'Fleet utilisation', value: '76%', delta: '+3 pts', up: true, progress: 76, icon: 'ti-gauge' },
          { label: 'Avg. hours / asset / day', value: '7.0 hrs', icon: 'ti-engine' },
          { label: 'Hour-meter readings pending', value: '3', icon: 'ti-alert-triangle', sub: 'Lakeview · Harbour View' },
        ],
        charts: [
          { title: 'Operating Hours by Equipment (Sep)', kind: 'hbar', categories: EQ, series: [{ name: 'Operating hrs', data: OP_HRS }], span: 2, height: 380 },
          { title: 'Operating vs Idle Hours — Monthly', kind: 'stacked', categories: ['Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep'], series: [{ name: 'Operating', data: [2610, 2720, 2480, 2590, 2735, 2904] }, { name: 'Idle', data: [1080, 1010, 1240, 1120, 980, 916] }] },
        ],
        table: {
          title: 'Hour-meter Log — September 2026',
          columns: [
            { key: 'eq', label: 'Equipment', type: 'code' },
            { key: 'name', label: 'Equipment Name' },
            { key: 'project', label: 'Project' },
            { key: 'op', label: 'Operating hrs', type: 'number' },
            { key: 'avail', label: 'Available hrs', type: 'number' },
            { key: 'util', label: 'Utilisation', type: 'percent' },
          ],
          rows: EQ.map((n, i) => ({ eq: `EQ-${String(i + 1).padStart(3, '0')}`, name: n, project: EQ_PROJECT[i % 8], op: OP_HRS[i], avail: OP_HRS[i] + IDLE_HRS[i], util: Math.round((OP_HRS[i] / (OP_HRS[i] + IDLE_HRS[i])) * 100) })),
        },
      }),
      page('Idle Hours', {
        type: 'analysis',
        title: 'Idle Hours — September 2026',
        kpis: [
          { label: 'Idle hours (Sep)', value: '916 hrs', delta: '-6.5%', up: false, good: true, icon: 'ti-clock-pause' },
          { label: 'Idle cost (rented assets)', value: '₹ 3.8 L', icon: 'ti-currency-rupee', sub: 'Hire charges paid while idle' },
          { label: 'Top idle reason', value: 'Awaiting front', icon: 'ti-hourglass', sub: '31% of idle hours' },
          { label: 'Assets idle > 25%', value: '5', icon: 'ti-alert-triangle' },
        ],
        charts: [
          { title: 'Idle Hours by Reason', kind: 'donut', categories: ['Awaiting front', 'Rain stoppage', 'Operator shortage', 'Material not received', 'Maintenance / breakdown', 'Standby'], series: [{ name: 'Hours', data: [284, 172, 118, 134, 88, 120] }] },
          { title: 'Idle Hours by Equipment (Sep)', kind: 'bar', categories: EQ.map((n) => n.split(' ').slice(0, 2).join(' ')), series: [{ name: 'Idle hrs', data: IDLE_HRS }], span: 2 },
        ],
        table: {
          title: 'Idle Time Register',
          columns: [
            { key: 'eq', label: 'Equipment', type: 'code' },
            { key: 'name', label: 'Equipment Name' },
            { key: 'idle', label: 'Idle hrs', type: 'number' },
            { key: 'share', label: 'Idle %', type: 'percent' },
            { key: 'reason', label: 'Main Reason' },
          ],
          rows: EQ.map((n, i) => ({ eq: `EQ-${String(i + 1).padStart(3, '0')}`, name: n, idle: IDLE_HRS[i], share: Math.round((IDLE_HRS[i] / (OP_HRS[i] + IDLE_HRS[i])) * 100), reason: IDLE_REASON[i] })),
        },
      }),
      page('Production', {
        type: 'analysis',
        title: 'Equipment Production — September 2026',
        kpis: [
          { label: 'Concrete produced (CP30)', value: '3,420 cum', delta: '+8%', up: true, icon: 'ti-building-factory-2' },
          { label: 'Concrete pumped', value: '2,860 cum', icon: 'ti-droplet' },
          { label: 'Earth excavated', value: '18,400 cum', icon: 'ti-bulldozer' },
          { label: 'Tower crane lifts', value: '2,940', icon: 'ti-crane', sub: 'Avg. 113 lifts / day' },
        ],
        charts: [
          { title: 'Output per Operating Hour vs Target', kind: 'bar', categories: ['Batching Plant', 'Boom Pump', 'Hitachi EX200', 'JCB 3DX', 'Transit Mixer', 'Tower Crane'], series: [{ name: 'Actual / hr', data: [14.5, 20.1, 62, 24, 2.2, 11.9] }, { name: 'Target / hr', data: [18, 22, 70, 25, 2.5, 12] }], span: 2 },
          { title: 'Production Trend — Concrete (cum)', kind: 'line', categories: ['Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep'], series: [{ name: 'Produced', data: [2950, 3110, 2680, 2890, 3160, 3420] }, { name: 'Pumped', data: [2380, 2560, 2240, 2410, 2620, 2860] }] },
        ],
        table: {
          title: 'Production Log by Equipment',
          columns: [
            { key: 'eq', label: 'Equipment', type: 'code' },
            { key: 'name', label: 'Equipment Name' },
            { key: 'output', label: 'Output', type: 'number' },
            { key: 'unit', label: 'Unit' },
            { key: 'hrs', label: 'Operating hrs', type: 'number' },
            { key: 'rate', label: 'Output / hr', type: 'number' },
            { key: 'status', label: 'Against Target', type: 'status' },
          ],
          rows: [
            { eq: 'EQ-006', name: 'Batching Plant CP30', output: 3420, unit: 'cum', hrs: 236, rate: 14.5, status: 'At Risk' },
            { eq: 'EQ-005', name: 'Concrete Boom Pump', output: 2860, unit: 'cum', hrs: 142, rate: 20.1, status: 'On Track' },
            { eq: 'EQ-003', name: 'Excavator Hitachi EX200', output: 11530, unit: 'cum', hrs: 186, rate: 62.0, status: 'At Risk' },
            { eq: 'EQ-002', name: 'Excavator JCB 3DX', output: 5090, unit: 'cum', hrs: 212, rate: 24.0, status: 'On Track' },
            { eq: 'EQ-004', name: 'Transit Mixer 7 cum', output: 486, unit: 'trips', hrs: 224, rate: 2.2, status: 'At Risk' },
            { eq: 'EQ-009', name: 'Tipper Tata Signa 2823', output: 1120, unit: 'trips', hrs: 198, rate: 5.7, status: 'On Track' },
            { eq: 'EQ-001', name: 'Tower Crane TC-5013', output: 2940, unit: 'lifts', hrs: 248, rate: 11.9, status: 'On Track' },
            { eq: 'EQ-012', name: 'Material Hoist', output: 1860, unit: 'trips', hrs: 232, rate: 8.0, status: 'On Track' },
            { eq: 'EQ-014', name: 'Bar Bending Machine', output: 212, unit: 'MT', hrs: 176, rate: 1.2, status: 'On Track' },
            { eq: 'EQ-013', name: 'Vibratory Roller', output: 9400, unit: 'sqm', hrs: 118, rate: 79.7, status: 'Critical' },
          ],
        },
      }),
    ]),
    group('Fuel', 'ti-gas-station', [
      page('Fuel Issue', register('eqFuelIssue', { views: ['table', 'calendar'], dateField: 'date' })),
      page('Consumption', {
        type: 'analysis',
        title: 'Fuel Consumption — September 2026',
        kpis: [
          { label: 'HSD consumed (Sep)', value: '27,700 L', delta: '+4.9%', up: true, good: false, icon: 'ti-gas-station' },
          { label: 'Fuel cost (Sep)', value: '₹ 25.5 L', icon: 'ti-currency-rupee', sub: '@ ₹ 92 / L average' },
          { label: 'Bowser stock', value: '6,400 L', progress: 64, icon: 'ti-barrel', sub: 'Capacity 10,000 L' },
          { label: 'Fuel receipts (Sep)', value: '7 loads', icon: 'ti-truck', sub: 'Coastal Fuel Services' },
        ],
        charts: [
          { title: 'Monthly Fuel Consumption (L)', kind: 'area', categories: ['Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep'], series: [{ name: 'Litres', data: [24100, 25300, 22800, 23900, 26400, 27700] }], span: 2 },
          { title: 'Consumption by Project (Sep, L)', kind: 'donut', categories: ['Skyline', 'Metro Tower', 'Greenfield', 'Riverside', 'Lakeview', 'Others'], series: [{ name: 'Litres', data: [9850, 6120, 4960, 2740, 1980, 2050] }] },
          { title: 'Consumption by Equipment (Sep, L)', kind: 'hbar', categories: ['DG Set 250 kVA', 'Excavator EX200', 'Boom Pump', 'DG Set 125 kVA', 'Transit Mixer', 'Tipper', 'Roller', 'JCB 3DX', 'Hydra 14 T', 'Mobile Crane', 'Bolero'], series: [{ name: 'Litres', data: [13260, 2790, 2190, 1930, 1650, 1580, 1160, 1120, 950, 760, 310] }], span: 3, height: 320 },
        ],
      }),
      page('Efficiency', {
        type: 'analysis',
        title: 'Fuel Efficiency vs Norms',
        kpis: [
          { label: 'Assets within norm', value: '6 / 11', progress: 55, icon: 'ti-gauge' },
          { label: 'Excess consumption (Sep)', value: '1,140 L', icon: 'ti-alert-triangle', sub: '≈ ₹ 1.05 L' },
          { label: 'DG specific consumption', value: '3.4 kWh / L', icon: 'ti-engine' },
          { label: 'Worst performer', value: 'Bolero +23%', icon: 'ti-truck' },
        ],
        charts: [
          { title: 'Actual vs Norm (L / hr)', kind: 'bar', categories: ['DG 250', 'DG 125', 'EX200', 'JCB 3DX', 'Boom Pump', 'Transit Mixer', 'Tipper', 'Hydra', 'Mobile Crane', 'Roller', 'Bolero'], series: [{ name: 'Actual', data: [33.0, 20.1, 15.0, 5.3, 15.4, 7.4, 8.0, 5.8, 13.1, 9.8, 7.4] }, { name: 'Norm', data: [34, 18, 14, 5.5, 16, 7, 7.5, 6, 12, 9, 6] }], span: 2 },
          { title: 'Fleet Fuel Efficiency Index', kind: 'gauge', series: [{ name: 'Index', data: [91] }], unit: '%' },
        ],
        table: {
          title: 'Efficiency Register — September 2026',
          columns: [
            { key: 'name', label: 'Equipment' },
            { key: 'hrs', label: 'Operating hrs', type: 'number' },
            { key: 'litres', label: 'Fuel (L)', type: 'number' },
            { key: 'actual', label: 'Actual L/hr', type: 'number' },
            { key: 'norm', label: 'Norm L/hr', type: 'number' },
            { key: 'status', label: 'Status', type: 'status' },
          ],
          rows: [
            { name: 'DG Set 250 kVA', hrs: 402, litres: 13260, actual: 33.0, norm: 34, status: 'On Track' },
            { name: 'DG Set 125 kVA', hrs: 96, litres: 1930, actual: 20.1, norm: 18, status: 'At Risk' },
            { name: 'Excavator Hitachi EX200', hrs: 186, litres: 2790, actual: 15.0, norm: 14, status: 'At Risk' },
            { name: 'Excavator JCB 3DX', hrs: 212, litres: 1120, actual: 5.3, norm: 5.5, status: 'On Track' },
            { name: 'Concrete Boom Pump', hrs: 142, litres: 2190, actual: 15.4, norm: 16, status: 'On Track' },
            { name: 'Transit Mixer 7 cum', hrs: 224, litres: 1650, actual: 7.4, norm: 7, status: 'On Track' },
            { name: 'Tipper Tata Signa 2823', hrs: 198, litres: 1580, actual: 8.0, norm: 7.5, status: 'At Risk' },
            { name: 'Hydra Crane 14 T', hrs: 164, litres: 950, actual: 5.8, norm: 6, status: 'On Track' },
            { name: 'Mobile Crane 50 T', hrs: 58, litres: 760, actual: 13.1, norm: 12, status: 'At Risk' },
            { name: 'Vibratory Roller', hrs: 118, litres: 1160, actual: 9.8, norm: 9, status: 'On Track' },
            { name: 'Pickup Mahindra Bolero', hrs: 42, litres: 310, actual: 7.4, norm: 6, status: 'Critical' },
          ],
        },
      }),
    ]),
    group('Maintenance', 'ti-tool', [
      page('Preventive', monthCalendar('Preventive Maintenance Schedule', 'eqPmSchedule', 'due')),
      page('Breakdown', register('eqBreakdown', { views: ['table', 'board'] })),
      page('Repair', register('eqRepair', { views: ['table', 'board'] })),
    ]),
  ],
  dashboard: {
    flow: [
      { label: 'Fleet', value: '16 assets' },
      { label: 'Deployed', value: '13 in use' },
      { label: 'Utilisation', value: '76% (Sep)' },
      { label: 'Maintenance', value: '1 in workshop' },
      { label: 'Breakdown', value: '1 open · 46 hrs down' },
    ],
    kpis: [
      { label: 'Total Equipment', value: '16', sub: '10 owned · 4 rented · 2 leased', progress: 100, icon: 'ti-bulldozer' },
      { label: 'Fleet Utilisation', value: '76%', delta: '+3 pts', up: true, progress: 76, icon: 'ti-gauge' },
      { label: 'Operating Hours (Sep)', value: '2,904 hrs', delta: '+6.2%', up: true, progress: 76, icon: 'ti-clock-hour-4' },
      { label: 'Fuel Cost (Sep)', value: '₹ 25.5 L', delta: '+4.9%', up: true, good: false, progress: 58, icon: 'ti-gas-station' },
      { label: 'Maintenance Cost (Sep)', value: '₹ 6.8 L', delta: '-12%', up: false, good: true, progress: 42, icon: 'ti-tool' },
    ],
    charts: [
      { title: 'Utilisation Trend', kind: 'barline', categories: ['Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep'], series: [{ name: 'Operating hrs', data: [2610, 2720, 2480, 2590, 2735, 2904], type: 'bar' }, { name: 'Idle hrs', data: [1080, 1010, 1240, 1120, 980, 916], type: 'bar' }, { name: 'Utilisation %', data: [71, 73, 67, 70, 74, 76], type: 'line' }], span: 2 },
      { title: 'Fleet by Status', kind: 'donut', categories: ['In Use', 'Idle', 'Under Maintenance', 'Breakdown'], series: [{ name: 'Assets', data: [13, 1, 1, 1] }], tones: ['blue', 'yellow', 'yellow', 'red'], subtitle: '16 assets' },
      { title: 'Equipment Cost Mix (Sep, ₹ L)', kind: 'hbar', categories: ['Hire charges', 'Fuel', 'Operator wages', 'Maintenance', 'Lease rentals', 'Insurance'], series: [{ name: '₹ L', data: [18.4, 25.5, 14.2, 6.8, 9.6, 1.9] }], unit: '₹L' },
      { title: 'Fuel Consumption (kL)', kind: 'line', categories: ['Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep'], series: [{ name: 'kL', data: [24.1, 25.3, 22.8, 23.9, 26.4, 27.7] }] },
    ],
    table: { entity: 'equipment', title: 'Equipment Register', columns: ['name', 'category', 'ownership', 'project', 'hours', 'status'], limit: 8 },
    rail: [
      { kind: 'health', title: 'Fleet Health', items: [{ label: 'In Use', value: 13, tone: 'blue' }, { label: 'Idle', value: 1, tone: 'yellow' }, { label: 'Under Maintenance', value: 1, tone: 'yellow' }, { label: 'Breakdown', value: 1, tone: 'red' }] },
      {
        kind: 'dates',
        title: 'Upcoming Services',
        items: [
          { date: '2026-10-02', title: '500-hr service — Tower Crane TC-5013', sub: 'Skyline Apartments' },
          { date: '2026-10-06', title: '250-hr service — Transit Mixer', sub: 'Metro Office Tower' },
          { date: '2026-10-11', title: 'Load test & certification — Material Hoist', sub: 'Skyline Apartments' },
          { date: '2026-10-18', title: 'Rental renewal — Excavator Hitachi EX200', sub: 'Greenfield Township' },
        ],
      },
      {
        kind: 'list',
        title: 'Recent Events',
        items: [
          { avatar: 'Farhan Ali', title: 'Breakdown logged — Mobile Crane 50 T', sub: 'Slew ring bearing failure · Orbit Tech Park', meta: '3 hours ago', status: 'Open' },
          { avatar: 'Murugan S', title: 'Fuel issued — 420 L to DG Set 250 kVA', sub: 'Skyline Apartments', meta: '5 hours ago' },
          { avatar: 'Selvam K', title: 'Hour-meter updated — Excavator JCB 3DX', sub: '6,284 hrs', meta: 'Yesterday' },
          { avatar: 'Farhan Ali', title: 'DG Set 125 kVA sent for overhaul', sub: 'Cummins service centre', meta: '2 days ago', status: 'In Progress' },
        ],
      },
    ],
  },
  entities: [
    {
      id: 'eqProjectAlloc',
      label: 'Project Allocation',
      plural: 'Project Allocations',
      app: 'equipment',
      codePrefix: 'EPA',
      titleField: 'equipment',
      count: 18,
      fields: [
        ref('equipment', 'Equipment', 'equipment', { required: true }),
        ref('project', 'Project', 'project', { required: true }),
        date('from', 'Allocated From', [-160, -5]),
        date('to', 'Allocated Till', [10, 180]),
        num('plannedHrs', 'Planned Hours / Month', [120, 280], { unit: 'hrs' }),
        money('rate', 'Internal Hire Rate / hr', [650, 6800]),
        ref('allocatedBy', 'Allocated By', 'employee'),
        status(['Allocated', 'Released', 'Planned'], { gen: ['Allocated', 'Allocated', 'Allocated', 'Allocated', 'Allocated', 'Allocated', 'Released', 'Allocated', 'Allocated', 'Planned', 'Allocated', 'Allocated', 'Released', 'Allocated', 'Allocated', 'Planned', 'Allocated', 'Allocated'] }),
      ],
    },
    {
      id: 'eqSiteAlloc',
      label: 'Site Deployment',
      plural: 'Site Deployments',
      app: 'equipment',
      codePrefix: 'ESD',
      titleField: 'equipment',
      count: 16,
      fields: [
        ref('equipment', 'Equipment', 'equipment', { required: true }),
        ref('site', 'Site', 'site', { required: true }),
        text('location', 'Location at Site', ['Tower A — north face', 'Batching yard', 'Tower B — core', 'Basement ramp', 'Block C excavation', 'Material yard', 'DG yard', 'Podium level', 'Clubhouse plot', 'Internal road — Phase 2', 'Steel yard', 'Hoist bay — Tower A', 'STP area', 'Main gate', 'Villa cluster 4', 'Hospital block — east wing']),
        ref('operator', 'Operator', 'employee'),
        select('shift', 'Shift', ['General', 'Day (2 shifts)', 'Round the clock']),
        date('mobilised', 'Mobilised On', [-200, -3]),
        status(['Deployed', 'In Transit', 'Released'], { gen: ['Deployed', 'Deployed', 'Deployed', 'Deployed', 'In Transit', 'Deployed', 'Deployed', 'Deployed', 'Released', 'Deployed', 'Deployed', 'Deployed', 'Deployed', 'In Transit', 'Deployed', 'Deployed'] }),
      ],
    },
    {
      id: 'eqActivityAlloc',
      label: 'Activity Allocation',
      plural: 'Activity Allocations',
      app: 'equipment',
      codePrefix: 'EAA',
      titleField: 'activity',
      count: 20,
      fields: [
        text('activity', 'Activity', ['Slab concreting L14 — Tower B', 'Column casting L15 — Tower B', 'Excavation — Block C', 'Raft concreting — Clubhouse', 'Steel lifting — Tower A', 'Blockwork material hoisting', 'Backfilling & compaction — Road 2', 'Soil disposal — Basement 2', 'Precast lintel erection', 'Façade bracket lifting', 'Sub-base compaction — Internal roads', 'Power backup — night pour', 'Bar bending — L15 slab', 'Trench excavation — storm drain', 'Transit of RMC — Tower B pour', 'Shuttering shifting — L14 to L15', 'Lift machine room lifting', 'Water tank concreting', 'Retaining wall backfill', 'Terrace material shifting'], { required: true }),
        ref('equipment', 'Equipment', 'equipment', { required: true }),
        ref('project', 'Project', 'project'),
        date('date', 'Planned Date', [-12, 18]),
        num('plannedHrs', 'Planned Hours', [4, 16], { unit: 'hrs' }),
        num('actualHrs', 'Actual Hours', [0, 16], { unit: 'hrs' }),
        ref('supervisor', 'Supervisor', 'employee'),
        status(['Scheduled', 'In Progress', 'Completed'], { gen: ['In Progress', 'Scheduled', 'Completed', 'Completed', 'In Progress', 'Scheduled', 'Completed', 'Completed', 'Scheduled', 'In Progress', 'Completed', 'Completed', 'Scheduled', 'Completed', 'In Progress', 'Scheduled', 'Scheduled', 'Completed', 'Completed', 'Scheduled'] }),
      ],
    },
    {
      id: 'eqFuelIssue',
      label: 'Fuel Issue',
      plural: 'Fuel Issues',
      app: 'equipment',
      codePrefix: 'FI',
      titleField: 'slip',
      count: 22,
      fields: [
        text('slip', 'Fuel Slip No.', ['FS/SKY/0921', 'FS/MOT/0412', 'FS/SKY/0922', 'FS/GFT/0388', 'FS/SKY/0923', 'FS/RVV/0214', 'FS/MOT/0413', 'FS/LKR/0156', 'FS/SKY/0924', 'FS/GFT/0389', 'FS/OTP/0301', 'FS/SKY/0925', 'FS/MOT/0414', 'FS/HVH/0122', 'FS/SBH/0098', 'FS/SKY/0926', 'FS/GFT/0390', 'FS/RVV/0215', 'FS/MOT/0415', 'FS/SKY/0927', 'FS/LKR/0157', 'FS/SKY/0928'], { required: true }),
        ref('equipment', 'Equipment', 'equipment', { required: true }),
        ref('project', 'Project', 'project'),
        date('date', 'Issue Date', [-26, 0]),
        num('qty', 'Quantity', [60, 480], { unit: 'L', required: true }),
        money('rate', 'Rate / L', [91, 94]),
        num('meter', 'Hour-meter Reading', [1200, 8600], { unit: 'hrs' }),
        select('source', 'Source', ['Site bowser', 'Coastal Fuel Services — direct', 'Barrel stock']),
        ref('issuedBy', 'Issued By', 'employee', { list: false }),
        status(['Issued', 'Pending', 'Approved'], { gen: ['Approved', 'Approved', 'Issued', 'Approved', 'Issued', 'Approved', 'Approved', 'Pending', 'Issued', 'Approved', 'Approved', 'Issued', 'Approved', 'Pending', 'Approved', 'Issued', 'Approved', 'Approved', 'Issued', 'Approved', 'Pending', 'Issued'] }),
      ],
    },
    {
      id: 'eqPmSchedule',
      label: 'Maintenance Task',
      plural: 'Preventive Maintenance',
      app: 'equipment',
      codePrefix: 'PM',
      titleField: 'task',
      count: 22,
      fields: [
        text('task', 'Maintenance Task', ['500-hr service — Tower Crane TC-5013', '250-hr service — Excavator JCB 3DX', 'Hydraulic oil change — EX200', '250-hr service — Transit Mixer', 'Boom pump pipeline inspection', 'Batching plant calibration', 'DG 250 kVA — 1000-hr overhaul', 'DG 125 kVA — top overhaul', 'Tipper — brake & tyre check', 'Hydra — wire rope inspection', 'Mobile crane — annual load test', 'Material hoist — safety device test', 'Vibratory roller — drum bearing grease', 'Bar bender — gearbox oil', 'Bar cutter — blade replacement', 'Bolero — 20,000 km service', 'Tower crane — anemometer calibration', 'JCB — air filter replacement', 'Transit mixer — drum roller check', 'DG 250 kVA — battery & coolant check', 'Hoist — rack & pinion lubrication', 'Boom pump — wear parts replacement'], { required: true }),
        ref('equipment', 'Equipment', 'equipment', { required: true }),
        select('type', 'Schedule Type', ['250-hr', '500-hr', '1000-hr', 'Monthly', 'Quarterly', 'Statutory']),
        date('due', 'Due Date', [-18, 40], { required: true }),
        num('meter', 'Due at Hour-meter', [800, 9000], { unit: 'hrs' }),
        ref('technician', 'Technician', 'employee'),
        money('estCost', 'Estimated Cost', [4500, 185000]),
        status(['Scheduled', 'Completed', 'Overdue', 'Pending'], { gen: ['Scheduled', 'Completed', 'Scheduled', 'Scheduled', 'Completed', 'Overdue', 'Scheduled', 'Pending', 'Completed', 'Scheduled', 'Scheduled', 'Completed', 'Scheduled', 'Completed', 'Scheduled', 'Pending', 'Scheduled', 'Completed', 'Scheduled', 'Overdue', 'Scheduled', 'Scheduled'] }),
      ],
    },
    {
      id: 'eqBreakdown',
      label: 'Breakdown',
      plural: 'Breakdowns',
      app: 'equipment',
      codePrefix: 'BD',
      titleField: 'issue',
      count: 14,
      form: 'page',
      sections: [
        { id: 'basic', title: 'Breakdown Details', icon: 'ti-alert-triangle' },
        { id: 'impact', title: 'Downtime & Cost', icon: 'ti-clock-pause' },
      ],
      fields: [
        text('issue', 'Breakdown', ['Slew ring bearing failure', 'Hydraulic hose burst — boom arm', 'Engine overheating', 'Drum motor failure', 'Pipeline blockage — boom pump', 'Mixer shaft seal leakage', 'Alternator AVR failure', 'Fuel injection pump fault', 'Tipper hydraulic cylinder leak', 'Wire rope damage — hoist drum', 'Hoist limit switch failure', 'Vibration motor failure', 'Clutch plate worn out', 'Starter motor failure'], { required: true, section: 'basic' }),
        ref('equipment', 'Equipment', 'equipment', { required: true, section: 'basic' }),
        ref('project', 'Project', 'project', { section: 'basic' }),
        date('reported', 'Reported On', [-60, 0], { section: 'basic' }),
        select('cause', 'Root Cause', ['Wear & tear', 'Operator error', 'Overloading', 'Poor maintenance', 'Component failure', 'Electrical fault'], { section: 'basic' }),
        num('downtime', 'Downtime', [4, 96], { unit: 'hrs', section: 'impact' }),
        money('cost', 'Repair Cost', [8500, 420000], { section: 'impact' }),
        select('repairBy', 'Repair By', ['In-house workshop', 'OEM service', 'Rental vendor'], { section: 'impact' }),
        area('action', 'Action Taken', ['OEM engineer called; bearing replacement in progress.', 'Hose replaced from site stock; machine back in service.', 'Radiator flushed and coolant replaced.', 'Standby equipment mobilised from Riverside site.', 'Vendor replaced unit under rental agreement.'], { section: 'impact' }),
        status(['Open', 'In Progress', 'Resolved', 'Closed'], { gen: ['Open', 'In Progress', 'Resolved', 'Closed', 'Resolved', 'Closed', 'In Progress', 'Closed', 'Resolved', 'Closed', 'Closed', 'Resolved', 'Closed', 'Closed'], section: 'basic' }),
      ],
    },
    {
      id: 'eqRepair',
      label: 'Repair Job',
      plural: 'Repair Jobs',
      app: 'equipment',
      codePrefix: 'RJ',
      titleField: 'job',
      count: 14,
      form: 'page',
      fields: [
        text('job', 'Repair Job', ['Slew ring bearing replacement', 'Boom hydraulic hose replacement', 'Radiator overhaul', 'Drum motor rewinding', 'Boom pump pipeline & reducer replacement', 'Mixer shaft seal replacement', 'AVR replacement', 'Fuel injection pump calibration', 'Hydraulic cylinder re-sealing', 'Wire rope replacement', 'Limit switch replacement', 'Vibration motor rewinding', 'Clutch plate replacement', 'Starter motor replacement'], { required: true }),
        ref('equipment', 'Equipment', 'equipment', { required: true }),
        ref('breakdown', 'Breakdown Ref', 'eqBreakdown'),
        text('workshop', 'Workshop / Vendor', ['Liebherr service — Chennai', 'In-house workshop — Skyline', 'Tata Motors dealer', 'Kirloskar authorised service', 'Schwing Stetter service', 'In-house workshop — Metro', 'Cummins service centre', 'Crane Hire India', 'In-house workshop — Greenfield']),
        date('start', 'Start Date', [-55, -1]),
        date('finish', 'Completion Date', [-20, 12]),
        money('parts', 'Spares Cost', [4500, 360000]),
        money('labour', 'Labour Cost', [2500, 65000]),
        status(['Pending Approval', 'Awaiting Parts', 'In Progress', 'Completed'], { gen: ['In Progress', 'Completed', 'Completed', 'Awaiting Parts', 'Completed', 'Completed', 'In Progress', 'Completed', 'Pending Approval', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed'] }),
      ],
    },
  ],
};

