import { approval, area, board, date, docs, group, money, num, page, pct, ref, register, select, status, text, lineItemsNoTax } from '../dsl';
import type { AppConfig } from '../types';

/* ───────── Assets handed over (aligned description / unit / qty / rate / section) ───────── */
const ASSETS: [string, string, number, number, string][] = [
  ['Passenger lift 13-passenger, 1.75 m/s (G+14)', 'Nos', 4, 3850000, 'Lifts & Escalators'],
  ['Service / stretcher lift 20-passenger', 'Nos', 2, 4420000, 'Lifts & Escalators'],
  ['Fireman lift with ARD', 'Nos', 1, 4180000, 'Lifts & Escalators'],
  ['DG set 750 kVA with AMF panel & acoustic enclosure', 'Nos', 2, 7250000, 'Electrical & DG'],
  ['Transformer 1600 kVA dry type', 'Nos', 2, 2860000, 'Electrical & DG'],
  ['LT panel — main distribution (MDB)', 'Set', 1, 3420000, 'Electrical & DG'],
  ['Solar rooftop PV system 120 kWp', 'Lot', 1, 5640000, 'Electrical & DG'],
  ['Air-cooled chiller 250 TR', 'Nos', 2, 9860000, 'HVAC'],
  ['AHU 15,000 CFM with VFD', 'Nos', 6, 1240000, 'HVAC'],
  ['Basement ventilation jet fans', 'Nos', 18, 96000, 'HVAC'],
  ['Fire hydrant & sprinkler pump set (main + jockey + diesel)', 'Set', 1, 4680000, 'Fire Fighting'],
  ['Addressable fire alarm panel (8-loop)', 'Nos', 1, 1860000, 'Fire Fighting'],
  ['Fire extinguishers — ABC 6 kg', 'Nos', 164, 3200, 'Fire Fighting'],
  ['Sewage treatment plant 250 KLD (MBBR)', 'Lot', 1, 8840000, 'Plumbing & STP'],
  ['Hydro-pneumatic pumping system', 'Set', 2, 980000, 'Plumbing & STP'],
  ['Water treatment plant 150 KLD (softener + RO)', 'Lot', 1, 2640000, 'Plumbing & STP'],
  ['CCTV system — 128 cameras with NVR', 'Lot', 1, 3120000, 'Security & BMS'],
  ['Boom barriers & RFID access control', 'Set', 4, 385000, 'Security & BMS'],
  ['Building management system (BMS) head-end', 'Lot', 1, 4260000, 'Security & BMS'],
  ['Video door phones — apartments', 'Nos', 224, 14500, 'Security & BMS'],
];

const MAKES = ['KONE MonoSpace 700', 'KONE TranSys', 'KONE MonoSpace 700', 'Cummins C750D5', 'Schneider Trihal', 'L&T SmartPanel', 'Tata Power Solar', 'Daikin EWAD-TZ', 'Blue Star BSAHU', 'Systemair AJ8', 'Kirloskar KFP', 'Honeywell Notifier NFS2', 'Ceasefire ABC-6', 'Thermax MBBR-250', 'Grundfos Hydro MPC', 'Ion Exchange ROX', 'Hikvision DS-96128', 'ZKTeco ProBG', 'Honeywell EBI R600', 'CP Plus VDP-7'];
const SERIALS = ['LFT-A1…A4', 'LFT-S1, S2', 'LFT-F1', 'DG-01, DG-02', 'TR-01, TR-02', 'MDB-01', 'PV-01', 'CH-01, CH-02', 'AHU-01…06', 'JF-01…18', 'FP-01', 'FAP-01', 'FE-001…164', 'STP-01', 'HP-01, HP-02', 'WTP-01', 'CCTV-NVR-01', 'BB-01…04', 'BMS-01', 'VDP-001…224'];

/* ───────── Completion % by project / area ───────── */
const AREAS = ['Structure', 'Masonry & Plaster', 'MEP', 'Finishes', 'External Works'];
const COMPLETION: [string, number[], number, number][] = [
  ['Skyline Apartments', [100, 96, 78, 64, 30], 68, 42],
  ['Riverside Villas', [92, 70, 48, 32, 12], 45, 18],
  ['Greenfield Township', [62, 38, 22, 12, 8], 32, 6],
  ['Metro Office Tower', [88, 72, 50, 34, 16], 55, 24],
  ['Lakeview Residency', [58, 30, 14, 6, 4], 28, 0],
  ['Orbit Tech Park Phase II', [100, 100, 96, 90, 78], 92, 86],
  ['Harbour View Hospital', [100, 98, 86, 72, 50], 84, 38],
  ['Sunrise Business Hotel', [100, 94, 74, 60, 42], 76, 12],
];

export const handoverApp: AppConfig = {
  id: 'handover',
  name: 'Handover',
  icon: 'ti-key',
  description: 'Completion, final inspection, snag rectification, handover documents, client acceptance and warranty',
  menus: [
    group('Completion', 'ti-flag-check', [
      page('Work Completion', {
        type: 'analysis',
        title: 'Work Completion',
        kpis: [
          { label: 'Portfolio completion', value: '60%', delta: '+4 pt', up: true, progress: 60, icon: 'ti-chart-donut', sub: 'Weighted by contract value' },
          { label: 'Projects in handover stage', value: '3', icon: 'ti-key', sub: 'Orbit TP · Harbour View · Skyline T-A' },
          { label: 'Completion certificates issued', value: '4', delta: '+1', up: true, icon: 'ti-certificate' },
          { label: 'Units handed over', value: '312 / 1,146', progress: 27, icon: 'ti-home-check' },
        ],
        charts: [
          { title: 'Completion by Project', kind: 'hbar', categories: COMPLETION.map((c) => c[0]), series: [{ name: 'Completion', data: COMPLETION.map((c) => c[2]) }], unit: '%' },
          { title: 'Completion % by Project and Area', kind: 'heatmap', categories: AREAS, yCategories: COMPLETION.map((c) => c[0]), series: [{ name: 'Completion %', data: COMPLETION.flatMap((c) => c[1]) }], span: 2, height: 300 },
        ],
        table: {
          title: 'Area-wise Completion Status',
          columns: [
            { key: 'project', label: 'Project' },
            ...AREAS.map((a, i) => ({ key: `a${i}`, label: a, type: 'percent' as const })),
            { key: 'overall', label: 'Overall', type: 'percent' },
            { key: 'handed', label: 'Handed Over', type: 'percent' },
            { key: 'status', label: 'Status', type: 'status' },
          ],
          rows: COMPLETION.map(([project, areas, overall, handed]) => ({
            project,
            ...Object.fromEntries(areas.map((v, i) => [`a${i}`, v])),
            overall,
            handed,
            status: overall >= 90 ? 'Handover in Progress' : overall >= 50 ? 'In Progress' : overall >= 30 ? 'At Risk' : 'Delayed',
          })),
        },
      }),
      page('Completion Certificate', {
        type: 'print',
        entity: 'hoCompletion',
        docTitle: 'Completion Certificate',
        lines: {
          columns: ['Scope Item', 'Contract Qty', 'Executed Qty', 'Completion'],
          rows: [
            ['RCC frame structure incl. podium', '1 LS', '1 LS', '100%'],
            ['Block work & internal plaster', '48,600 sqm', '48,600 sqm', '100%'],
            ['Flooring, tiling & granite', '36,200 sqm', '36,050 sqm', '99.6%'],
            ['Electrical installation incl. DG & transformers', '1 LS', '1 LS', '100%'],
            ['Plumbing, STP & WTP', '1 LS', '1 LS', '100%'],
            ['Fire fighting & fire alarm', '1 LS', '1 LS', '100%'],
            ['Lifts (7 nos) — installation & commissioning', '7 Nos', '7 Nos', '100%'],
            ['External development & landscaping', '1 LS', '0.96 LS', '96%'],
          ],
        },
        totals: [
          { label: 'Contract value (incl. variations)', value: '₹ 18,42,60,000' },
          { label: 'Value of work certified', value: '₹ 18,21,40,000' },
          { label: 'Retention held (5%)', value: '₹ 91,07,000' },
          { label: 'Defect Liability Period', value: '12 months from date of this certificate', bold: true },
        ],
        signatures: ['Contractor — Project Manager', 'Project Management Consultant', 'Client Representative'],
      }),
      page('Final Inspection', {
        type: 'checklist',
        title: 'Final Inspection Checklist',
        subject: 'hoCompletion',
        groups: [
          { title: 'Civil & Structure', items: ['No visible cracks, seepage or dampness in slabs and walls', 'Terrace & toilet waterproofing ponding test passed', 'Expansion joints sealed and covered', 'Staircase & railings complete, fixed firmly'] },
          { title: 'Finishes', items: ['Flooring free from hollowness, chipping and stains', 'Doors & windows aligned, hardware functional', 'Painting uniform — no patches or drips', 'Kitchen & toilet fixtures installed and sealed', 'Final cleaning completed in all units'] },
          { title: 'MEP Services', items: ['All points live-tested; ELCB / RCCB trip test done', 'Lifts commissioned with statutory licence', 'Plumbing pressure test and flow at all outlets', 'DG auto-changeover tested under load', 'STP & WTP commissioned — test reports attached'] },
          { title: 'Fire & Life Safety', items: ['Fire NOC obtained from Fire & Rescue Services', 'Hydrant & sprinkler system pressure tested', 'Fire alarm & PA system functional', 'Exit signage & emergency lighting working'] },
          { title: 'External Works', items: ['Internal roads, kerbs and parking marking complete', 'Landscaping & irrigation complete', 'Compound wall, gates & security cabin complete', 'Storm-water drains clear and connected'] },
          { title: 'Documentation', items: ['As-built drawings submitted (civil, MEP)', 'O&M manuals and warranty cards handed over', 'Occupancy certificate (OC) obtained', 'Keys & access cards inventory reconciled'] },
        ],
      }),
    ]),
    group('Snag Management', 'ti-list-check', [
      page('Snag', register('hoSnag', { tabs: { field: 'severity', values: ['Minor', 'Major', 'Critical'] } })),
      page('Assignment', register('hoSnagAssignment')),
      page('Rectification', board('hoSnag', 'status', ['location', 'assigned', 'due'], ['Assigned', 'In Progress', 'Completed', 'Verified'])),
      page('Verification', approval('hoSnag', ['Contractor', 'Site Engineer', 'QA/QC', 'Client'])),
    ]),
    group('Handover', 'ti-key', [
      page('Handover Documents', docs(['As-built Drawings', 'O&M Manuals', 'Certificates', 'Warranty Documents', 'Test Reports'], undefined, 'Handover Documents')),
      page('Asset Handover', lineItemsNoTax('hoAsset', 'Asset Handover Register — Orbit Tech Park Phase II', ['make', 'serial'])),
      page('Client Acceptance', approval('hoHandoverRequest', ['Handover Request', 'Client Review', 'Acceptance'])),
    ]),
    group('Warranty', 'ti-shield', [
      page('Warranty', register('hoWarranty', { tabs: { field: 'status', values: ['Valid', 'Expiring Soon', 'Expired'] } })),
      page('Defect Liability Period', register('hoDlp', { views: ['table', 'calendar'], dateField: 'end', tabs: { field: 'status', values: ['Active', 'Expiring Soon', 'Completed'] } })),
      page('Defects', register('hoDefect', { views: ['table', 'board'] })),
    ]),
  ],
  dashboard: {
    flow: [
      { label: 'Completion', value: '3 projects ≥ 84%' },
      { label: 'Snags', value: '486 raised · 94 open' },
      { label: 'Rectification', value: '81% verified' },
      { label: 'Handover', value: '312 units handed over' },
      { label: 'Warranty', value: '6 expiring in 90 days' },
    ],
    kpis: [
      { label: 'Units Handed Over', value: '312', delta: '+48', up: true, progress: 27, icon: 'ti-home-check', sub: 'of 1,146 units' },
      { label: 'Open Snags', value: '94', delta: '-37', up: false, good: true, icon: 'ti-list-check', sub: '11 critical' },
      { label: 'Snags Verified', value: '81%', delta: '+6 pt', up: true, progress: 81, icon: 'ti-circle-check' },
      { label: 'Handover Documents', value: '87%', delta: '+9 pt', up: true, progress: 87, icon: 'ti-files', sub: '262 of 301 submitted' },
      { label: 'Warranties Expiring (90 days)', value: '6', icon: 'ti-shield', sub: '2 lift AMCs · 1 chiller' },
    ],
    charts: [
      {
        title: 'Snag Status by Project',
        kind: 'stacked',
        categories: ['Orbit TP', 'Harbour View', 'Skyline T-A', 'Sunrise Hotel', 'Metro Tower'],
        series: [
          { name: 'Open', data: [6, 18, 32, 14, 9] },
          { name: 'In Progress', data: [4, 12, 21, 8, 6] },
          { name: 'Completed', data: [10, 14, 18, 7, 5] },
          { name: 'Verified', data: [148, 76, 52, 18, 8] },
        ],
        span: 2,
      },
      { title: 'Snags by Severity', kind: 'donut', categories: ['Minor', 'Major', 'Critical'], series: [{ name: 'Snags', data: [362, 98, 26] }], tones: ['yellow', 'red', 'red'], subtitle: '486 raised' },
      { title: 'Snags Raised vs Verified (weekly)', kind: 'line', categories: ['W33', 'W34', 'W35', 'W36', 'W37', 'W38', 'W39'], series: [{ name: 'Raised', data: [62, 71, 58, 66, 49, 42, 38] }, { name: 'Verified', data: [38, 46, 55, 61, 64, 58, 52] }], span: 2 },
      { title: 'Handover Readiness — Orbit TP', kind: 'gauge', series: [{ name: 'Checklist complete', data: [92] }], unit: '%' },
    ],
    table: { entity: 'hoSnag', title: 'Open Snags', columns: ['description', 'project', 'location', 'severity', 'assigned', 'due', 'status'], limit: 8 },
    rail: [
      {
        kind: 'dates',
        title: 'Upcoming Handovers',
        items: [
          { date: '2026-10-06', title: 'Block B — client walkthrough', sub: 'Orbit Tech Park Phase II' },
          { date: '2026-10-15', title: 'OPD wing handover', sub: 'Harbour View Hospital' },
          { date: '2026-10-30', title: 'Tower A — flats 101–1204', sub: 'Skyline Apartments' },
          { date: '2026-11-20', title: 'Guest floors L3–L6', sub: 'Sunrise Business Hotel' },
        ],
      },
      {
        kind: 'health',
        title: 'Handover Readiness',
        items: [
          { label: 'Orbit Tech Park Phase II', value: '92%', tone: 'green' },
          { label: 'Harbour View Hospital', value: '78%', tone: 'yellow' },
          { label: 'Skyline Apartments — T-A', value: '71%', tone: 'yellow' },
          { label: 'Sunrise Business Hotel', value: '54%', tone: 'red' },
        ],
      },
      {
        kind: 'list',
        title: 'Recent Activity',
        items: [
          { avatar: 'Deepak Sharma', title: 'Deepak Sharma verified 18 snags', sub: 'Orbit TP — Block B', meta: '1 hour ago', status: 'Verified' },
          { avatar: 'Divya T', title: 'Divya T uploaded O&M manuals (lifts)', sub: 'Harbour View Hospital', meta: '3 hours ago' },
          { avatar: 'Vivek Menon', title: 'Client accepted handover HR-004', sub: 'Orbit Tech Parks', meta: 'Yesterday', status: 'Accepted' },
          { avatar: 'Ravi Kumar K', title: 'Ravi Kumar K raised 24 snags', sub: 'Skyline Apartments — Tower A', meta: '2 days ago' },
        ],
      },
    ],
  },
  entities: [
    {
      id: 'hoCompletion',
      label: 'Completion Record',
      plural: 'Completion Records',
      app: 'handover',
      codePrefix: 'CC',
      titleField: 'scope',
      count: 10,
      fields: [
        text('scope', 'Completed Scope', ['Orbit Tech Park Phase II — Block A (G+9)', 'Orbit Tech Park Phase II — Block B (G+9)', 'Harbour View Hospital — IPD Tower', 'Skyline Apartments — Tower A structure & finishes', 'Harbour View Hospital — OPD Wing', 'Sunrise Business Hotel — Podium & Banquet', 'Metro Office Tower — Basement & Podium', 'Riverside Villas — Cluster A (24 villas)', 'Orbit Tech Park Phase II — Food Court', 'Skyline Apartments — Clubhouse'], { required: true }),
        ref('project', 'Project', 'project', { required: true }),
        ref('client', 'Client', 'client'),
        text('contract', 'Contract Ref.', ['CON-006 / WO-14', 'CON-006 / WO-15', 'CON-007 / WO-03', 'CON-001 / WO-08', 'CON-007 / WO-04', 'CON-008 / WO-02', 'CON-004 / WO-05', 'CON-002 / WO-06', 'CON-006 / WO-18', 'CON-001 / WO-11']),
        pct('completion', 'Completion', [94, 100]),
        date('completedOn', 'Completion Date', [-120, 20]),
        ref('certifiedBy', 'Certified By', 'employee'),
        status(['Certified', 'Under Review', 'Pending'], { gen: ['Certified', 'Certified', 'Certified', 'Under Review', 'Pending', 'Pending', 'Certified', 'Under Review', 'Pending', 'Pending'] }),
      ],
    },
    {
      id: 'hoSnag',
      label: 'Snag',
      plural: 'Snags',
      app: 'handover',
      codePrefix: 'SNG',
      titleField: 'description',
      count: 24,
      form: 'page',
      import: true,
      sections: [
        { id: 'snag', title: 'Snag Details', icon: 'ti-list-check' },
        { id: 'assign', title: 'Assignment & Rectification', icon: 'ti-user-check' },
      ],
      fields: [
        text('description', 'Snag Description', ['Hairline crack on living-room wall', 'Tile hollow sound — master bathroom', 'Door closer not functional — main door', 'Paint patch near switchboard', 'Window sliding track jammed', 'Water seepage below kitchen sink', 'Loose skirting tiles — bedroom 2', 'Balcony railing grout missing', 'Switch plate cracked — hall', 'Wash basin waste pipe leaking', 'Chipped granite edge — kitchen platform', 'Uneven floor level near balcony door', 'Lift landing door scratch — L7', 'Fire door vision panel cracked', 'Staircase handrail loose — L5', 'Sprinkler head misaligned — corridor', 'Car park line marking faded', 'Terrace drain outlet blocked', 'Mirror not fixed — common toilet', 'Exhaust fan not working — toilet 2', 'Wardrobe shutter misaligned', 'Gap between frame and wall — window', 'Lobby false ceiling tile stained', 'Grating missing — storm drain'], { required: true, section: 'snag' }),
        ref('project', 'Project', 'project', { required: true, section: 'snag' }),
        text('location', 'Location', ['Tower A — Flat 1203', 'Tower A — Flat 804', 'Block B — L3 Office 302', 'Tower A — Flat 1102', 'Villa A-07', 'Tower A — Flat 604', 'Block A — L5', 'Tower A — Flat 1001', 'OPD Wing — Room 112', 'IPD Tower — L4 Ward', 'Tower A — Flat 702', 'Villa A-12', 'Tower A — Lift lobby L7', 'Block B — Stair 2', 'Tower A — Stair core 1', 'IPD Tower — L2 corridor', 'Basement B1', 'Tower A — Terrace', 'Block A — L2 common toilet', 'Tower A — Flat 905', 'Tower A — Flat 1204', 'Villa A-03', 'Block B — Lobby', 'External — Road R2'], { section: 'snag' }),
        select('category', 'Trade', ['Civil', 'Finishes', 'Carpentry', 'Electrical', 'Plumbing', 'Fire', 'External'], { section: 'snag', list: false }),
        select('severity', 'Severity', ['Minor', 'Major', 'Critical'], { required: true, section: 'snag', gen: ['Minor', 'Major', 'Minor', 'Minor', 'Minor', 'Major', 'Minor', 'Minor', 'Minor', 'Major', 'Minor', 'Major', 'Minor', 'Critical', 'Major', 'Critical', 'Minor', 'Major', 'Minor', 'Minor', 'Minor', 'Minor', 'Minor', 'Critical'] }),
        date('raisedOn', 'Raised On', [-40, -1], { section: 'snag', list: false }),
        ref('assigned', 'Assigned To', 'subcontractor', { section: 'assign' }),
        date('due', 'Due Date', [-7, 21], { section: 'assign' }),
        area('remarks', 'Rectification Remarks', ['Crack filled with polymer putty and repainted.', 'Tiles removed and re-laid with adhesive.', 'Closer replaced under warranty.', 'Awaiting material from vendor.', 'Rework done; ready for verification.'], { section: 'assign' }),
        status(['Open', 'Assigned', 'In Progress', 'Completed', 'Verified', 'Rejected'], { section: 'assign', gen: ['Assigned', 'In Progress', 'Completed', 'Verified', 'Assigned', 'In Progress', 'Verified', 'Completed', 'Verified', 'In Progress', 'Open', 'Assigned', 'Verified', 'In Progress', 'Completed', 'Assigned', 'Verified', 'Rejected', 'Completed', 'Open', 'Verified', 'In Progress', 'Completed', 'Assigned'] }),
      ],
    },
    {
      id: 'hoSnagAssignment',
      label: 'Snag Assignment',
      plural: 'Snag Assignments',
      app: 'handover',
      codePrefix: 'SA',
      titleField: 'instruction',
      count: 18,
      fields: [
        text('instruction', 'Work Instruction', ['Batch 12 — civil touch-ups, Tower A L10–L12', 'Re-lay hollow tiles — 14 flats Tower A', 'Door hardware replacement — Block B', 'Paint touch-up — Tower A L6–L9', 'Window track servicing — Villa cluster A', 'Plumbing leak rectification — 9 kitchens', 'Skirting re-fixing — Tower A L4–L5', 'Railing grouting — balconies Tower A', 'Electrical accessories replacement — OPD', 'Waste-pipe joint sealing — IPD wards', 'Granite edge polishing — 11 kitchens', 'Floor levelling — Villa A-12', 'Lift door scratch removal — all landings', 'Fire door glass replacement — Block B', 'Handrail re-anchoring — stair core 1', 'Sprinkler realignment — IPD corridors', 'Car park re-marking — Basement B1', 'Terrace drain cleaning & testing'], { required: true }),
        ref('snag', 'Snag', 'hoSnag'),
        ref('assignee', 'Subcontractor', 'subcontractor', { required: true }),
        ref('supervisor', 'Site Supervisor', 'employee'),
        num('snags', 'Snags in Batch', [3, 36]),
        date('assignedOn', 'Assigned On', [-25, -1]),
        date('target', 'Target Date', [-5, 20]),
        status(['Assigned', 'In Progress', 'Completed', 'Overdue'], { gen: ['In Progress', 'Assigned', 'Completed', 'In Progress', 'Completed', 'Overdue', 'Completed', 'In Progress', 'Assigned', 'Completed', 'In Progress', 'Assigned', 'Completed', 'Overdue', 'In Progress', 'Completed', 'Assigned', 'In Progress'] }),
      ],
    },
    {
      id: 'hoAsset',
      label: 'Handover Asset',
      plural: 'Handover Assets',
      app: 'handover',
      codePrefix: 'AST',
      titleField: 'description',
      count: ASSETS.length,
      fields: [
        text('description', 'Asset Description', ASSETS.map((a) => a[0]), { required: true }),
        select('section', 'System', ['Lifts & Escalators', 'Electrical & DG', 'HVAC', 'Fire Fighting', 'Plumbing & STP', 'Security & BMS'], { gen: ASSETS.map((a) => a[4]) }),
        text('make', 'Make / Model', MAKES, { list: false }),
        text('serial', 'Serial / Tag No.', SERIALS, { list: false }),
        text('unit', 'Unit', ASSETS.map((a) => a[1])),
        num('qty', 'Qty', [1, 200]),
        money('rate', 'Asset Value', [3200, 9860000]),
      ],
      rows: ASSETS.map(([description, unit, qty, rate, section], i) => {
        const code = `AST-${String(i + 1).padStart(3, '0')}`;
        return { id: code, code, description, unit, qty, rate, section, make: MAKES[i], serial: SERIALS[i] };
      }),
    },
    {
      id: 'hoHandoverRequest',
      label: 'Handover Request',
      plural: 'Handover Requests',
      app: 'handover',
      codePrefix: 'HR',
      titleField: 'title',
      count: 12,
      form: 'wizard',
      sections: [
        { id: 'request', title: 'Handover Request', icon: 'ti-file-description' },
        { id: 'readiness', title: 'Readiness & Documents', icon: 'ti-checklist' },
        { id: 'review', title: 'Client Review', icon: 'ti-user-search' },
        { id: 'acceptance', title: 'Acceptance', icon: 'ti-circle-check' },
      ],
      fields: [
        text('title', 'Handover Package', ['Block A — office floors G–L9', 'Block B — office floors G–L9', 'IPD Tower — wards L1–L6', 'Food court & amenities', 'OPD Wing — consultation rooms', 'Tower A — flats 101–1204', 'Villa cluster A — 24 villas', 'Podium & banquet hall', 'Clubhouse & swimming pool', 'Basement parking B1–B2', 'Guest floors L3–L6', 'Landscape & external works'], { required: true, section: 'request' }),
        ref('project', 'Project', 'project', { required: true, section: 'request' }),
        ref('client', 'Client', 'client', { required: true, section: 'request' }),
        num('units', 'Units / Areas', [1, 96], { section: 'request' }),
        date('requestedOn', 'Requested On', [-60, -2], { section: 'request' }),
        pct('documents', 'Documents Submitted', [62, 100], { section: 'readiness' }),
        num('openSnags', 'Open Snags', [0, 38], { section: 'readiness' }),
        text('oc', 'OC / Fire NOC Ref.', ['OC/CMDA/2026/0412', 'OC/CMDA/2026/0413', 'FNOC/TNFRS/2026/1188', 'OC/CMDA/2026/0419', 'Applied — awaiting', 'OC/CMDA/2026/0401'], { section: 'readiness', list: false }),
        text('reviewer', 'Client Reviewer', ['Vivek Menon', 'Vivek Menon', 'Dr. Padma Rao', 'Vivek Menon', 'Dr. Padma Rao', 'Ramesh Iyer', 'Anand Krishnan', 'Arvind Pillai', 'Ramesh Iyer', 'Kiran Rao', 'Arvind Pillai', 'Sanjay Mehta'], { section: 'review', list: false }),
        date('reviewOn', 'Joint Inspection Date', [-30, 25], { section: 'review' }),
        area('comments', 'Client Comments / Rejection Reasons', ['Accepted subject to closure of 6 minor snags within 15 days.', 'Lift licence copy to be submitted before handover.', 'Accepted without reservations.', 'Rejected — fire NOC pending; re-inspection requested.', 'Landscape irrigation to be demonstrated.'], { section: 'acceptance' }),
        status(['Submitted', 'Under Review', 'Accepted', 'Rejected'], { section: 'acceptance', gen: ['Accepted', 'Accepted', 'Accepted', 'Accepted', 'Under Review', 'Submitted', 'Under Review', 'Submitted', 'Rejected', 'Under Review', 'Submitted', 'Submitted'] }),
      ],
    },
    {
      id: 'hoWarranty',
      label: 'Warranty',
      plural: 'Warranties',
      app: 'handover',
      codePrefix: 'WAR',
      titleField: 'item',
      count: 18,
      fields: [
        text('item', 'Warranty Item', ['Passenger lifts — 4 nos (Block A)', 'DG sets 750 kVA — 2 nos', 'Waterproofing — terrace & podium (10-year)', 'Chillers 250 TR — 2 nos', 'Façade glazing & sealant (10-year)', 'Fire pump set', 'Transformers 1600 kVA', 'STP 250 KLD — MBBR', 'Solar PV system (25-year performance)', 'Anti-termite treatment (10-year)', 'Aluminium windows — hardware', 'CCTV & NVR system', 'Hydro-pneumatic pumps', 'Vitrified tiles — manufacturing defects', 'BMS head-end & controllers', 'AHUs — 6 nos', 'Boom barriers & access control', 'Modular kitchen fittings'], { required: true }),
        ref('project', 'Project', 'project', { required: true }),
        ref('vendor', 'Supplier / OEM', 'vendor'),
        num('months', 'Warranty Period', [12, 120], { unit: 'months' }),
        date('start', 'Warranty Start', [-420, -30]),
        date('expiry', 'Expiry', [-20, 900]),
        text('certificate', 'Warranty Certificate', ['WC/KONE/26/0412', 'WC/CUM/26/0088', 'WC/TWP/26/0145', 'WC/DAI/26/0311', 'WC/SGA/26/0077', 'WC/KIR/26/0192'], { list: false }),
        status(['Valid', 'Expiring Soon', 'Expired'], { gen: ['Valid', 'Valid', 'Valid', 'Expiring Soon', 'Valid', 'Valid', 'Expiring Soon', 'Valid', 'Valid', 'Valid', 'Expired', 'Valid', 'Expiring Soon', 'Valid', 'Valid', 'Valid', 'Expiring Soon', 'Expired'] }),
      ],
    },
    {
      id: 'hoDlp',
      label: 'Defect Liability Period',
      plural: 'Defect Liability Periods',
      app: 'handover',
      codePrefix: 'DLP',
      titleField: 'scope',
      count: 10,
      info: 'Retention is released on expiry of the DLP after a joint inspection and closure of all reported defects.',
      fields: [
        text('scope', 'Scope under DLP', ['Orbit TP — Block A', 'Orbit TP — Block B', 'Harbour View — IPD Tower', 'Orbit TP — Food Court', 'Metro Tower — Basement & Podium', 'Riverside — Cluster A villas', 'Orbit Tech Park Phase I', 'Sunrise Hotel — Podium', 'Harbour View — OPD Wing', 'Skyline — Clubhouse'], { required: true }),
        ref('project', 'Project', 'project', { required: true }),
        ref('client', 'Client', 'client'),
        date('start', 'DLP Start', [-360, -20]),
        date('end', 'DLP End', [15, 340]),
        num('months', 'DLP Duration', [12, 24], { unit: 'months' }),
        money('retention', 'Retention Held', [1800000, 9200000]),
        num('defects', 'Open Defects', [0, 14]),
        status(['Active', 'Expiring Soon', 'Completed'], { gen: ['Active', 'Active', 'Active', 'Expiring Soon', 'Active', 'Active', 'Completed', 'Active', 'Expiring Soon', 'Active'] }),
      ],
    },
    {
      id: 'hoDefect',
      label: 'Defect',
      plural: 'Defects',
      app: 'handover',
      codePrefix: 'DEF',
      titleField: 'description',
      count: 18,
      form: 'page',
      fields: [
        text('description', 'Defect Reported', ['Seepage in basement retaining wall', 'Lift A2 stopping between floors', 'DG not auto-starting on mains failure', 'Terrace leakage above L9 office', 'Chiller CH-02 high-pressure trip', 'Cracks in podium paving', 'Sprinkler leak — L4 corridor', 'Glazing sealant failure — east façade', 'STP blower noise & odour', 'Toilet flush valve leaking — Block B', 'Door lock malfunction — 6 rooms', 'Loose floor tiles — food court', 'Water hammer in riser — L7', 'Solar inverter fault', 'Access card reader not working — gate 2', 'Paint peeling — external wall', 'Drain back-flow in monsoon', 'Emergency light battery failure'], { required: true }),
        ref('project', 'Project', 'project', { required: true }),
        select('reportedBy', 'Reported By', ['Client facility team', 'RWA / Tenant', 'Client PMC', 'Joint inspection']),
        date('reportedOn', 'Reported On', [-90, -1]),
        select('category', 'Category', ['Civil', 'Waterproofing', 'Electrical', 'Lifts', 'HVAC', 'Plumbing', 'Fire', 'Façade']),
        select('severity', 'Severity', ['Minor', 'Major', 'Critical'], { gen: ['Major', 'Critical', 'Critical', 'Major', 'Major', 'Minor', 'Major', 'Major', 'Minor', 'Minor', 'Minor', 'Minor', 'Major', 'Major', 'Minor', 'Minor', 'Major', 'Minor'] }),
        ref('assigned', 'Assigned To', 'subcontractor'),
        area('resolution', 'Resolution', ['Injection grouting done; monitoring for 2 weeks.', 'OEM technician replaced controller card.', 'AMF panel relay replaced; tested OK.', 'Membrane patch repair and ponding test passed.', 'Refrigerant topped up; condenser coils cleaned.']),
        status(['Open', 'Assigned', 'In Progress', 'Resolved', 'Closed'], { gen: ['In Progress', 'Resolved', 'Closed', 'In Progress', 'Resolved', 'Open', 'Closed', 'Assigned', 'In Progress', 'Closed', 'Closed', 'Assigned', 'Open', 'Resolved', 'Closed', 'Assigned', 'Open', 'Closed'] }),
      ],
    },
  ],
};
