import { area, date, docs, f, fieldView, group, mapView, money, num, page, pct, ref, register, select, status, text } from '../dsl';
import type { AppConfig, Row } from '../types';

const CR = 1e7;
const cr = (x: number) => Math.round(x * CR);
const pad = (n: number) => String(n).padStart(3, '0');

const POTENTIAL = ['Residential', 'Villa Plots', 'Township', 'Commercial', 'Industrial / Warehousing', 'Mixed Use'];
const LAND_STATUS = ['New', 'Site Visit Scheduled', 'Under Review', 'Negotiation', 'Approved', 'Registered', 'Rejected'];
const LAND_FOLDERS = ['Title Documents', 'Sale Deeds', 'Patta & Chitta', 'Encumbrance Certificates', 'Survey Sketches (FMB)', 'Legal Opinions', 'Approvals & NOCs'];

/** [parcel, location, city, state, acres, survey no., owner / seller, source, asking ₹Cr, guidance ₹Cr, potential, officer, status] */
const parcelData: [string, string, string, string, number, string, string, string, number, number, string, string, string][] = [
  ['Kelambakkam Land Parcel', 'Kelambakkam, OMR', 'Chennai', 'Tamil Nadu', 12.4, 'S.No. 214/2A, 215/1', 'R. Subramaniam & 3 others', 'Broker', 58, 31, 'Residential', 'EMP-040', 'Negotiation'],
  ['Oragadam Industrial Plot', 'Vallam Vadagal, Oragadam', 'Sriperumbudur', 'Tamil Nadu', 24.6, 'S.No. 88/1 – 88/6', 'Sri Venkateswara Agro Farms', 'Direct Owner', 49, 27, 'Industrial / Warehousing', 'EMP-040', 'Under Review'],
  ['Hosur Bagalur Road Parcel', 'Bagalur Road, Hosur', 'Hosur', 'Tamil Nadu', 18.2, 'S.No. 341/3', 'K. Munirathnam', 'Referral', 36, 19, 'Township', 'EMP-028', 'Approved'],
  ['Saravanampatti Villa Land', 'Saravanampatti, Coimbatore', 'Coimbatore', 'Tamil Nadu', 9.8, 'S.F. No. 402/1B', 'P. Natarajan (HUF)', 'Broker', 29, 16, 'Villa Plots', 'EMP-040', 'Site Visit Scheduled'],
  ['Kokapet Residential Parcel', 'Kokapet, Gandipet Mandal', 'Hyderabad', 'Telangana', 6.5, 'Sy. No. 147', 'Lakeview Estates (JD offer)', 'Joint Development Offer', 84, 52, 'Residential', 'EMP-028', 'Under Review'],
  ['Whitefield Commercial Plot', 'Hoodi, Whitefield', 'Bengaluru', 'Karnataka', 3.2, 'Sy. No. 62/4', 'Prakash Family Trust', 'Broker', 72, 44, 'Commercial', 'EMP-040', 'Negotiation'],
  ['Mambakkam Warehousing Land', 'Mambakkam, Sriperumbudur', 'Sriperumbudur', 'Tamil Nadu', 31.0, 'S.No. 12/1 – 12/9', 'Multiple owners (7)', 'Broker', 52, 30, 'Industrial / Warehousing', 'EMP-040', 'New'],
  ['Madurai Ring Road Hotel Site', 'Ring Road, Madurai', 'Madurai', 'Tamil Nadu', 2.4, 'T.S. No. 1184', 'A. Karuppasamy', 'Direct Owner', 14, 8.5, 'Commercial', 'EMP-028', 'Registered'],
  ['Guduvanchery Township Land', 'Guduvanchery, GST Road', 'Chengalpattu', 'Tamil Nadu', 26.8, 'S.No. 510 – 514', 'Sri Lakshmi Estates', 'Broker', 62, 38, 'Township', 'EMP-040', 'Rejected'],
  ['Hinjewadi Phase 3 Plot', 'Maan, Hinjewadi Phase 3', 'Pune', 'Maharashtra', 5.6, 'Gat No. 227', 'Pinnacle Realty (JD offer)', 'Joint Development Offer', 46, 28, 'Mixed Use', 'EMP-028', 'Under Review'],
  ['Rushikonda Beach Road Parcel', 'Rushikonda, Beach Road', 'Visakhapatnam', 'Andhra Pradesh', 4.1, 'Sy. No. 92/2', 'Coastal Healthcare Trust (surplus land)', 'Existing Client', 38, 21, 'Mixed Use', 'EMP-040', 'Site Visit Scheduled'],
  ['Thirumazhisai Plotted Development', 'Thirumazhisai, Poonamallee', 'Chennai', 'Tamil Nadu', 14.9, 'S.No. 76/2', 'M. Gopal & Sons', 'Auction', 33, 21, 'Villa Plots', 'EMP-028', 'New'],
  ['Perungudi IT Corridor Plot', 'Perungudi, OMR', 'Chennai', 'Tamil Nadu', 1.8, 'S.No. 45/1B', 'Orbit Tech Parks (sale)', 'Existing Client', 54, 31, 'Commercial', 'EMP-040', 'Registered'],
  ['Neelambur Warehousing Land', 'Neelambur, Avinashi Road', 'Coimbatore', 'Tamil Nadu', 24.7, 'S.F. No. 118/2', 'Kongu Textiles Pvt Ltd', 'Direct Owner', 38, 22, 'Industrial / Warehousing', 'EMP-028', 'Approved'],
];

const parcelRows: Row[] = parcelData.map(([name, location, city, stateName, acres, surveyNo, owner, source, asking, guidance, potential, officer, st], i) => ({
  id: `LL-${pad(i + 1)}`,
  code: `LL-${pad(i + 1)}`,
  name,
  location,
  city,
  state: stateName,
  area: acres,
  surveyNo,
  owner,
  source,
  askingPrice: cr(asking),
  guidanceValue: cr(guidance),
  potential,
  officer,
  status: st,
}));

/** [title, parcel, seller, agreement date, consideration ₹Cr, advance ₹Cr, completion date, status] */
const agreementData: [string, string, string, string, number, number, string, string][] = [
  ['Agreement for Sale — Kelambakkam 12.4 acres', 'LL-001', 'R. Subramaniam & 3 others', '2026-09-25', 49.2, 4.92, '2027-01-31', 'Signed'],
  ['Agreement for Sale — Hosur Bagalur Road 18.2 acres', 'LL-003', 'K. Munirathnam', '2026-09-18', 33.5, 3.35, '2026-12-31', 'Under Review'],
  ['Agreement for Sale — Neelambur 24.7 acres', 'LL-014', 'Kongu Textiles Pvt Ltd', '2026-10-05', 36.4, 3.64, '2027-02-28', 'Draft'],
  ['Sale Deed — Madurai Ring Road 2.4 acres', 'LL-008', 'A. Karuppasamy', '2026-05-14', 13.2, 1.32, '2026-07-10', 'Registered'],
  ['Sale Deed — Perungudi 1.8 acres', 'LL-013', 'Orbit Tech Parks', '2026-04-22', 51.8, 5.18, '2026-06-30', 'Registered'],
  ['Agreement for Sale — Whitefield 3.2 acres', 'LL-006', 'Prakash Family Trust', '2026-10-20', 66.0, 6.6, '2027-03-31', 'Draft'],
];
const agreementRows: Row[] = agreementData.map(([title, parcel, seller, agreementDate, consideration, advance, completion, st], i) => ({
  id: `AGR-${pad(i + 1)}`,
  code: `AGR-${pad(i + 1)}`,
  title,
  parcel,
  seller,
  purchaser: 'Sterling Constructions Pvt Ltd',
  agreementDate,
  consideration: cr(consideration),
  advance: cr(advance),
  stampDuty: Math.round(cr(consideration) * 0.07),
  completion,
  status: st,
}));

const PARCEL_NAMES = parcelData.map((p) => p[0]);

export const landApp: AppConfig = {
  id: 'land',
  name: 'Land',
  icon: 'ti-map-2',
  description: 'Land identification, ownership, legal & technical due diligence, approvals and acquisition',
  menus: [
    group('Land Identification', 'ti-map-pin', [
      page('Land Lead', register('landLead', { views: ['table', 'board'] })),
      page('Location', mapView('landLead', 'Land Parcels — Location Map')),
      page('Area', fieldView('landLead', 'area')),
      page('Land Owner', register('landOwner')),
    ]),
    group('Ownership', 'ti-user-check', [
      page('Owner Details', register('landOwnership')),
      page('Title Documents', docs(LAND_FOLDERS, 'Title Documents', 'Title Documents')),
      page('Sale Deed', docs(LAND_FOLDERS, 'Sale Deeds', 'Sale Deeds')),
      page('Encumbrance', register('landEncumbrance')),
    ]),
    group('Legal Verification', 'ti-scale', [
      page('Title Verification', {
        type: 'checklist',
        title: 'Title Verification',
        subject: 'landLead',
        groups: [
          { title: 'Title Chain (30 years)', items: ['Parent documents traced for 30+ years', 'Link documents complete — no gaps in chain', 'Sale / gift / partition deeds registered and stamped', 'Legal heirship certificate for inherited shares', 'Release deeds from all co-owners obtained'] },
          { title: 'Revenue Records', items: ['Patta in the name of the vendor', 'Chitta & Adangal extracts match patta', 'FMB sketch matches survey numbers & extent', 'Land classification — not poramboke / government land', 'Not assigned land (no alienation restriction)'] },
          { title: 'Identity & Authority', items: ['KYC of all vendors (Aadhaar, PAN)', 'Power of attorney verified at issuing SRO', 'Board resolution for company-owned land', 'Minor’s share — court permission obtained'] },
          { title: 'Physical Verification', items: ['Boundaries match the schedule of property', 'No encroachment or third-party possession', 'Vendor in peaceful possession'] },
        ],
      }),
      page('Encumbrance Check', {
        type: 'checklist',
        title: 'Encumbrance Check',
        subject: 'landLead',
        groups: [
          { title: 'Encumbrance Certificate', items: ['EC obtained for 30 years from the jurisdictional SRO', 'All transactions in EC match the title chain', 'No unexplained entries in the EC'] },
          { title: 'Mortgages & Charges', items: ['No subsisting mortgage with banks / NBFCs', 'CERSAI search — no charge registered', 'ROC charge search for company vendors', 'Loan closure / release deed for past mortgages'] },
          { title: 'Court & Government', items: ['No lis pendens or attachment orders', 'Not notified under Land Acquisition Act / RFCTLARR', 'No Urban Land Ceiling surplus declaration', 'Not in HACA / CRZ / eco-sensitive zone restrictions'] },
          { title: 'Tax & Dues', items: ['Property tax / land revenue paid up to date', 'No pending EB / water dues', 'Income-tax clearance (Sec. 281) where applicable'] },
        ],
      }),
      page('Litigation', register('landLitigation')),
      page('Legal Opinion', register('landLegalOpinion')),
    ]),
    group('Technical Verification', 'ti-ruler-measure', [
      page('Land Survey', register('landSurvey')),
      page('Soil Test', register('landSoilTest')),
      page('Topographical Survey', register('landTopo')),
      page('Site Conditions', {
        type: 'checklist',
        title: 'Site Conditions',
        subject: 'landLead',
        groups: [
          { title: 'Access & Connectivity', items: ['Abutting public road ≥ 12 m wide', 'All-weather access for heavy vehicles', 'Distance to highway / arterial road < 3 km', 'Public transport within 1 km'] },
          { title: 'Utilities', items: ['HT / LT power line within 500 m', 'Municipal water or ground-water availability', 'Sewer / drainage connection available', 'Telecom & fibre connectivity'] },
          { title: 'Physical Features', items: ['Land level above HFL — no inundation history', 'No HT tower lines crossing the parcel', 'No water bodies / channels within the parcel', 'Regular shape suitable for layout'] },
          { title: 'Surroundings & Environment', items: ['No polluting industries within 500 m', 'No burial ground / dumping yard adjacent', 'Not within airport height restriction funnel', 'Neighbourhood development supports proposed use'] },
        ],
      }),
    ]),
    group('Regulatory', 'ti-building-bank', [
      page('Zoning', register('landZoning')),
      page('Land Use', register('landUse')),
      page('Approvals', register('landApproval', { views: ['table', 'board'] })),
      page('NOCs', register('landNoc')),
    ]),
    group('Acquisition', 'ti-file-certificate', [
      page('Negotiation', {
        type: 'timeline',
        title: 'Negotiation History — LL-001 Kelambakkam Land Parcel',
        subject: 'landLead',
        events: [
          { date: '2026-06-12', title: 'Seller asking price', actor: 'Arjun Menon', text: 'Asking ₹ 4.68 Cr / acre through broker Sri Sai Realtors.', status: 'Open', amount: cr(58.0) },
          { date: '2026-06-28', title: 'First offer', actor: 'Arjun Menon', text: 'Offer based on guidance value ₹ 2.5 Cr / acre plus 40% market premium.', status: 'Submitted', amount: cr(44.0) },
          { date: '2026-07-10', title: 'Counter-offer from seller', actor: 'R. Subramaniam', text: 'Seller cites adjacent sale at ₹ 4.4 Cr / acre (S.No. 216).', status: 'Under Review', amount: cr(54.0) },
          { date: '2026-07-30', title: 'Revised offer after EC & survey', actor: 'Arjun Menon', text: 'Survey found 0.3 acre shortfall; offer revised accordingly.', status: 'Submitted', amount: cr(47.5) },
          { date: '2026-08-21', title: 'Seller counter-offer', actor: 'R. Subramaniam', text: 'Seller agrees to bear patta sub-division costs.', status: 'Under Review', amount: cr(51.0) },
          { date: '2026-09-12', title: 'Offer approved by Land Committee', actor: 'Gayathri S', text: 'Approved at ₹ 3.97 Cr / acre; within the board-approved ceiling of ₹ 50 Cr.', status: 'Approved', amount: cr(49.2) },
          { date: '2026-09-25', title: 'Final agreed value — agreement signed', actor: 'Pooja Reddy', text: 'Agreement for Sale AGR-001 executed; 10% advance released.', status: 'Signed', amount: cr(49.2) },
        ],
      }),
      page('Agreement', {
        type: 'print',
        entity: 'landAgreement',
        docTitle: 'Agreement for Sale',
        lines: {
          columns: ['Payment Milestone', 'Due On', 'Share', 'Amount (₹)'],
          rows: [
            ['Advance on execution of agreement', '25 Sep 2026', '10%', 49200000],
            ['On delivery of original title deeds & clear EC', '15 Nov 2026', '20%', 98400000],
            ['On patta sub-division & transfer approval', '31 Dec 2026', '30%', 147600000],
            ['Balance on registration of sale deed', '31 Jan 2027', '40%', 196800000],
          ],
        },
        totals: [
          { label: 'Total sale consideration', value: '₹ 49,20,00,000' },
          { label: 'Stamp duty @ 7%', value: '₹ 3,44,40,000' },
          { label: 'Registration fee @ 2%', value: '₹ 98,40,000' },
          { label: 'Total acquisition outlay', value: '₹ 53,62,80,000', bold: true },
        ],
        signatures: ['Vendor(s)', 'Purchaser — Authorised Signatory', 'Witness'],
      }),
      page('Purchase', register('landPurchase')),
      page('Ownership Transfer', {
        type: 'wizard',
        title: 'Ownership Transfer',
        submitLabel: 'Complete Transfer',
        steps: [
          {
            title: 'Sale Deed Registration',
            icon: 'ti-file-certificate',
            fields: [
              ref('parcel', 'Land Parcel', 'landLead', { required: true }),
              ref('agreement', 'Agreement for Sale', 'landAgreement', { required: true }),
              text('deedNo', 'Registered Document No.', undefined, { required: true, placeholder: 'e.g. 4127/2026' }),
              text('sro', 'Sub-Registrar Office', undefined, { placeholder: 'e.g. SRO Thiruporur' }),
              date('registeredOn', 'Registration Date', undefined, { required: true }),
              money('stampDuty', 'Stamp Duty Paid'),
              money('regFee', 'Registration Fee Paid'),
            ],
            upload: ['Registered sale deed (scanned)', 'Stamp duty & fee challans'],
          },
          {
            title: 'Patta Transfer & Mutation',
            icon: 'ti-id',
            note: 'Apply for patta transfer on the Tamil Nilam / state revenue portal within 30 days of registration.',
            fields: [
              text('mutationNo', 'Mutation Application No.', undefined, { required: true }),
              date('appliedOn', 'Applied On'),
              select('office', 'Revenue Office', ['Village Administrative Officer', 'Taluk Office', 'Zonal Deputy Tahsildar']),
              select('subdivision', 'Sub-division Required', ['Yes', 'No']),
            ],
            checklist: ['Patta transferred in company name', 'Chitta & Adangal updated', 'FMB sketch updated after sub-division', 'Property tax assessment transferred', 'EB service connection name changed'],
          },
          {
            title: 'Possession & Handover',
            icon: 'ti-key',
            fields: [
              date('possessionOn', 'Possession Date', undefined, { required: true }),
              ref('custodian', 'Land Custodian', 'employee', { required: true }),
              ref('project', 'Allotted to Project', 'project'),
              area('remarks', 'Remarks'),
            ],
            checklist: ['Boundary stones fixed & jointly verified', 'Fencing and signage erected', 'Possession certificate signed by vendor'],
            upload: ['Possession certificate', 'Mutated patta copy'],
          },
        ],
      }),
    ]),
  ],
  dashboard: {
    flow: [
      { label: 'Land Leads', value: '14 parcels · 186 acres' },
      { label: 'Verification', value: '7 of 11 titles cleared' },
      { label: 'Approvals', value: '9 pending' },
      { label: 'Negotiation', value: '2 active · ₹ 130 Cr asking' },
      { label: 'Acquired', value: '2 registered · 4.2 acres' },
    ],
    kpis: [
      { label: 'Parcels in Pipeline', value: '11', delta: '+2', up: true, icon: 'ti-map-pin', sub: 'Excl. 2 registered, 1 rejected' },
      { label: 'Total Area Evaluated', value: '186 acres', icon: 'ti-ruler-measure', sub: '14 parcels · 7 cities' },
      { label: 'Acquisition Pipeline', value: '₹ 535 Cr', delta: '+₹ 52 Cr', up: true, progress: 58, icon: 'ti-currency-rupee', sub: 'Guidance value ₹ 311 Cr' },
      { label: 'Legal Clearance', value: '64%', progress: 64, icon: 'ti-scale', sub: '7 of 11 titles verified' },
      { label: 'Pending Approvals & NOCs', value: '9', delta: '3 > 60 days', up: true, good: false, icon: 'ti-building-bank' },
      { label: 'Open Litigation', value: '2', icon: 'ti-alert-triangle', sub: 'Next hearing 8 Oct 2026' },
    ],
    charts: [
      {
        title: 'Asking vs Guidance Value by City (₹ Cr)',
        kind: 'bar',
        categories: ['Chennai', 'Sriperumbudur', 'Hyderabad', 'Bengaluru', 'Coimbatore', 'Chengalpattu', 'Pune', 'Visakhapatnam', 'Hosur', 'Madurai'],
        series: [
          { name: 'Asking', data: [145, 101, 84, 72, 67, 62, 46, 38, 36, 14] },
          { name: 'Guidance', data: [83, 57, 52, 44, 38, 38, 28, 21, 19, 8.5] },
        ],
        unit: '₹Cr',
        span: 2,
      },
      { title: 'Land Pipeline (parcels)', kind: 'funnel', categories: ['Identified', 'Site Visited', 'Legally Verified', 'Negotiated', 'Acquired'], series: [{ name: 'Parcels', data: [14, 10, 7, 4, 2] }] },
      { title: 'Development Potential (acres)', kind: 'donut', categories: POTENTIAL, series: [{ name: 'Acres', data: [18.9, 24.7, 45, 7.4, 80.3, 9.7] }], subtitle: '186 acres' },
      { title: 'Approvals by Authority', kind: 'stacked', categories: ['CMDA', 'DTCP', 'HMDA', 'BDA', 'PMRDA', 'VMRDA'], series: [{ name: 'Approved', data: [3, 2, 1, 1, 0, 0] }, { name: 'Pending', data: [2, 3, 1, 1, 1, 1] }], span: 2 },
    ],
    table: { entity: 'landLead', title: 'Land Register', columns: ['name', 'location', 'area', 'askingPrice', 'potential', 'status'], limit: 8 },
    rail: [
      { kind: 'health', title: 'Parcel Status', items: [{ label: 'New / Site Visit', value: 4, tone: 'blue' }, { label: 'Under Review', value: 3, tone: 'yellow' }, { label: 'Negotiation', value: 2, tone: 'blue' }, { label: 'Approved', value: 2, tone: 'green' }, { label: 'Registered', value: 2, tone: 'green' }, { label: 'Rejected', value: 1, tone: 'red' }] },
      {
        kind: 'dates',
        title: 'Hearings & Deadlines',
        items: [
          { date: '2026-10-03', title: 'Site visit — Saravanampatti', sub: 'LL-004 · Arjun Menon' },
          { date: '2026-10-08', title: 'Hearing — O.S. 412/2024', sub: 'District Court, Chengalpattu' },
          { date: '2026-10-15', title: 'Legal opinion due — Kokapet', sub: 'LL-005 · Pooja Reddy' },
          { date: '2026-11-15', title: 'Title deeds delivery — Kelambakkam', sub: 'AGR-001 milestone 2' },
        ],
      },
      {
        kind: 'list',
        title: 'Recent Activity',
        items: [
          { avatar: 'Arjun Menon', title: 'Arjun Menon signed AGR-001', sub: 'Kelambakkam Land Parcel — ₹ 49.2 Cr', meta: '4 days ago' },
          { avatar: 'Pooja Reddy', title: 'Pooja Reddy uploaded EC (30 yrs)', sub: 'Oragadam Industrial Plot', meta: 'Yesterday' },
          { avatar: 'Prakash J', title: 'Prakash J completed DGPS survey', sub: 'Neelambur Warehousing Land', meta: '2 days ago' },
          { avatar: 'Gayathri S', title: 'Gayathri S released advance ₹ 4.92 Cr', sub: 'Kelambakkam Land Parcel', meta: '4 days ago' },
        ],
      },
    ],
  },
  entities: [
    {
      id: 'landLead',
      label: 'Land Parcel',
      plural: 'Land Parcels',
      app: 'land',
      codePrefix: 'LL',
      titleField: 'name',
      form: 'page',
      sections: [
        { id: 'basic', title: 'Parcel Details', icon: 'ti-map-pin' },
        { id: 'owner', title: 'Owner & Source', icon: 'ti-user' },
        { id: 'value', title: 'Value & Potential', icon: 'ti-currency-rupee' },
      ],
      fields: [
        text('name', 'Land Parcel', PARCEL_NAMES, { required: true, section: 'basic' }),
        text('location', 'Location', undefined, { required: true, section: 'basic' }),
        text('city', 'City / District', undefined, { section: 'basic', list: false }),
        text('state', 'State', undefined, { section: 'basic', list: false }),
        num('area', 'Area', undefined, { required: true, unit: 'acres', section: 'basic' }),
        text('surveyNo', 'Survey No.', undefined, { section: 'basic' }),
        text('owner', 'Owner / Seller', undefined, { section: 'owner' }),
        select('source', 'Lead Source', ['Broker', 'Direct Owner', 'Referral', 'Existing Client', 'Joint Development Offer', 'Auction'], { section: 'owner', list: false }),
        money('askingPrice', 'Asking Price', undefined, { section: 'value' }),
        money('guidanceValue', 'Guidance Value', undefined, { section: 'value', list: false }),
        select('potential', 'Development Potential', POTENTIAL, { section: 'value' }),
        ref('officer', 'Land Officer', 'employee', { section: 'owner', list: false }),
        status(LAND_STATUS, { section: 'basic' }),
      ],
      rows: parcelRows,
    },
    {
      id: 'landOwner',
      label: 'Land Owner',
      plural: 'Land Owners',
      app: 'land',
      codePrefix: 'LO',
      titleField: 'name',
      count: 16,
      fields: [
        text('name', 'Owner Name', ['R. Subramaniam', 'Sri Venkateswara Agro Farms', 'K. Munirathnam', 'P. Natarajan (HUF)', 'Lakeview Estates', 'Prakash Family Trust', 'S. Kandasamy', 'A. Karuppasamy', 'Sri Lakshmi Estates', 'Pinnacle Realty', 'Coastal Healthcare Trust', 'M. Gopal', 'Orbit Tech Parks', 'Kongu Textiles Pvt Ltd', 'R. Meenakshi', 'V. Balaji'], { required: true }),
        ref('parcel', 'Land Parcel', 'landLead', { required: true }),
        select('type', 'Owner Type', ['Individual', 'Joint Owners', 'HUF', 'Company', 'Trust'], { gen: ['Joint Owners', 'Company', 'Individual', 'HUF', 'Company', 'Trust', 'Individual', 'Individual', 'Company', 'Company', 'Trust', 'Joint Owners', 'Company', 'Company', 'Individual', 'Individual'] }),
        pct('share', 'Ownership Share', [25, 100]),
        f('phone', 'Phone', 'phone', { gen: ['+91 98410 55123', '+91 94440 21876', '+91 98433 60219', '+91 98422 17754', '+91 99490 44810', '+91 98450 30217', '+91 97890 11456', '+91 98940 72233'] }),
        text('city', 'City', ['Chennai', 'Kanchipuram', 'Hosur', 'Coimbatore', 'Hyderabad', 'Bengaluru', 'Sriperumbudur', 'Madurai', 'Chengalpattu', 'Pune', 'Visakhapatnam', 'Chennai', 'Chennai', 'Coimbatore', 'Chennai', 'Kanchipuram']),
        text('pan', 'PAN', ['AKPPS4821L', 'AAFFS7712K', 'ADMPM3390R', 'AAHHN1023P', 'AABCL5561E', 'AAATP8834G', 'BGRPK2219M', 'AFKPK7745C'], { list: false }),
        status(['Verified', 'Pending', 'Under Review'], { gen: ['Verified', 'Verified', 'Verified', 'Pending', 'Under Review', 'Verified', 'Pending', 'Verified', 'Under Review', 'Pending', 'Verified', 'Pending', 'Verified', 'Verified', 'Pending', 'Under Review'] }),
      ],
    },
    {
      id: 'landOwnership',
      label: 'Ownership Record',
      plural: 'Ownership Records',
      app: 'land',
      codePrefix: 'OWN',
      titleField: 'owner',
      count: 16,
      fields: [
        text('owner', 'Recorded Owner', ['R. Subramaniam', 'R. Kumar (brother)', 'Sri Venkateswara Agro Farms', 'K. Munirathnam', 'P. Natarajan (HUF)', 'Lakeview Estates', 'Prakash Family Trust', 'S. Kandasamy', 'A. Karuppasamy', 'Sri Lakshmi Estates', 'Pinnacle Realty', 'Coastal Healthcare Trust', 'M. Gopal', 'Orbit Tech Parks', 'Kongu Textiles Pvt Ltd', 'R. Meenakshi'], { required: true }),
        ref('parcel', 'Land Parcel', 'landLead', { required: true }),
        text('surveyNo', 'Survey No.', ['214/2A', '215/1', '88/1', '341/3', '402/1B', '147', '62/4', '12/3', '1184', '510', '227', '92/2', '76/2', '45/1B', '118/2', '12/7']),
        text('patta', 'Patta No.', ['1482', '1483', '2210', '879', '3341', '—', '—', '614', '5127', '2098', '—', '—', '1776', '3302', '4410', '618']),
        select('ownership', 'Ownership Type', ['Absolute', 'Joint', 'Inherited', 'Power of Attorney', 'Leasehold']),
        select('acquiredBy', 'Acquired By', ['Inheritance', 'Sale Deed', 'Gift Deed', 'Partition Deed', 'Settlement Deed']),
        num('extent', 'Extent', [0.8, 12.5], { unit: 'acres' }),
        date('since', 'Owned Since', [-12000, -600]),
        status(['Verified', 'Pending', 'Disputed'], { gen: ['Verified', 'Verified', 'Verified', 'Verified', 'Pending', 'Verified', 'Verified', 'Pending', 'Verified', 'Disputed', 'Pending', 'Verified', 'Pending', 'Verified', 'Verified', 'Pending'] }),
      ],
    },
    {
      id: 'landEncumbrance',
      label: 'Encumbrance Record',
      plural: 'Encumbrance Records',
      app: 'land',
      codePrefix: 'EC',
      titleField: 'ecNo',
      count: 14,
      fields: [
        text('ecNo', 'EC Number', ['EC/THP/2026/10482', 'EC/SPR/2026/08816', 'EC/HSR/2026/04471', 'EC/CBE/2026/12093', 'EC/GND/2026/3312', 'EC/KRP/2026/2208', 'EC/SPR/2026/09154', 'EC/MDU/2026/06120', 'EC/CGL/2026/11745', 'EC/MLS/2026/5528', 'EC/VSP/2026/2871', 'EC/PML/2026/07733', 'EC/SLG/2026/01928', 'EC/CBE/2026/12610'], { required: true }),
        ref('parcel', 'Land Parcel', 'landLead', { required: true }),
        text('sro', 'Sub-Registrar Office', ['SRO Thiruporur', 'SRO Sriperumbudur', 'SRO Hosur', 'SRO Gandhipuram', 'SRO Gandipet', 'SRO K.R. Puram', 'SRO Sriperumbudur', 'SRO Madurai North', 'SRO Guduvanchery', 'SRO Mulshi', 'SRO Madhurawada', 'SRO Poonamallee', 'SRO Sholinganallur', 'SRO Peelamedu']),
        text('period', 'EC Period', ['1996 – 2026 (30 yrs)', '1994 – 2026 (32 yrs)', '1996 – 2026 (30 yrs)', '1990 – 2026 (36 yrs)']),
        select('charge', 'Encumbrance Found', ['Nil', 'Mortgage', 'Lien', 'Lease', 'Court Attachment'], { gen: ['Nil', 'Mortgage', 'Nil', 'Nil', 'Lease', 'Nil', 'Nil', 'Nil', 'Court Attachment', 'Mortgage', 'Nil', 'Nil', 'Nil', 'Lien'] }),
        text('holder', 'Charge Holder', ['—', 'Indian Bank, Sriperumbudur', '—', '—', 'Agri lease (expired 2019)', '—', '—', '—', 'District Court, Chengalpattu', 'HDFC Bank', '—', '—', '—', 'Canara Bank']),
        money('amount', 'Charge Amount', [0, 45000000]),
        date('issued', 'EC Date', [-120, -2]),
        status(['Clear', 'Under Review', 'Disputed', 'Pending'], { gen: ['Clear', 'Under Review', 'Clear', 'Clear', 'Clear', 'Clear', 'Pending', 'Clear', 'Disputed', 'Under Review', 'Clear', 'Pending', 'Clear', 'Under Review'] }),
      ],
    },
    {
      id: 'landLitigation',
      label: 'Litigation',
      plural: 'Litigation Cases',
      app: 'land',
      codePrefix: 'LIT',
      titleField: 'caseTitle',
      count: 10,
      form: 'page',
      fields: [
        text('caseTitle', 'Case', ['Partition suit by legal heirs — S.No. 512', 'Boundary dispute with adjoining owner', 'Injunction against alienation', 'Tenancy claim by cultivating tenant', 'Title dispute — forged GPA alleged', 'Road access easement claim', 'Land acquisition compensation appeal', 'Specific performance suit by prior buyer', 'Patta cancellation appeal', 'Encroachment eviction petition'], { required: true }),
        ref('parcel', 'Land Parcel', 'landLead', { required: true }),
        text('caseNo', 'Case No.', ['O.S. 412/2024', 'O.S. 118/2025', 'I.A. 776/2025', 'R.C.O.P. 22/2023', 'O.S. 903/2022', 'O.S. 57/2026', 'L.A.O.P. 14/2021', 'O.S. 266/2025', 'R.A. 31/2026', 'W.P. 18841/2025']),
        text('court', 'Court / Forum', ['District Court, Chengalpattu', 'Sub Court, Sriperumbudur', 'District Munsif, Thiruporur', 'Rent Controller, Coimbatore', 'City Civil Court, Hyderabad', 'Sub Court, Hosur', 'LAO Court, Kanchipuram', 'City Civil Court, Bengaluru', 'RDO, Poonamallee', 'High Court of Madras']),
        select('type', 'Case Type', ['Title Dispute', 'Partition Suit', 'Injunction', 'Boundary Dispute', 'Tenancy', 'Land Acquisition', 'Specific Performance']),
        text('counsel', 'Our Counsel', ['Adv. S. Ramanathan', 'Adv. K. Revathi', 'Adv. M. Prabhakar', 'Adv. J. Anitha']),
        date('nextHearing', 'Next Hearing', [5, 90]),
        money('exposure', 'Financial Exposure', [2000000, 60000000]),
        area('remarks', 'Case Summary', ['Plaintiffs claim 1/5th share; settlement talks in progress.', 'Commissioner appointed for measurement.', 'Interim injunction vacated on 12 Aug 2026.']),
        status(['Open', 'Under Review', 'Resolved', 'Closed'], { gen: ['Open', 'Under Review', 'Resolved', 'Closed', 'Open', 'Under Review', 'Closed', 'Resolved', 'Under Review', 'Closed'] }),
      ],
    },
    {
      id: 'landLegalOpinion',
      label: 'Legal Opinion',
      plural: 'Legal Opinions',
      app: 'land',
      codePrefix: 'LOP',
      titleField: 'subject',
      count: 12,
      fields: [
        text('subject', 'Opinion On', PARCEL_NAMES.slice(0, 12).map((p) => `Title opinion — ${p}`), { required: true }),
        ref('parcel', 'Land Parcel', 'landLead', { required: true }),
        text('advocate', 'Advocate / Firm', ['Ramanathan & Associates', 'K. Revathi, Advocate', 'Prabhakar Legal LLP', 'Anitha & Co.', 'Reddy Law Chambers', 'Kulkarni & Partners']),
        date('date', 'Opinion Date', [-90, 10]),
        select('opinion', 'Opinion', ['Clear & Marketable', 'Clear with Conditions', 'Defective Title', 'Pending Documents'], { gen: ['Clear with Conditions', 'Clear & Marketable', 'Clear & Marketable', 'Pending Documents', 'Pending Documents', 'Clear with Conditions', 'Pending Documents', 'Clear & Marketable', 'Defective Title', 'Pending Documents', 'Pending Documents', 'Clear & Marketable'] }),
        money('fee', 'Professional Fee', [75000, 350000]),
        area('conditions', 'Conditions / Remarks', ['Release deed from co-owner R. Kumar to be registered before sale.', 'Mortgage with Indian Bank to be closed and release deed obtained.', 'Original 1984 parent deed to be produced.']),
        status(['Draft', 'Under Review', 'Approved', 'Rejected'], { gen: ['Approved', 'Approved', 'Approved', 'Under Review', 'Draft', 'Approved', 'Under Review', 'Approved', 'Rejected', 'Draft', 'Under Review', 'Approved'] }),
      ],
    },
    {
      id: 'landSurvey',
      label: 'Land Survey',
      plural: 'Land Surveys',
      app: 'land',
      codePrefix: 'SRV',
      titleField: 'title',
      count: 12,
      fields: [
        text('title', 'Survey', PARCEL_NAMES.slice(0, 12).map((p) => `DGPS survey — ${p}`), { required: true }),
        ref('parcel', 'Land Parcel', 'landLead', { required: true }),
        select('type', 'Survey Type', ['DGPS Survey', 'Total Station', 'Boundary Demarcation', 'FMB Verification']),
        text('agency', 'Survey Agency', ['GeoPoint Surveyors', 'Precision Land Survey Co.', 'TerraMap Consultants', 'Prakash J (in-house)']),
        date('date', 'Survey Date', [-75, 20]),
        num('recorded', 'Recorded Extent', [1.8, 31], { unit: 'acres' }),
        num('measured', 'Measured Extent', [1.7, 30.6], { unit: 'acres' }),
        num('variance', 'Variance', [-3.5, 1.5], { unit: '%' }),
        status(['Scheduled', 'In Progress', 'Completed', 'Under Review'], { gen: ['Completed', 'Completed', 'Completed', 'Scheduled', 'In Progress', 'Completed', 'Scheduled', 'Completed', 'Completed', 'Under Review', 'Scheduled', 'Completed'] }),
      ],
    },
    {
      id: 'landSoilTest',
      label: 'Soil Test',
      plural: 'Soil Tests',
      app: 'land',
      codePrefix: 'SOIL',
      titleField: 'title',
      count: 10,
      fields: [
        text('title', 'Investigation', PARCEL_NAMES.slice(0, 10).map((p) => `Geotechnical investigation — ${p}`), { required: true }),
        ref('parcel', 'Land Parcel', 'landLead', { required: true }),
        text('lab', 'Testing Agency', ['Geo Foundations & Structurals', 'Soil Tech Labs, Chennai', 'NABL Geotech Services', 'Deccan Soil Investigations']),
        num('boreholes', 'Bore Holes', [4, 12]),
        num('depth', 'Max Depth', [15, 30], { unit: 'm' }),
        select('soilType', 'Predominant Strata', ['Hard Murram', 'Sandy Clay', 'Black Cotton Soil', 'Weathered Rock', 'Silty Sand', 'Hard Rock']),
        num('sbc', 'Safe Bearing Capacity', [12, 45], { unit: 't/m²' }),
        num('waterTable', 'Water Table', [1.5, 12], { unit: 'm bgl' }),
        select('foundation', 'Recommended Foundation', ['Isolated Footing', 'Raft', 'Pile Foundation', 'Combined Footing'], { list: false }),
        status(['Scheduled', 'In Progress', 'Completed', 'Under Review'], { gen: ['Completed', 'In Progress', 'Completed', 'Scheduled', 'Under Review', 'Completed', 'Scheduled', 'Completed', 'Completed', 'In Progress'] }),
      ],
    },
    {
      id: 'landTopo',
      label: 'Topographical Survey',
      plural: 'Topographical Surveys',
      app: 'land',
      codePrefix: 'TOPO',
      titleField: 'title',
      count: 10,
      fields: [
        text('title', 'Survey', PARCEL_NAMES.slice(0, 10).map((p) => `Contour survey — ${p}`), { required: true }),
        ref('parcel', 'Land Parcel', 'landLead', { required: true }),
        text('agency', 'Agency', ['GeoPoint Surveyors', 'TerraMap Consultants', 'SkyEye Drone Surveys', 'Precision Land Survey Co.']),
        date('date', 'Survey Date', [-60, 15]),
        num('contour', 'Contour Interval', [0.5, 1], { unit: 'm' }),
        num('levelDiff', 'Level Difference', [0.6, 7.5], { unit: 'm' }),
        num('cutFill', 'Cut / Fill Volume', [4000, 85000], { unit: 'cum' }),
        select('drainage', 'Natural Drainage', ['Slope towards north', 'Slope towards east', 'Flat — storm drain needed', 'Low-lying — filling required']),
        status(['Scheduled', 'In Progress', 'Completed', 'Under Review'], { gen: ['Completed', 'Completed', 'In Progress', 'Scheduled', 'Completed', 'Under Review', 'Scheduled', 'Completed', 'Completed', 'In Progress'] }),
      ],
    },
    {
      id: 'landZoning',
      label: 'Zoning Record',
      plural: 'Zoning Records',
      app: 'land',
      codePrefix: 'ZN',
      titleField: 'masterPlan',
      count: 12,
      fields: [
        text('masterPlan', 'Master Plan', ['CMDA Second Master Plan 2026', 'DTCP Sriperumbudur LPA', 'Hosur LPA Master Plan', 'Coimbatore LPA Master Plan', 'HMDA Master Plan 2031', 'BDA RMP 2015', 'DTCP Sriperumbudur LPA', 'Madurai LPA Master Plan', 'CMDA Second Master Plan 2026', 'PMRDA Development Plan', 'VMRDA Master Plan 2041', 'CMDA Second Master Plan 2026'], { required: true }),
        ref('parcel', 'Land Parcel', 'landLead', { required: true }),
        select('authority', 'Authority', ['CMDA', 'DTCP', 'HMDA', 'BDA', 'PMRDA', 'VMRDA'], { gen: ['CMDA', 'DTCP', 'DTCP', 'DTCP', 'HMDA', 'BDA', 'DTCP', 'DTCP', 'CMDA', 'PMRDA', 'VMRDA', 'CMDA'] }),
        select('zone', 'Zone', ['Primary Residential', 'Mixed Residential', 'Commercial', 'Industrial', 'Agricultural', 'Institutional']),
        num('fsi', 'Permissible FSI', [1.5, 3.25]),
        num('height', 'Max Height', [15, 90], { unit: 'm' }),
        num('roadWidth', 'Abutting Road Width', [9, 30], { unit: 'm' }),
        status(['Verified', 'Under Review', 'Pending'], { gen: ['Verified', 'Verified', 'Verified', 'Under Review', 'Verified', 'Pending', 'Under Review', 'Verified', 'Verified', 'Pending', 'Under Review', 'Verified'] }),
      ],
    },
    {
      id: 'landUse',
      label: 'Land Use Conversion',
      plural: 'Land Use Records',
      app: 'land',
      codePrefix: 'LU',
      titleField: 'applicationNo',
      count: 12,
      fields: [
        text('applicationNo', 'Application No.', ['LUC/CMDA/2026/0412', 'LUC/DTCP/KPM/2026/118', 'LUC/DTCP/KGI/2026/077', 'LUC/DTCP/CBE/2026/204', 'CLU/HMDA/2026/1893', 'CLU/BDA/2026/338', 'LUC/DTCP/KPM/2026/131', 'LUC/DTCP/MDU/2025/412', 'LUC/CMDA/2026/0388', 'NA/PMRDA/2026/2117', 'CLU/VMRDA/2026/091', 'LUC/CMDA/2026/0457'], { required: true }),
        ref('parcel', 'Land Parcel', 'landLead', { required: true }),
        select('currentUse', 'Current Use', ['Agricultural (Wet)', 'Agricultural (Dry)', 'Vacant', 'Plantation', 'Industrial']),
        select('proposedUse', 'Proposed Use', ['Residential', 'Commercial', 'Industrial', 'Institutional', 'Mixed Use']),
        date('appliedOn', 'Applied On', [-180, -10]),
        money('fee', 'Conversion Fee', [450000, 9800000]),
        status(['Not Started', 'Pending', 'Under Review', 'Approved', 'Rejected'], { gen: ['Under Review', 'Pending', 'Approved', 'Not Started', 'Under Review', 'Pending', 'Not Started', 'Approved', 'Rejected', 'Pending', 'Not Started', 'Approved'] }),
      ],
    },
    {
      id: 'landApproval',
      label: 'Planning Approval',
      plural: 'Planning Approvals',
      app: 'land',
      codePrefix: 'APR',
      titleField: 'name',
      count: 14,
      form: 'page',
      fields: [
        text('name', 'Approval', ['Layout Approval (DTCP)', 'Planning Permission (CMDA)', 'Building Plan Approval', 'Land Use Conversion', 'Environmental Clearance (SEIAA)', 'RERA Project Registration', 'Sub-division Approval', 'Change of Land Use (HMDA)', 'Industrial Building Approval (DISH)', 'Road Access Permission (NHAI)', 'Development Permission (PMRDA)', 'Height Clearance (AAI NOCAS)', 'Group Development Approval', 'Commencement Certificate'], { required: true }),
        ref('parcel', 'Land Parcel', 'landLead', { required: true }),
        text('authority', 'Authority', ['DTCP Tamil Nadu', 'CMDA', 'Hosur Local Planning Authority', 'DTCP Tamil Nadu', 'SEIAA Tamil Nadu', 'TNRERA', 'DTCP Tamil Nadu', 'HMDA', 'DISH Tamil Nadu', 'NHAI PIU Chennai', 'PMRDA', 'Airports Authority of India', 'CMDA', 'Greater Hyderabad Municipal Corporation']),
        text('applicationNo', 'Application No.', ['DTCP/LA/2026/1182', 'CMDA/PP/2026/4471', 'HLPA/BPA/2026/219', 'DTCP/LUC/2026/077', 'SEIAA/TN/F.9812/2026', 'TN/29/Building/0418/2026', 'DTCP/SD/2026/332', 'HMDA/CLU/2026/1893']),
        date('submitted', 'Submitted On', [-150, -5]),
        date('expected', 'Expected Approval', [10, 150]),
        money('fee', 'Fees Paid', [250000, 18500000]),
        ref('owner', 'Liaison Officer', 'employee'),
        status(['Not Started', 'Submitted', 'Under Review', 'Approved', 'Rejected'], { gen: ['Approved', 'Under Review', 'Approved', 'Submitted', 'Under Review', 'Not Started', 'Approved', 'Under Review', 'Submitted', 'Approved', 'Not Started', 'Under Review', 'Submitted', 'Rejected'] }),
      ],
    },
    {
      id: 'landNoc',
      label: 'NOC',
      plural: 'NOCs',
      app: 'land',
      codePrefix: 'NOC',
      titleField: 'name',
      count: 12,
      fields: [
        text('name', 'NOC', ['Fire Service NOC', 'Airport Authority Height NOC', 'Pollution Control Board — CTE', 'Highways Access NOC', 'Water Resources (PWD) NOC', 'Electricity Board NOC', 'Forest Department NOC', 'Railway Boundary NOC', 'Revenue Department NOC', 'Metro Water Feasibility NOC', 'Police (Traffic) NOC', 'Heritage Committee NOC'], { required: true }),
        ref('parcel', 'Land Parcel', 'landLead', { required: true }),
        text('department', 'Department', ['TN Fire & Rescue Services', 'Airports Authority of India', 'TNPCB', 'State Highways', 'WRD — PWD', 'TANGEDCO', 'District Forest Office', 'Southern Railway', 'District Collectorate', 'CMWSSB', 'Greater Chennai Traffic Police', 'Heritage Conservation Committee']),
        date('applied', 'Applied On', [-120, -5]),
        date('validity', 'Valid Till', [-20, 900]),
        status(['Pending', 'Submitted', 'Approved', 'Rejected', 'Expired'], { gen: ['Approved', 'Approved', 'Pending', 'Submitted', 'Approved', 'Pending', 'Submitted', 'Approved', 'Expired', 'Pending', 'Rejected', 'Submitted'] }),
      ],
    },
    {
      id: 'landAgreement',
      label: 'Land Agreement',
      plural: 'Land Agreements',
      app: 'land',
      codePrefix: 'AGR',
      titleField: 'title',
      fields: [
        text('title', 'Agreement', agreementData.map((a) => a[0]), { required: true }),
        ref('parcel', 'Land Parcel', 'landLead', { required: true }),
        text('seller', 'Vendor(s)'),
        text('purchaser', 'Purchaser'),
        date('agreementDate', 'Agreement Date'),
        money('consideration', 'Sale Consideration'),
        money('advance', 'Advance Paid'),
        money('stampDuty', 'Stamp Duty'),
        date('completion', 'Completion Date'),
        status(['Draft', 'Under Review', 'Signed', 'Registered']),
      ],
      rows: agreementRows,
    },
    {
      id: 'landPurchase',
      label: 'Purchase Payment',
      plural: 'Purchase Payments',
      app: 'land',
      codePrefix: 'LPY',
      titleField: 'description',
      count: 16,
      fields: [
        text('description', 'Payment', ['Advance — Kelambakkam parcel', 'Advance — Madurai Ring Road site', 'Balance consideration — Madurai site', 'Stamp duty — Madurai site', 'Registration fee — Madurai site', 'Advance — Perungudi plot', 'Balance consideration — Perungudi plot', 'Stamp duty — Perungudi plot', 'Brokerage — Perungudi plot', 'Part payment — Kelambakkam (title deeds)', 'Part payment — Kelambakkam (patta transfer)', 'Balance — Kelambakkam (registration)', 'Advance — Hosur Bagalur Road', 'Token advance — Neelambur', 'Legal & survey charges — Kelambakkam', 'Brokerage — Kelambakkam'], { required: true }),
        ref('parcel', 'Land Parcel', 'landLead', { required: true }),
        select('milestone', 'Milestone', ['Advance', 'Part Payment', 'Balance Payment', 'Stamp Duty', 'Registration Fee', 'Brokerage', 'Other Charges'], { gen: ['Advance', 'Advance', 'Balance Payment', 'Stamp Duty', 'Registration Fee', 'Advance', 'Balance Payment', 'Stamp Duty', 'Brokerage', 'Part Payment', 'Part Payment', 'Balance Payment', 'Advance', 'Advance', 'Other Charges', 'Brokerage'] }),
        money('amount', 'Amount', [800000, 190000000]),
        date('due', 'Due Date', [-160, 130]),
        select('mode', 'Payment Mode', ['RTGS', 'NEFT', 'Demand Draft', 'e-Challan']),
        text('utr', 'UTR / Challan No.', ['UTIBR52026092514', 'HDFCR52026051422', 'HDFCR52026071008', 'TNREG/2026/448120', 'TNREG/2026/448121', 'ICICR52026042209', 'ICICR52026063011', 'TNREG/2026/391044', 'NEFT-88412', '—', '—', '—', '—', '—', 'NEFT-90217', '—'], { list: false }),
        status(['Paid', 'Scheduled', 'Pending', 'Overdue'], { gen: ['Paid', 'Paid', 'Paid', 'Paid', 'Paid', 'Paid', 'Paid', 'Paid', 'Paid', 'Scheduled', 'Scheduled', 'Scheduled', 'Pending', 'Overdue', 'Paid', 'Pending'] }),
      ],
    },
  ],
};
