import { addDays, DEMO_TODAY, toISO } from '@/lib/format';
import { area, date, group, lineItems, money, monthCalendar, num, page, pct, ref, register, select, status, statusView, text } from '../dsl';
import type { AppConfig, Row } from '../types';

const d = (n: number) => toISO(addDays(DEMO_TODAY, n));
const code = (prefix: string, i: number) => `${prefix}-${String(i + 1).padStart(3, '0')}`;

const PO_STATUS = ['Draft', 'Pending Approval', 'Approved', 'Ordered', 'Partially Received', 'Fully Received', 'Closed', 'Cancelled'];
const PAY_TERMS = ['100% advance', '30 days credit', '45 days credit', '60 days credit', '10% advance, balance 30 days', 'Against delivery'];
const PR_CATEGORIES = ['Steel', 'Cement', 'Ready Mix Concrete', 'Aggregates & Sand', 'Bricks & Blocks', 'Plumbing', 'Electrical', 'Finishes', 'Shuttering', 'Chemicals', 'Hardware', 'Safety', 'Fuel', 'Paints', 'Equipment Hire', 'Testing & Survey', 'Treatment', 'Maintenance', 'Housekeeping'];
const PO_CATEGORIES = ['Steel', 'Cement', 'Ready Mix Concrete', 'Aggregates & Sand', 'Bricks & Blocks', 'Electrical', 'Plumbing', 'Paints', 'Finishes', 'Shuttering', 'Safety', 'Hardware', 'Glazing', 'Equipment Rental', 'Timber', 'Fuel', 'Chemicals', 'Vertical Transport', 'Landscaping'];

/* ───────── Purchase orders (fixed rows so vendor, material and value always agree) ───────── */
// [description, vendor, project, category, value (₹ incl. GST), PO date offset, delivery offset, payment terms, received %, status]
const poData: [string, string, string, string, number, number, number, string, number, string][] = [
  ['TMT Steel Fe500D — Tower A & B slabs', 'VEN-002', 'PRJ-001', 'Steel', 10945200, -38, 6, '30 days credit', 64, 'Partially Received'],
  ['Cement OPC 53 & PPC — Q3 requirement', 'VEN-001', 'PRJ-001', 'Cement', 4537600, -34, 4, '30 days credit', 78, 'Partially Received'],
  ['RMC M25 / M30 — superstructure L8–L12', 'VEN-003', 'PRJ-004', 'Ready Mix Concrete', 14320000, -30, 14, '45 days credit', 55, 'Partially Received'],
  ['M-Sand, P-Sand & 20mm aggregate — Phase 2', 'VEN-004', 'PRJ-003', 'Aggregates & Sand', 3790000, -9, 8, 'Against delivery', 0, 'Ordered'],
  ['AAC blocks & block-joint mortar — Cluster 3', 'VEN-005', 'PRJ-002', 'Bricks & Blocks', 4002000, -7, 11, '30 days credit', 0, 'Ordered'],
  ['FR cables, DBs & conduits — Tower A floors 5–12', 'VEN-006', 'PRJ-001', 'Electrical', 1886000, -3, 18, '45 days credit', 0, 'Approved'],
  ['CPVC & uPVC piping — Villas cluster 3', 'VEN-007', 'PRJ-002', 'Plumbing', 948000, -2, 21, '30 days credit', 0, 'Pending Approval'],
  ['Interior & exterior emulsion paints', 'VEN-008', 'PRJ-006', 'Paints', 1420000, -52, -18, '30 days credit', 100, 'Fully Received'],
  ['Vitrified tiles 600×600 & Black Galaxy granite', 'VEN-009', 'PRJ-005', 'Finishes', 6240000, -12, 16, '10% advance, balance 30 days', 0, 'Ordered'],
  ['Aluminium formwork system — hire 4 months', 'VEN-010', 'PRJ-004', 'Shuttering', 2860000, -61, -40, '100% advance', 100, 'Fully Received'],
  ['PPE kits — helmets, harnesses, safety shoes', 'VEN-011', 'PRJ-003', 'Safety', 685000, -74, -60, 'Against delivery', 100, 'Closed'],
  ['Hardware & site consumables — September', 'VEN-012', 'PRJ-005', 'Hardware', 312000, -28, -15, '30 days credit', 100, 'Closed'],
  ['Façade glazing — toughened glass 8mm & sections', 'VEN-013', 'PRJ-004', 'Glazing', 12840000, -15, 24, '10% advance, balance 30 days', 0, 'Ordered'],
  ['DG set 250 kVA rental — 6 months', 'VEN-014', 'PRJ-003', 'Equipment Rental', 1140000, -4, 3, '30 days credit', 0, 'Approved'],
  ['Mobile crane 50 T hire — façade lifting', 'VEN-015', 'PRJ-004', 'Equipment Rental', 875000, -20, 2, '30 days credit', 40, 'Partially Received'],
  ['Shuttering plywood & timber battens', 'VEN-016', 'PRJ-002', 'Timber', 764000, -45, -30, '30 days credit', 100, 'Fully Received'],
  ['HSD diesel — site DG & equipment (Aug)', 'VEN-017', 'PRJ-001', 'Fuel', 1260000, -58, -32, 'Against delivery', 100, 'Closed'],
  ['Crystalline waterproofing — basement', 'VEN-018', 'PRJ-005', 'Chemicals', 990000, 0, 28, '30 days credit', 0, 'Draft'],
  ['Passenger lifts 13-pax × 4 — supply & install', 'VEN-019', 'PRJ-001', 'Vertical Transport', 23600000, -26, 30, '10% advance, balance 30 days', 0, 'Ordered'],
  ['Landscaping & softscape — clubhouse', 'VEN-020', 'PRJ-003', 'Landscaping', 1840000, -40, 20, '30 days credit', 0, 'Cancelled'],
  ['TMT Steel Fe500D 12 / 16mm — raft', 'VEN-002', 'PRJ-005', 'Steel', 7860000, -90, -64, '30 days credit', 100, 'Fully Received'],
  ['RMC M30 — raft & basement walls', 'VEN-003', 'PRJ-007', 'Ready Mix Concrete', 9650000, -110, -70, '45 days credit', 100, 'Closed'],
  ['Cement PPC — block work & plaster', 'VEN-001', 'PRJ-008', 'Cement', 2240000, -18, 5, '30 days credit', 45, 'Partially Received'],
  ['Coarse aggregate 20mm — internal roads', 'VEN-004', 'PRJ-003', 'Aggregates & Sand', 1480000, -1, 12, 'Against delivery', 0, 'Pending Approval'],
];
const BUYERS = ['EMP-011', 'EMP-011', 'EMP-009', 'EMP-011', 'EMP-029'];
const poRows: Row[] = poData.map(([title, vendor, project, category, amount, poDate, delivery, paymentTerms, received, st], i) => ({
  id: code('PO', i),
  code: code('PO', i),
  title,
  vendor,
  project,
  category,
  amount,
  delivery: d(delivery),
  received,
  status: st,
  buyer: BUYERS[i % BUYERS.length],
  poDate: d(poDate),
  paymentTerms,
  deliveryTerms: i % 3 === 0 ? 'FOR site' : i % 3 === 1 ? 'Door delivery' : 'Ex-works',
}));

/* ───────── Delivery schedule (upcoming & delayed consignments) ───────── */
// [consignment, PO, vendor, project, date offset, quantity, status]
const deliveryData: [string, string, string, string, number, string, string][] = [
  ['TMT 16mm — balance lot', 'PO-001', 'VEN-002', 'PRJ-001', -4, '16 MT', 'Delayed'],
  ['Cement OPC 53 — lot 3', 'PO-002', 'VEN-001', 'PRJ-001', -2, '1,000 Bags', 'Delayed'],
  ['RMC M30 — L10 slab pour', 'PO-003', 'VEN-003', 'PRJ-004', -1, '310 Cum', 'Delayed'],
  ['Mobile crane mobilisation', 'PO-015', 'VEN-015', 'PRJ-004', -3, '1 No', 'Delayed'],
  ['Cement PPC — lot 2', 'PO-023', 'VEN-001', 'PRJ-008', -5, '2,400 Bags', 'Delayed'],
  ['TMT 25mm — columns L11', 'PO-001', 'VEN-002', 'PRJ-001', 0, '22 MT', 'In Transit'],
  ['DG set 250 kVA', 'PO-014', 'VEN-014', 'PRJ-003', 1, '1 No', 'Dispatched'],
  ['RMC M25 — staircase & lift core', 'PO-003', 'VEN-003', 'PRJ-004', 2, '120 Cum', 'Scheduled'],
  ['M-Sand — lot 1', 'PO-004', 'VEN-004', 'PRJ-003', 4, '300 Cum', 'Scheduled'],
  ['Cement OPC 53 — lot 4', 'PO-002', 'VEN-001', 'PRJ-001', 5, '1,300 Bags', 'Scheduled'],
  ['AAC blocks — lot 1', 'PO-005', 'VEN-005', 'PRJ-002', 7, '16,000 Nos', 'Scheduled'],
  ['Coarse aggregate 20mm — lot 1', 'PO-004', 'VEN-004', 'PRJ-003', 9, '380 Cum', 'Scheduled'],
  ['Vitrified tiles 600×600', 'PO-009', 'VEN-009', 'PRJ-005', 12, '2,400 Sqm', 'Scheduled'],
  ['FR cables & DBs', 'PO-006', 'VEN-006', 'PRJ-001', 15, '320 Coils + 96 Nos', 'Scheduled'],
  ['Toughened glass 8mm — lot 1', 'PO-013', 'VEN-013', 'PRJ-004', 19, '1,850 Sqm', 'Scheduled'],
  ['CPVC / uPVC pipes & fittings', 'PO-007', 'VEN-007', 'PRJ-002', 21, '2,600 Mtr', 'Scheduled'],
  ['Lift cars & machines — Tower A', 'PO-019', 'VEN-019', 'PRJ-001', 27, '2 Sets', 'Scheduled'],
  ['Lift cars & machines — Tower B', 'PO-019', 'VEN-019', 'PRJ-001', 34, '2 Sets', 'Scheduled'],
];
const deliveryRows: Row[] = deliveryData.map(([title, po, vendor, project, dt, qty, st], i) => ({
  id: code('DS', i),
  code: code('DS', i),
  title,
  po,
  vendor,
  project,
  scheduled: d(dt),
  qty,
  vehicle: ['TN 01 AX 4412', 'TN 22 BK 7781', 'KA 05 MN 2210', 'TN 09 CQ 6634', 'TN 58 AR 1109', 'TN 01 BZ 9087'][i % 6],
  status: st,
}));

/* ───────── PO line items ───────── */
// [section (PO), description, unit, qty, rate, received]
const poLineData: [string, string, string, number, number, number][] = [
  ['PO-001 · Shree Balaji Steel Traders', 'TMT Bar Fe500D 8mm', 'MT', 18, 62400, 18],
  ['PO-001 · Shree Balaji Steel Traders', 'TMT Bar Fe500D 12mm', 'MT', 42, 61100, 30],
  ['PO-001 · Shree Balaji Steel Traders', 'TMT Bar Fe500D 16mm', 'MT', 56, 60700, 40],
  ['PO-001 · Shree Balaji Steel Traders', 'TMT Bar Fe500D 25mm', 'MT', 34, 60300, 12],
  ['PO-001 · Shree Balaji Steel Traders', 'Binding Wire 18G', 'Kg', 1800, 76, 1800],
  ['PO-002 · UltraBuild Cements', 'Cement OPC 53 Grade', 'Bag', 6000, 382, 3700],
  ['PO-002 · UltraBuild Cements', 'Cement PPC', 'Bag', 3500, 358, 3500],
  ['PO-003 · Chennai RMC Pvt Ltd', 'Ready Mix Concrete M25', 'Cum', 850, 5450, 520],
  ['PO-003 · Chennai RMC Pvt Ltd', 'Ready Mix Concrete M30', 'Cum', 620, 5820, 310],
  ['PO-003 · Chennai RMC Pvt Ltd', 'Boom pump charges (36 m)', 'Cum', 1470, 280, 830],
  ['PO-004 · Sri Murugan Aggregates', 'M-Sand', 'Cum', 900, 1840, 0],
  ['PO-004 · Sri Murugan Aggregates', 'P-Sand (Plastering)', 'Cum', 420, 2120, 0],
  ['PO-004 · Sri Murugan Aggregates', 'Coarse Aggregate 20mm', 'Cum', 760, 1640, 0],
  ['PO-005 · Kaveri Bricks & Blocks', 'AAC Block 600×200×200', 'Nos', 48000, 57, 0],
  ['PO-005 · Kaveri Bricks & Blocks', 'Block-joint mortar (40 kg)', 'Bag', 1600, 410, 0],
  ['PO-006 · Apex Electricals', 'FR Cable 2.5 sq.mm (90 m coil)', 'Coil', 320, 2340, 0],
  ['PO-006 · Apex Electricals', 'Distribution Board 12-way TPN', 'Nos', 96, 4750, 0],
  ['PO-006 · Apex Electricals', 'PVC Conduit 25mm (heavy gauge)', 'Mtr', 12000, 38, 0],
];
const poLineRows: Row[] = poLineData.map(([section, description, unit, qty, rate, received], i) => ({ id: code('POL', i), code: code('POL', i), section, description, unit, qty, rate, received }));

const RATE_VENDORS = ['Shree Balaji Steel Traders', 'Deccan Hardware Mart', 'Sri Lakshmi Steel Agencies', 'Coromandel Iron & Steel'];

export const procurementApp: AppConfig = {
  id: 'procurement',
  name: 'Procurement',
  icon: 'ti-shopping-cart',
  description: 'Purchase requests, RFQs, vendor quotations, comparison, purchase orders and delivery tracking',
  menus: [
    group('Purchase Request', 'ti-file-plus', [
      page('Material Request', register('procPr', { filter: { type: 'Material Request' } })),
      page('Service Request', register('procPr', { filter: { type: 'Service Request' } })),
      page('Purchase Indent', register('procPr', { filter: { type: 'Purchase Indent' } })),
    ]),
    group('RFQ', 'ti-mail-forward', [
      page('Vendor Selection', {
        type: 'wizard',
        title: 'RFQ Vendor Selection',
        entity: 'procRfq',
        submitLabel: 'Issue RFQ',
        steps: [
          {
            title: 'Select Purchase Request',
            icon: 'ti-file-plus',
            note: 'Only approved purchase requests can be converted into an RFQ.',
            fields: [
              ref('pr', 'Purchase Request', 'procPr', { required: true }),
              ref('project', 'Project', 'project', { required: true }),
              select('category', 'Material Category', PR_CATEGORIES),
              date('due', 'Quotation Due Date', undefined, { required: true }),
            ],
          },
          {
            title: 'Shortlist Vendors',
            icon: 'ti-users',
            note: 'Vendors are suggested from the approved vendor list for the selected category.',
            lines: {
              columns: ['Vendor', 'Category', 'City', 'Rating', 'POs (FY)', 'Last Rate (₹/MT)', 'Shortlist'],
              rows: [
                ['VEN-002 · Shree Balaji Steel Traders', 'Steel', 'Chennai', 4.2, 14, '61,100', 'Yes'],
                ['VEN-012 · Deccan Hardware Mart', 'Hardware / Steel', 'Hyderabad', 4.0, 6, '61,800', 'Yes'],
                ['Sri Lakshmi Steel Agencies', 'Steel', 'Chennai', 4.3, 3, '61,400', 'Yes'],
                ['Coromandel Iron & Steel', 'Steel', 'Coimbatore', 3.9, 2, '62,600', 'Yes'],
                ['Tamil Nadu Rolling Mills Depot', 'Steel', 'Madurai', 3.6, 0, '—', 'No'],
              ],
            },
          },
          {
            title: 'Commercial Terms',
            icon: 'ti-file-description',
            fields: [
              select('paymentTerms', 'Payment Terms', PAY_TERMS, { required: true }),
              select('deliveryTerms', 'Delivery Terms', ['FOR site', 'Door delivery', 'Ex-works']),
              num('validity', 'Quote Validity', undefined, { unit: 'days', placeholder: '30' }),
              select('gst', 'Price Basis', ['Inclusive of GST', 'Exclusive of GST']),
              area('notes', 'Special Conditions', undefined, { placeholder: 'Mill test certificate with every lot; unloading at site by vendor…' }),
            ],
          },
          {
            title: 'Issue RFQ',
            icon: 'ti-send',
            checklist: ['Technical specification attached', 'Quantity schedule / BOQ attached', 'Delivery schedule defined', 'Vendor contact e-mails verified', 'Procurement Manager approval obtained'],
            upload: ['Technical Specification', 'Quantity Schedule (BOQ)'],
          },
        ],
      }),
      page('RFQ', register('procRfq', { tabs: { field: 'status', values: ['Draft', 'Issued', 'Under Evaluation', 'Closed', 'Cancelled'] } })),
      page('Quotation Request', register('procQuoteRequest')),
    ]),
    group('Vendor Quotations', 'ti-file-invoice', [
      page('Quotations', register('procQuotation')),
      page('Rate Comparison', {
        type: 'comparison',
        title: 'Rate Comparison — RFQ-001 TMT Steel Fe500D (Metro Office Tower)',
        subjectLabel: 'Item / Commercial term',
        subjects: RATE_VENDORS,
        recommend: 0,
        note: 'RFQ-001 · 150 MT TMT Fe500D + 1,800 kg binding wire for Metro Office Tower L8–L12. Rates in ₹ per unit, ex-GST. L1 on landed cost: Shree Balaji Steel Traders.',
        rows: [
          { group: 'Unit rates (₹)', label: 'TMT Fe500D 8mm — 18 MT (₹/MT)', values: [62400, 63200, 61900, 64100], best: 'min', format: 'currency' },
          { group: 'Unit rates (₹)', label: 'TMT Fe500D 12mm — 42 MT (₹/MT)', values: [61100, 61800, 61400, 62600], best: 'min', format: 'currency' },
          { group: 'Unit rates (₹)', label: 'TMT Fe500D 16mm — 56 MT (₹/MT)', values: [60700, 61300, 60500, 62000], best: 'min', format: 'currency' },
          { group: 'Unit rates (₹)', label: 'TMT Fe500D 25mm — 34 MT (₹/MT)', values: [60300, 60900, 60600, 61500], best: 'min', format: 'currency' },
          { group: 'Unit rates (₹)', label: 'Binding wire 18G — 1,800 kg (₹/kg)', values: [76, 74, 79, 72], best: 'min', format: 'currency' },
          { group: 'Totals (₹)', label: 'Basic value', values: [9275600, 9369800, 9283600, 9475600], best: 'min', format: 'currency' },
          { group: 'Totals (₹)', label: 'Freight & unloading', values: [0, 45000, 38000, 0], best: 'min', format: 'currency' },
          { group: 'Totals (₹)', label: 'GST @ 18%', values: [1669608, 1694664, 1677888, 1705608], format: 'currency' },
          { group: 'Totals (₹)', label: 'Landed cost (incl. GST)', values: [10945208, 11109464, 10999488, 11181208], best: 'min', format: 'currency' },
          { group: 'Commercial terms', label: 'Delivery lead time (days)', values: [7, 10, 5, 12], best: 'min', format: 'number' },
          { group: 'Commercial terms', label: 'Credit period (days)', values: [30, 45, 0, 30], best: 'max', format: 'number' },
          { group: 'Commercial terms', label: 'Payment terms', values: ['30 days credit', '45 days credit', '100% advance', '30 days credit'], format: 'text' },
          { group: 'Commercial terms', label: 'Quote validity (days)', values: [15, 7, 10, 15], best: 'max', format: 'number' },
          { group: 'Commercial terms', label: 'Vendor rating (out of 5)', values: [4.2, 4.0, 4.3, 3.9], best: 'max', format: 'number' },
        ],
      }),
      page('Technical Comparison', {
        type: 'comparison',
        title: 'Technical Comparison — RFQ-001 TMT Steel Fe500D',
        subjectLabel: 'Technical criterion',
        subjects: RATE_VENDORS,
        recommend: 0,
        note: 'Evaluated by QA/QC (Deepak Sharma) against IS 1786:2008 and project specification SPEC-STR-04.',
        rows: [
          { group: 'Specification compliance', label: 'IS 1786 Fe500D certification', values: ['Compliant', 'Compliant', 'Compliant', 'Compliant'], format: 'status' },
          { group: 'Specification compliance', label: 'Mill test certificate per heat', values: ['Compliant', 'Compliant', 'Pending', 'Compliant'], format: 'status' },
          { group: 'Specification compliance', label: 'Brand / source mill', values: ['Primary mill — TMT Fe500D', 'Primary mill — TMT Fe500D', 'Secondary mill — TMT Fe500D', 'Primary mill — TMT Fe500D'], format: 'text' },
          { group: 'Specification compliance', label: 'Third-party lab test (tensile / bend)', values: ['Passed', 'Passed', 'Under Review', 'Passed'], format: 'status' },
          { group: 'Capability', label: 'Supply experience (years)', values: [18, 11, 7, 22], best: 'max', format: 'number' },
          { group: 'Capability', label: 'Similar projects supplied', values: [26, 12, 8, 31], best: 'max', format: 'number' },
          { group: 'Capability', label: 'Monthly supply capacity (MT)', values: [900, 420, 350, 1200], best: 'max', format: 'number' },
          { group: 'Capability', label: 'Cut & bend facility', values: ['Compliant', 'Non-Compliant', 'Non-Compliant', 'Compliant'], format: 'status' },
          { group: 'Vendor compliance', label: 'GST & PAN verification', values: ['Verified', 'Verified', 'Verified', 'Verified'], format: 'status' },
          { group: 'Vendor compliance', label: 'Past delivery performance (on-time %)', values: [94, 88, 81, 90], best: 'max', format: 'percent' },
          { group: 'Vendor compliance', label: 'Overall technical result', values: ['Compliant', 'Compliant', 'Under Review', 'Compliant'], format: 'status' },
        ],
      }),
    ]),
    group('Purchase Order', 'ti-receipt', [
      page('PO', register('procPo', { tabs: { field: 'status', values: PO_STATUS } })),
      page('PO Items', lineItems('procPoItem', 'PO Items — open purchase orders', ['received'])),
      page('Delivery Schedule', monthCalendar('Delivery Schedule', 'procDelivery', 'scheduled')),
      page('Terms', register('procTerms')),
    ]),
    group('Procurement Tracking', 'ti-truck-delivery', [
      page('Ordered', statusView('procPo', 'Ordered')),
      page('Partially Received', statusView('procPo', 'Partially Received')),
      page('Fully Received', statusView('procPo', 'Fully Received')),
      page('Closed', statusView('procPo', 'Closed')),
    ]),
  ],
  dashboard: {
    flow: [
      { label: 'PR', value: '17 pending' },
      { label: 'RFQ', value: '9 open' },
      { label: 'Quotation', value: '23 received' },
      { label: 'PO', value: '42 open · ₹ 26.8 Cr' },
      { label: 'Delivery', value: '5 delayed' },
    ],
    kpis: [
      { label: 'Open Purchase Orders', value: '42', sub: '₹ 26.8 Cr open value', delta: '+6', up: true, progress: 64, icon: 'ti-receipt' },
      { label: 'Pending Purchase Requests', value: '17', delta: '-4', up: false, good: true, icon: 'ti-file-plus' },
      { label: 'Open RFQs', value: '9', sub: '23 quotations received', icon: 'ti-mail-forward' },
      { label: 'Deliveries Delayed', value: '5', delta: '+2', up: true, good: false, icon: 'ti-truck-delivery' },
      { label: 'PR → PO Cycle Time', value: '6.2 days', delta: '-0.8 d', up: false, good: true, icon: 'ti-clock' },
      { label: 'Negotiated Savings (FY)', value: '₹ 1.14 Cr', sub: '3.8% below budget rates', progress: 38, icon: 'ti-discount' },
    ],
    charts: [
      {
        title: 'Monthly PO Value vs Deliveries Received (₹ Cr)',
        kind: 'barline',
        categories: ['Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep'],
        series: [
          { name: 'PO value', data: [8.4, 9.6, 11.2, 10.1, 12.8, 9.9], type: 'bar' },
          { name: 'Received', data: [7.1, 8.8, 9.4, 10.6, 11.0, 8.2], type: 'line' },
        ],
        unit: '₹Cr',
        span: 2,
      },
      {
        title: 'Purchase Order Status',
        kind: 'donut',
        categories: ['Pending Approval', 'Approved', 'Ordered', 'Partially Received', 'Fully Received'],
        series: [{ name: 'POs', data: [8, 6, 20, 16, 31] }],
        tones: ['yellow', 'green', 'blue', 'yellow', 'green'],
        subtitle: '42 open POs',
      },
      {
        title: 'Spend by Category — FY 2026-27 (₹ Cr)',
        kind: 'hbar',
        categories: ['Steel', 'Ready Mix Concrete', 'Cement', 'Electrical', 'Vertical Transport', 'Aggregates & Sand', 'Finishes', 'Glazing'],
        series: [{ name: 'Spend', data: [12.6, 9.4, 4.8, 3.8, 3.6, 3.2, 2.9, 2.4] }],
        unit: '₹Cr',
        span: 2,
      },
      {
        title: 'Procurement Funnel (FY)',
        kind: 'funnel',
        categories: ['Purchase requests', 'RFQs issued', 'Quotations evaluated', 'POs placed'],
        series: [{ name: 'Count', data: [128, 96, 88, 74] }],
      },
    ],
    table: { entity: 'procPo', title: 'Recent Purchase Orders', columns: ['title', 'vendor', 'project', 'amount', 'delivery', 'status'], limit: 8 },
    rail: [
      {
        kind: 'health',
        title: 'Delivery Performance',
        items: [
          { label: 'On time', value: 34, tone: 'green' },
          { label: 'In transit', value: 9, tone: 'blue' },
          { label: 'Awaiting dispatch', value: 6, tone: 'yellow' },
          { label: 'Delayed', value: 5, tone: 'red' },
        ],
      },
      {
        kind: 'dates',
        title: 'Upcoming Deliveries',
        items: [
          { date: d(0), title: 'TMT 25mm — 22 MT', sub: 'Shree Balaji Steel Traders · Skyline Apartments' },
          { date: d(2), title: 'RMC M25 — 120 Cum', sub: 'Chennai RMC Pvt Ltd · Metro Office Tower' },
          { date: d(4), title: 'M-Sand — 300 Cum', sub: 'Sri Murugan Aggregates · Greenfield Township' },
          { date: d(7), title: 'AAC blocks — 16,000 Nos', sub: 'Kaveri Bricks & Blocks · Riverside Villas' },
        ],
      },
      {
        kind: 'list',
        title: 'Awaiting Your Approval',
        items: [
          { avatar: 'Rajesh Nair', title: 'PO-007 · CPVC & uPVC piping', sub: 'FlowLine Pipes & Fittings · ₹ 9.48 L', status: 'Pending Approval' },
          { avatar: 'Rajesh Nair', title: 'PO-024 · Coarse aggregate 20mm', sub: 'Sri Murugan Aggregates · ₹ 14.8 L', status: 'Pending Approval' },
          { avatar: 'Vignesh B', title: 'PR-003 · AAC blocks — Villas cluster 4', sub: 'Riverside Villas', status: 'Pending Approval' },
          { avatar: 'Ravi Kumar K', title: 'PR-001 · TMT 16mm — Tower B slab L7', sub: 'Skyline Apartments', status: 'Pending Approval' },
        ],
      },
    ],
  },
  entities: [
    {
      id: 'procPr',
      label: 'Purchase Request',
      plural: 'Purchase Requests',
      app: 'procurement',
      codePrefix: 'PR',
      titleField: 'title',
      count: 24,
      form: 'page',
      sections: [
        { id: 'basic', title: 'Request Details', icon: 'ti-file-plus' },
        { id: 'need', title: 'Requirement', icon: 'ti-package' },
      ],
      info: 'Material requests come from site engineers, service requests from project teams and purchase indents from stores for replenishment.',
      fields: [
        text('title', 'Request Description', [
          'TMT Fe500D 16mm — Tower B slab L7', 'RMC M30 — column casting L9', 'AAC blocks — Villas cluster 4', 'CPVC pipes & fittings — Block C', 'Vitrified tiles 600×600 — main lobby', 'Shuttering plywood 12mm — Tower B', 'FR cables 2.5 sq.mm — floors 5–8', 'Waterproofing compound — terrace',
          'Tower crane operator — night shift', 'Soil investigation — Phase 2 plots', 'Anti-termite treatment — Block A', 'Third-party cube testing — September', 'DG set AMC — 250 kVA', 'Topographical survey — access road', 'Debris removal & site cleaning', 'Scaffolding hire — façade works',
          'Stock replenishment — Cement OPC 53', 'Stock replenishment — binding wire 18G', 'Safety helmets & harnesses — new gangs', 'HSD diesel — October requirement', 'M-Sand & 20mm aggregate — central store', 'Admixture (superplasticiser) — batching plant', 'Distribution boards 12-way — stock', 'Interior emulsion — central store',
        ], { required: true, list: true, section: 'basic' }),
        select('type', 'Request Type', ['Material Request', 'Service Request', 'Purchase Indent'], {
          required: true, list: false, section: 'basic',
          gen: [...Array(8).fill('Material Request'), ...Array(8).fill('Service Request'), ...Array(8).fill('Purchase Indent')],
        }),
        ref('project', 'Project', 'project', { required: true, list: true, section: 'basic' }),
        ref('requestedBy', 'Requested By', 'employee', { list: true, section: 'basic' }),
        select('category', 'Category', PR_CATEGORIES, {
          list: true, section: 'need',
          gen: ['Steel', 'Ready Mix Concrete', 'Bricks & Blocks', 'Plumbing', 'Finishes', 'Shuttering', 'Electrical', 'Chemicals', 'Equipment Hire', 'Testing & Survey', 'Treatment', 'Testing & Survey', 'Maintenance', 'Testing & Survey', 'Housekeeping', 'Equipment Hire', 'Cement', 'Hardware', 'Safety', 'Fuel', 'Aggregates & Sand', 'Chemicals', 'Electrical', 'Paints'],
        }),
        text('qty', 'Quantity', ['24 MT', '180 Cum', '12,000 Nos', '1,800 Mtr', '2,400 Sqm', '350 Sheets', '120 Coils', '1,500 Kg', '1 operator × 3 months', '12 boreholes', '4,800 Sqm', '240 cubes', '12 months', '3.2 km', '60 truck loads', '6,500 Sqm', '4,000 Bags', '1,200 Kg', '250 Nos', '18,000 Ltr', '600 Cum', '2,500 Ltr', '40 Nos', '1,800 Ltr'], { list: false, section: 'need' }),
        money('amount', 'Estimated Amount', [85000, 1650000], { list: true, section: 'need' }),
        date('required', 'Required Date', [-3, 30], { list: true, section: 'need' }),
        select('priority', 'Priority', ['Low', 'Medium', 'High', 'Critical'], { list: false, section: 'basic' }),
        area('justification', 'Justification', ['Required as per 3-week look-ahead schedule.', 'Current stock below reorder level at site store.', 'Client-approved sample; bulk order required.', 'Statutory / QA requirement before next pour.', 'Replacement for rejected lot (NCR-014).'], { section: 'need' }),
        status(['Draft', 'Pending Approval', 'Approved', 'RFQ Issued', 'PO Issued', 'Rejected'], {
          section: 'basic',
          gen: ['Pending Approval', 'Approved', 'Pending Approval', 'RFQ Issued', 'PO Issued', 'Pending Approval', 'Draft', 'Approved', 'Pending Approval', 'RFQ Issued', 'Approved', 'PO Issued', 'Pending Approval', 'Rejected', 'Approved', 'Pending Approval', 'Pending Approval', 'PO Issued', 'Approved', 'Pending Approval', 'RFQ Issued', 'Pending Approval', 'Draft', 'Approved'],
        }),
      ],
    },
    {
      id: 'procRfq',
      label: 'RFQ',
      plural: 'RFQs',
      app: 'procurement',
      codePrefix: 'RFQ',
      titleField: 'title',
      count: 14,
      fields: [
        text('title', 'RFQ Subject', ['TMT Steel Fe500D — Metro Office Tower L8–L12', 'RMC M25 / M30 — Skyline Tower B', 'AAC blocks — Riverside Villas', 'Vitrified tiles & granite — Lakeview', 'Electrical cables & DBs — Skyline Tower A', 'CPVC / uPVC piping — Riverside', 'Façade glazing — Metro Office Tower', 'Passenger lifts — Skyline Apartments', 'Crystalline waterproofing — Lakeview basement', 'Aggregates & M-Sand — Greenfield Phase 2', 'DG set rental — Greenfield', 'Paints — Orbit Tech Park', 'Scaffolding hire — Harbour View Hospital', 'Cement PPC — Sunrise Business Hotel'], { required: true }),
        ref('pr', 'Purchase Request', 'procPr'),
        ref('project', 'Project', 'project'),
        num('invited', 'Vendors Invited', [3, 6]),
        num('responses', 'Responses', [1, 5]),
        date('issued', 'Issued On', [-25, -2]),
        date('due', 'Due Date', [-4, 12]),
        ref('buyer', 'Buyer', 'employee'),
        status(['Draft', 'Issued', 'Under Evaluation', 'Closed', 'Cancelled'], { gen: ['Under Evaluation', 'Issued', 'Closed', 'Issued', 'Under Evaluation', 'Issued', 'Under Evaluation', 'Closed', 'Draft', 'Issued', 'Closed', 'Closed', 'Cancelled', 'Issued'] }),
      ],
    },
    {
      id: 'procQuoteRequest',
      label: 'Quotation Request',
      plural: 'Quotation Requests',
      app: 'procurement',
      codePrefix: 'QR',
      titleField: 'subject',
      count: 18,
      info: 'Vendor-wise RFQ dispatch and response tracking.',
      fields: [
        text('subject', 'Request Subject', ['TMT Fe500D — 150 MT', 'TMT Fe500D — 150 MT', 'TMT Fe500D — 150 MT', 'TMT Fe500D — 150 MT', 'RMC M25 / M30 — 1,470 Cum', 'RMC M25 / M30 — 1,470 Cum', 'AAC blocks — 48,000 Nos', 'AAC blocks — 48,000 Nos', 'Vitrified tiles — 2,400 Sqm', 'Vitrified tiles — 2,400 Sqm', 'FR cables — 320 coils', 'FR cables — 320 coils', 'Toughened glass 8mm — 1,850 Sqm', 'Passenger lifts — 4 Nos', 'Waterproofing — 1,500 Kg', 'M-Sand — 900 Cum', 'DG set 250 kVA — 6 months', 'Interior emulsion — 1,800 Ltr'], { required: true }),
        ref('rfq', 'RFQ', 'procRfq'),
        ref('vendor', 'Vendor', 'vendor', { required: true }),
        select('mode', 'Sent Via', ['Email', 'Vendor Portal', 'Phone']),
        date('sentOn', 'Sent On', [-20, -1]),
        date('due', 'Response Due', [-3, 10]),
        num('reminders', 'Reminders Sent', [0, 3]),
        status(['Issued', 'Awaiting Response', 'Received', 'Overdue', 'Cancelled'], { gen: ['Received', 'Received', 'Awaiting Response', 'Overdue', 'Received', 'Issued', 'Received', 'Awaiting Response', 'Received', 'Received', 'Issued', 'Awaiting Response', 'Received', 'Received', 'Overdue', 'Received', 'Cancelled', 'Issued'] }),
      ],
    },
    {
      id: 'procQuotation',
      label: 'Quotation',
      plural: 'Quotations',
      app: 'procurement',
      codePrefix: 'VQ',
      titleField: 'title',
      count: 20,
      form: 'page',
      fields: [
        text('title', 'Vendor Quote Ref', ['SBST/Q/2026/418', 'DHM/QTN/1187', 'SLSA/26-27/092', 'CIS/Q/0561', 'CRMC/QT/2026/233', 'UBC/QTN/774', 'KBB/Q/2026/145', 'STG/QT/318', 'AE/Q/26/904', 'FLP/QTN/212', 'SGA/Q/2026/077', 'BLE/QT/1402', 'TWP/Q/331', 'SMA/QT/2026/58', 'PGR/Q/903', 'CCP/Q/2026/611', 'FTS/QTN/245', 'SGP/Q/112', 'NTD/Q/2026/39', 'CFS/QT/718'], { required: true }),
        ref('vendor', 'Vendor', 'vendor', { required: true }),
        ref('rfq', 'RFQ', 'procRfq'),
        money('amount', 'Quoted Amount', [420000, 14500000]),
        num('deliveryDays', 'Delivery', [4, 45], { unit: 'days' }),
        select('paymentTerms', 'Payment Terms', PAY_TERMS),
        date('validity', 'Valid Until', [-5, 40]),
        date('received', 'Received On', [-18, -1], { list: false }),
        area('remarks', 'Remarks', ['Freight included up to site.', 'Prices firm for 15 days; subject to mill price revision.', 'Unloading by buyer.', 'Includes 1-year warranty and installation.', 'Excludes GST; test certificates provided.']),
        status(['Received', 'Under Evaluation', 'Approved', 'Rejected', 'Expired'], { gen: ['Approved', 'Under Evaluation', 'Under Evaluation', 'Rejected', 'Approved', 'Received', 'Under Evaluation', 'Received', 'Approved', 'Rejected', 'Received', 'Under Evaluation', 'Expired', 'Approved', 'Received', 'Under Evaluation', 'Approved', 'Rejected', 'Received', 'Expired'] }),
      ],
    },
    {
      id: 'procPo',
      label: 'Purchase Order',
      plural: 'Purchase Orders',
      app: 'procurement',
      codePrefix: 'PO',
      titleField: 'title',
      form: 'wizard',
      sections: [
        { id: 'vendor', title: 'Vendor & Project', icon: 'ti-building-store' },
        { id: 'items', title: 'Items & Value', icon: 'ti-list-details' },
        { id: 'delivery', title: 'Delivery & Terms', icon: 'ti-truck-delivery' },
      ],
      tabs: ['Financial'],
      fields: [
        text('title', 'PO Description', undefined, { required: true, section: 'items' }),
        ref('vendor', 'Vendor', 'vendor', { required: true, section: 'vendor' }),
        ref('project', 'Project', 'project', { required: true, section: 'vendor' }),
        select('category', 'Category', PO_CATEGORIES, { section: 'items' }),
        money('amount', 'PO Value (incl. GST)', undefined, { required: true, section: 'items' }),
        date('delivery', 'Delivery Date', undefined, { required: true, section: 'delivery' }),
        pct('received', 'Received', undefined, { section: 'items' }),
        status(PO_STATUS, { section: 'delivery' }),
        ref('buyer', 'Buyer', 'employee', { section: 'vendor', list: false }),
        date('poDate', 'PO Date', undefined, { section: 'vendor', list: false }),
        select('paymentTerms', 'Payment Terms', PAY_TERMS, { section: 'delivery', list: false }),
        select('deliveryTerms', 'Delivery Terms', ['FOR site', 'Door delivery', 'Ex-works'], { section: 'delivery', list: false }),
      ],
      rows: poRows,
    },
    {
      id: 'procPoItem',
      label: 'PO Item',
      plural: 'PO Items',
      app: 'procurement',
      codePrefix: 'POL',
      titleField: 'description',
      fields: [
        select('section', 'Purchase Order', [...new Set(poLineData.map((x) => x[0]))]),
        text('description', 'Item Description', undefined, { required: true }),
        text('unit', 'Unit'),
        num('qty', 'Ordered Qty'),
        money('rate', 'Rate'),
        num('received', 'Received Qty'),
      ],
      rows: poLineRows,
    },
    {
      id: 'procDelivery',
      label: 'Delivery',
      plural: 'Deliveries',
      app: 'procurement',
      codePrefix: 'DS',
      titleField: 'title',
      fields: [
        text('title', 'Consignment', undefined, { required: true }),
        ref('po', 'Purchase Order', 'procPo', { required: true }),
        ref('vendor', 'Vendor', 'vendor'),
        ref('project', 'Project', 'project'),
        date('scheduled', 'Scheduled Date', undefined, { required: true }),
        text('qty', 'Quantity'),
        text('vehicle', 'Vehicle No.', undefined, { list: false }),
        status(['Scheduled', 'Dispatched', 'In Transit', 'Received', 'Delayed']),
      ],
      rows: deliveryRows,
    },
    {
      id: 'procTerms',
      label: 'Terms Template',
      plural: 'Terms Templates',
      app: 'procurement',
      codePrefix: 'TT',
      titleField: 'name',
      count: 10,
      form: 'page',
      fields: [
        text('name', 'Template Name', ['Standard Supply Terms — Steel', 'Standard Supply Terms — Cement', 'RMC Supply Terms', 'Aggregates & Sand — Supply', 'Electrical Materials — Supply', 'Equipment Hire Terms', 'Lifts — Supply, Install & Commission', 'Façade Glazing — Supply', 'Services — Testing & Survey', 'Safety / PPE Supply'], { required: true }),
        select('category', 'Applies To', ['Material', 'Equipment Hire', 'Supply & Install', 'Services'], { gen: ['Material', 'Material', 'Material', 'Material', 'Material', 'Equipment Hire', 'Supply & Install', 'Supply & Install', 'Services', 'Material'] }),
        select('paymentTerms', 'Payment Terms', PAY_TERMS),
        text('delivery', 'Delivery Clause', ['FOR site, unloading by vendor', 'FOR site, 50-bag stacks on pallets', 'Pour-wise schedule, 90 min max transit', 'FOR site, tipper delivery', 'Door delivery, packed & labelled', 'Mobilisation within 48 hrs', 'Phased as per lift shaft readiness', 'Floor-wise as per façade programme', 'Within 7 days of work order', 'Door delivery within 5 days']),
        text('penalty', 'LD / Penalty', ['0.5% per week, max 5%', '0.5% per week, max 5%', 'Rejection + replacement at vendor cost', '0.5% per week, max 5%', '1% per week, max 10%', '₹ 5,000 per day of breakdown', '0.5% per week, max 10%', '1% per week, max 10%', '—', '0.5% per week, max 5%']),
        text('warranty', 'Warranty', ['As per IS 1786', 'Manufacturing date ≤ 30 days', 'Cube strength guarantee', '—', '12 months', '—', '24 months + 12 months AMC', '10 years sealant warranty', '—', '6 months']),
        num('clauses', 'Clauses', [12, 38]),
        status(['Active', 'Under Review', 'Inactive'], { gen: ['Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Under Review', 'Active', 'Active', 'Inactive'] }),
      ],
    },
  ],
};
