import { area, date, fieldView, gantt, group, money, num, page, pct, ref, register, select, status, text } from '../dsl';
import type { AppConfig } from '../types';

const PROJ = ['Skyline Apartments', 'Riverside Villas', 'Greenfield Township', 'Metro Office Tower', 'Lakeview Residency', 'Orbit Tech Park Phase II'];

export const projectApp: AppConfig = {
  id: 'project',
  name: 'Project',
  icon: 'ti-building-skyscraper',
  description: 'Project master, WBS, schedule, budget, progress, issues and risks',
  menus: [
    group('Project Master', 'ti-building', [
      page('Project Code', fieldView('project', 'code')),
      page('Project Name', fieldView('project', 'name')),
      page('Client', fieldView('project', 'client')),
      page('Site', fieldView('project', 'site')),
      page('Project Type', register('projectType')),
      page('Status', register('project', { tabs: { field: 'status', values: ['Planned', 'On Track', 'At Risk', 'Delayed', 'On Hold', 'Completed', 'Cancelled'] } })),
    ]),
    group('Project Setup', 'ti-adjustments-horizontal', [
      page('Start Date', fieldView('project', 'start')),
      page('End Date', fieldView('project', 'end')),
      page('Project Manager', fieldView('project', 'manager')),
      page('Team', register('projectTeam')),
      page('Contract', fieldView('project', 'contract')),
    ]),
    group('Project Structure', 'ti-hierarchy-3', [
      page('WBS', {
        type: 'tree',
        title: 'Work Breakdown Structure — PRJ-001 Skyline Apartments',
        columns: [
          { key: 'costCode', label: 'Cost Code' },
          { key: 'budget', label: 'Budget', type: 'currency' },
          { key: 'actual', label: 'Actual Cost', type: 'currency' },
          { key: 'progress', label: 'Progress', type: 'percent' },
          { key: 'status', label: 'Status', type: 'status' },
        ],
        nodes: [
          {
            label: 'Preliminaries & Site Setup', code: '1', values: { costCode: 'CC-100', budget: 21500000, actual: 20900000, progress: 100, status: 'Completed' },
            children: [
              { label: 'Site office & fencing', code: '1.1', values: { costCode: 'CC-110', budget: 6500000, actual: 6200000, progress: 100, status: 'Completed' } },
              { label: 'Temporary services', code: '1.2', values: { costCode: 'CC-120', budget: 15000000, actual: 14700000, progress: 100, status: 'Completed' } },
            ],
          },
          {
            label: 'Substructure', code: '2', values: { costCode: 'CC-200', budget: 118000000, actual: 121400000, progress: 100, status: 'Completed' },
            children: [
              { label: 'Excavation & shoring', code: '2.1', values: { costCode: 'CC-210', budget: 32000000, actual: 34100000, progress: 100, status: 'Completed' } },
              { label: 'Raft foundation', code: '2.2', values: { costCode: 'CC-220', budget: 54000000, actual: 55200000, progress: 100, status: 'Completed' } },
              { label: 'Basement walls & waterproofing', code: '2.3', values: { costCode: 'CC-230', budget: 32000000, actual: 32100000, progress: 100, status: 'Completed' } },
            ],
          },
          {
            label: 'Superstructure', code: '3', values: { costCode: 'CC-300', budget: 262000000, actual: 214000000, progress: 82, status: 'In Progress' },
            children: [
              { label: 'Tower A — Frame', code: '3.1', values: { costCode: 'CC-310', budget: 131000000, actual: 118000000, progress: 90, status: 'In Progress' },
                children: [
                  { label: 'Columns & shear walls', code: '3.1.1', values: { costCode: 'CC-311', budget: 52000000, actual: 49800000, progress: 95, status: 'In Progress' } },
                  { label: 'Slabs L1 – L12', code: '3.1.2', values: { costCode: 'CC-312', budget: 79000000, actual: 68200000, progress: 86, status: 'In Progress' } },
                ] },
              { label: 'Tower B — Frame', code: '3.2', values: { costCode: 'CC-320', budget: 131000000, actual: 96000000, progress: 74, status: 'At Risk' } },
            ],
          },
          {
            label: 'Masonry & Finishes', code: '4', values: { costCode: 'CC-400', budget: 168000000, actual: 72000000, progress: 38, status: 'In Progress' },
            children: [
              { label: 'Block work', code: '4.1', values: { costCode: 'CC-410', budget: 42000000, actual: 30500000, progress: 72, status: 'In Progress' } },
              { label: 'Plastering', code: '4.2', values: { costCode: 'CC-420', budget: 38000000, actual: 21000000, progress: 51, status: 'In Progress' } },
              { label: 'Flooring & tiling', code: '4.3', values: { costCode: 'CC-430', budget: 52000000, actual: 14500000, progress: 22, status: 'In Progress' } },
              { label: 'Painting', code: '4.4', values: { costCode: 'CC-440', budget: 36000000, actual: 6000000, progress: 8, status: 'Not Started' } },
            ],
          },
          {
            label: 'MEP Services', code: '5', values: { costCode: 'CC-500', budget: 126000000, actual: 48000000, progress: 36, status: 'In Progress' },
            children: [
              { label: 'Electrical', code: '5.1', values: { costCode: 'CC-510', budget: 48000000, actual: 19000000, progress: 40, status: 'In Progress' } },
              { label: 'Plumbing & drainage', code: '5.2', values: { costCode: 'CC-520', budget: 34000000, actual: 14000000, progress: 42, status: 'In Progress' } },
              { label: 'Fire fighting', code: '5.3', values: { costCode: 'CC-530', budget: 22000000, actual: 9000000, progress: 35, status: 'In Progress' } },
              { label: 'Lifts', code: '5.4', values: { costCode: 'CC-540', budget: 22000000, actual: 6000000, progress: 18, status: 'Delayed' } },
            ],
          },
          { label: 'External Works & Landscaping', code: '6', values: { costCode: 'CC-600', budget: 35000000, actual: 0, progress: 0, status: 'Not Started' } },
        ],
      }),
      page('Work Packages', register('workPackage', { views: ['table', 'board'] })),
      page('Activities', register('activity', { views: ['table', 'board', 'calendar'], dateField: 'finish' })),
      page('Milestones', register('milestone', { views: ['table', 'calendar'], dateField: 'planned' })),
    ]),
    group('Budget', 'ti-report-money', [
      page('Approved Budget', {
        type: 'analysis',
        title: 'Approved Budget',
        kpis: [
          { label: 'Approved budget (all projects)', value: '₹ 275.2 Cr', icon: 'ti-report-money', sub: 'Revision R2 · approved 14 Aug 2026' },
          { label: 'Committed (POs + WOs)', value: '₹ 208.4 Cr', progress: 76, icon: 'ti-file-check' },
          { label: 'Actual cost to date', value: '₹ 186.0 Cr', progress: 68, icon: 'ti-coins' },
          { label: 'Forecast at completion', value: '₹ 281.6 Cr', delta: '+2.3%', up: true, good: false, icon: 'ti-chart-arrows' },
        ],
        charts: [
          { title: 'Budget vs Actual by Project (₹ Cr)', kind: 'bar', categories: ['Skyline', 'Riverside', 'Greenfield', 'Metro Tower', 'Lakeview', 'Orbit TP', 'Harbour View', 'Sunrise'], series: [{ name: 'Budget', data: [73.1, 36.1, 49.9, 55.0, 24.1, 15.5, 12.9, 8.6] }, { name: 'Actual', data: [52, 22, 24, 40, 10, 17, 13, 8] }], unit: '₹Cr', span: 2 },
          { title: 'Budget Revisions', kind: 'waterfall', categories: ['Original', 'Scope add', 'Steel escalation', 'Design change', 'Savings', 'Current'], series: [{ name: 'Budget', data: [262.4, 6.8, 4.1, 3.6, -1.7, 0] }], unit: '₹Cr' },
        ],
        table: {
          title: 'Budget Revisions Register',
          columns: [
            { key: 'rev', label: 'Revision', type: 'code' },
            { key: 'project', label: 'Project' },
            { key: 'reason', label: 'Reason' },
            { key: 'amount', label: 'Change', type: 'currency' },
            { key: 'date', label: 'Approved On', type: 'date' },
            { key: 'status', label: 'Status', type: 'status' },
          ],
          rows: [
            { rev: 'BR-011', project: 'Greenfield Township', reason: 'Additional clubhouse scope', amount: 34000000, date: '2026-09-12', status: 'Pending Approval' },
            { rev: 'BR-010', project: 'Skyline Apartments', reason: 'Steel price escalation', amount: 18600000, date: '2026-08-14', status: 'Approved' },
            { rev: 'BR-009', project: 'Metro Office Tower', reason: 'Façade design change', amount: 21000000, date: '2026-07-30', status: 'Approved' },
            { rev: 'BR-008', project: 'Riverside Villas', reason: 'Value engineering savings', amount: -9200000, date: '2026-07-02', status: 'Approved' },
            { rev: 'BR-007', project: 'Lakeview Residency', reason: 'Soil stabilisation', amount: 6400000, date: '2026-06-18', status: 'Approved' },
          ],
        },
      }),
      page('Cost Heads', register('costHead')),
      page('Budget Allocation', {
        type: 'tree',
        title: 'Budget Allocation by Cost Head — All Projects',
        columns: [
          { key: 'budget', label: 'Allocated', type: 'currency' },
          { key: 'committed', label: 'Committed', type: 'currency' },
          { key: 'actual', label: 'Actual', type: 'currency' },
          { key: 'used', label: 'Utilised', type: 'percent' },
        ],
        nodes: [
          { label: 'Material', code: 'CH-01', values: { budget: 1045000000, committed: 812000000, actual: 706800000, used: 68 }, children: [
            { label: 'Steel', code: 'CH-01.1', values: { budget: 382000000, committed: 318000000, actual: 276000000, used: 72 } },
            { label: 'Cement & RMC', code: 'CH-01.2', values: { budget: 296000000, committed: 231000000, actual: 204000000, used: 69 } },
            { label: 'Aggregates & sand', code: 'CH-01.3', values: { budget: 118000000, committed: 86000000, actual: 79000000, used: 67 } },
            { label: 'Finishing materials', code: 'CH-01.4', values: { budget: 249000000, committed: 177000000, actual: 147800000, used: 59 } },
          ] },
          { label: 'Labour', code: 'CH-02', values: { budget: 605000000, committed: 452000000, actual: 409200000, used: 68 } },
          { label: 'Subcontract', code: 'CH-03', values: { budget: 495000000, committed: 398000000, actual: 334800000, used: 68 } },
          { label: 'Equipment', code: 'CH-04', values: { budget: 275000000, committed: 214000000, actual: 186000000, used: 68 } },
          { label: 'Site overheads', code: 'CH-05', values: { budget: 332000000, committed: 208000000, actual: 223200000, used: 67 } },
        ],
      }),
    ]),
    group('Planning & Control', 'ti-calendar-stats', [
      page('Schedule', gantt('Master Schedule', 'schedule')),
      page('Dependencies', gantt('Activity Dependencies', 'dependencies')),
      page('Resources', {
        type: 'analysis',
        title: 'Resources',
        kpis: [
          { label: 'Labour on site today', value: '1,717', delta: '+42', up: true, icon: 'ti-users' },
          { label: 'Material consumed (Sep)', value: '₹ 14.8 Cr', icon: 'ti-package' },
          { label: 'Equipment deployed', value: '14 / 16', progress: 88, icon: 'ti-bulldozer' },
          { label: 'Active subcontractors', value: '11', icon: 'ti-users-group' },
        ],
        charts: [
          { title: 'Labour Histogram — Planned vs Deployed', kind: 'bar', categories: ['Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov'], series: [{ name: 'Planned', data: [1450, 1520, 1600, 1650, 1700, 1760, 1800, 1720] }, { name: 'Deployed', data: [1380, 1470, 1510, 1590, 1655, 1717, 0, 0] }], span: 2 },
          { title: 'Resource Cost Mix (Sep)', kind: 'donut', categories: ['Labour', 'Material', 'Equipment', 'Subcontract'], series: [{ name: '₹ Cr', data: [6.4, 14.8, 2.1, 4.9] }], unit: '₹Cr' },
        ],
        table: {
          title: 'Resource Deployment by Project (today)',
          columns: [
            { key: 'project', label: 'Project' },
            { key: 'labour', label: 'Labour', type: 'number' },
            { key: 'equipment', label: 'Equipment', type: 'number' },
            { key: 'subs', label: 'Subcontractors', type: 'number' },
            { key: 'material', label: 'Material Issued (₹)', type: 'currency' },
          ],
          rows: PROJ.map((p, i) => ({ project: p, labour: [412, 186, 264, 338, 142, 96][i], equipment: [4, 2, 3, 3, 1, 1][i], subs: [4, 2, 3, 3, 1, 2][i], material: [1840000, 620000, 910000, 1260000, 380000, 290000][i] })),
        },
      }),
      page('Issues', register('issue', { views: ['table', 'board'] })),
      page('Risks', register('risk', { views: ['table', 'board'], boardField: 'rating' })),
      page('Delays', register('delay')),
    ]),
  ],
  dashboard: {
    flow: [
      { label: 'Progress', value: '56% overall' },
      { label: 'Cost', value: '₹ 186 Cr incurred' },
      { label: 'Schedule', value: '1 delayed · 2 at risk' },
      { label: 'Risks', value: '9 open · 3 high' },
      { label: 'Issues', value: '14 open · 4 overdue' },
    ],
    kpis: [
      { label: 'Active Projects', value: '8', delta: '+14%', up: true, progress: 40, icon: 'ti-folder' },
      { label: 'Total Contract Value', value: '₹ 320 Cr', delta: '+8%', up: true, progress: 62, icon: 'ti-file-text' },
      { label: 'Total Cost Incurred', value: '₹ 186 Cr', delta: '+12%', up: true, good: false, progress: 58, icon: 'ti-database' },
      { label: 'Overall Progress', value: '56%', delta: '+6%', up: true, progress: 56, icon: 'ti-chart-line' },
    ],
    charts: [
      {
        title: 'Project Progress',
        kind: 'barline',
        categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
        series: [
          { name: 'Planned', data: [28, 34, 40, 46, 50, 55, 62, 70, 78, 82, 86, 90], type: 'bar' },
          { name: 'Actual', data: [22, 30, 29, 42, 48, 45, 52, 60, 66, 70, 72, 0], type: 'bar' },
          { name: 'Actual trend', data: [20, 28, 34, 40, 46, 50, 56, 62, 72, 75, 80, 82], type: 'line' },
        ],
        unit: '%',
      },
      { title: 'Project Cost Summary', kind: 'donut', categories: ['Material', 'Labour', 'Subcontract', 'Equipment', 'Others'], series: [{ name: 'Share', data: [38, 22, 18, 10, 12] }], unit: '%', subtitle: '₹ 320 Cr total budget' },
      { title: 'Risk Heat Map (open risks)', kind: 'heatmap', categories: ['Rare', 'Unlikely', 'Possible', 'Likely', 'Almost certain'], yCategories: ['Minor', 'Moderate', 'Major', 'Severe'], series: [{ name: 'Risks', data: [1, 0, 1, 0, 0, 0, 1, 2, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0] }], span: 2, height: 200 },
    ],
    table: { entity: 'project', title: 'Active Projects', columns: ['name', 'client', 'start', 'end', 'progress', 'status'], limit: 8 },
    updates: [
      { title: 'Riverside Villas', sub: 'Second floor slab completed', date: '28 Sep 2026' },
      { title: 'Metro Office Tower', sub: 'Formwork in progress — L9', date: '27 Sep 2026' },
      { title: 'Greenfield Township', sub: 'Site mobilization — Phase 2', date: '26 Sep 2026' },
      { title: 'Skyline Apartments', sub: 'Tower A — column casting', date: '25 Sep 2026' },
    ],
    rail: [
      { kind: 'health', title: 'Project Health', items: [{ label: 'On Track', value: 5, tone: 'green' }, { label: 'At Risk', value: 2, tone: 'yellow' }, { label: 'Delayed', value: 1, tone: 'red' }, { label: 'Completed', value: 3, tone: 'blue' }] },
      {
        kind: 'dates',
        title: 'Upcoming Milestones',
        items: [
          { date: '2026-10-05', title: 'Structure Completion', sub: 'Riverside Villas' },
          { date: '2026-10-12', title: 'MEP Installation', sub: 'Metro Office Tower' },
          { date: '2026-10-20', title: 'Internal Finishing', sub: 'Skyline Apartments' },
          { date: '2026-10-28', title: 'Client Inspection', sub: 'Greenfield Township' },
        ],
      },
      {
        kind: 'list',
        title: 'Recent Activities',
        items: [
          { avatar: 'Ravi Kumar K', title: 'Ravi K approved material request', sub: 'Riverside Villas', meta: '2 hours ago' },
          { avatar: 'Sneha P', title: 'Sneha P updated project progress', sub: 'Metro Office Tower', meta: '4 hours ago' },
          { avatar: 'Divya T', title: 'Divya T added a new document', sub: 'Greenfield Township', meta: '5 hours ago' },
          { avatar: 'Arun S', title: 'Arun S created a new project', sub: 'Lakeview Residency', meta: '1 day ago' },
        ],
      },
    ],
  },
  entities: [
    {
      id: 'projectType',
      label: 'Project Type',
      plural: 'Project Types',
      app: 'project',
      codePrefix: 'PT',
      titleField: 'name',
      count: 9,
      fields: [
        text('name', 'Project Type', ['Residential High-rise', 'Residential', 'Villas', 'Township', 'Commercial', 'IT Park', 'Institutional', 'Hospitality', 'Infrastructure'], { required: true }),
        select('category', 'Category', ['Building', 'Infrastructure', 'Industrial'], { gen: ['Building', 'Building', 'Building', 'Building', 'Building', 'Building', 'Building', 'Building', 'Infrastructure'] }),
        text('wbsTemplate', 'WBS Template', ['WBS-RES-HR', 'WBS-RES', 'WBS-VIL', 'WBS-TWN', 'WBS-COM', 'WBS-ITP', 'WBS-INS', 'WBS-HOS', 'WBS-INF']),
        num('projects', 'Projects', [0, 4]),
        status(['Active', 'Inactive'], { gen: ['Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Inactive'] }),
      ],
    },
    {
      id: 'projectTeam',
      label: 'Team Member',
      plural: 'Team Members',
      app: 'project',
      codePrefix: 'TM',
      titleField: 'member',
      count: 20,
      fields: [
        ref('member', 'Team Member', 'employee', { required: true }),
        ref('project', 'Project', 'project', { required: true }),
        select('role', 'Project Role', ['Project Manager', 'Site Engineer', 'Planning Engineer', 'QS Engineer', 'Safety Officer', 'Store Keeper', 'MEP Coordinator', 'QA/QC Engineer']),
        pct('allocation', 'Allocation', [25, 100]),
        date('from', 'From', [-300, -30]),
        date('to', 'To', [60, 420]),
        status(['Active', 'Released']),
      ],
    },
    {
      id: 'workPackage',
      label: 'Work Package',
      plural: 'Work Packages',
      app: 'project',
      codePrefix: 'WP',
      titleField: 'name',
      count: 16,
      fields: [
        text('name', 'Work Package', ['Raft foundation — Tower A', 'Superstructure — Tower A', 'Superstructure — Tower B', 'Block work — Tower A', 'Internal plaster', 'Electrical rough-in', 'Plumbing & drainage', 'Fire fighting system', 'Façade glazing', 'Flooring & tiling', 'External development', 'Lift installation', 'Waterproofing — terrace', 'HVAC ducting', 'Painting — internal', 'STP & utilities']),
        ref('project', 'Project', 'project', { required: true }),
        text('wbs', 'WBS Code', ['2.2', '3.1', '3.2', '4.1', '4.2', '5.1', '5.2', '5.3', '6.1', '4.3', '7.1', '5.4', '2.3', '5.5', '4.4', '7.2']),
        ref('owner', 'Package Owner', 'employee'),
        money('budget', 'Budget', [8000000, 90000000]),
        pct('progress', 'Progress', [0, 100]),
        date('finish', 'Planned Finish', [-30, 240]),
        status(['Not Started', 'In Progress', 'Completed', 'On Hold', 'Delayed']),
      ],
    },
    {
      id: 'activity',
      label: 'Activity',
      plural: 'Activities',
      app: 'project',
      codePrefix: 'ACT',
      titleField: 'name',
      count: 24,
      form: 'page',
      sections: [
        { id: 'basic', title: 'Activity Details', icon: 'ti-list-details' },
        { id: 'plan', title: 'Schedule & Assignment', icon: 'ti-calendar' },
      ],
      fields: [
        text('name', 'Activity', ['Excavation — Block B', 'PCC below raft', 'Raft reinforcement', 'Raft concreting', 'Column casting L5', 'Slab shuttering L6', 'Slab concreting L6', 'Block work L3', 'Conduiting L4', 'Plumbing sleeves L5', 'Internal plaster L2', 'Tiling L1', 'Façade bracket fixing', 'Lift shaft construction', 'Terrace waterproofing', 'Staircase casting', 'Column casting L6', 'Slab concreting L7', 'Electrical wiring L2', 'Painting primer L1', 'Compound wall', 'Internal roads', 'STP civil works', 'Fire hydrant piping'], { required: true, section: 'basic' }),
        ref('project', 'Project', 'project', { required: true, section: 'basic' }),
        ref('workPackage', 'Work Package', 'workPackage', { section: 'basic' }),
        ref('assignee', 'Assigned To', 'employee', { section: 'plan' }),
        date('start', 'Start', [-60, 20], { section: 'plan' }),
        date('finish', 'Finish', [-10, 80], { section: 'plan' }),
        text('predecessor', 'Predecessor', ['—', 'ACT-001', 'ACT-002', 'ACT-003', 'ACT-004', 'ACT-005', 'ACT-006', 'ACT-005', 'ACT-008', 'ACT-008'], { section: 'plan', list: false }),
        pct('progress', 'Progress', [0, 100], { section: 'plan' }),
        status(['Not Started', 'In Progress', 'Completed', 'Delayed', 'On Hold'], { section: 'basic' }),
      ],
    },
    {
      id: 'milestone',
      label: 'Milestone',
      plural: 'Milestones',
      app: 'project',
      codePrefix: 'MS',
      titleField: 'name',
      count: 14,
      fields: [
        text('name', 'Milestone', ['Structure Completion', 'MEP Installation', 'Internal Finishing', 'Client Inspection', 'Raft Completion', 'Topping Out', 'Façade Completion', 'Lift Commissioning', 'OC Application', 'Handover — Tower A', 'Basement Completion', 'Slab L10 Completion', 'Fire NOC', 'Handover — Tower B'], { required: true }),
        ref('project', 'Project', 'project', { required: true }),
        date('planned', 'Planned Date', [-120, 200], { required: true }),
        date('actual', 'Actual Date', [-110, 0]),
        select('type', 'Type', ['Contractual', 'Internal', 'Payment']),
        status(['Planned', 'Completed', 'At Risk', 'Delayed']),
      ],
    },
    {
      id: 'costHead',
      label: 'Cost Head',
      plural: 'Cost Heads',
      app: 'project',
      codePrefix: 'CH',
      titleField: 'name',
      count: 12,
      fields: [
        text('name', 'Cost Head', ['Material — Steel', 'Material — Cement & RMC', 'Material — Aggregates', 'Material — Finishes', 'Labour — Direct', 'Labour — Contract', 'Subcontract — Civil', 'Subcontract — MEP', 'Equipment — Owned', 'Equipment — Hired', 'Site Overheads', 'Contingency'], { required: true }),
        text('ledger', 'GL Account', ['5101', '5102', '5103', '5104', '5201', '5202', '5301', '5302', '5401', '5402', '5501', '5901']),
        money('budget', 'Budget', [80000000, 380000000]),
        money('actual', 'Actual', [50000000, 280000000]),
        pct('used', 'Utilised', [52, 96]),
        status(['Active', 'Inactive'], { gen: ['Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active'] }),
      ],
    },
    {
      id: 'issue',
      label: 'Issue',
      plural: 'Issues',
      app: 'project',
      codePrefix: 'ISS',
      titleField: 'title',
      count: 18,
      form: 'page',
      fields: [
        text('title', 'Issue', ['Drawing revision pending for Tower B slab', 'Delay in RMC supply', 'Labour shortage — shuttering gang', 'Client approval pending for tiles', 'Crane breakdown — TC-5013', 'Water seepage in basement', 'Excess steel wastage', 'Permit renewal pending', 'Design clash — MEP vs beam', 'Scaffolding inspection failed', 'Payment delay to subcontractor', 'Power outage at site', 'Material quality complaint', 'Access road blocked', 'Survey mismatch — grid C', 'Façade sample rejected', 'Lift shaft misalignment', 'Rain damage to curing'], { required: true }),
        ref('project', 'Project', 'project', { required: true }),
        select('category', 'Category', ['Design', 'Material', 'Labour', 'Equipment', 'Client', 'Statutory', 'Quality', 'Safety']),
        select('priority', 'Priority', ['Low', 'Medium', 'High', 'Critical'], { required: true }),
        ref('assignee', 'Assigned To', 'employee'),
        date('due', 'Due Date', [-15, 30]),
        area('resolution', 'Resolution', ['Revised drawing issued by consultant.', 'Alternate supplier engaged.', 'Additional gang mobilised from Riverside site.', 'Awaiting client decision.', 'Crane repaired; OEM visit completed.']),
        status(['Open', 'In Progress', 'Resolved', 'Closed', 'Overdue']),
      ],
    },
    {
      id: 'risk',
      label: 'Risk',
      plural: 'Risks',
      app: 'project',
      codePrefix: 'RSK',
      titleField: 'title',
      count: 14,
      form: 'page',
      fields: [
        text('title', 'Risk', ['Steel price escalation', 'Monsoon impact on superstructure', 'Delay in environmental clearance', 'Labour unrest', 'Client cash-flow constraints', 'Design changes by architect', 'Subcontractor insolvency', 'Soil strata variation', 'Delay in lift delivery', 'Safety incident at height', 'Power supply disruption', 'Import duty on façade glass', 'Scope creep — clubhouse', 'Key staff attrition'], { required: true }),
        ref('project', 'Project', 'project', { required: true }),
        select('probability', 'Probability', ['Rare', 'Unlikely', 'Possible', 'Likely', 'Almost Certain']),
        select('impact', 'Impact', ['Minor', 'Moderate', 'Major', 'Severe']),
        select('rating', 'Risk Rating', ['Low', 'Medium', 'High', 'Critical']),
        area('mitigation', 'Mitigation', ['Price-variation clause invoked; bulk booking done.', 'Rain protection and revised sequence planned.', 'Follow-up with authority; alternate plan ready.', 'Welfare committee formed; wages revised.', 'Milestone-linked payment agreed.']),
        ref('owner', 'Risk Owner', 'employee'),
        status(['Open', 'Mitigated', 'Closed', 'Escalated']),
      ],
    },
    {
      id: 'delay',
      label: 'Delay Event',
      plural: 'Delay Events',
      app: 'project',
      codePrefix: 'DLY',
      titleField: 'event',
      count: 12,
      fields: [
        text('event', 'Delay Event', ['Late drawing issue — Tower B', 'RMC plant shutdown', 'Heavy rainfall', 'Crane breakdown', 'Client design change', 'Material shortage — steel', 'Statutory inspection hold', 'Labour strike', 'Late handover of site area', 'Power outage', 'Revised structural design', 'Utility shifting delay'], { required: true }),
        ref('project', 'Project', 'project', { required: true }),
        select('cause', 'Cause', ['Client', 'Contractor', 'Neutral', 'Consultant']),
        num('days', 'Delay', [2, 28], { unit: 'days' }),
        date('from', 'From', [-120, -10]),
        select('critical', 'On Critical Path', ['Yes', 'No']),
        status(['Open', 'EOT Claimed', 'Resolved']),
      ],
    },
  ],
};
