import { area, board, date, group, num, page, pct, ref, register, select, status, text } from '../dsl';
import type { AppConfig, Row } from '../types';

/* ───────── Material testing (aligned so each test carries its own spec and observed value) ───────── */
const TESTS: [string, string, string, string, string, string][] = [
  ['Concrete cube — M30, Tower A slab L10 (7-day)', 'Concrete', '7-day compressive strength', '≥ 20.0 N/mm²', '23.4 N/mm²', 'Passed'],
  ['Concrete cube — M30, Tower A slab L9 (28-day)', 'Concrete', '28-day compressive strength', '≥ 30.0 N/mm²', '36.8 N/mm²', 'Passed'],
  ['Concrete cube — M25, Riverside villa B-07 (28-day)', 'Concrete', '28-day compressive strength', '≥ 25.0 N/mm²', '23.1 N/mm²', 'Failed'],
  ['TMT Fe500D 16 mm — heat no. SB-24418', 'Steel', 'Tensile & yield strength', 'YS ≥ 500 N/mm² · UTS/YS ≥ 1.10', 'YS 548 · ratio 1.14', 'Passed'],
  ['Soil compaction — Greenfield internal road CH 0+240', 'Soil', 'Field dry density (core cutter)', '≥ 95% MDD', '96.8% MDD', 'Passed'],
  ['Concrete cube — M40, Metro Tower columns L11 (7-day)', 'Concrete', '7-day compressive strength', '≥ 26.0 N/mm²', 'Awaiting lab result', 'Pending'],
  ['Fresh concrete slump — RMC truck TN-09-BK-4412', 'Concrete', 'Slump test', '100 ± 25 mm', '110 mm', 'Passed'],
  ['TMT Fe500D 25 mm — heat no. SB-24502', 'Steel', 'Bend & rebend test', 'No cracks at 4d mandrel', 'Hairline crack observed', 'Failed'],
  ['Cement OPC 53 — batch UB-0926', 'Cement', 'Setting time & fineness', 'Initial ≥ 30 min · Final ≤ 600 min', 'IST 95 min · FST 240 min', 'Passed'],
  ['Soil compaction — Lakeview plinth fill, zone 2', 'Soil', 'Field dry density (sand replacement)', '≥ 95% MDD', '93.2% MDD', 'Failed'],
  ['AAC block 600×200×200 — lot KBB-233', 'Masonry', 'Compressive strength', '≥ 3.5 N/mm²', '4.1 N/mm²', 'Passed'],
  ['M-Sand — Sri Murugan Aggregates lot 419', 'Aggregates', 'Sieve analysis & silt content', 'Zone II · silt ≤ 3%', 'Zone II · silt 2.1%', 'Passed'],
  ['Concrete cube — M30, Orbit TP podium (28-day)', 'Concrete', '28-day compressive strength', '≥ 30.0 N/mm²', 'Awaiting lab result', 'Pending'],
  ['Waterproofing membrane — terrace, Tower B', 'Waterproofing', 'Ponding test (48 hrs)', 'No leakage', 'No leakage observed', 'Passed'],
  ['Vitrified tile 600×600 — lot STG-415', 'Finishes', 'Water absorption & flatness', '≤ 0.5% · ± 0.5 mm', '0.3% · 0.4 mm', 'Passed'],
  ['Concrete core — Harbour View column C-22', 'Concrete', 'Core compressive strength', '≥ 85% of fck', 'Sample dispatched to NABL lab', 'Pending'],
];

/* ───────── HIRA (aligned likelihood × severity → rating) ───────── */
const HIRA: [string, string, string, string, string][] = [
  ['Work at height — slab edge shuttering', 'Fall of person from height', 'Likely', 'Major', 'High'],
  ['Tower crane lifting — rebar cages', 'Load drop / swing collision', 'Possible', 'Severe', 'Critical'],
  ['Excavation > 3 m — Greenfield STP', 'Trench collapse / cave-in', 'Possible', 'Severe', 'High'],
  ['Hot work — MS railing welding', 'Fire / burns / eye injury', 'Possible', 'Moderate', 'Medium'],
  ['Temporary electrical distribution', 'Electric shock / short circuit', 'Unlikely', 'Major', 'Medium'],
  ['Scaffold erection — façade Tower B', 'Scaffold collapse / fall', 'Possible', 'Major', 'High'],
  ['Concrete pumping — boom placer', 'Line burst / boom contact', 'Unlikely', 'Major', 'Medium'],
  ['Manual handling — block work', 'Musculoskeletal injury', 'Likely', 'Minor', 'Medium'],
  ['Lift shaft work — Metro Tower', 'Fall into shaft / falling objects', 'Possible', 'Severe', 'Critical'],
  ['Night work — slab casting', 'Poor visibility / fatigue', 'Possible', 'Moderate', 'Medium'],
  ['Material hoist operation', 'Entrapment / overload', 'Unlikely', 'Major', 'Medium'],
  ['Painting with solvents — basement', 'Inhalation / fire', 'Unlikely', 'Moderate', 'Low'],
  ['Dewatering pump near public road', 'Slip / traffic interface', 'Rare', 'Moderate', 'Low'],
  ['Demolition of temporary structures', 'Struck by debris', 'Possible', 'Major', 'High'],
];

/* ───────── Accidents (seeded so LTI flag and days lost agree) ───────── */
const ACC: [string, string, string, string, string, string, string, number, string][] = [
  ['Finger laceration while cutting rebar', 'PRJ-001', '2026-09-18', 'Muthu K', 'Bar Bender', 'Laceration', 'No', 0, 'Closed'],
  ['Twisted ankle on uneven access ramp', 'PRJ-004', '2026-09-09', 'Ravi Shankar', 'Helper', 'Sprain', 'No', 0, 'Closed'],
  ['Foreign particle in eye during grinding', 'PRJ-003', '2026-08-27', 'Abdul Rahim', 'Fitter', 'Eye injury', 'No', 0, 'Closed'],
  ['Hand crushed between formwork panels', 'PRJ-001', '2026-08-12', 'Selvaraj P', 'Carpenter', 'Fracture', 'Yes', 21, 'Closed'],
  ['Minor burn from welding spatter', 'PRJ-006', '2026-07-30', 'Jayakumar R', 'Welder', 'Burn', 'No', 0, 'Closed'],
  ['Fall from 1.8 m mobile scaffold', 'PRJ-002', '2026-07-14', 'Ganesan M', 'Mason', 'Fracture', 'Yes', 34, 'Closed'],
  ['Struck by falling shuttering clamp', 'PRJ-004', '2026-06-22', 'Prakash V', 'Helper', 'Contusion', 'No', 0, 'Closed'],
  ['Back strain lifting cement bags', 'PRJ-005', '2026-06-05', 'Kannan S', 'Helper', 'Sprain', 'Yes', 4, 'Closed'],
  ['Cut on forearm from sheet edge', 'PRJ-007', '2026-09-24', 'Rajan T', 'Plumber', 'Laceration', 'No', 0, 'Under Review'],
  ['Slipped on wet tiles — lobby', 'PRJ-008', '2026-09-26', 'Suresh D', 'Tile Layer', 'Contusion', 'No', 0, 'Open'],
];
const accidentRows: Row[] = ACC.map(([description, project, dt, injured, trade, injury, lti, daysLost, st], i) => {
  const code = `ACC-${String(i + 1).padStart(3, '0')}`;
  return { id: code, code, description, project, date: dt, injured, trade, injury, lti, daysLost, reportedBy: ['EMP-013', 'EMP-036'][i % 2], status: st };
});

export const qualitySafetyApp: AppConfig = {
  id: 'quality-and-safety',
  name: 'Quality & Safety',
  icon: 'ti-shield-check',
  description: 'Quality plans, inspections, testing, NCR & CAPA — and site safety, incidents, HIRA and training',
  menus: [
    group('Quality', 'ti-rosette-discount-check', [
      page('Quality Plan', register('qsQualityPlan')),
      page('Inspection', register('qsInspection', { views: ['table', 'board'], boardField: 'status' })),
      page('Checklist', {
        type: 'checklist',
        title: 'Pre-Concreting Checklist',
        subject: 'qsInspection',
        groups: [
          {
            title: 'Formwork',
            items: ['Line, level and plumb checked against drawing', 'Shuttering joints sealed — no gaps for slurry leakage', 'Props / staging at specified spacing, base plates on firm ground', 'Shuttering oil applied, surface cleaned of debris', 'Cover blocks & chamfer strips in place'],
          },
          {
            title: 'Reinforcement',
            items: ['Bar dia., spacing and number as per BBS', 'Lap length and staggering as per IS 456', 'Clear cover maintained (20 mm slab / 40 mm column)', 'Chairs and spacers provided, bars tied firmly', 'Reinforcement free from rust, oil and mud'],
          },
          {
            title: 'Embedments & Services',
            items: ['Electrical conduits and junction boxes fixed', 'Plumbing sleeves and inserts positioned', 'Fire-fighting sleeves / cut-outs provided', 'MEP clearance signed by MEP engineer', 'Construction joint location approved'],
          },
          {
            title: 'Concrete & Equipment',
            items: ['Mix design approved (grade and slump confirmed)', 'RMC delivery schedule confirmed with plant', 'Vibrators (2 + 1 standby) and pump available', 'Cube moulds and slump cone at site', 'Curing arrangement ready (hessian / water)'],
          },
          {
            title: 'Safety',
            items: ['Edge protection and handrails in place', 'Work permit issued for pour', 'Adequate lighting for night pour', 'Workers wearing helmets, gloves and gumboots', 'Pump boom area barricaded'],
          },
        ],
      }),
      page('Material Testing', register('qsMaterialTest', { tabs: { field: 'status', values: ['Pending', 'Passed', 'Failed'] } })),
      page('NCR', register('qsNcr', { tabs: { field: 'status', values: ['Open', 'Under Review', 'Overdue', 'Closed'] } })),
      page('Corrective Action', board('qsCapa', 'status', ['owner', 'due', 'source'])),
    ]),
    group('Safety', 'ti-helmet', [
      page('Safety Plan', register('qsSafetyPlan')),
      page('Safety Inspection', register('qsSafetyInspection', { tabs: { field: 'status', values: ['Compliant', 'Non-Compliant', 'Pending', 'Closed'] } })),
      page('PPE', register('qsPpe')),
      page('Incident', register('qsIncident', { tabs: { field: 'type', values: ['Near Miss', 'First Aid', 'Property Damage', 'Environmental', 'Fire'] } })),
      page('Accident', register('qsAccident')),
      page('Risk Assessment', register('qsRiskAssessment', { views: ['table', 'board'], boardField: 'rating' })),
      page('Safety Training', register('qsTraining', { views: ['table', 'calendar'], dateField: 'date' })),
    ]),
  ],
  dashboard: {
    flow: [
      { label: 'Inspections', value: '412 · 91% passed' },
      { label: 'NCR', value: '8 open · 2 major' },
      { label: 'Incidents', value: '3 MTD · 7 near misses' },
      { label: 'Corrective Actions', value: '11 open · 2 overdue' },
    ],
    kpis: [
      { label: 'Inspections Passed', value: '91%', delta: '+2.4 pt', up: true, progress: 91, icon: 'ti-clipboard-check', sub: '375 of 412 (FY to date)' },
      { label: 'Open NCRs', value: '8', delta: '-3', up: false, good: true, icon: 'ti-alert-octagon', sub: '2 major · 1 overdue' },
      { label: 'Open Corrective Actions', value: '11', delta: '+2', up: true, good: false, icon: 'ti-tool', sub: '2 overdue' },
      { label: 'Safe Man-hours', value: '1.26 M', delta: '+0.18 M', up: true, icon: 'ti-shield-check', sub: 'Since last LTI (12 Aug 2026)' },
      { label: 'Safety Incidents (MTD)', value: '3', delta: '-1', up: false, good: true, icon: 'ti-first-aid-kit', sub: '7 near misses · 0 LTI' },
      { label: 'Training Completion', value: '88%', delta: '+5 pt', up: true, progress: 88, icon: 'ti-school', sub: '1,512 of 1,717 workers' },
    ],
    charts: [
      {
        title: 'Inspection Results by Month',
        kind: 'stacked',
        categories: ['Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep'],
        series: [
          { name: 'Passed', data: [52, 58, 61, 63, 68, 73] },
          { name: 'Failed', data: [6, 7, 5, 6, 7, 6] },
        ],
        span: 2,
      },
      { title: 'NCRs by Category (FY)', kind: 'donut', categories: ['Workmanship', 'Material', 'Documentation', 'Design'], series: [{ name: 'NCRs', data: [14, 7, 4, 3] }], subtitle: '28 raised · 8 open' },
      {
        title: 'Safety Incidents Trend',
        kind: 'stacked',
        categories: ['Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep'],
        series: [
          { name: 'Near Miss', data: [9, 7, 8, 6, 8, 7] },
          { name: 'First Aid', data: [3, 2, 4, 2, 3, 2] },
          { name: 'Property Damage', data: [1, 0, 1, 1, 0, 1] },
          { name: 'Lost-time Incident', data: [0, 0, 1, 1, 1, 0] },
        ],
        span: 2,
      },
      { title: 'Safety Training Completion', kind: 'gauge', series: [{ name: 'Workers trained (FY)', data: [88] }], unit: '%' },
    ],
    table: { entity: 'qsNcr', title: 'Open Non-Conformance Reports', columns: ['description', 'project', 'severity', 'raisedOn', 'target', 'status'], limit: 8 },
    rail: [
      {
        kind: 'health',
        title: 'Site Safety Scores (Sep)',
        items: [
          { label: 'Skyline Apartments', value: '94%', tone: 'green' },
          { label: 'Metro Office Tower', value: '91%', tone: 'green' },
          { label: 'Riverside Villas', value: '88%', tone: 'green' },
          { label: 'Greenfield Township', value: '79%', tone: 'yellow' },
          { label: 'Lakeview Residency', value: '72%', tone: 'red' },
        ],
      },
      {
        kind: 'dates',
        title: 'Upcoming Audits & Trainings',
        items: [
          { date: '2026-10-01', title: 'Monthly HSE audit', sub: 'Greenfield Township' },
          { date: '2026-10-03', title: 'Work-at-height refresher', sub: 'Skyline Apartments · 42 workers' },
          { date: '2026-10-08', title: 'Client QA audit', sub: 'Metro Office Tower' },
          { date: '2026-10-14', title: 'Mock fire drill', sub: 'Harbour View Hospital' },
        ],
      },
      {
        kind: 'list',
        title: 'Recent Observations',
        items: [
          { avatar: 'Mohammed Imran', title: 'Near miss — unsecured plank at L9', sub: 'Metro Office Tower', meta: '2 hours ago', status: 'Open' },
          { avatar: 'Deepak Sharma', title: 'NCR-008 raised — honeycombing C-14', sub: 'Skyline Apartments', meta: '5 hours ago', status: 'Open' },
          { avatar: 'Joseph D', title: 'Toolbox talk — excavation safety', sub: 'Greenfield Township · 64 attendees', meta: '1 day ago', status: 'Completed' },
          { avatar: 'Deepak Sharma', title: 'Cube test failed — M25 villa B-07', sub: 'Riverside Villas', meta: '1 day ago', status: 'Failed' },
        ],
      },
    ],
  },
  entities: [
    /* ───────────── Quality ───────────── */
    {
      id: 'qsQualityPlan',
      label: 'Quality Plan',
      plural: 'Quality Plans',
      app: 'quality-and-safety',
      codePrefix: 'QP',
      titleField: 'name',
      count: 12,
      fields: [
        text('name', 'Quality Plan / ITP', ['Project Quality Plan — Skyline Apartments', 'ITP — RCC Superstructure', 'ITP — Block Work & Plastering', 'Project Quality Plan — Metro Office Tower', 'ITP — Waterproofing', 'ITP — Flooring & Tiling', 'ITP — Electrical Installation', 'ITP — Plumbing & Drainage', 'Project Quality Plan — Greenfield Township', 'ITP — Façade Glazing', 'ITP — Fire Fighting System', 'ITP — Road & External Works'], { required: true }),
        ref('project', 'Project', 'project', { required: true }),
        select('scope', 'Scope', ['Project-wide', 'Civil', 'Finishes', 'MEP', 'External Works'], { gen: ['Project-wide', 'Civil', 'Civil', 'Project-wide', 'Civil', 'Finishes', 'MEP', 'MEP', 'Project-wide', 'Finishes', 'MEP', 'External Works'] }),
        text('revision', 'Revision', ['R3', 'R2', 'R1', 'R2', 'R1', 'R0', 'R1', 'R1', 'R2', 'R0', 'R1', 'R0']),
        num('holdPoints', 'Hold Points', [4, 26]),
        ref('preparedBy', 'Prepared By', 'employee'),
        date('approvedOn', 'Approved On', [-280, -5]),
        status(['Approved', 'Under Review', 'Draft'], { gen: ['Approved', 'Approved', 'Approved', 'Approved', 'Under Review', 'Approved', 'Approved', 'Approved', 'Approved', 'Draft', 'Under Review', 'Draft'] }),
      ],
    },
    {
      id: 'qsInspection',
      label: 'Inspection Request',
      plural: 'Inspection Requests',
      app: 'quality-and-safety',
      codePrefix: 'IR',
      titleField: 'activity',
      count: 24,
      form: 'page',
      sections: [
        { id: 'request', title: 'Inspection Request', icon: 'ti-clipboard-list' },
        { id: 'result', title: 'Inspection Result', icon: 'ti-clipboard-check' },
      ],
      fields: [
        text('activity', 'Activity / Element', ['Slab reinforcement — Tower A L10', 'Column shuttering — Tower B L7', 'Pre-pour check — raft block R3', 'Block work alignment — Villa B-07', 'Internal plaster — Tower A L4', 'Waterproofing — terrace Tower B', 'Conduiting in slab — L10', 'Beam reinforcement — podium', 'Tiling — lobby ground floor', 'Plumbing pressure test — L5 shafts', 'Staircase reinforcement — core 2', 'Lift shaft verticality — Metro Tower', 'Slab concreting — Tower A L10', 'Façade bracket anchoring — east face', 'Internal road sub-base — CH 0+240', 'Shear wall shuttering — L11', 'Toilet waterproofing — Villa A-03', 'Column casting — Metro Tower L11', 'External plaster — Tower A west', 'Fire sprinkler piping — basement', 'False ceiling framing — Orbit TP', 'Kerb stone laying — Greenfield', 'Granite cladding — entrance', 'Masonry — compound wall'], { required: true, section: 'request' }),
        ref('project', 'Project', 'project', { required: true, section: 'request' }),
        select('type', 'Inspection Type', ['Reinforcement', 'Formwork', 'Concrete Pour', 'Masonry', 'Plastering', 'Waterproofing', 'MEP Rough-in', 'Finishes', 'External Works'], { section: 'request' }),
        text('location', 'Grid / Location', ['Grid A1–D4', 'Grid C2–F6', 'Block R3', 'Villa B-07', 'Flats 401–408', 'Terrace', 'Grid A1–F6', 'Podium P1'], { section: 'request', list: false }),
        ref('requestedBy', 'Requested By', 'employee', { section: 'request', list: false }),
        date('date', 'Inspection Date', [-25, 3], { required: true, section: 'request' }),
        ref('inspector', 'QA/QC Inspector', 'employee', { section: 'result' }),
        area('remarks', 'Observations', ['Cover blocks missing at two locations; rectified during inspection.', 'Lap length short at grid C4 — rework instructed.', 'All items conforming to approved drawing R3.', 'Minor honeycombing risk — additional vibration advised.', 'Line & level within tolerance.'], { section: 'result' }),
        status(['Pending', 'Passed', 'Failed'], { section: 'result', gen: ['Passed', 'Passed', 'Passed', 'Failed', 'Passed', 'Passed', 'Pending', 'Passed', 'Passed', 'Passed', 'Failed', 'Passed', 'Pending', 'Passed', 'Passed', 'Passed', 'Passed', 'Pending', 'Passed', 'Passed', 'Passed', 'Passed', 'Passed', 'Passed'] }),
      ],
    },
    {
      id: 'qsMaterialTest',
      label: 'Material Test',
      plural: 'Material Tests',
      app: 'quality-and-safety',
      codePrefix: 'MT',
      titleField: 'sample',
      count: TESTS.length,
      fields: [
        text('sample', 'Sample', TESTS.map((t) => t[0]), { required: true }),
        select('material', 'Material', ['Concrete', 'Steel', 'Cement', 'Soil', 'Masonry', 'Aggregates', 'Waterproofing', 'Finishes'], { gen: TESTS.map((t) => t[1]) }),
        ref('project', 'Project', 'project', { required: true }),
        text('test', 'Test', TESTS.map((t) => t[2])),
        text('spec', 'Acceptance Criteria', TESTS.map((t) => t[3])),
        text('observed', 'Observed Result', TESTS.map((t) => t[4])),
        select('lab', 'Laboratory', ['Site lab', 'NABL lab — Chennai Testing House', 'NABL lab — SGS India', 'Third-party — IIT Madras'], { list: false }),
        date('sampledOn', 'Sampled On', [-35, -1]),
        status(['Pending', 'Passed', 'Failed'], { gen: TESTS.map((t) => t[5]) }),
      ],
    },
    {
      id: 'qsNcr',
      label: 'Non-Conformance Report',
      plural: 'Non-Conformance Reports',
      app: 'quality-and-safety',
      codePrefix: 'NCR',
      titleField: 'description',
      count: 16,
      form: 'page',
      sections: [
        { id: 'ncr', title: 'Non-Conformance', icon: 'ti-alert-octagon' },
        { id: 'analysis', title: 'Root Cause & Disposition', icon: 'ti-zoom-question' },
        { id: 'closure', title: 'Closure', icon: 'ti-circle-check' },
      ],
      fields: [
        text('description', 'Non-Conformance', ['Honeycombing in column C-14 at L5', 'Cube strength below fck — villa B-07 slab', 'Lap length short — beam B-22 podium', 'Tile hollowness > 5% — lobby', 'Plaster thickness exceeding 20 mm — L4', 'Waterproofing coat skipped at parapet junction', 'Rebar bend test failure — heat SB-24502', 'Block work out of plumb — Tower B L3', 'Unapproved admixture used in pour', 'Conduit crushing in slab — L9', 'Shuttering bulge — shear wall L8', 'Soil compaction below 95% MDD — plinth fill', 'Missing test certificate — cement batch', 'Expansion joint not provided — podium', 'Façade anchor spacing deviation', 'Cover to reinforcement < 20 mm — slab L7'], { required: true, section: 'ncr' }),
        ref('project', 'Project', 'project', { required: true, section: 'ncr' }),
        select('category', 'Category', ['Workmanship', 'Material', 'Documentation', 'Design'], { section: 'ncr', gen: ['Workmanship', 'Material', 'Workmanship', 'Workmanship', 'Workmanship', 'Workmanship', 'Material', 'Workmanship', 'Material', 'Workmanship', 'Workmanship', 'Material', 'Documentation', 'Design', 'Workmanship', 'Workmanship'] }),
        select('severity', 'Severity', ['Minor', 'Major', 'Critical'], { required: true, section: 'ncr', gen: ['Major', 'Critical', 'Major', 'Minor', 'Minor', 'Major', 'Major', 'Minor', 'Major', 'Minor', 'Minor', 'Major', 'Minor', 'Major', 'Minor', 'Major'] }),
        ref('raisedBy', 'Raised By', 'employee', { section: 'ncr', list: false }),
        date('raisedOn', 'Raised On', [-60, -1], { section: 'ncr' }),
        ref('responsible', 'Responsible Subcontractor', 'subcontractor', { section: 'analysis' }),
        area('rootCause', 'Root Cause', ['Inadequate vibration near congested reinforcement.', 'RMC water-cement ratio exceeded at site.', 'Bar bending schedule not updated after revision R3.', 'Insufficient bedding mortar under tiles.', 'Untrained gang deployed for plastering.'], { section: 'analysis' }),
        select('disposition', 'Disposition', ['Rework', 'Repair', 'Use as is (concession)', 'Reject & replace'], { section: 'analysis' }),
        date('target', 'Target Closure', [-10, 25], { section: 'closure' }),
        status(['Open', 'Under Review', 'Overdue', 'Closed'], { section: 'closure', gen: ['Open', 'Open', 'Under Review', 'Closed', 'Closed', 'Open', 'Under Review', 'Closed', 'Closed', 'Closed', 'Open', 'Overdue', 'Closed', 'Open', 'Closed', 'Open'] }),
      ],
    },
    {
      id: 'qsCapa',
      label: 'Corrective Action',
      plural: 'Corrective Actions',
      app: 'quality-and-safety',
      codePrefix: 'CAPA',
      titleField: 'action',
      count: 18,
      fields: [
        text('action', 'Action', ['Chip & re-grout honeycombed column C-14', 'Core test & structural review — villa B-07', 'Add lap bars at B-22 per consultant sketch', 'Re-lay hollow tiles — lobby', 'Retrain plastering gang on thickness control', 'Apply additional waterproof coat at parapet', 'Quarantine & return heat SB-24502', 'Install guardrails on L9 slab edge', 'Revise lifting plan for rebar cages', 'Introduce admixture approval register', 'Replace crushed conduits before plaster', 'Toolbox talk — housekeeping at stair cores', 'Re-compact plinth fill zone 2', 'Update ITP for expansion joints', 'Provide anti-slip mats on wet ramps', 'Verify façade anchor spacing — east face', 'Increase cover block stock at site', 'Barricade excavation edge — STP'], { required: true }),
        select('source', 'Source', ['NCR', 'Inspection', 'Safety Inspection', 'Incident', 'Client Audit'], { gen: ['NCR', 'NCR', 'NCR', 'NCR', 'NCR', 'NCR', 'NCR', 'Safety Inspection', 'Incident', 'NCR', 'Inspection', 'Safety Inspection', 'NCR', 'Client Audit', 'Incident', 'Inspection', 'Inspection', 'Safety Inspection'] }),
        select('kind', 'Type', ['Corrective', 'Preventive']),
        ref('project', 'Project', 'project'),
        ref('owner', 'Action Owner', 'employee', { required: true }),
        date('due', 'Due Date', [-8, 30]),
        status(['Open', 'In Progress', 'Pending Verification', 'Closed'], { gen: ['In Progress', 'Open', 'In Progress', 'Closed', 'Closed', 'Pending Verification', 'Closed', 'Closed', 'In Progress', 'Open', 'Pending Verification', 'Closed', 'In Progress', 'Open', 'Closed', 'Open', 'Closed', 'In Progress'] }),
      ],
    },
    /* ───────────── Safety ───────────── */
    {
      id: 'qsSafetyPlan',
      label: 'Safety Plan',
      plural: 'Safety Plans',
      app: 'quality-and-safety',
      codePrefix: 'SP',
      titleField: 'name',
      count: 12,
      fields: [
        text('name', 'Safety Plan', ['Site HSE Plan — Skyline Apartments', 'Emergency Response Plan — Skyline', 'Lifting Plan — Tower Crane TC-5013', 'Site HSE Plan — Metro Office Tower', 'Work at Height Plan — façade', 'Fire Safety Plan — Harbour View', 'Traffic Management Plan — Greenfield', 'Site HSE Plan — Riverside Villas', 'Excavation Safety Plan — STP', 'Electrical Safety Plan — Orbit TP', 'Monsoon Preparedness Plan', 'Site HSE Plan — Lakeview Residency'], { required: true }),
        ref('project', 'Project', 'project', { required: true }),
        select('type', 'Plan Type', ['HSE Plan', 'Emergency Response', 'Lifting Plan', 'Work at Height', 'Fire Safety', 'Traffic Management', 'Excavation', 'Electrical Safety'], { gen: ['HSE Plan', 'Emergency Response', 'Lifting Plan', 'HSE Plan', 'Work at Height', 'Fire Safety', 'Traffic Management', 'HSE Plan', 'Excavation', 'Electrical Safety', 'Emergency Response', 'HSE Plan'] }),
        text('revision', 'Revision', ['R2', 'R1', 'R3', 'R1', 'R0', 'R1', 'R0', 'R2', 'R1', 'R0', 'R1', 'R0']),
        ref('preparedBy', 'Prepared By', 'employee'),
        date('reviewDue', 'Next Review', [-10, 150]),
        status(['Approved', 'Under Review', 'Expired', 'Draft'], { gen: ['Approved', 'Approved', 'Approved', 'Approved', 'Under Review', 'Approved', 'Approved', 'Expired', 'Approved', 'Under Review', 'Approved', 'Draft'] }),
      ],
    },
    {
      id: 'qsSafetyInspection',
      label: 'Safety Inspection',
      plural: 'Safety Inspections',
      app: 'quality-and-safety',
      codePrefix: 'SI',
      titleField: 'area',
      count: 20,
      fields: [
        text('area', 'Area / Equipment', ['Scaffolding — Tower B east face', 'Tower crane TC-5013 — weekly', 'Temporary electrical DBs — L1–L10', 'Excavation edge — Greenfield STP', 'Housekeeping — basement B1', 'Fire extinguishers — site office', 'Material hoist — Tower A', 'Labour camp — hygiene & fire', 'Edge protection — slab L10', 'Welding area — MS fabrication yard', 'Lift shaft openings — Metro Tower', 'Batching area & RMC access', 'First-aid centre — Skyline', 'Safety nets — façade Tower A', 'Dewatering pumps & cables', 'DG set & fuel storage', 'Access ladders — villa cluster B', 'Hot-work permits audit', 'Concrete pump & boom placer', 'PPE compliance walk — all floors'], { required: true }),
        ref('project', 'Project', 'project', { required: true }),
        select('type', 'Inspection Type', ['Daily walk-through', 'Weekly HSE audit', 'Scaffold inspection', 'Lifting equipment', 'Electrical safety', 'Fire safety', 'Housekeeping']),
        ref('inspector', 'Inspected By', 'employee'),
        date('date', 'Date', [-20, 0]),
        num('observations', 'Observations', [0, 9]),
        pct('score', 'Score', [68, 100]),
        status(['Compliant', 'Non-Compliant', 'Pending', 'Closed'], { gen: ['Non-Compliant', 'Compliant', 'Compliant', 'Non-Compliant', 'Compliant', 'Compliant', 'Pending', 'Compliant', 'Closed', 'Compliant', 'Non-Compliant', 'Compliant', 'Compliant', 'Closed', 'Compliant', 'Compliant', 'Pending', 'Compliant', 'Compliant', 'Closed'] }),
      ],
    },
    {
      id: 'qsPpe',
      label: 'PPE Issue',
      plural: 'PPE Issues',
      app: 'quality-and-safety',
      codePrefix: 'PPE',
      titleField: 'item',
      count: 20,
      fields: [
        text('item', 'PPE Item', ['Safety helmet (IS 2925) — yellow', 'Full-body harness with double lanyard', 'Safety shoes — steel toe', 'Reflective jacket — Class 2', 'Cotton hand gloves', 'Welding shield & leather gloves', 'Safety goggles — anti-fog', 'Ear plugs — reusable', 'Gumboots — PVC', 'Dust mask — N95', 'Safety helmet — white (engineers)', 'Rubber gloves — electrical 1.1 kV', 'Full-body harness — fall arrester', 'Reflective jacket — night work', 'Safety shoes — ankle high', 'Face shield — grinding', 'Rain coat — monsoon', 'Chemical gloves — waterproofing', 'Ear muffs — DG operator', 'Knee pads — tile layers'], { required: true }),
        text('issuedTo', 'Issued To', ['Muthu K — Bar Bender', 'Ganesan M — Mason', 'Selvaraj P — Carpenter', 'Ravi Shankar — Helper', 'Abdul Rahim — Fitter', 'Jayakumar R — Welder', 'Prakash V — Helper', 'Kannan S — Helper', 'Rajan T — Plumber', 'Suresh D — Tile Layer', 'Murugan S — Crane Operator', 'Anand R — Electrician', 'Velu P — Scaffolder', 'Sekar M — Night Watch', 'Dhanush K — Mason', 'Ilango T — Grinder', 'Arul J — Helper', 'Peter D — Waterproofing', 'Selvam K — DG Operator', 'Suresh D — Tile Layer']),
        ref('project', 'Project', 'project'),
        num('qty', 'Qty', [1, 4], { unit: 'nos' }),
        date('issuedOn', 'Issued On', [-120, -1]),
        date('nextDue', 'Replacement Due', [-10, 180]),
        status(['Issued', 'Due', 'Expired'], { gen: ['Issued', 'Issued', 'Issued', 'Issued', 'Due', 'Issued', 'Issued', 'Issued', 'Issued', 'Issued', 'Issued', 'Due', 'Expired', 'Issued', 'Issued', 'Issued', 'Issued', 'Due', 'Issued', 'Issued'] }),
      ],
    },
    {
      id: 'qsIncident',
      label: 'Incident',
      plural: 'Incidents',
      app: 'quality-and-safety',
      codePrefix: 'INC',
      titleField: 'description',
      count: 18,
      form: 'page',
      fields: [
        text('description', 'Incident', ['Unsecured plank found at slab edge L9', 'Worker slipped on wet ramp — no injury', 'Rebar bundle swung close to workers during lift', 'Minor cut while handling sheet metal', 'Excavator bucket touched temporary cable', 'Small fire in welding area — extinguished', 'Brick fell from L6 into barricaded zone', 'Diesel spill near DG set (20 L)', 'Worker without harness at 3 m', 'Scaffold board cracked under load', 'Dust exposure complaint — grinding', 'Tipper reversing without banksman', 'Glass panel cracked during unloading', 'Electric shock (minor) at DB-4', 'Nail puncture on foot — first aid', 'Crane outrigger sinking — soft ground', 'Formwork prop dislodged', 'Heat exhaustion — afternoon shift'], { required: true }),
        ref('project', 'Project', 'project', { required: true }),
        select('type', 'Incident Type', ['Near Miss', 'First Aid', 'Property Damage', 'Environmental', 'Fire'], { required: true, gen: ['Near Miss', 'Near Miss', 'Near Miss', 'First Aid', 'Property Damage', 'Fire', 'Near Miss', 'Environmental', 'Near Miss', 'Near Miss', 'Near Miss', 'Near Miss', 'Property Damage', 'First Aid', 'First Aid', 'Near Miss', 'Near Miss', 'First Aid'] }),
        text('location', 'Location', ['Tower A — L9', 'Access ramp B1', 'Tower crane zone', 'Fabrication yard', 'STP excavation', 'Welding bay', 'Tower B — L6', 'DG yard', 'Façade scaffold', 'Villa cluster B']),
        date('date', 'Date & Time', [-45, 0]),
        select('severity', 'Potential Severity', ['Low', 'Medium', 'High'], { gen: ['High', 'Low', 'High', 'Low', 'Medium', 'Medium', 'High', 'Medium', 'High', 'Medium', 'Low', 'Medium', 'Low', 'Medium', 'Low', 'High', 'Medium', 'Low'] }),
        ref('reportedBy', 'Reported By', 'employee'),
        area('action', 'Immediate Action', ['Area barricaded and plank secured; toolbox talk held.', 'Anti-slip mats provided; ramp cleaned.', 'Lift stopped; lifting plan reviewed with rigger.', 'First aid given at site; worker resumed work.', 'Cable rerouted overhead; permit re-issued.']),
        status(['Open', 'Under Review', 'Closed'], { gen: ['Open', 'Closed', 'Under Review', 'Closed', 'Closed', 'Closed', 'Open', 'Closed', 'Closed', 'Closed', 'Under Review', 'Closed', 'Closed', 'Closed', 'Closed', 'Closed', 'Open', 'Closed'] }),
      ],
    },
    {
      id: 'qsAccident',
      label: 'Accident',
      plural: 'Accidents',
      app: 'quality-and-safety',
      codePrefix: 'ACC',
      titleField: 'description',
      form: 'page',
      info: 'Lost-time injuries are reported to the Inspector of Factories / BOCW board in Form IV within 48 hours. 1.26 M safe man-hours since the last LTI.',
      rows: accidentRows,
      fields: [
        text('description', 'Accident', ACC.map((a) => a[0]), { required: true }),
        ref('project', 'Project', 'project', { required: true }),
        date('date', 'Date', [-120, 0], { required: true }),
        text('injured', 'Injured Person', ACC.map((a) => a[3])),
        select('trade', 'Trade', ['Bar Bender', 'Helper', 'Fitter', 'Carpenter', 'Welder', 'Mason', 'Plumber', 'Tile Layer']),
        select('injury', 'Nature of Injury', ['Laceration', 'Sprain', 'Eye injury', 'Fracture', 'Burn', 'Contusion']),
        select('lti', 'Lost-time Injury', ['Yes', 'No']),
        num('daysLost', 'Days Lost', [0, 40], { unit: 'days' }),
        ref('reportedBy', 'Investigated By', 'employee', { list: false }),
        status(['Open', 'Under Review', 'Closed']),
      ],
    },
    {
      id: 'qsRiskAssessment',
      label: 'Risk Assessment',
      plural: 'Risk Assessments (HIRA)',
      app: 'quality-and-safety',
      codePrefix: 'HIRA',
      titleField: 'activity',
      count: HIRA.length,
      form: 'page',
      fields: [
        text('activity', 'Activity', HIRA.map((h) => h[0]), { required: true }),
        text('hazard', 'Hazard', HIRA.map((h) => h[1])),
        ref('project', 'Project', 'project'),
        select('likelihood', 'Likelihood', ['Rare', 'Unlikely', 'Possible', 'Likely', 'Almost Certain'], { gen: HIRA.map((h) => h[2]) }),
        select('severity', 'Severity', ['Minor', 'Moderate', 'Major', 'Severe'], { gen: HIRA.map((h) => h[3]) }),
        select('rating', 'Risk Rating', ['Low', 'Medium', 'High', 'Critical'], { gen: HIRA.map((h) => h[4]) }),
        area('controls', 'Control Measures', ['Guardrails, safety nets and harness anchored to lifeline.', 'Certified rigger & signalman; exclusion zone during lift.', 'Shoring / benching as per soil report; daily permit.', 'Hot-work permit, fire watch and extinguisher at location.', 'ELCB-protected DBs; weekly insulation check.']),
        ref('owner', 'Risk Owner', 'employee', { list: false }),
        date('review', 'Next Review', [5, 90]),
        status(['Approved', 'Under Review', 'Draft'], { gen: ['Approved', 'Approved', 'Approved', 'Approved', 'Approved', 'Under Review', 'Approved', 'Approved', 'Approved', 'Under Review', 'Approved', 'Approved', 'Draft', 'Approved'] }),
      ],
    },
    {
      id: 'qsTraining',
      label: 'Safety Training',
      plural: 'Safety Trainings',
      app: 'quality-and-safety',
      codePrefix: 'TRN',
      titleField: 'topic',
      count: 22,
      fields: [
        text('topic', 'Topic', ['Site safety induction — new joiners', 'Toolbox talk — work at height', 'Toolbox talk — excavation safety', 'Scaffold erection & inspection', 'Fire extinguisher handling', 'Toolbox talk — housekeeping', 'First aid & CPR', 'Crane signalling & rigging', 'Toolbox talk — electrical safety', 'Confined space entry', 'Toolbox talk — monsoon hazards', 'Site safety induction — new joiners', 'Hot work & welding safety', 'Toolbox talk — PPE usage', 'Mock fire drill', 'Toolbox talk — manual handling', 'Work at height — harness refresher', 'Toolbox talk — heat stress', 'Site safety induction — new joiners', 'Toolbox talk — traffic management', 'Emergency evacuation drill', 'Toolbox talk — slip, trip & fall'], { required: true }),
        select('type', 'Training Type', ['Induction', 'Toolbox Meeting', 'Skill Training', 'Drill'], { gen: ['Induction', 'Toolbox Meeting', 'Toolbox Meeting', 'Skill Training', 'Skill Training', 'Toolbox Meeting', 'Skill Training', 'Skill Training', 'Toolbox Meeting', 'Skill Training', 'Toolbox Meeting', 'Induction', 'Skill Training', 'Toolbox Meeting', 'Drill', 'Toolbox Meeting', 'Skill Training', 'Toolbox Meeting', 'Induction', 'Toolbox Meeting', 'Drill', 'Toolbox Meeting'] }),
        ref('project', 'Project', 'project', { required: true }),
        ref('trainer', 'Trainer', 'employee'),
        date('date', 'Date', [-25, 20], { required: true }),
        num('attendees', 'Attendees', [12, 86]),
        num('hours', 'Duration', [1, 8], { unit: 'hrs' }),
        status(['Scheduled', 'Completed', 'Cancelled'], { gen: ['Completed', 'Completed', 'Completed', 'Scheduled', 'Completed', 'Completed', 'Scheduled', 'Completed', 'Completed', 'Scheduled', 'Completed', 'Completed', 'Scheduled', 'Completed', 'Scheduled', 'Completed', 'Completed', 'Cancelled', 'Scheduled', 'Completed', 'Scheduled', 'Completed'] }),
      ],
    },
  ],
};
