import { area, board, date, gallery, group, money, num, page, pct, ref, register, select, status, text, lineItemsNoTax } from '../dsl';
import type { AppConfig, Row } from '../types';

const code = (prefix: string, i: number) => `${prefix}-${String(i + 1).padStart(3, '0')}`;

const PROJ = ['Skyline Apartments', 'Riverside Villas', 'Greenfield Township', 'Metro Office Tower', 'Lakeview Residency', 'Orbit Tech Park II', 'Harbour View Hospital', 'Sunrise Business Hotel'];
const LABOUR = [412, 186, 264, 338, 142, 96, 158, 121]; // = 1,717 on site today
const ACTUAL = [68, 45, 32, 55, 28, 92, 84, 76];
const PLANNED = [70, 48, 38, 56, 34, 93, 88, 78];

/* ───────── Quantity progress — PRJ-001 Skyline Apartments (cumulative) ───────── */
// [section, description, unit, BOQ qty, executed qty, BOQ rate]
const qtyData: [string, string, string, number, number, number][] = [
  ['Substructure', 'Earthwork excavation in all soils incl. disposal', 'Cum', 18500, 18500, 285],
  ['Substructure', 'PCC M15 below raft (100 mm)', 'Cum', 620, 620, 4650],
  ['Substructure', 'RCC M30 raft foundation', 'Cum', 3850, 3850, 6450],
  ['Substructure', 'Reinforcement Fe500D — substructure', 'MT', 412, 412, 72500],
  ['Substructure', 'Basement waterproofing membrane', 'Sqm', 6400, 6400, 780],
  ['Superstructure', 'RCC M30 columns & shear walls', 'Cum', 2950, 2660, 6850],
  ['Superstructure', 'RCC M25 beams & slabs', 'Cum', 7800, 6420, 6380],
  ['Superstructure', 'Reinforcement Fe500D — superstructure', 'MT', 1480, 1230, 72500],
  ['Superstructure', 'Formwork to slabs & beams', 'Sqm', 58000, 47600, 520],
  ['Superstructure', 'Staircase & lift core walls', 'Cum', 640, 470, 7100],
  ['Masonry & Finishes', 'AAC block masonry 200 mm', 'Cum', 4200, 3020, 5400],
  ['Masonry & Finishes', 'Internal plaster 12 mm (CM 1:4)', 'Sqm', 96000, 48960, 265],
  ['Masonry & Finishes', 'External plaster 20 mm (two coat)', 'Sqm', 38000, 11400, 340],
  ['Masonry & Finishes', 'Vitrified tile flooring 600×600', 'Sqm', 42000, 9240, 1180],
  ['Masonry & Finishes', 'Internal emulsion painting (2 coats)', 'Sqm', 120000, 9600, 125],
  ['MEP Services', 'Electrical conduiting & wiring', 'Point', 14800, 6070, 1450],
  ['MEP Services', 'CPVC / uPVC plumbing incl. fittings', 'Mtr', 22000, 9460, 520],
  ['MEP Services', 'Fire sprinkler piping (MS ERW)', 'Mtr', 8600, 3010, 1150],
];
const qtyRows: Row[] = qtyData.map(([section, description, unit, boqQty, qty, rate], i) => ({
  id: code('QP', i),
  code: code('QP', i),
  section,
  description,
  unit,
  boqQty,
  qty,
  rate,
  progress: Math.round((qty / boqQty) * 100),
}));

const SITE_ISSUES = ['Scaffold tie missing at L9 — Tower B', 'Honeycombing in column C-14 L7', 'RMC truck delayed 3 hrs — slab pour', 'Shuttering gang short by 18 workers', 'Tower crane TC-5013 hoist brake fault', 'Rain water logging in basement B2', 'Cement stock below 2 days requirement', 'Unsafe edge protection — terrace', 'Tile shade mismatch — lobby', 'Batching plant power trip', 'Survey mismatch at grid C/7', 'Excavator breakdown — road works', 'Labour camp water supply disrupted', 'Cube test failure — batch B-218', 'Drawing revision awaited — lift pit', 'Hoist overload incident — no injury', 'Plaster cracks — L3 corridor', 'Diesel pilferage suspected'];

export const siteApp: AppConfig = {
  id: 'site',
  name: 'Site',
  icon: 'ti-helmet',
  description: 'Site setup, daily work, progress, site resources and daily progress reports',
  menus: [
    group('Site Management', 'ti-map-pin', [
      page('Site Master', register('site')),
      page('Site Setup', {
        type: 'wizard',
        title: 'Site Setup',
        submitLabel: 'Complete Site Setup',
        steps: [
          {
            title: 'Site Office',
            icon: 'ti-building',
            note: 'Set up the site office, stores and utilities before mobilising the first gang.',
            fields: [
              ref('site', 'Site', 'site', { required: true }),
              select('officeType', 'Site Office Type', ['Porta cabin', 'Container office', 'Rented building', 'Temporary shed']),
              num('officeArea', 'Office Area', undefined, { unit: 'sq ft', placeholder: '1200' }),
              select('power', 'Power Supply', ['EB connection + DG backup', 'DG only', 'EB only']),
              select('water', 'Water Source', ['Borewell', 'Tanker supply', 'Municipal connection']),
              ref('siteManager', 'Site Manager', 'employee', { required: true }),
            ],
          },
          {
            title: 'Site Zones',
            icon: 'ti-layout-grid',
            lines: {
              columns: ['Zone', 'Description', 'Area (sqm)', 'In-charge'],
              rows: [
                ['Z1', 'Tower A footprint & podium', 2400, 'Ravi Kumar K'],
                ['Z2', 'Tower B footprint & podium', 2350, 'Vignesh B'],
                ['Z3', 'Steel yard & bar-bending shed', 900, 'Bala Murugan'],
                ['Z4', 'Cement shed & site store', 450, 'Suresh Babu'],
                ['Z5', 'Labour camp & welfare area', 1800, 'Mohammed Imran'],
                ['Z6', 'Batching plant & wash bay', 1200, 'Farhan Ali'],
              ],
            },
          },
          {
            title: 'Work Areas',
            icon: 'ti-crane',
            lines: {
              columns: ['Work Area', 'Zone', 'Current Activity', 'Supervisor'],
              rows: [
                ['Tower A — L9 slab', 'Z1', 'Slab shuttering & reinforcement', 'Ravi Kumar K'],
                ['Tower A — L4 to L6', 'Z1', 'Block work & conduiting', 'Dinesh M'],
                ['Tower B — L7 columns', 'Z2', 'Column casting', 'Vignesh B'],
                ['Basement B1 / B2', 'Z1', 'Waterproofing & MEP sleeves', 'Sathish R'],
                ['External — compound wall', 'Z5', 'Foundation & plinth', 'Prakash J'],
              ],
            },
          },
          {
            title: 'Site Facilities',
            icon: 'ti-first-aid-kit',
            checklist: ['Labour camp with toilets and bathing area', 'RO drinking water points', 'First-aid room & ambulance tie-up', 'Security cabin, boom barrier & CCTV', 'Cement shed and covered steel yard', 'Transit mixer wash area & silt trap', 'Fire extinguishers at stores, DG and office', 'Safety signage & induction room'],
            upload: ['Site layout plan', 'Temporary works drawing'],
          },
        ],
      }),
      page('Site Mobilization', {
        type: 'checklist',
        title: 'Site Mobilization',
        subject: 'site',
        groups: [
          { title: 'Approvals & Permits', items: ['Building plan approval copy on site', 'Commencement notice submitted to authority', 'BOCW registration & labour licence', 'Temporary EB / DG permission', 'Ground water / borewell permission'] },
          { title: 'Temporary Works', items: ['Site boundary fencing & gates', 'Site office & store set up', 'Internal access road & hard standing', 'Batching plant / RMC access verified', 'Survey benchmarks & grid established'] },
          { title: 'Manpower & Resources', items: ['Site team deployed as per organisation chart', 'Subcontractors mobilised with work orders', 'Tower crane / hoist erected & load tested', 'Initial material stock received at site store'] },
          { title: 'Health & Safety', items: ['Safety induction completed for all workers', 'PPE issued and register maintained', 'Emergency contact & evacuation plan displayed', 'Fire-fighting arrangements in place'] },
        ],
      }),
    ]),
    group('Daily Work', 'ti-hammer', [
      page('Activities', register('siteActivity', { views: ['table', 'board'] })),
      page('Work Packages', register('siteWorkPackage', { views: ['table', 'board'] })),
      page('Daily Tasks', board('siteTask', 'status', ['assignee', 'site', 'due'], ['Open', 'In Progress', 'On Hold', 'Completed'])),
    ]),
    group('Progress', 'ti-chart-line', [
      page('Quantity Completed', lineItemsNoTax('siteQtyProgress', 'Quantity Completed — PRJ-001 Skyline Apartments (cumulative to 28 Sep 2026)', ['boqQty', 'progress'])),
      page('Percentage Complete', {
        type: 'analysis',
        title: 'Percentage Complete',
        kpis: [
          { label: 'Overall physical progress', value: '56%', progress: 56, delta: '+4% this month', up: true, icon: 'ti-chart-line' },
          { label: 'Planned progress', value: '61%', progress: 61, icon: 'ti-target' },
          { label: 'Schedule Performance Index', value: '0.92', delta: '-0.03', up: false, good: false, icon: 'ti-gauge' },
          { label: 'Sites behind plan (> 3%)', value: '3 of 8', sub: 'Greenfield, Lakeview, Harbour View', icon: 'ti-alert-triangle' },
        ],
        charts: [
          { title: 'Planned vs Actual Progress by Site (%)', kind: 'bar', categories: PROJ, series: [{ name: 'Planned', data: PLANNED }, { name: 'Actual', data: ACTUAL }], unit: '%', span: 2 },
          { title: 'Overall Progress Gauge', kind: 'gauge', series: [{ name: 'Progress', data: [56] }], unit: '%' },
          {
            title: 'Progress S-Curve — All Sites (cumulative %)',
            kind: 'line',
            categories: ['Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
            series: [
              { name: 'Planned', data: [34, 39, 44, 49, 55, 61, 67, 73, 79] },
              { name: 'Actual', data: [31, 35, 40, 45, 51, 56, 0, 0, 0] },
            ],
            unit: '%',
            span: 3,
          },
        ],
        table: {
          title: 'Site-wise Progress',
          columns: [
            { key: 'site', label: 'Site' },
            { key: 'planned', label: 'Planned', type: 'percent' },
            { key: 'actual', label: 'Actual', type: 'percent' },
            { key: 'variance', label: 'Variance', type: 'number' },
            { key: 'status', label: 'Status', type: 'status' },
          ],
          rows: PROJ.map((p, i) => ({ site: p, planned: PLANNED[i], actual: ACTUAL[i], variance: ACTUAL[i] - PLANNED[i], status: PLANNED[i] - ACTUAL[i] > 3 ? 'At Risk' : 'On Track' })),
        },
      }),
      page('Progress Photos', gallery('Progress Photos', ['Tower A — L9 slab reinforcement', 'Tower B — column casting L7', 'Riverside Villas — second floor slab', 'Metro Office Tower — formwork L9', 'Greenfield — Phase 2 road sub-base', 'Lakeview — raft reinforcement', 'Orbit Tech Park — façade glazing', 'Harbour View — OT block MEP', 'Sunrise Hotel — block work L4', 'Skyline — basement waterproofing', 'Metro Tower — tower crane climbing', 'Riverside — villa cluster 3 plastering'])),
      page('Milestones', {
        type: 'timeline',
        title: 'Site Milestones',
        subject: 'site',
        events: [
          { date: '2026-09-28', title: 'Second floor slab completed — Riverside Villas', actor: 'Karthik R', text: 'Cluster 2 villas 1–12 slab cast; 186 cum M25.', status: 'Completed' },
          { date: '2026-09-25', title: 'Tower A L8 slab cast — Skyline Apartments', actor: 'Ravi Kumar K', text: '312 cum M30 poured in 14 hrs with boom pump.', status: 'Completed' },
          { date: '2026-09-20', title: 'Façade mock-up approved — Metro Office Tower', actor: 'Sneha P', text: 'Client & architect approved unitised panel mock-up.', status: 'Approved' },
          { date: '2026-09-14', title: 'Phase 2 mobilisation — Greenfield Township', actor: 'Kumaravel P', text: 'Site office, labour camp and batching plant set up.', status: 'Completed' },
          { date: '2026-09-05', title: 'Raft completion — Lakeview Residency', actor: 'Ganesh T', text: 'Raft delayed 9 days due to soil stabilisation.', status: 'Delayed' },
          { date: '2026-10-05', title: 'Structure completion — Riverside Villas cluster 2', actor: 'Karthik R', status: 'Planned' },
          { date: '2026-10-12', title: 'MEP installation start — Metro Office Tower L1–L6', actor: 'Sathish R', status: 'Planned' },
          { date: '2026-10-20', title: 'Internal finishing start — Skyline Tower A', actor: 'Arun S', status: 'Planned' },
        ],
      }),
    ]),
    group('Site Resources', 'ti-users', [
      page('Labour', register('siteLabour')),
      page('Materials', register('siteMaterial')),
      page('Equipment', register('siteEquipment')),
    ]),
    group('Daily Reports', 'ti-report', [
      page('DPR', register('siteDpr', { tabs: { field: 'status', values: ['Draft', 'Submitted', 'Approved', 'Rejected'] } })),
      page('Site Photos', gallery('Site Photos', ['Morning toolbox talk — Tower A', 'Concrete pour — slab L8', 'Cube sampling at site', 'Steel yard stacking', 'Labour camp inspection', 'Housekeeping drive — basement', 'Safety net installation L10', 'Transit mixer wash bay', 'Material receipt at gate', 'Client walkthrough', 'Scaffold inspection tag', 'Evening site cleaning'])),
      page('Site Remarks', register('siteRemark', { tabs: { field: 'type', values: ['Client Instruction', 'Engineer Instruction', 'Site Instruction'] } })),
      page('Site Issues', register('siteIssue', { views: ['table', 'board'] })),
    ]),
  ],
  dashboard: {
    flow: [
      { label: "Today's Work", value: '46 activities' },
      { label: 'Labour', value: '1,717 on site' },
      { label: 'Material', value: '₹ 42.8 L issued' },
      { label: 'Equipment', value: '14 / 16 working' },
      { label: 'Progress', value: '56% overall' },
    ],
    kpis: [
      { label: 'DPRs Submitted Today', value: '7 / 8', progress: 88, sub: 'Pending: Harbour View Hospital', icon: 'ti-report' },
      { label: 'Labour on Site Today', value: '1,717', delta: '+42', up: true, icon: 'ti-users' },
      { label: 'Activities in Progress', value: '46', sub: '9 completed today', icon: 'ti-hammer' },
      { label: 'Open Site Issues', value: '12', delta: '4 critical', up: true, good: false, icon: 'ti-alert-triangle' },
      { label: 'Equipment Working', value: '14 / 16', progress: 88, sub: '1 breakdown · 1 idle', icon: 'ti-bulldozer' },
      { label: 'LTI-free Days', value: '142', icon: 'ti-shield-check' },
    ],
    charts: [
      { title: 'Labour on Site Today by Project', kind: 'bar', categories: PROJ, series: [{ name: 'Labour', data: LABOUR }], span: 2, subtitle: '1,717 workers across 8 sites' },
      { title: 'Open Site Issues by Category', kind: 'donut', categories: ['Safety', 'Quality', 'Material', 'Labour', 'Equipment', 'Delay'], series: [{ name: 'Issues', data: [2, 3, 3, 1, 2, 1] }], subtitle: '12 open issues' },
      { title: 'Planned vs Actual Progress (%)', kind: 'bar', categories: PROJ, series: [{ name: 'Planned', data: PLANNED }, { name: 'Actual', data: ACTUAL }], unit: '%', span: 2 },
      { title: 'Labour Trend — last 7 days', kind: 'area', categories: ['23 Sep', '24 Sep', '25 Sep', '26 Sep', '27 Sep', '28 Sep', '29 Sep'], series: [{ name: 'Labour', data: [1642, 1668, 1690, 1702, 1588, 1675, 1717] }] },
    ],
    table: { entity: 'siteDpr', title: 'Recent Daily Progress Reports', columns: ['title', 'reportDate', 'site', 'preparedBy', 'labourCount', 'status'], limit: 8 },
    updates: [
      { title: 'Riverside Villas', sub: 'Second floor slab completed', date: '28 Sep 2026' },
      { title: 'Metro Office Tower', sub: 'Formwork in progress — L9', date: '27 Sep 2026' },
      { title: 'Greenfield Township', sub: 'Site mobilization — Phase 2', date: '26 Sep 2026' },
      { title: 'Skyline Apartments', sub: 'Tower A — column casting', date: '25 Sep 2026' },
    ],
    rail: [
      {
        kind: 'health',
        title: 'DPR Status — Today',
        items: [
          { label: 'Submitted', value: 7, tone: 'green' },
          { label: 'Pending', value: 1, tone: 'yellow' },
          { label: 'Open issues', value: 12, tone: 'red' },
          { label: 'Instructions awaiting acknowledgement', value: 5, tone: 'blue' },
        ],
      },
      {
        kind: 'list',
        title: 'Critical Site Issues',
        items: [
          { avatar: 'Mohammed Imran', title: 'Scaffold tie missing at L9 — Tower B', sub: 'Skyline Apartments', status: 'Open' },
          { avatar: 'Deepak Sharma', title: 'Cube test failure — batch B-218', sub: 'Metro Office Tower', status: 'Overdue' },
          { avatar: 'Farhan Ali', title: 'Tower crane TC-5013 hoist brake fault', sub: 'Skyline Apartments', status: 'In Progress' },
          { avatar: 'Ganesh T', title: 'Rain water logging in basement B2', sub: 'Lakeview Residency', status: 'Open' },
        ],
      },
      {
        kind: 'dates',
        title: 'Upcoming Site Milestones',
        items: [
          { date: '2026-10-05', title: 'Structure completion', sub: 'Riverside Villas — cluster 2' },
          { date: '2026-10-12', title: 'MEP installation start', sub: 'Metro Office Tower' },
          { date: '2026-10-20', title: 'Internal finishing start', sub: 'Skyline Apartments' },
          { date: '2026-10-28', title: 'Client inspection', sub: 'Greenfield Township' },
        ],
      },
    ],
  },
  entities: [
    {
      id: 'siteActivity',
      label: 'Site Activity',
      plural: 'Site Activities',
      app: 'site',
      codePrefix: 'SA',
      titleField: 'title',
      count: 20,
      fields: [
        text('title', 'Activity', ['Slab shuttering L9 — Tower A', 'Column casting L7 — Tower B', 'Block work L5 — Tower A', 'Conduiting L6 — Tower A', 'Second floor slab — Villa cluster 2', 'Road sub-base — Phase 2', 'Raft reinforcement — Block B', 'Formwork L9 — core walls', 'Internal plaster L3', 'Façade glazing L5', 'OT block ductwork', 'Block work L4 — hotel', 'Basement waterproofing B2', 'Lift core walls L8', 'Plumbing risers — Villa cluster 3', 'Compound wall foundation', 'Staircase casting L8', 'Tiling — Tower A lobby', 'Cable tray installation L2', 'Curing & de-shuttering L8'], { required: true }),
        ref('site', 'Site', 'site', { required: true }),
        text('location', 'Location', ['Tower A · L9', 'Tower B · L7', 'Tower A · L5', 'Tower A · L6', 'Cluster 2', 'Phase 2 · Road R4', 'Block B', 'Core · L9', 'Block C · L3', 'East face · L5', 'OT block · L2', 'Hotel · L4', 'Basement B2', 'Tower B · L8', 'Cluster 3', 'North boundary', 'Tower B · L8', 'Tower A · GF', 'Block A · L2', 'Tower A · L8']),
        ref('supervisor', 'Supervisor', 'employee'),
        text('qty', "Today's Output", ['620 sqm', '38 cum', '42 cum', '860 m', '186 cum', '420 cum', '18 MT', '540 sqm', '1,150 sqm', '24 panels', '140 m', '36 cum', '380 sqm', '22 cum', '96 m', '68 m', '14 cum', '210 sqm', '120 m', '1,200 sqm']),
        pct('progress', 'Progress', [5, 100]),
        date('date', 'Date', [-2, 0]),
        status(['Not Started', 'In Progress', 'Completed', 'Delayed', 'On Hold'], { gen: ['In Progress', 'In Progress', 'In Progress', 'In Progress', 'Completed', 'In Progress', 'Delayed', 'In Progress', 'In Progress', 'In Progress', 'On Hold', 'In Progress', 'Completed', 'In Progress', 'In Progress', 'Not Started', 'Completed', 'In Progress', 'Delayed', 'Completed'] }),
      ],
    },
    {
      id: 'siteWorkPackage',
      label: 'Site Work Package',
      plural: 'Site Work Packages',
      app: 'site',
      codePrefix: 'SWP',
      titleField: 'name',
      count: 14,
      fields: [
        text('name', 'Work Package', ['Superstructure — Tower A', 'Superstructure — Tower B', 'Block work — Tower A', 'Electrical rough-in — Tower A', 'Villa cluster 2 — structure', 'Internal roads — Phase 2', 'Raft & basement — Block B', 'Core walls & slabs L8–L12', 'Plastering — Block C', 'Façade glazing — east & south', 'OT block MEP', 'Hotel block work', 'Basement waterproofing', 'Lift shaft construction'], { required: true }),
        ref('site', 'Site', 'site', { required: true }),
        ref('subcontractor', 'Subcontractor', 'subcontractor'),
        ref('engineer', 'Site Engineer', 'employee'),
        text('scope', 'Scope Qty', ['7,800 cum', '7,400 cum', '4,200 cum', '14,800 points', '2,150 cum', '3.2 km', '4,600 cum', '3,100 cum', '52,000 sqm', '9,800 sqm', '1,850 m', '2,600 cum', '6,400 sqm', '640 cum']),
        pct('progress', 'Progress', [12, 96]),
        date('finish', 'Planned Finish', [15, 210]),
        status(['Not Started', 'In Progress', 'Completed', 'Delayed', 'On Hold'], { gen: ['In Progress', 'In Progress', 'In Progress', 'In Progress', 'In Progress', 'Delayed', 'Completed', 'In Progress', 'In Progress', 'In Progress', 'On Hold', 'In Progress', 'Completed', 'Delayed'] }),
      ],
    },
    {
      id: 'siteTask',
      label: 'Daily Task',
      plural: 'Daily Tasks',
      app: 'site',
      codePrefix: 'TSK',
      titleField: 'title',
      count: 20,
      fields: [
        text('title', 'Task', ['Pour card sign-off — slab L9', 'Check cover blocks — Tower B columns', 'Arrange 20 extra bar benders', 'Toolbox talk — work at height', 'Cube test results follow-up', 'Update BBS for L10', 'Hoist inspection certificate renewal', 'Clear debris — basement B1', 'Line & level check — block work L5', 'RMC schedule for tomorrow', 'Photograph pre-pour inspection', 'Collect labour attendance from subcontractors', 'Tile layout approval from client', 'Rectify honeycombing C-14', 'Verify GRN — steel 22 MT', 'Survey grid C/7 re-check', 'Water tank cleaning — labour camp', 'Submit DPR by 6 PM', 'Scaffold tagging audit', 'Conduct curing check L8'], { required: true }),
        ref('site', 'Site', 'site'),
        ref('assignee', 'Assigned To', 'employee'),
        select('priority', 'Priority', ['Low', 'Medium', 'High', 'Critical']),
        date('due', 'Due', [0, 3]),
        status(['Open', 'In Progress', 'On Hold', 'Completed'], { gen: ['In Progress', 'Open', 'Open', 'Completed', 'In Progress', 'Open', 'On Hold', 'Completed', 'In Progress', 'Open', 'Completed', 'In Progress', 'Open', 'In Progress', 'Completed', 'Open', 'On Hold', 'Open', 'In Progress', 'Completed'] }),
      ],
    },
    {
      id: 'siteQtyProgress',
      label: 'Quantity Progress Line',
      plural: 'Quantity Progress Lines',
      app: 'site',
      codePrefix: 'QP',
      titleField: 'description',
      fields: [
        select('section', 'Section', ['Substructure', 'Superstructure', 'Masonry & Finishes', 'MEP Services']),
        text('description', 'BOQ Item', undefined, { required: true }),
        text('unit', 'Unit'),
        num('boqQty', 'BOQ Qty'),
        num('qty', 'Executed Qty'),
        money('rate', 'BOQ Rate'),
        pct('progress', 'Complete'),
      ],
      rows: qtyRows,
    },
    {
      id: 'siteLabour',
      label: 'Labour Deployment',
      plural: 'Labour Deployment',
      app: 'site',
      codePrefix: 'LD',
      titleField: 'gang',
      count: 20,
      fields: [
        text('gang', 'Gang / Crew', ['Shuttering gang — Tower A', 'Bar bending gang — Tower B', 'Concrete gang — Tower A', 'Masonry gang — Tower A L5', 'Electrical crew — Tower A', 'Villa slab gang — cluster 2', 'Road crew — Phase 2', 'Steel fixers — Block B', 'Shuttering gang — core walls', 'Plaster gang — Block C', 'Façade installers — east face', 'MEP crew — OT block', 'Masonry gang — hotel L4', 'Waterproofing crew — basement', 'Lift shaft gang', 'Plumbing crew — cluster 3', 'Helpers pool — general', 'Tiling gang — Tower A lobby', 'Housekeeping crew', 'Security & watch'], { required: true }),
        ref('site', 'Site', 'site'),
        ref('contractor', 'Labour Contractor', 'subcontractor'),
        select('trade', 'Trade', ['Carpenter', 'Bar Bender', 'Mason', 'Electrician', 'Plumber', 'Helper', 'Operator', 'Painter', 'Tiler', 'Welder'], { gen: ['Carpenter', 'Bar Bender', 'Helper', 'Mason', 'Electrician', 'Carpenter', 'Operator', 'Bar Bender', 'Carpenter', 'Mason', 'Welder', 'Electrician', 'Mason', 'Helper', 'Carpenter', 'Plumber', 'Helper', 'Tiler', 'Helper', 'Helper'] }),
        num('headcount', 'Headcount', [8, 64]),
        num('hours', 'Hours Worked', [8, 10], { unit: 'hrs' }),
        money('cost', 'Labour Cost (Day)', [7200, 62000]),
        date('date', 'Date', [-1, 0]),
        status(['Pending', 'Submitted', 'Verified'], { gen: ['Verified', 'Verified', 'Submitted', 'Verified', 'Submitted', 'Verified', 'Pending', 'Verified', 'Verified', 'Submitted', 'Verified', 'Pending', 'Verified', 'Submitted', 'Verified', 'Verified', 'Submitted', 'Verified', 'Verified', 'Verified'] }),
      ],
    },
    {
      id: 'siteMaterial',
      label: 'Material Consumption',
      plural: 'Material Consumption',
      app: 'site',
      codePrefix: 'MC',
      titleField: 'material',
      count: 18,
      fields: [
        text('material', 'Material', ['Ready Mix Concrete M30', 'TMT Bar Fe500D 16mm', 'AAC Block 600x200x200', 'Cement OPC 53 Grade', 'FR Cable 2.5 sq.mm', 'Ready Mix Concrete M25', 'Coarse Aggregate 20mm', 'TMT Bar Fe500D 12mm', 'Shuttering Plywood 12mm', 'P-Sand (Plastering)', 'Toughened Glass 8mm', 'CPVC Pipe 25mm', 'Cement PPC', 'Waterproofing Compound', 'Binding Wire 18G', 'uPVC Pipe 110mm', 'Vitrified Tile 600x600', 'HSD (Diesel)'], { required: true }),
        ref('site', 'Site', 'site'),
        text('activity', 'Used For', ['Slab L8 — Tower A', 'Columns L7 — Tower B', 'Block work L5', 'Block mortar L5', 'Conduiting L6', 'Villa slab — cluster 2', 'Road sub-base R4', 'Raft — Block B', 'Core wall formwork', 'Plaster — Block C L3', 'Façade L5', 'Plumbing risers', 'Hotel block work L4', 'Basement B2', 'Slab L9 reinforcement', 'Drainage — cluster 3', 'Lobby flooring', 'DG & equipment']),
        text('qty', 'Qty Consumed', ['312 Cum', '6.4 MT', '2,400 Nos', '140 Bags', '18 Coils', '186 Cum', '96 Cum', '4.8 MT', '60 Sheets', '22 Cum', '48 Sqm', '240 Mtr', '120 Bags', '320 Kg', '180 Kg', '160 Mtr', '210 Sqm', '640 Ltr']),
        money('value', 'Value', [24000, 1850000]),
        date('date', 'Date', [-2, 0]),
        status(['Pending', 'Verified'], { gen: ['Verified', 'Verified', 'Pending', 'Verified', 'Verified', 'Verified', 'Pending', 'Verified', 'Verified', 'Pending', 'Verified', 'Verified', 'Verified', 'Pending', 'Verified', 'Verified', 'Pending', 'Verified'] }),
      ],
    },
    {
      id: 'siteEquipment',
      label: 'Equipment Deployment',
      plural: 'Equipment Deployment',
      app: 'site',
      codePrefix: 'ED',
      titleField: 'activity',
      count: 16,
      fields: [
        text('activity', 'Deployed For', ['Material lifting — Tower A', 'Excavation — Block B', 'Road sub-base — Phase 2', 'RMC transport — slab L8', 'Slab pour L8 — boom pump', 'Concrete production', 'Site power — DG', 'Standby power', 'Earth disposal', 'Façade panel lifting', 'Heavy lift — lift machines', 'Material hoisting L1–L9', 'Road compaction', 'Bar bending yard', 'Bar cutting yard', 'Site logistics'], { required: true }),
        ref('equipment', 'Equipment', 'equipment'),
        ref('site', 'Site', 'site'),
        num('hours', 'Working Hours', [2, 10], { unit: 'hrs' }),
        num('idle', 'Idle Hours', [0, 4], { unit: 'hrs' }),
        num('fuel', 'Fuel Used', [20, 180], { unit: 'Ltr' }),
        ref('operator', 'Operator', 'employee', { list: false }),
        date('date', 'Date', [-1, 0]),
        status(['Working', 'Idle', 'Breakdown'], { gen: ['Working', 'Working', 'Working', 'Working', 'Working', 'Working', 'Working', 'Idle', 'Working', 'Working', 'Breakdown', 'Working', 'Working', 'Working', 'Working', 'Working'] }),
      ],
    },
    {
      id: 'siteDpr',
      label: 'Daily Progress Report',
      plural: 'Daily Progress Reports',
      app: 'site',
      codePrefix: 'DPR',
      titleField: 'title',
      count: 16,
      form: 'page',
      sections: [
        { id: 'work', title: 'Work Done', icon: 'ti-hammer' },
        { id: 'labour', title: 'Labour', icon: 'ti-users' },
        { id: 'material', title: 'Material', icon: 'ti-package' },
        { id: 'equipment', title: 'Equipment', icon: 'ti-bulldozer' },
        { id: 'issues', title: 'Issues & Hindrances', icon: 'ti-alert-triangle' },
        { id: 'weather', title: 'Weather', icon: 'ti-cloud-rain' },
      ],
      tabs: ['Progress'],
      fields: [
        text('title', 'Key Work Done', ['Tower A L9 slab shuttering 70% complete', 'Riverside cluster 2 second floor slab cast', 'Greenfield Phase 2 road sub-base 420 cum', 'Metro Tower core walls L9 poured', 'Lakeview Block B raft reinforcement 18 MT', 'Orbit TP façade glazing east face L5', 'Harbour View OT block ductwork', 'Sunrise Hotel block work L4 36 cum', 'Tower B column casting L7 — 38 cum', 'Riverside cluster 3 plumbing risers', 'Greenfield compound wall footing', 'Metro Tower staircase L8 cast', 'Lakeview basement B2 waterproofing', 'Orbit TP cable tray installation', 'Harbour View L3 internal plaster', 'Sunrise Hotel lift core L3'], { required: true, section: 'work' }),
        date('reportDate', 'Report Date', [-6, 0], { required: true, section: 'work' }),
        ref('site', 'Site', 'site', { required: true, section: 'work' }),
        ref('preparedBy', 'Prepared By', 'employee', { section: 'work' }),
        num('labourCount', 'Labour on Site', [90, 420], { section: 'labour' }),
        pct('progress', 'Cumulative Progress', [28, 92], { section: 'work' }),
        select('weather', 'Weather', ['Sunny', 'Partly Cloudy', 'Cloudy', 'Light Rain', 'Heavy Rain'], { section: 'weather' }),
        status(['Draft', 'Submitted', 'Approved', 'Rejected'], { section: 'work', gen: ['Submitted', 'Submitted', 'Submitted', 'Approved', 'Submitted', 'Submitted', 'Draft', 'Submitted', 'Approved', 'Approved', 'Approved', 'Approved', 'Rejected', 'Approved', 'Approved', 'Approved'] }),
        area('workDetail', 'Work Completed Today', ['Shuttering for slab L9 bays 1–6; reinforcement started in bay 1.', 'Slab cast 186 cum M25 with boom pump; curing started.', 'Sub-base laid & compacted on road R4 ch. 0+000 to 0+420.', 'Core wall pour 64 cum; de-shuttering of L8 done.', 'Bottom mat reinforcement completed; chairs placed.'], { section: 'work' }),
        num('skilled', 'Skilled Workers', [40, 180], { section: 'labour', list: false }),
        num('unskilled', 'Unskilled Workers', [50, 240], { section: 'labour', list: false }),
        area('materialUsed', 'Material Consumed', ['RMC M30 312 cum, TMT 16mm 6.4 MT, binding wire 180 kg.', 'RMC M25 186 cum, cover blocks 2,400 nos.', 'GSB 420 cum, water 60 KL.', 'Cement OPC 140 bags, AAC blocks 2,400 nos.', 'Waterproofing compound 320 kg, P-sand 22 cum.'], { section: 'material' }),
        money('materialValue', 'Material Value', [120000, 2400000], { section: 'material', list: false }),
        num('equipmentCount', 'Equipment Deployed', [2, 6], { section: 'equipment', list: false }),
        num('equipmentHours', 'Equipment Hours', [8, 52], { section: 'equipment', list: false, unit: 'hrs' }),
        area('issues', 'Issues / Hindrances', ['RMC truck delayed by 3 hours; pour extended to 11 PM.', 'Shuttering gang short by 18 workers.', 'No hindrance reported.', 'Tower crane down for 2 hours — hoist brake fault.', 'Drawing revision awaited for lift pit.'], { section: 'issues' }),
        num('rainfall', 'Rainfall', [0, 42], { section: 'weather', list: false, unit: 'mm' }),
        num('temperature', 'Max Temperature', [27, 36], { section: 'weather', list: false, unit: '°C' }),
      ],
    },
    {
      id: 'siteRemark',
      label: 'Site Instruction',
      plural: 'Site Instructions & Remarks',
      app: 'site',
      codePrefix: 'SI',
      titleField: 'title',
      count: 16,
      form: 'page',
      fields: [
        text('title', 'Instruction / Remark', ['Provide additional safety nets at L10 edge', 'Change lobby tile to 800×800 as per revised finish schedule', 'Increase cover to 50 mm for basement walls', 'Stop concreting if rain exceeds 10 mm/hr', 'Relocate DG set away from labour camp', 'Submit revised BBS for Tower B L10', 'Maintain curing for 10 days on raft', 'Client wants sample flat ready by 30 Oct', 'Provide 1:10 slope in terrace screed', 'Housekeeping to be improved at stairwells', 'Use approved AAC block brand only', 'Mock-up of façade bracket before bulk fixing', 'Shift material hoist to east face', 'Install CCTV at steel yard', 'Hold plastering until conduit inspection', 'Keep access road clear for fire tender'], { required: true }),
        select('type', 'Type', ['Client Instruction', 'Engineer Instruction', 'Site Instruction', 'Remark'], { gen: ['Engineer Instruction', 'Client Instruction', 'Engineer Instruction', 'Site Instruction', 'Site Instruction', 'Engineer Instruction', 'Engineer Instruction', 'Client Instruction', 'Engineer Instruction', 'Remark', 'Client Instruction', 'Engineer Instruction', 'Site Instruction', 'Client Instruction', 'Site Instruction', 'Remark'] }),
        ref('site', 'Site', 'site'),
        text('issuedBy', 'Issued By', ['Mohammed Imran (Safety)', 'Ramesh Iyer (ABC Builders)', 'Structural consultant — Er. Natarajan', 'Senthil Kumar (Site Manager)', 'Senthil Kumar (Site Manager)', 'Structural consultant — Er. Natarajan', 'Deepak Sharma (QA/QC)', 'Anand Krishnan (XYZ Developers)', 'Architect — Keerthana V', 'Arun S (Project Manager)', 'Sanjay Mehta (Greenfield Infra)', 'Façade consultant — Er. Joseph', 'Ganesh T (Site Manager)', 'Kiran Rao (Metro Constructions)', 'Kumaravel P (Site Manager)', 'Mohammed Imran (Safety)']),
        ref('assignedTo', 'Assigned To', 'employee'),
        date('issued', 'Issued On', [-14, 0]),
        date('due', 'Comply By', [-3, 12]),
        select('acknowledgement', 'Acknowledgement', ['Acknowledged', 'Pending'], { gen: ['Acknowledged', 'Acknowledged', 'Pending', 'Acknowledged', 'Acknowledged', 'Pending', 'Acknowledged', 'Acknowledged', 'Pending', 'Acknowledged', 'Acknowledged', 'Pending', 'Acknowledged', 'Pending', 'Acknowledged', 'Acknowledged'] }),
        area('response', 'Action Taken', ['Safety nets installed on east and north faces.', 'Revised tile sample submitted for approval.', 'Cover blocks changed; inspected by QA.', 'Rain gauge installed at batching plant.', 'DG shifted; noise barrier provided.']),
        status(['Open', 'In Progress', 'Closed', 'Overdue'], { gen: ['Closed', 'In Progress', 'Open', 'Closed', 'Closed', 'Overdue', 'Closed', 'In Progress', 'Open', 'Closed', 'In Progress', 'Open', 'Closed', 'Overdue', 'In Progress', 'Closed'] }),
      ],
    },
    {
      id: 'siteIssue',
      label: 'Site Issue',
      plural: 'Site Issues',
      app: 'site',
      codePrefix: 'SIS',
      titleField: 'title',
      count: 18,
      form: 'page',
      fields: [
        text('title', 'Issue', SITE_ISSUES, { required: true }),
        select('category', 'Category', ['Safety', 'Quality', 'Material', 'Labour', 'Equipment', 'Delay'], { gen: ['Safety', 'Quality', 'Delay', 'Labour', 'Equipment', 'Quality', 'Material', 'Safety', 'Quality', 'Equipment', 'Quality', 'Equipment', 'Labour', 'Quality', 'Delay', 'Safety', 'Quality', 'Material'] }),
        ref('site', 'Site', 'site', { required: true }),
        select('priority', 'Priority', ['Low', 'Medium', 'High', 'Critical'], { gen: ['Critical', 'High', 'High', 'Medium', 'Critical', 'Medium', 'High', 'Critical', 'Low', 'Medium', 'Medium', 'Medium', 'High', 'Critical', 'Medium', 'High', 'Low', 'High'] }),
        ref('raisedBy', 'Raised By', 'employee'),
        ref('assignedTo', 'Assigned To', 'employee'),
        date('due', 'Target Date', [-6, 10]),
        area('resolution', 'Resolution', ['Ties provided and scaffold re-tagged.', 'Honeycomb chipped and repaired with polymer mortar.', 'Alternate RMC plant engaged as backup.', 'Additional gang mobilised from Riverside site.', 'OEM technician replaced hoist brake pads.']),
        status(['Open', 'In Progress', 'Resolved', 'Closed', 'Overdue'], { gen: ['Open', 'Overdue', 'Resolved', 'In Progress', 'In Progress', 'Closed', 'Open', 'Open', 'Resolved', 'In Progress', 'Open', 'Closed', 'Resolved', 'Overdue', 'Open', 'Closed', 'In Progress', 'Open'] }),
      ],
    },
  ],
};
