import { addDays, DEMO_TODAY, toISO } from '@/lib/format';
import { area, date, fieldView, group, money, num, page, ref, register, select, status, text } from '../dsl';
import type { AppConfig } from '../types';

const d = (n: number) => toISO(addDays(DEMO_TODAY, n));

/* Receipt register — material, unit, vendor and PO stay aligned row by row. */
const RCV_MATERIAL = ['TMT Bar Fe500D 16mm', 'Cement OPC 53 Grade', 'Ready Mix Concrete M30', 'M-Sand', 'AAC Block 600x200x200', 'FR Cable 2.5 sq.mm', 'CPVC Pipe 25mm', 'Interior Emulsion', 'Vitrified Tile 600x600', 'Shuttering Plywood 12mm', 'Safety Helmet', 'Binding Wire 18G', 'Toughened Glass 8mm', 'HSD (Diesel)', 'Waterproofing Compound', 'TMT Bar Fe500D 12mm', 'Coarse Aggregate 20mm', 'Cement PPC'];
const RCV_VENDOR = ['Shree Balaji Steel Traders', 'UltraBuild Cements', 'Chennai RMC Pvt Ltd', 'Sri Murugan Aggregates', 'Kaveri Bricks & Blocks', 'Apex Electricals', 'FlowLine Pipes & Fittings', 'ColorCraft Paints', 'Stonecraft Tiles & Granite', 'FormTech Shuttering', 'SafeGuard PPE Supplies', 'Deccan Hardware Mart', 'Southern Glass & Aluminium', 'Coastal Fuel Services', 'Techno Waterproofing', 'Shree Balaji Steel Traders', 'Sri Murugan Aggregates', 'UltraBuild Cements'];
const RCV_PO = ['PO-001', 'PO-002', 'PO-003', 'PO-004', 'PO-005', 'PO-006', 'PO-007', 'PO-008', 'PO-009', 'PO-016', 'PO-011', 'PO-012', 'PO-013', 'PO-017', 'PO-018', 'PO-021', 'PO-024', 'PO-023'];
const RCV_QTY = ['22 MT', '1,300 Bags', '64 Cum', '48 Cum', '8,000 Nos', '60 Coils', '900 Mtr', '600 Ltr', '1,200 Sqm', '180 Sheets', '150 Nos', '400 Kg', '420 Sqm', '12,000 Ltr', '750 Kg', '18 MT', '52 Cum', '1,200 Bags'];
const VEHICLES = ['TN 01 AX 4412', 'TN 22 BK 7781', 'TN 09 CQ 6634', 'TN 21 AL 3308', 'TN 70 D 5521', 'KA 05 MN 2210', 'TN 38 BY 1045', 'TN 01 BZ 9087', 'TS 09 EK 4471', 'TN 02 AM 7730', 'TN 07 CE 2294', 'TS 13 UA 8806', 'KA 01 AF 6358', 'TN 58 AR 1109', 'TN 10 BN 5540', 'TN 01 AX 4412'];

const STORE_TYPE = ['Central Store', 'Warehouse', 'Site Store'];

export const storeApp: AppConfig = {
  id: 'store',
  name: 'Store',
  icon: 'ti-building-warehouse',
  description: 'Stores, material receipt, inventory, material movement and stock control',
  menus: [
    group('Store Master', 'ti-building-store', [
      page('Stores', register('storeStore', { filter: { type: 'Central Store' } })),
      page('Warehouses', register('storeStore', { filter: { type: 'Warehouse' } })),
      page('Site Stores', register('storeStore', { filter: { type: 'Site Store' } })),
      page('Locations', {
        type: 'tree',
        title: 'Store Locations — Zone → Rack → Bin',
        columns: [
          { key: 'items', label: 'SKUs', type: 'number' },
          { key: 'value', label: 'Stock Value', type: 'currency' },
          { key: 'used', label: 'Space Utilised', type: 'percent' },
          { key: 'status', label: 'Status', type: 'status' },
        ],
        nodes: [
          {
            label: 'Central Store — Ambattur, Chennai', code: 'ST-001', values: { items: 186, value: 48200000, used: 78, status: 'Active' },
            children: [
              {
                label: 'Zone A — Steel Yard (open)', code: 'A', values: { items: 9, value: 29800000, used: 84, status: 'Active' },
                children: [
                  { label: 'Bay A1 — TMT 8 / 10 / 12mm', code: 'A1', values: { items: 3, value: 11400000, used: 88, status: 'Active' } },
                  { label: 'Bay A2 — TMT 16 / 20 / 25mm', code: 'A2', values: { items: 3, value: 17600000, used: 91, status: 'Active' } },
                  { label: 'Bay A3 — Binding wire & couplers', code: 'A3', values: { items: 3, value: 800000, used: 46, status: 'Active' } },
                ],
              },
              {
                label: 'Zone B — Cement Godown', code: 'B', values: { items: 4, value: 7100000, used: 72, status: 'Active' },
                children: [
                  { label: 'Rack B1 — OPC 53 Grade (pallets 1–40)', code: 'B1', values: { items: 1, value: 4200000, used: 80, status: 'Active' } },
                  { label: 'Rack B2 — PPC (pallets 1–30)', code: 'B2', values: { items: 1, value: 2600000, used: 66, status: 'Active' } },
                  { label: 'Rack B3 — Admixtures & chemicals', code: 'B3', values: { items: 2, value: 300000, used: 38, status: 'Active' } },
                ],
              },
              {
                label: 'Zone C — Covered Racks', code: 'C', values: { items: 173, value: 11300000, used: 69, status: 'Active' },
                children: [
                  { label: 'Rack C1 · Bins 01–12 — Electrical', code: 'C1', values: { items: 64, value: 5800000, used: 75, status: 'Active' } },
                  { label: 'Rack C2 · Bins 01–10 — Plumbing', code: 'C2', values: { items: 58, value: 3900000, used: 71, status: 'Active' } },
                  { label: 'Rack C3 · Bins 01–08 — Safety & PPE', code: 'C3', values: { items: 51, value: 1600000, used: 52, status: 'Active' } },
                ],
              },
            ],
          },
          {
            label: 'Warehouse — Sriperumbudur', code: 'ST-003', values: { items: 142, value: 24100000, used: 64, status: 'Active' },
            children: [
              { label: 'Zone A — Tiles & granite', code: 'A', values: { items: 38, value: 14600000, used: 81, status: 'Active' } },
              { label: 'Zone B — Paints & chemicals', code: 'B', values: { items: 46, value: 5200000, used: 58, status: 'Active' } },
              { label: 'Zone C — Sanitary & CP fittings', code: 'C', values: { items: 58, value: 4300000, used: 49, status: 'Active' } },
            ],
          },
          {
            label: 'Site Store — Skyline Apartments', code: 'ST-007', values: { items: 94, value: 19000000, used: 88, status: 'Active' },
            children: [
              { label: 'Steel yard — near Tower B', code: 'Y1', values: { items: 6, value: 12400000, used: 93, status: 'Active' } },
              { label: 'Cement shed (600 bag capacity)', code: 'S1', values: { items: 2, value: 2400000, used: 96, status: 'Active' } },
              { label: 'Container store · Bins 01–24', code: 'K1', values: { items: 86, value: 4200000, used: 71, status: 'Active' } },
            ],
          },
          {
            label: 'Site Store — Metro Office Tower', code: 'ST-010', values: { items: 81, value: 15000000, used: 74, status: 'Active' },
            children: [
              { label: 'Basement B1 — Steel & shuttering', code: 'B1', values: { items: 12, value: 9800000, used: 82, status: 'Active' } },
              { label: 'Ground floor — Façade material bay', code: 'G1', values: { items: 22, value: 3700000, used: 61, status: 'Active' } },
              { label: 'Container store · Bins 01–18', code: 'K1', values: { items: 47, value: 1500000, used: 58, status: 'Active' } },
            ],
          },
        ],
      }),
    ]),
    group('Material Receipt', 'ti-package-import', [
      page('Gate Entry', register('storeGateEntry', { tabs: { field: 'status', values: ['Awaiting Inspection', 'Accepted', 'Partially Received', 'Rejected'] } })),
      page('GRN', register('storeGrn', { tabs: { field: 'status', values: ['Draft', 'Pending Verification', 'Verified', 'Rejected'] } })),
      page('Quantity Check', {
        type: 'checklist',
        title: 'Quantity Verification',
        subject: 'storeGrn',
        groups: [
          { title: 'Document Verification', items: ['PO number and line items match the delivery challan', 'Tax invoice quantity matches challan quantity', 'E-way bill verified for consignments above ₹ 50,000', 'Vehicle number matches gate entry'] },
          { title: 'Physical Count', items: ['Steel weighed at weighbridge — slip attached', 'Cement bags counted and stacked 10 high on pallets', 'Sand / aggregate measured by truck body volume (cum)', 'Pipes, cables and fittings counted against packing list', 'Tiles counted by box with pieces per box verified'] },
          { title: 'Discrepancy Handling', items: ['Short / excess quantity recorded on GRN', 'Damaged units segregated and photographed', 'Vendor representative signature obtained on discrepancy note'] },
        ],
      }),
      page('Quality Check', {
        type: 'checklist',
        title: 'Quality Verification',
        subject: 'storeGrn',
        scored: true,
        groups: [
          { title: 'Steel (IS 1786)', items: ['Mill test certificate received for each heat number', 'Brand embossing and grade Fe500D visible on bars', 'Diameter and unit weight within tolerance', 'No excessive rust, pitting or bends'] },
          { title: 'Cement (IS 269 / IS 1489)', items: ['Week of manufacture within 30 days', 'Bags intact — no lumps or moisture', 'Manufacturer test certificate attached'] },
          { title: 'Aggregates & Sand', items: ['Silt content below 8% (field test)', 'Grading as per IS 383 zone II', 'Free from clay lumps and organic matter'] },
          { title: 'Ready Mix Concrete', items: ['Delivery ticket shows grade and batch time', 'Transit time within 90 minutes', 'Slump within specified range', 'Cube samples taken (6 per 50 cum)'] },
        ],
      }),
    ]),
    group('Inventory', 'ti-packages', [
      page('Stock', register('item', { tabs: { field: 'status', values: ['In Stock', 'Reorder Level', 'Low Stock', 'Out of Stock'] } })),
      page('Batch', register('storeBatch')),
      page('Serial', register('storeSerial')),
      page('Location', fieldView('storeStockLocation', 'location')),
    ]),
    group('Material Movement', 'ti-arrows-exchange', [
      page('Material Issue', register('storeIssue', { tabs: { field: 'issueType', values: ['Site Issue', 'Project Issue', 'Department Issue'] } })),
      page('Material Transfer', register('storeTransfer', { tabs: { field: 'transferType', values: ['Store-to-Store', 'Store-to-Site', 'Site-to-Store'] } })),
      page('Material Return', register('storeReturn', { tabs: { field: 'returnType', values: ['Reusable', 'Damaged', 'Excess'] } })),
      page('Stock Adjustment', register('storeAdjustment')),
    ]),
    group('Stock Control', 'ti-adjustments-alt', [
      page('Wastage', register('storeWastage')),
      page('Stock Reconciliation', {
        type: 'comparison',
        title: 'Stock Reconciliation — September 2026 physical count',
        subjectLabel: 'Item / measure',
        subjects: ['Central Store — Ambattur', 'Site Store — Skyline Apartments', 'Site Store — Metro Office Tower', 'Site Store — Greenfield Township'],
        note: 'Physical count taken 27–28 Sep 2026 against system stock as on 26 Sep. Negative variance = physical below system. Variances above 2% need Project Manager approval before stock adjustment.',
        rows: [
          { group: 'TMT Bar Fe500D 12mm (MT)', label: 'TMT 12mm — system stock', values: [58.4, 21.6, 18.2, 12.8], format: 'number' },
          { group: 'TMT Bar Fe500D 12mm (MT)', label: 'TMT 12mm — physical count', values: [58.1, 21.2, 18.2, 12.1], format: 'number' },
          { group: 'TMT Bar Fe500D 12mm (MT)', label: 'TMT 12mm — variance', values: [-0.3, -0.4, 0, -0.7], best: 'max', format: 'number' },
          { group: 'Cement OPC 53 Grade (Bag)', label: 'Cement OPC 53 — system stock', values: [1840, 620, 410, 380], format: 'number' },
          { group: 'Cement OPC 53 Grade (Bag)', label: 'Cement OPC 53 — physical count', values: [1832, 598, 410, 361], format: 'number' },
          { group: 'Cement OPC 53 Grade (Bag)', label: 'Cement OPC 53 — variance', values: [-8, -22, 0, -19], best: 'max', format: 'number' },
          { group: 'M-Sand (Cum)', label: 'M-Sand — system stock', values: [0, 142, 96, 210], format: 'number' },
          { group: 'M-Sand (Cum)', label: 'M-Sand — physical count', values: [0, 136, 92, 188], format: 'number' },
          { group: 'M-Sand (Cum)', label: 'M-Sand — variance', values: [0, -6, -4, -22], format: 'number' },
          { group: 'AAC Block 600x200x200 (Nos)', label: 'AAC Block — system stock', values: [9200, 0, 0, 6400], format: 'number' },
          { group: 'AAC Block 600x200x200 (Nos)', label: 'AAC Block — physical count', values: [9150, 0, 0, 6230], format: 'number' },
          { group: 'AAC Block 600x200x200 (Nos)', label: 'AAC Block — variance', values: [-50, 0, 0, -170], format: 'number' },
          { group: 'Binding Wire 18G (Kg)', label: 'Binding wire — system stock', values: [860, 240, 180, 150], format: 'number' },
          { group: 'Binding Wire 18G (Kg)', label: 'Binding wire — physical count', values: [852, 231, 180, 138], format: 'number' },
          { group: 'Binding Wire 18G (Kg)', label: 'Binding wire — variance', values: [-8, -9, 0, -12], best: 'max', format: 'number' },
          { group: 'Summary', label: 'System stock value (₹)', values: [4883160, 1842040, 1463330, 1701060], format: 'currency' },
          { group: 'Summary', label: 'Variance value (₹)', values: [-24964, -44752, -7400, -101651], best: 'max', format: 'currency' },
          { group: 'Summary', label: 'Variance % of value', values: [0.5, 2.4, 0.5, 6.0], best: 'min', format: 'percent' },
          { group: 'Summary', label: 'Stock accuracy', values: [99.5, 97.6, 99.5, 94.0], best: 'max', format: 'percent' },
          { group: 'Summary', label: 'Reconciliation status', values: ['Reconciled', 'Under Review', 'Reconciled', 'Pending Approval'], format: 'status' },
        ],
      }),
    ]),
  ],
  dashboard: {
    flow: [
      { label: 'Gate Entry', value: '11 vehicles today' },
      { label: 'GRN', value: '6 pending' },
      { label: 'Stock', value: '₹ 18.6 Cr' },
      { label: 'Issue', value: '₹ 42.8 L today' },
      { label: 'Consumption', value: '2.1% wastage' },
    ],
    kpis: [
      { label: 'Inventory Value', value: '₹ 18.6 Cr', delta: '+4.2%', up: true, sub: '14 stores · 30 stocked items', icon: 'ti-packages' },
      { label: 'Items Below Reorder', value: '7', sub: '1 critically low — RMC M25', delta: '+2', up: true, good: false, icon: 'ti-alert-triangle' },
      { label: 'GRNs Pending Verification', value: '6', icon: 'ti-package-import' },
      { label: 'Material Issued Today', value: '₹ 42.8 L', delta: '+8%', up: true, icon: 'ti-package-export' },
      { label: 'Wastage (Sep)', value: '2.1%', sub: 'Allowance 2.5%', progress: 84, icon: 'ti-recycle' },
      { label: 'Stock Accuracy', value: '98.4%', progress: 98, icon: 'ti-checklist' },
    ],
    charts: [
      {
        title: 'Receipts vs Issues (₹ Cr)',
        kind: 'bar',
        categories: ['Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep'],
        series: [
          { name: 'Receipts (GRN)', data: [7.1, 8.8, 9.4, 10.6, 11.0, 8.2] },
          { name: 'Issues', data: [6.8, 8.2, 9.9, 10.1, 10.4, 9.1] },
        ],
        unit: '₹Cr',
        span: 2,
      },
      {
        title: 'Inventory by Category',
        kind: 'donut',
        categories: ['Steel', 'Cement & RMC', 'Finishes', 'Electrical', 'Aggregates', 'Others'],
        series: [{ name: 'Share', data: [38, 16, 14, 11, 9, 12] }],
        unit: '%',
        subtitle: '₹ 18.6 Cr stock value',
      },
      {
        title: 'Stock Value by Store (₹ Cr)',
        kind: 'hbar',
        categories: ['CS Ambattur', 'CS Peenya', 'WH Sriperumbudur', 'Skyline site', 'WH Hosur', 'Greenfield site', 'Metro Tower site', 'Other sites'],
        series: [{ name: 'Stock value', data: [4.8, 3.1, 2.4, 1.9, 1.8, 1.7, 1.5, 1.4] }],
        unit: '₹Cr',
      },
      {
        title: 'Wastage vs Allowance by Material (%)',
        kind: 'bar',
        categories: ['Steel', 'Cement', 'M-Sand', 'AAC Blocks', 'Tiles', 'Plywood'],
        series: [
          { name: 'Actual', data: [2.8, 2.4, 4.6, 3.1, 5.2, 6.8] },
          { name: 'Allowance', data: [3.0, 2.0, 5.0, 3.0, 5.0, 8.0] },
        ],
        unit: '%',
        span: 2,
      },
    ],
    table: { entity: 'item', title: 'Stock Position', columns: ['name', 'category', 'unit', 'stock', 'reorder', 'status'], limit: 8 },
    rail: [
      {
        kind: 'health',
        title: 'Stock Health',
        items: [
          { label: 'In Stock', value: 23, tone: 'green' },
          { label: 'Reorder Level', value: 6, tone: 'yellow' },
          { label: 'Low Stock', value: 1, tone: 'red' },
          { label: 'Expiring batches (30 days)', value: 3, tone: 'yellow' },
        ],
      },
      {
        kind: 'dates',
        title: 'Expected Receipts',
        items: [
          { date: d(0), title: 'TMT 25mm — 22 MT', sub: 'Shree Balaji Steel Traders · Skyline site store' },
          { date: d(2), title: 'RMC M25 — 120 Cum', sub: 'Chennai RMC Pvt Ltd · Metro Office Tower' },
          { date: d(4), title: 'M-Sand — 300 Cum', sub: 'Sri Murugan Aggregates · Greenfield site store' },
          { date: d(5), title: 'Cement OPC 53 — 1,300 Bags', sub: 'UltraBuild Cements · Skyline site store' },
        ],
      },
      {
        kind: 'list',
        title: 'Recent GRNs',
        items: [
          { avatar: 'Suresh Babu', title: 'GRN-001 · TMT 16mm — 22 MT', sub: 'Shree Balaji Steel Traders', status: 'Verified' },
          { avatar: 'Vinoth A', title: 'GRN-002 · Cement OPC 53 — 1,300 Bags', sub: 'UltraBuild Cements', status: 'Pending Verification' },
          { avatar: 'Suresh Babu', title: 'GRN-003 · RMC M30 — 64 Cum', sub: 'Chennai RMC Pvt Ltd', status: 'Verified' },
          { avatar: 'Vinoth A', title: 'GRN-004 · M-Sand — 48 Cum', sub: 'Sri Murugan Aggregates', status: 'Rejected' },
        ],
      },
    ],
  },
  entities: [
    {
      id: 'storeStore',
      label: 'Store',
      plural: 'Stores',
      app: 'store',
      codePrefix: 'ST',
      titleField: 'name',
      count: 14,
      fields: [
        text('name', 'Store Name', ['Central Store — Ambattur, Chennai', 'Central Store — Peenya, Bengaluru', 'Warehouse — Sriperumbudur', 'Warehouse — Hosur SIPCOT', 'Warehouse — Kurichi, Coimbatore', 'Warehouse — Medchal, Hyderabad', 'Site Store — Skyline Apartments', 'Site Store — Riverside Villas', 'Site Store — Greenfield Township', 'Site Store — Metro Office Tower', 'Site Store — Lakeview Residency', 'Site Store — Orbit Tech Park', 'Site Store — Harbour View Hospital', 'Site Store — Sunrise Business Hotel'], { required: true }),
        select('type', 'Store Type', STORE_TYPE, { required: true, gen: ['Central Store', 'Central Store', 'Warehouse', 'Warehouse', 'Warehouse', 'Warehouse', 'Site Store', 'Site Store', 'Site Store', 'Site Store', 'Site Store', 'Site Store', 'Site Store', 'Site Store'] }),
        text('city', 'City', ['Chennai', 'Bengaluru', 'Sriperumbudur', 'Hosur', 'Coimbatore', 'Hyderabad', 'Chennai', 'Coimbatore', 'Hosur', 'Bengaluru', 'Hyderabad', 'Chennai', 'Visakhapatnam', 'Madurai']),
        text('serves', 'Serves', ['All Chennai projects', 'Metro Office Tower, Greenfield', 'Finishes — all projects', 'Greenfield Township', 'Riverside Villas', 'Lakeview Residency', 'PRJ-001 Skyline Apartments', 'PRJ-002 Riverside Villas', 'PRJ-003 Greenfield Township', 'PRJ-004 Metro Office Tower', 'PRJ-005 Lakeview Residency', 'PRJ-006 Orbit Tech Park Phase II', 'PRJ-007 Harbour View Hospital', 'PRJ-008 Sunrise Business Hotel']),
        ref('keeper', 'Store Keeper', 'employee'),
        num('areaSqft', 'Covered Area', [1200, 24000], { unit: 'sq ft' }),
        num('skus', 'Items Stocked', [40, 190]),
        money('value', 'Stock Value', [4500000, 48000000]),
        status(['Active', 'Inactive'], { gen: ['Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active'] }),
      ],
    },
    {
      id: 'storeGateEntry',
      label: 'Gate Entry',
      plural: 'Gate Entries',
      app: 'store',
      codePrefix: 'GE',
      titleField: 'material',
      count: 16,
      fields: [
        text('material', 'Material', RCV_MATERIAL.slice(0, 16), { required: true }),
        text('vendor', 'Vendor', RCV_VENDOR.slice(0, 16)),
        text('poNo', 'PO No.', RCV_PO.slice(0, 16)),
        text('vehicle', 'Vehicle No.', VEHICLES),
        text('challan', 'Challan No.', ['DC-44812', 'UBC/DC/9921', 'CRMC-T-20874', 'SMA/2213', 'KBB/DC/0418', 'AE/DC/3350', 'FLP/771', 'CCP/DC/1182', 'STG/DC/566', 'FTS/DC/209', 'SPS/DC/118', 'DHM/DC/4410', 'SGA/DC/092', 'CFS/7781', 'TWP/DC/305', 'DC-44890']),
        ref('store', 'Store', 'storeStore'),
        date('entryDate', 'Entry Date', [-6, 0]),
        text('inTime', 'In Time', ['07:42', '08:15', '08:50', '09:05', '09:40', '10:12', '10:55', '11:20', '11:48', '12:30', '14:05', '14:40', '15:15', '15:50', '16:25', '17:10'], { list: false }),
        status(['Awaiting Inspection', 'Accepted', 'Partially Received', 'Rejected'], { gen: ['Accepted', 'Awaiting Inspection', 'Accepted', 'Rejected', 'Accepted', 'Awaiting Inspection', 'Accepted', 'Accepted', 'Partially Received', 'Accepted', 'Accepted', 'Accepted', 'Awaiting Inspection', 'Accepted', 'Partially Received', 'Awaiting Inspection'] }),
      ],
    },
    {
      id: 'storeGrn',
      label: 'GRN',
      plural: 'GRNs',
      app: 'store',
      codePrefix: 'GRN',
      titleField: 'material',
      count: 18,
      form: 'page',
      sections: [
        { id: 'receipt', title: 'Receipt Details', icon: 'ti-package-import' },
        { id: 'qty', title: 'Quantity Verification', icon: 'ti-scale' },
        { id: 'qc', title: 'Quality Verification', icon: 'ti-shield-check' },
      ],
      tabs: ['Financial'],
      fields: [
        text('material', 'Material', RCV_MATERIAL, { required: true, section: 'receipt' }),
        text('vendor', 'Vendor', RCV_VENDOR, { required: true, section: 'receipt' }),
        text('poNo', 'PO No.', RCV_PO, { required: true, section: 'receipt' }),
        ref('gateEntry', 'Gate Entry', 'storeGateEntry', { section: 'receipt', list: false }),
        ref('store', 'Receiving Store', 'storeStore', { section: 'receipt' }),
        date('grnDate', 'GRN Date', [-12, 0], { section: 'receipt' }),
        text('challan', 'Challan / Invoice No.', ['DC-44812', 'UBC/DC/9921', 'CRMC-T-20874', 'SMA/2213', 'KBB/DC/0418', 'AE/DC/3350', 'FLP/771', 'CCP/DC/1182', 'STG/DC/566', 'FTS/DC/209', 'SPS/DC/118', 'DHM/DC/4410', 'SGA/DC/092', 'CFS/7781', 'TWP/DC/305', 'DC-44890', 'SMA/2260', 'UBC/DC/9987'], { section: 'receipt', list: false }),
        text('received', 'Received Qty', RCV_QTY, { section: 'qty' }),
        text('rejected', 'Rejected Qty', ['0', '12 Bags', '0', '48 Cum', '240 Nos', '0', '0', '0', '36 Sqm', '6 Sheets', '0', '0', '14 Sqm', '0', '0', '0', '0', '0'], { section: 'qty', list: false }),
        money('value', 'Accepted Value', [180000, 1480000], { section: 'qty' }),
        select('qcResult', 'QC Result', ['Passed', 'Failed', 'Pending'], { section: 'qc', list: false, gen: ['Passed', 'Passed', 'Passed', 'Failed', 'Passed', 'Pending', 'Passed', 'Passed', 'Passed', 'Passed', 'Passed', 'Passed', 'Pending', 'Passed', 'Passed', 'Passed', 'Pending', 'Passed'] }),
        ref('receivedBy', 'Received By', 'employee', { section: 'qc', list: false }),
        area('remarks', 'Remarks', ['Weighbridge slip attached; MTC verified.', '12 bags found torn — debit note raised.', 'Slump 110 mm, 6 cubes cast.', 'Silt content 11% — lot rejected and returned.', 'Broken blocks segregated, photos uploaded.'], { section: 'qc' }),
        status(['Draft', 'Pending Verification', 'Verified', 'Rejected'], { section: 'receipt', gen: ['Verified', 'Pending Verification', 'Verified', 'Rejected', 'Verified', 'Pending Verification', 'Verified', 'Verified', 'Pending Verification', 'Verified', 'Verified', 'Verified', 'Pending Verification', 'Verified', 'Draft', 'Verified', 'Pending Verification', 'Pending Verification'] }),
      ],
    },
    {
      id: 'storeBatch',
      label: 'Batch',
      plural: 'Batches',
      app: 'store',
      codePrefix: 'BT',
      titleField: 'batchNo',
      count: 16,
      fields: [
        text('batchNo', 'Batch / Heat No.', ['OPC-2609-W37', 'OPC-2609-W38', 'PPC-2609-W36', 'HT-58812 (12mm)', 'HT-58840 (16mm)', 'HT-59017 (25mm)', 'ADM-SP-0926', 'WP-CRX-2608', 'EMU-INT-7741', 'EMU-EXT-7702', 'OPC-2608-W33', 'HT-58301 (8mm)', 'ADM-SP-0826', 'PPC-2608-W32', 'WP-CRX-2606', 'EMU-INT-7390'], { required: true }),
        text('item', 'Item', ['Cement OPC 53 Grade', 'Cement OPC 53 Grade', 'Cement PPC', 'TMT Bar Fe500D 12mm', 'TMT Bar Fe500D 16mm', 'TMT Bar Fe500D 25mm', 'Admixture (Superplasticiser)', 'Waterproofing Compound', 'Interior Emulsion', 'Exterior Emulsion', 'Cement OPC 53 Grade', 'TMT Bar Fe500D 8mm', 'Admixture (Superplasticiser)', 'Cement PPC', 'Waterproofing Compound', 'Interior Emulsion']),
        text('qty', 'Quantity', ['1,300 Bags', '900 Bags', '1,100 Bags', '18 MT', '22 MT', '12 MT', '1,200 Ltr', '750 Kg', '600 Ltr', '420 Ltr', '380 Bags', '9 MT', '300 Ltr', '260 Bags', '180 Kg', '140 Ltr']),
        ref('store', 'Store', 'storeStore'),
        date('mfg', 'Mfg. Date', [-75, -6]),
        date('expiry', 'Expiry / Use By', [-4, 160]),
        text('certificate', 'Test Certificate', ['MTC-UBC-3721', 'MTC-UBC-3790', 'MTC-UBC-3655', 'MTC-SB-58812', 'MTC-SB-58840', 'MTC-SB-59017', 'COA-0926', 'COA-2608', 'COA-7741', 'COA-7702', 'MTC-UBC-3502', 'MTC-SB-58301', 'COA-0826', 'MTC-UBC-3488', 'COA-2606', 'COA-7390'], { list: false }),
        status(['Available', 'Allocated', 'Expiring Soon', 'Expired'], { gen: ['Available', 'Available', 'Allocated', 'Available', 'Allocated', 'Available', 'Available', 'Available', 'Available', 'Allocated', 'Expiring Soon', 'Available', 'Expiring Soon', 'Expiring Soon', 'Expired', 'Available'] }),
      ],
    },
    {
      id: 'storeSerial',
      label: 'Serialised Item',
      plural: 'Serialised Items',
      app: 'store',
      codePrefix: 'SR',
      titleField: 'serialNo',
      count: 14,
      fields: [
        text('serialNo', 'Serial No.', ['DB12-TPN-240918', 'DB12-TPN-240931', 'HRN-FB-77120', 'HRN-FB-77134', 'VIB-60-11893', 'GSB13-3601A91', 'WLD-400-5521', 'TS07-1877342', 'AL-B40-20931', 'CUBE-150-0412', 'DRL-SDS-88410', 'GRD-100-33019', 'HRN-FB-77161', 'VIB-60-11907'], { required: true }),
        text('asset', 'Item', ['Distribution Board 12-way', 'Distribution Board 12-way', 'Safety Harness (Full Body)', 'Safety Harness (Full Body)', 'Needle Vibrator 60mm', 'Impact Drill 13mm', 'Welding Machine 400A', 'Total Station', 'Auto Level', 'Cube Mould 150mm (set of 6)', 'Rotary Hammer SDS', 'Angle Grinder 100mm', 'Safety Harness (Full Body)', 'Needle Vibrator 60mm']),
        ref('store', 'Store', 'storeStore'),
        ref('issuedTo', 'Issued To', 'employee'),
        date('warranty', 'Warranty Until', [-30, 540]),
        date('lastInspection', 'Last Inspection', [-60, -1], { list: false }),
        status(['In Stock', 'Issued', 'Under Maintenance', 'Inactive'], { gen: ['In Stock', 'Issued', 'Issued', 'In Stock', 'Issued', 'Issued', 'Under Maintenance', 'Issued', 'In Stock', 'Issued', 'Issued', 'In Stock', 'Inactive', 'Under Maintenance'] }),
      ],
    },
    {
      id: 'storeStockLocation',
      label: 'Stock Location',
      plural: 'Stock Locations',
      app: 'store',
      codePrefix: 'SL',
      titleField: 'item',
      count: 20,
      fields: [
        text('item', 'Item', ['TMT Bar Fe500D 12mm', 'TMT Bar Fe500D 16mm', 'TMT Bar Fe500D 25mm', 'Binding Wire 18G', 'Cement OPC 53 Grade', 'Cement PPC', 'Admixture (Superplasticiser)', 'FR Cable 2.5 sq.mm', 'Distribution Board 12-way', 'CPVC Pipe 25mm', 'uPVC Pipe 110mm', 'Safety Helmet', 'Safety Harness (Full Body)', 'Vitrified Tile 600x600', 'Granite Slab (Black Galaxy)', 'Interior Emulsion', 'Exterior Emulsion', 'Waterproofing Compound', 'Shuttering Plywood 12mm', 'AAC Block 600x200x200'], { required: true }),
        text('location', 'Rack / Bin', ['Zone A · Bay A1', 'Zone A · Bay A2', 'Zone A · Bay A2', 'Zone A · Bay A3', 'Zone B · Rack B1', 'Zone B · Rack B2', 'Zone B · Rack B3', 'Rack C1 · Bin 04', 'Rack C1 · Bin 09', 'Rack C2 · Bin 02', 'Rack C2 · Bin 07', 'Rack C3 · Bin 01', 'Rack C3 · Bin 03', 'Zone A · Tiles', 'Zone A · Tiles', 'Zone B · Paints', 'Zone B · Paints', 'Zone B · Rack B3', 'Steel yard · Bay 2', 'Open yard · Stack 4']),
        ref('store', 'Store', 'storeStore'),
        text('qty', 'On Hand', ['58.1 MT', '46.4 MT', '21.0 MT', '852 Kg', '1,832 Bags', '1,140 Bags', '640 Ltr', '84 Coils', '26 Nos', '1,420 Mtr', '980 Mtr', '410 Nos', '64 Nos', '3,120 Sqm', '410 Sqm', '720 Ltr', '1,060 Ltr', '480 Kg', '240 Sheets', '9,150 Nos']),
        money('value', 'Stock Value', [45000, 3600000]),
        date('counted', 'Last Counted', [-30, -1]),
        status(['In Stock', 'Reorder Level', 'Low Stock'], { gen: ['In Stock', 'In Stock', 'In Stock', 'In Stock', 'In Stock', 'In Stock', 'In Stock', 'Reorder Level', 'In Stock', 'In Stock', 'In Stock', 'In Stock', 'In Stock', 'In Stock', 'In Stock', 'Reorder Level', 'In Stock', 'In Stock', 'Reorder Level', 'In Stock'] }),
      ],
    },
    {
      id: 'storeIssue',
      label: 'Material Issue',
      plural: 'Material Issues',
      app: 'store',
      codePrefix: 'MI',
      titleField: 'purpose',
      count: 18,
      form: 'page',
      fields: [
        text('purpose', 'Issue For', ['Slab L9 concreting — Tower A', 'Column casting L10 — Tower B', 'Block work L4 — Tower A', 'Conduiting L6 — Tower A', 'Plumbing sleeves — Villa cluster 3', 'Terrace waterproofing — Block C', 'Raft reinforcement — Block B', 'Internal plaster L3', 'Lobby flooring — Tower A', 'Shuttering — staircase L8', 'New gang induction — PPE', 'DG set & equipment fuel', 'Façade bracket fixing L6', 'Kerb & drain — internal road', 'Lift core walls L7', 'Electrical DB installation L5', 'Painting primer — clubhouse', 'Safety office — general stores'], { required: true }),
        text('material', 'Material', ['Ready Mix Concrete M30', 'TMT Bar Fe500D 16mm', 'AAC Block 600x200x200', 'FR Cable 2.5 sq.mm', 'CPVC Pipe 25mm', 'Waterproofing Compound', 'TMT Bar Fe500D 12mm', 'P-Sand (Plastering)', 'Vitrified Tile 600x600', 'Shuttering Plywood 12mm', 'Safety Helmet', 'HSD (Diesel)', 'Aluminium Window Section', 'Coarse Aggregate 20mm', 'TMT Bar Fe500D 25mm', 'Distribution Board 12-way', 'Interior Emulsion', 'Safety Harness (Full Body)']),
        text('qty', 'Quantity', ['86 Cum', '6.4 MT', '2,400 Nos', '18 Coils', '240 Mtr', '320 Kg', '4.8 MT', '22 Cum', '480 Sqm', '40 Sheets', '60 Nos', '1,800 Ltr', '260 Kg', '38 Cum', '3.2 MT', '8 Nos', '160 Ltr', '12 Nos']),
        select('issueType', 'Issue Type', ['Site Issue', 'Project Issue', 'Department Issue'], { gen: ['Site Issue', 'Site Issue', 'Site Issue', 'Project Issue', 'Site Issue', 'Project Issue', 'Site Issue', 'Site Issue', 'Project Issue', 'Site Issue', 'Department Issue', 'Department Issue', 'Project Issue', 'Site Issue', 'Site Issue', 'Project Issue', 'Project Issue', 'Department Issue'] }),
        ref('project', 'Project', 'project'),
        ref('store', 'Issuing Store', 'storeStore'),
        ref('issuedTo', 'Issued To', 'employee'),
        money('value', 'Issue Value', [18000, 520000]),
        date('issueDate', 'Issue Date', [-10, 0]),
        status(['Draft', 'Pending Approval', 'Issued', 'Cancelled'], { gen: ['Issued', 'Issued', 'Pending Approval', 'Issued', 'Issued', 'Draft', 'Issued', 'Issued', 'Pending Approval', 'Issued', 'Issued', 'Issued', 'Pending Approval', 'Issued', 'Issued', 'Cancelled', 'Issued', 'Issued'] }),
      ],
    },
    {
      id: 'storeTransfer',
      label: 'Material Transfer',
      plural: 'Material Transfers',
      app: 'store',
      codePrefix: 'MT',
      titleField: 'material',
      count: 16,
      fields: [
        text('material', 'Material', ['TMT Bar Fe500D 12mm', 'Cement OPC 53 Grade', 'Shuttering Plywood 12mm', 'Vitrified Tile 600x600', 'Binding Wire 18G', 'Safety Harness (Full Body)', 'Aluminium formwork panels', 'CPVC Pipe 25mm', 'Excess TMT 25mm offcuts', 'Scaffolding cup-lock set', 'Interior Emulsion', 'FR Cable 2.5 sq.mm', 'Returned plywood (reusable)', 'Cement PPC', 'Granite Slab (Black Galaxy)', 'M-Sand'], { required: true }),
        select('transferType', 'Transfer Type', ['Store-to-Store', 'Store-to-Site', 'Site-to-Store'], { gen: ['Store-to-Site', 'Store-to-Site', 'Site-to-Store', 'Store-to-Store', 'Store-to-Site', 'Store-to-Site', 'Site-to-Store', 'Store-to-Store', 'Site-to-Store', 'Store-to-Site', 'Store-to-Store', 'Store-to-Site', 'Site-to-Store', 'Store-to-Site', 'Store-to-Store', 'Store-to-Site'] }),
        ref('fromStore', 'From', 'storeStore'),
        ref('toStore', 'To', 'storeStore'),
        text('qty', 'Quantity', ['8.5 MT', '600 Bags', '120 Sheets', '640 Sqm', '300 Kg', '24 Nos', '180 Panels', '400 Mtr', '2.2 MT', '60 Sets', '240 Ltr', '30 Coils', '85 Sheets', '400 Bags', '120 Sqm', '40 Cum']),
        text('vehicle', 'Vehicle No.', VEHICLES, { list: false }),
        date('dispatched', 'Dispatched On', [-12, 0]),
        status(['Draft', 'In Transit', 'Received', 'Cancelled'], { gen: ['Received', 'In Transit', 'Received', 'Received', 'In Transit', 'Received', 'Received', 'Draft', 'Received', 'In Transit', 'Received', 'Received', 'Received', 'In Transit', 'Cancelled', 'Received'] }),
      ],
    },
    {
      id: 'storeReturn',
      label: 'Material Return',
      plural: 'Material Returns',
      app: 'store',
      codePrefix: 'MR',
      titleField: 'material',
      count: 14,
      fields: [
        text('material', 'Material', ['Shuttering Plywood 12mm', 'TMT Bar Fe500D 16mm', 'AAC Block 600x200x200', 'Cement OPC 53 Grade', 'CPVC Pipe 25mm', 'Vitrified Tile 600x600', 'FR Cable 2.5 sq.mm', 'Safety Helmet', 'Binding Wire 18G', 'Granite Slab (Black Galaxy)', 'Scaffolding cup-lock set', 'Interior Emulsion', 'Aluminium formwork panels', 'Toughened Glass 8mm'], { required: true }),
        select('returnType', 'Return Type', ['Reusable', 'Damaged', 'Excess'], { gen: ['Reusable', 'Excess', 'Damaged', 'Excess', 'Excess', 'Damaged', 'Excess', 'Reusable', 'Excess', 'Damaged', 'Reusable', 'Excess', 'Reusable', 'Damaged'] }),
        ref('project', 'From Project', 'project'),
        ref('store', 'Return To', 'storeStore'),
        text('qty', 'Quantity', ['140 Sheets', '1.6 MT', '420 Nos', '80 Bags', '160 Mtr', '46 Sqm', '6 Coils', '35 Nos', '120 Kg', '12 Sqm', '80 Sets', '60 Ltr', '96 Panels', '8 Sqm']),
        money('value', 'Return Value', [9000, 380000]),
        date('returnDate', 'Return Date', [-20, 0]),
        area('reason', 'Reason', ['Floor cycle completed; plywood reusable for 3 more cycles.', 'Excess over BBS after slab L9.', 'Broken during handling at hoist.', 'Balance after block work completion.', 'Chipped edges — to be claimed on vendor.']),
        status(['Pending', 'Accepted', 'Rejected'], { gen: ['Accepted', 'Accepted', 'Pending', 'Accepted', 'Pending', 'Rejected', 'Accepted', 'Accepted', 'Pending', 'Accepted', 'Accepted', 'Pending', 'Accepted', 'Rejected'] }),
      ],
    },
    {
      id: 'storeAdjustment',
      label: 'Stock Adjustment',
      plural: 'Stock Adjustments',
      app: 'store',
      codePrefix: 'SA',
      titleField: 'material',
      count: 12,
      fields: [
        text('material', 'Material', ['TMT Bar Fe500D 12mm', 'Cement OPC 53 Grade', 'M-Sand', 'AAC Block 600x200x200', 'Binding Wire 18G', 'Cement PPC', 'Admixture (Superplasticiser)', 'Safety Helmet', 'Interior Emulsion', 'CPVC Pipe 25mm', 'Vitrified Tile 600x600', 'HSD (Diesel)'], { required: true }),
        ref('store', 'Store', 'storeStore'),
        select('direction', 'Adjustment', ['Increase', 'Decrease'], { gen: ['Decrease', 'Decrease', 'Decrease', 'Decrease', 'Decrease', 'Increase', 'Decrease', 'Increase', 'Decrease', 'Increase', 'Decrease', 'Decrease'] }),
        text('qty', 'Quantity', ['0.7 MT', '19 Bags', '22 Cum', '170 Nos', '12 Kg', '40 Bags', '35 Ltr', '20 Nos', '18 Ltr', '60 Mtr', '28 Sqm', '240 Ltr']),
        select('reason', 'Reason', ['Physical count variance', 'Damage in storage', 'Theft / pilferage', 'Data entry correction', 'Expiry / set material']),
        money('value', 'Value Impact', [4000, 110000]),
        ref('approvedBy', 'Approver', 'employee'),
        status(['Draft', 'Pending Approval', 'Approved', 'Rejected'], { gen: ['Pending Approval', 'Pending Approval', 'Pending Approval', 'Approved', 'Approved', 'Approved', 'Draft', 'Approved', 'Approved', 'Rejected', 'Pending Approval', 'Approved'] }),
      ],
    },
    {
      id: 'storeWastage',
      label: 'Wastage Entry',
      plural: 'Wastage Entries',
      app: 'store',
      codePrefix: 'WS',
      titleField: 'material',
      count: 14,
      form: 'page',
      fields: [
        text('material', 'Material', ['TMT Bar Fe500D 16mm', 'Cement OPC 53 Grade', 'Ready Mix Concrete M30', 'AAC Block 600x200x200', 'Vitrified Tile 600x600', 'Shuttering Plywood 12mm', 'M-Sand', 'Cement PPC', 'Binding Wire 18G', 'Granite Slab (Black Galaxy)', 'Interior Emulsion', 'CPVC Pipe 25mm', 'Toughened Glass 8mm', 'TMT Bar Fe500D 12mm'], { required: true }),
        ref('project', 'Project', 'project'),
        text('activity', 'Activity', ['Slab L8 reinforcement', 'Block work mortar L3', 'Column pour L10 — excess order', 'Block work L4', 'Lobby flooring', 'Staircase shuttering', 'Plastering L2', 'Ceiling plaster', 'Raft reinforcement', 'Kitchen platforms', 'Internal painting L1', 'Plumbing — Villa cluster 2', 'Façade glazing L5', 'Beam reinforcement L9']),
        text('qty', 'Quantity Wasted', ['1.4 MT', '46 Bags', '3.5 Cum', '380 Nos', '96 Sqm', '38 Sheets', '11 Cum', '28 Bags', '42 Kg', '14 Sqm', '38 Ltr', '64 Mtr', '6 Sqm', '0.9 MT']),
        num('wastagePct', 'Wastage', [1.2, 7.8], { unit: '%' }),
        select('reason', 'Reason', ['Cutting / lapping loss', 'Spillage', 'Breakage in handling', 'Over-ordering', 'Set / expired material', 'Theft / pilferage', 'Rework'], { gen: ['Cutting / lapping loss', 'Set / expired material', 'Over-ordering', 'Breakage in handling', 'Breakage in handling', 'Rework', 'Spillage', 'Spillage', 'Cutting / lapping loss', 'Breakage in handling', 'Spillage', 'Cutting / lapping loss', 'Breakage in handling', 'Cutting / lapping loss'] }),
        money('cost', 'Cost Impact', [6000, 480000]),
        date('reported', 'Reported On', [-25, 0]),
        area('action', 'Corrective Action', ['BBS optimised; offcuts to be used for chairs & stirrups.', 'Cement shed roofing repaired; FIFO enforced.', 'RMC ordering to be based on pour-card quantities.', 'Hoist loading supervised by store keeper.', 'Cutting plan approved before tile laying.']),
        status(['Under Review', 'Approved', 'Rejected'], { gen: ['Approved', 'Under Review', 'Approved', 'Approved', 'Under Review', 'Approved', 'Approved', 'Rejected', 'Approved', 'Under Review', 'Approved', 'Approved', 'Under Review', 'Approved'] }),
      ],
    },
  ],
};
