import { area, board, date, docs, group, money, monthCalendar, num, page, pct, ref, register, select, status, statusView, text } from '../dsl';
import type { AppConfig, Row } from '../types';

const CR = 1e7;
const cr = (x: number) => Math.round(x * CR);
const pad = (n: number) => String(n).padStart(3, '0');
/** ISO date shifted by n days (UTC, no DST drift). */
const shift = (iso: string, n: number) => new Date(Date.parse(`${iso}T00:00:00Z`) + n * 864e5).toISOString().slice(0, 10);

const TENDER_TYPES = ['Open Tender', 'Limited Tender', 'Selective Tender', 'Negotiated', 'Design & Build', 'EPC', 'Item Rate', 'Lump Sum', 'Percentage Rate'];
const CATEGORIES = ['Residential', 'Commercial', 'Institutional', 'Industrial', 'Hospitality', 'Infrastructure'];
const TENDER_STATUS = ['Open', 'Under Evaluation', 'Bid Preparation', 'Draft', 'Under Review', 'Submitted', 'Won', 'Lost', 'No Bid', 'Cancelled'];
const DOC_FOLDERS = ['Tender Notice', 'Specifications', 'Drawings', 'Terms & Conditions', 'Addendums', 'Pre-bid Queries'];

const SCOPE: Record<string, string> = {
  Residential: 'Civil, structural and finishing works for residential towers including basement parking, MEP coordination and external development.',
  Commercial: 'Shell & core civil and structural works, podium parking, façade support structure and MEP sleeves.',
  Institutional: 'Complete civil, structural, finishing and MEP works including specialised flooring, medical gas provisions and external works.',
  Industrial: 'RCC and PEB structures, industrial flooring (FM2), internal roads, storm-water drains and utility buildings.',
  Hospitality: 'Civil, structural and finishing works for hotel blocks, banquet hall, pool deck and landscaping.',
  Infrastructure: 'Roads, storm-water drains, culverts, utility corridors and multi-level parking structure.',
};

/** [title, tender no., type, category, client, location, issue date, deadline, value ₹Cr, status, owner, bid/no-bid, our bid ₹Cr] */
const tenderData: [string, string, string, string, string, string, string, string, number, string, string, string, number][] = [
  ['Harbour View Hospital — Phase II Medical Block', 'CHT/HVH-II/CIV/2026/014', 'EPC', 'Institutional', 'CL-007', 'Visakhapatnam', '2026-08-18', '2026-10-08', 148, 'Bid Preparation', 'EMP-021', 'Bid', 142.9],
  ['Orbit Tech Park Phase III — Tower C & D Shell', 'OTP/PH3/SC/2026/007', 'Design & Build', 'Commercial', 'CL-006', 'Chennai', '2026-08-05', '2026-10-03', 176, 'Under Review', 'EMP-032', 'Bid', 169.2],
  ['Meridian Logistics Park — Warehouse Blocks A–F', 'MIP/LOG/WH/26-27/018', 'Lump Sum', 'Industrial', 'CL-010', 'Sriperumbudur', '2026-08-22', '2026-10-14', 92, 'Bid Preparation', 'EMP-016', 'Bid', 88.7],
  ['Pinnacle Heights — G+22 Residential Towers', 'PR/PH/CIV/2026/031', 'Item Rate', 'Residential', 'CL-009', 'Pune', '2026-09-01', '2026-10-21', 134, 'Draft', 'EMP-021', 'Bid', 128.8],
  ['Sunrise Resort & Convention Centre', 'SH/KDK/RES/2026/004', 'Negotiated', 'Hospitality', 'CL-008', 'Kodaikanal', '2026-09-08', '2026-10-28', 68, 'Open', 'EMP-038', 'Under Evaluation', 0],
  ['Greenfield Township Phase 3 — Villas & Clubhouse', 'GIL/TWN-3/VIL/2026/022', 'Item Rate', 'Residential', 'CL-003', 'Hosur', '2026-07-28', '2026-09-24', 112, 'Submitted', 'EMP-021', 'Bid', 110.8],
  ['Metro Corporate Park — Block B Superstructure', 'MC/MCP-B/STR/2026/011', 'Item Rate', 'Commercial', 'CL-004', 'Bengaluru', '2026-07-15', '2026-09-18', 86, 'Submitted', 'EMP-032', 'Bid', 84.9],
  ['Lakeview Residency Phase 2 — Towers 5 & 6', 'LE/LVR-2/T56/2026/009', 'Item Rate', 'Residential', 'CL-005', 'Hyderabad', '2026-06-20', '2026-08-12', 96, 'Won', 'EMP-021', 'Bid', 93.4],
  ['Coastal Nursing College & Hostel', 'CHT/NC/CIV/2026/006', 'Open Tender', 'Institutional', 'CL-007', 'Visakhapatnam', '2026-06-02', '2026-07-22', 38, 'Lost', 'EMP-006', 'Bid', 38.9],
  ['ABC Grand — Luxury Apartments, Adyar', 'ABC/ADY/LUX/2026/003', 'Negotiated', 'Residential', 'CL-001', 'Chennai', '2026-09-10', '2026-10-16', 58, 'Bid Preparation', 'EMP-038', 'Bid', 56.4],
  ['XYZ Riverfront Mall — Civil & Structure', 'XYZ/RFM/CS/2026/012', 'Lump Sum', 'Commercial', 'CL-002', 'Coimbatore', '2026-09-04', '2026-10-10', 124, 'Under Review', 'EMP-032', 'Bid', 118.4],
  ['Meridian Industrial Park — Internal Roads & Drains', 'MIP/INF/RD/26-27/024', 'Percentage Rate', 'Infrastructure', 'CL-010', 'Sriperumbudur', '2026-09-15', '2026-11-05', 42, 'Open', 'EMP-006', 'Under Evaluation', 0],
  ['Orbit Data Centre — Civil Works', 'OTP/DC1/CIV/2026/015', 'EPC', 'Industrial', 'CL-006', 'Siruseri, Chennai', '2026-09-12', '2026-10-30', 158, 'Under Evaluation', 'EMP-021', 'Under Evaluation', 0],
  ['Sunrise Business Hotel — Annex Block', 'SH/MDU/ANX/2026/002', 'Item Rate', 'Hospitality', 'CL-008', 'Madurai', '2026-07-01', '2026-08-20', 34, 'Won', 'EMP-038', 'Bid', 33.2],
  ['Pinnacle IT Park — Hinjewadi Phase 1', 'PR/HJW/ITP/2026/019', 'Design & Build', 'Commercial', 'CL-009', 'Pune', '2026-05-20', '2026-07-10', 142, 'Lost', 'EMP-032', 'Bid', 139.6],
  ['Greenfield School Campus', 'GIL/EDU/SCH/2026/027', 'Open Tender', 'Institutional', 'CL-003', 'Hosur', '2026-09-18', '2026-11-12', 28, 'Under Evaluation', 'EMP-006', 'Under Evaluation', 0],
  ['Metro Office Tower — Façade & Interiors Package', 'MC/MOT/FI/2026/008', 'Limited Tender', 'Commercial', 'CL-004', 'Bengaluru', '2026-06-10', '2026-07-30', 46, 'Won', 'EMP-021', 'Bid', 45.6],
  ['Lakeview Villas — Kokapet', 'LE/KKP/VIL/2026/005', 'Item Rate', 'Residential', 'CL-005', 'Hyderabad', '2026-05-12', '2026-06-30', 64, 'Lost', 'EMP-038', 'Bid', 66.1],
  ['ABC Builders — Commercial Complex, T. Nagar', 'ABC/TNR/COM/2026/004', 'Lump Sum', 'Commercial', 'CL-001', 'Chennai', '2026-09-20', '2026-11-18', 72, 'Open', 'EMP-032', 'Under Evaluation', 0],
  ['XYZ Developers — Affordable Housing (480 units)', 'XYZ/AH/480/2026/015', 'Item Rate', 'Residential', 'CL-002', 'Coimbatore', '2026-08-28', '2026-10-06', 54, 'Draft', 'EMP-016', 'Bid', 52.3],
  ['Coastal Healthcare — Diagnostic Centre', 'CHT/DGC/CIV/2026/011', 'Limited Tender', 'Institutional', 'CL-007', 'Visakhapatnam', '2026-08-10', '2026-09-22', 22, 'Submitted', 'EMP-006', 'Bid', 21.4],
  ['Meridian Cold Storage Facility', 'MIP/CSF/EPC/26-27/020', 'EPC', 'Industrial', 'CL-010', 'Sriperumbudur', '2026-09-02', '2026-10-01', 31, 'No Bid', 'EMP-016', 'No Bid', 0],
  ['Sunrise Heritage Hotel Renovation', 'SH/HTG/REN/2026/003', 'Negotiated', 'Hospitality', 'CL-008', 'Madurai', '2026-07-08', '2026-08-28', 18, 'Cancelled', 'EMP-038', 'Bid', 0],
  ['Orbit Tech Park — Multi-level Car Park', 'OTP/MLCP/2026/019', 'Item Rate', 'Infrastructure', 'CL-006', 'Chennai', '2026-09-22', '2026-11-20', 26, 'Under Evaluation', 'EMP-006', 'Under Evaluation', 0],
];

const RATIONALE: Record<string, string> = {
  Bid: 'Strategic client, eligibility met, capacity available in Q4; bid approved by the Bid Committee.',
  'No Bid': 'Specialised refrigeration EPC outside core capability; margin below 6% threshold.',
  'Under Evaluation': 'Bid / no-bid assessment in progress — feasibility score due this week.',
};

const tenderRows: Row[] = tenderData.map(([title, tenderNo, type, category, client, location, issue, deadline, value, st, owner, decision, bid], i) => ({
  id: `TND-${pad(i + 1)}`,
  code: `TND-${pad(i + 1)}`,
  title,
  tenderNo,
  type,
  category,
  client,
  location,
  scope: SCOPE[category],
  issueDate: issue,
  preBid: shift(issue, 12),
  deadline,
  value: cr(value),
  emd: Math.round((value * CR * 0.01) / 100000) * 100000,
  bidPrice: bid ? cr(bid) : 0,
  decision,
  owner,
  winProb: [35, 40, 45, 30, 25, 50, 45, 100, 0, 55, 35, 30, 25, 100, 0, 40, 100, 0, 30, 45, 55, 0, 0, 35][i],
  rationale: RATIONALE[decision],
  status: st,
}));

/** Line-item seed rows: [section, description, unit, qty, rate, ...extra] */
function lines(prefix: string, data: [string, string, string, number, number][]): Row[] {
  return data.map(([section, description, unit, qty, rate], i) => ({ id: `${prefix}-${pad(i + 1)}`, code: `${prefix}-${pad(i + 1)}`, section, description, unit, qty, rate }));
}

const boqData: [string, string, string, number, number][] = [
  ['Earthwork', 'Excavation for basement in all soils incl. shoring support', 'Cum', 96000, 310],
  ['Earthwork', 'Excavation in hard rock by controlled chiselling (no blasting)', 'Cum', 8200, 1180],
  ['Earthwork', 'Dewatering during basement construction', 'Month', 8, 420000],
  ['Earthwork', 'Back-filling around basement retaining walls', 'Cum', 12400, 220],
  ['Concrete Works', 'PCC M15 levelling course below raft', 'Cum', 2300, 5450],
  ['Concrete Works', 'RCC M35 raft foundation (RMC, pump placed)', 'Cum', 14800, 7150],
  ['Concrete Works', 'RCC M40 columns & core walls', 'Cum', 11200, 8100],
  ['Concrete Works', 'RCC M35 flat slabs & beams', 'Cum', 21600, 7650],
  ['Concrete Works', 'Staging & shuttering — slabs, beams, columns', 'Sqm', 218000, 560],
  ['Reinforcement', 'TMT Fe500D 8–16 mm — cut, bend & place', 'MT', 2450, 66400],
  ['Reinforcement', 'TMT Fe500D 20–32 mm — cut, bend & place', 'MT', 4180, 65100],
  ['Reinforcement', 'Mechanical couplers 25–32 mm', 'Nos', 21500, 195],
  ['Masonry', 'AAC block masonry 200 mm — core & shafts', 'Cum', 3600, 5650],
  ['Masonry', 'AAC block masonry 100 mm — toilets & services', 'Cum', 900, 5950],
  ['Finishes', 'Internal plaster 12 mm CM 1:4 — core areas', 'Sqm', 48000, 355],
  ['Finishes', 'Fibre-reinforced screed 50 mm — floor plates', 'Sqm', 57600, 420],
  ['Finishes', 'Anti-skid tiles — staircases & lift lobbies', 'Sqm', 6800, 1150],
  ['Waterproofing', 'Basement waterproofing — HDPE membrane', 'Sqm', 22500, 980],
  ['Waterproofing', 'Terrace waterproofing — PU coating + protective screed', 'Sqm', 5200, 860],
];

/** [section, description, unit, tender BOQ qty, take-off qty, rate] */
const qtyData: [string, string, string, number, number, number][] = [
  ['Substructure', 'Excavation up to 3 m depth incl. disposal', 'Cum', 40000, 42600, 295],
  ['Substructure', 'Rock excavation by chiselling', 'Cum', 2500, 3800, 1150],
  ['Substructure', 'PCC M10 below footings & raft', 'Cum', 1400, 1480, 5150],
  ['Substructure', 'RCC M25 raft & footings', 'Cum', 5400, 5620, 6650],
  ['Substructure', 'RCC M25 retaining walls & lift pits', 'Cum', 1500, 1480, 7100],
  ['Superstructure', 'RCC M30 columns & shear walls', 'Cum', 3850, 3960, 7650],
  ['Superstructure', 'RCC M30 beams & slabs incl. staircase', 'Cum', 7400, 7580, 7450],
  ['Superstructure', 'Reinforcement TMT Fe500D — all diameters', 'MT', 2300, 2420, 65700],
  ['Superstructure', 'Centering & shuttering — all heights', 'Sqm', 98000, 102400, 545],
  ['Masonry & Finishes', 'AAC block masonry 200 mm in CM 1:4', 'Cum', 4200, 4120, 5650],
  ['Masonry & Finishes', 'Internal plaster 12 mm CM 1:4', 'Sqm', 84000, 86400, 360],
  ['Masonry & Finishes', 'Vitrified tile flooring 800×800', 'Sqm', 22000, 21600, 1280],
  ['Masonry & Finishes', 'Epoxy flooring — OT & ICU areas', 'Sqm', 2800, 3200, 2450],
  ['External Works', 'Paver block roads & parking', 'Sqm', 9500, 10200, 1050],
  ['External Works', 'Storm-water drain, RCC 600 mm wide', 'Rmt', 1450, 1520, 4800],
  ['External Works', 'Compound wall with MS grill', 'Rmt', 820, 860, 7200],
];

const rateData: [string, string, string, number, number][] = [
  ['Material', 'Cement OPC 53 grade', 'Bag', 8.4, 385],
  ['Material', 'Coarse aggregate 20 mm', 'Cum', 0.54, 1650],
  ['Material', 'Coarse aggregate 10 mm', 'Cum', 0.3, 1700],
  ['Material', 'M-Sand (manufactured sand)', 'Cum', 0.46, 1850],
  ['Material', 'Admixture — superplasticiser', 'Ltr', 3.4, 95],
  ['Material', 'Water for mixing & curing', 'KL', 0.2, 150],
  ['Labour', 'Mason — concreting supervision', 'Day', 0.1, 1050],
  ['Labour', 'Mazdoor — placing & compaction', 'Day', 0.6, 750],
  ['Labour', 'Vibrator operator', 'Day', 0.07, 900],
  ['Labour', 'Curing labour (7 days)', 'Day', 0.1, 750],
  ['Equipment', 'Batching plant 30 cum/hr', 'Hr', 0.04, 3200],
  ['Equipment', 'Transit mixer 7 cum', 'Hr', 0.15, 1400],
  ['Equipment', 'Concrete boom pump 36 m', 'Cum', 1, 320],
  ['Equipment', 'Needle vibrator 60 mm', 'Hr', 0.3, 100],
  ['Overhead', 'Site overheads & supervision', 'LS', 1, 540],
  ['Overhead', 'Water & electricity', 'LS', 1, 85],
  ['Overhead', 'QA/QC cube testing', 'LS', 1, 60],
  ['Overhead', 'Wastage allowance @ 2% of material', 'LS', 1, 117],
];

const overheadData: [string, string, string, number, number][] = [
  ['Site Staff', 'Project Manager', 'Man-month', 24, 220000],
  ['Site Staff', 'Site engineers (4 nos)', 'Man-month', 96, 75000],
  ['Site Staff', 'QS & planning engineers (2 nos)', 'Man-month', 48, 85000],
  ['Site Staff', 'Safety officers (2 nos)', 'Man-month', 48, 60000],
  ['Site Staff', 'Stores & administration (3 nos)', 'Man-month', 72, 38000],
  ['Site Facilities', 'Site office, stores & yard', 'LS', 1, 4200000],
  ['Site Facilities', 'Labour camp with sanitation', 'LS', 1, 6800000],
  ['Site Facilities', 'Temporary power & DG running', 'Month', 24, 320000],
  ['Site Facilities', 'Construction water', 'Month', 24, 85000],
  ['Site Facilities', 'Security & housekeeping', 'Month', 24, 240000],
  ['Site Facilities', 'Site vehicles & transport', 'Month', 24, 180000],
  ['Site Facilities', 'Field QA/QC laboratory', 'Month', 24, 75000],
  ['Insurance & Bonds', 'Contractor’s All Risk (CAR) policy', 'LS', 1, 4800000],
  ['Insurance & Bonds', 'Performance bank guarantee charges', 'LS', 1, 2200000],
  ['Insurance & Bonds', 'Workmen compensation policy', 'LS', 1, 950000],
  ['Head Office', 'Head-office overhead @ 2.5% of direct cost', 'LS', 1, 29500000],
  ['Head Office', 'Tender, design & pre-construction costs', 'LS', 1, 1800000],
];

const HV = 'TND-001 Harbour View Hospital — Phase II';

export const tenderApp: AppConfig = {
  id: 'tender',
  name: 'Tender',
  icon: 'ti-gavel',
  description: 'Tender register, documents, eligibility evaluation, bid preparation and submission',
  menus: [
    group('Tender Management', 'ti-file-description', [
      page('Tender Registration', register('tender')),
      page('Tender Details', register('tender', { views: ['table', 'board'], boardField: 'status' })),
      page('Tender Type', register('tenderType')),
      page('Submission Deadline', monthCalendar('Submission Deadlines', 'tender', 'deadline')),
      page('Tender Status', board('tender', 'status', ['client', 'value', 'deadline'])),
    ]),
    group('Tender Documents', 'ti-folders', [
      page('Tender Notice', docs(DOC_FOLDERS, 'Tender Notice', 'Tender Notice')),
      page('Specifications', docs(DOC_FOLDERS, 'Specifications', 'Specifications')),
      page('Drawings', docs(DOC_FOLDERS, 'Drawings', 'Tender Drawings')),
      page('BOQ', { type: 'lineitems', entity: 'tenderBoq', title: 'Tender BOQ — TND-002 Orbit Tech Park Phase III' }),
      page('Terms & Conditions', docs(DOC_FOLDERS, 'Terms & Conditions', 'Terms & Conditions')),
    ]),
    group('Evaluation', 'ti-clipboard-check', [
      page('Technical Eligibility', {
        type: 'checklist',
        title: 'Technical Eligibility',
        subject: 'tender',
        groups: [
          { title: 'Similar Work Experience', items: ['One similar work ≥ 80% of estimated value completed in last 7 years', 'Two similar works ≥ 50% of estimated value', 'Three similar works ≥ 40% of estimated value', 'Experience in hospital / institutional buildings ≥ 2 lakh sq ft'] },
          { title: 'Technical Capability', items: ['In-house planning & QS team (min. 10 engineers)', 'ISO 9001:2015 and ISO 45001:2018 certification valid', 'Concrete batching plant (30 cum/hr) owned or on long lease', 'Tower cranes — minimum 2 nos available for deployment'] },
          { title: 'Key Personnel', items: ['Project Manager — B.E. Civil with 15+ years', 'Planning Engineer — Primavera P6 proficiency', 'QA/QC Engineer — 10+ years in high-rise works', 'Safety Officer — NEBOSH / ADIS qualified'] },
          { title: 'Plant & Machinery', items: ['Concrete boom pump 36 m', 'Transit mixers — 6 nos', 'Material hoists — 2 nos', 'DG sets 250 kVA — 2 nos'] },
        ],
      }),
      page('Financial Eligibility', {
        type: 'checklist',
        title: 'Financial Eligibility',
        subject: 'tender',
        groups: [
          { title: 'Turnover & Net Worth', items: ['Average annual turnover ≥ ₹ 150 Cr (last 3 FY)', 'Positive net worth in each of the last 3 FY', 'Audited balance sheets FY 23-24, 24-25, 25-26 attached', 'CA-certified turnover certificate'] },
          { title: 'Bid Capacity', items: ['Available bid capacity (2.5 × A × N − B) ≥ estimated value', 'Statement of works in hand with balance value', 'Solvency certificate ≥ ₹ 40 Cr from scheduled bank'] },
          { title: 'Banking & Security', items: ['EMD of ₹ 1.48 Cr via bank guarantee / DD', 'Bank willing to issue performance guarantee @ 5%', 'Working-capital limits sanction letter'] },
          { title: 'Tax Compliance', items: ['GST registration & last 12 months returns filed', 'PAN and income-tax returns for 3 years', 'No outstanding statutory dues (PF / ESI)'] },
        ],
      }),
      page('Experience', {
        type: 'checklist',
        title: 'Experience',
        subject: 'tender',
        groups: [
          { title: 'Similar Works Completed (last 7 years)', items: ['Orbit Tech Park Phase I — ₹ 142 Cr (2023)', 'Pearl Residency G+9 — ₹ 64 Cr (2019)', 'Coastal Healthcare OPD Block — ₹ 48 Cr (2022)', 'Metro Office Tower podium — ₹ 38 Cr (2024)'] },
          { title: 'Completion Certificates', items: ['Completion certificates signed by client (not below EE rank for public works)', 'Work orders and final bill copies attached', 'Performance certificates — quality & timeliness'] },
          { title: 'Client References', items: ['Reference letter — Coastal Healthcare Trust', 'Reference letter — Orbit Tech Parks', 'No termination or debarment in the last 5 years'] },
        ],
      }),
      page('Compliance', {
        type: 'checklist',
        title: 'Compliance',
        subject: 'tender',
        groups: [
          { title: 'Statutory Registrations', items: ['Company incorporation & MoA / AoA', 'GST, PAN, PF and ESI registrations', 'Labour licence under CLRA Act', 'BOCW registration in the state of work'] },
          { title: 'Bid Documents', items: ['Tender form signed & stamped on every page', 'Power of attorney for authorised signatory', 'Integrity pact executed', 'Addenda 1–3 acknowledged'] },
          { title: 'Commercial Compliance', items: ['Price bid in the prescribed BOQ format', 'No conditional or deviation clauses in price bid', 'Bid validity 120 days from submission', 'Taxes quoted as per tender instructions'] },
          { title: 'HSE & Quality', items: ['Site-specific safety plan submitted', 'Quality assurance plan (QAP) submitted', 'Environmental management plan submitted'] },
        ],
      }),
      page('Feasibility', {
        type: 'checklist',
        title: 'Feasibility',
        subject: 'tender',
        scored: true,
        groups: [
          { title: 'Strategic Fit', items: ['Client is strategic / repeat client', 'Project type aligns with FY 26-27 business plan', 'Geography within existing operating cluster', 'Reference value for future bids'] },
          { title: 'Technical Feasibility', items: ['Design & drawings adequate for pricing', 'Schedule achievable with available resources', 'No specialised works beyond in-house capability'] },
          { title: 'Commercial Feasibility', items: ['Expected margin ≥ 8% on cost', 'Payment terms — monthly RA bills within 30 days', 'Mobilisation advance available against BG', 'Price variation clause for steel & cement'] },
          { title: 'Risk & Resources', items: ['Liquidated damages capped at 5–10%', 'Key staff available from Oct 2026', 'Working capital requirement within limits', 'No adverse site / soil conditions reported'] },
        ],
      }),
    ]),
    group('Bid Preparation', 'ti-file-dollar', [
      page('Quantity', { type: 'lineitems', tax: 0, entity: 'tenderQty', title: `Bid Quantity Take-off — ${HV}`, extra: ['boqQty'] }),
      page('Rate Analysis', { type: 'lineitems', tax: 0, entity: 'tenderRate', title: 'Rate Build-up — RCC M30 beams & slabs (per cum)' }),
      page('Cost Estimate', {
        type: 'analysis',
        title: `Cost Estimate — ${HV}`,
        kpis: [
          { label: 'Total estimated cost', value: '₹ 129.9 Cr', icon: 'ti-sum', sub: 'Estimate R2 · 3.4 lakh sq ft' },
          { label: 'Direct cost', value: '₹ 118.0 Cr', progress: 91, icon: 'ti-stack-2', sub: 'Material · Labour · Equipment · Subcontract' },
          { label: 'Overheads', value: '₹ 9.4 Cr', icon: 'ti-building', sub: '8.0% of direct cost' },
          { label: 'Contingency', value: '₹ 2.5 Cr', icon: 'ti-shield-check', sub: '2.0% of base cost' },
          { label: 'Cost per sq ft', value: '₹ 3,821', delta: '-3.5% vs client', up: false, good: true, icon: 'ti-ruler-measure' },
        ],
        charts: [
          { title: 'Cost Build-up (₹ Cr)', kind: 'waterfall', categories: ['Material', 'Labour', 'Equipment', 'Subcontract', 'Overheads', 'Contingency', 'Total cost'], series: [{ name: 'Cost', data: [62.4, 24.6, 9.8, 21.2, 9.4, 2.5, 0] }], unit: '₹Cr', span: 2 },
          { title: 'Cost Mix', kind: 'donut', categories: ['Material', 'Labour', 'Equipment', 'Subcontract', 'Overheads', 'Contingency'], series: [{ name: '₹ Cr', data: [62.4, 24.6, 9.8, 21.2, 9.4, 2.5] }], unit: '₹Cr' },
        ],
        table: {
          title: 'Direct Cost by Work Package',
          columns: [
            { key: 'pkg', label: 'Work Package' },
            { key: 'material', label: 'Material', type: 'currency' },
            { key: 'labour', label: 'Labour', type: 'currency' },
            { key: 'equipment', label: 'Equipment', type: 'currency' },
            { key: 'sub', label: 'Subcontract', type: 'currency' },
            { key: 'total', label: 'Total', type: 'currency' },
          ],
          rows: [
            { pkg: 'Substructure', material: cr(8.6), labour: cr(3.2), equipment: cr(2.6), sub: cr(1.2), total: cr(15.6) },
            { pkg: 'Superstructure', material: cr(24.8), labour: cr(9.4), equipment: cr(4.2), sub: cr(0.8), total: cr(39.2) },
            { pkg: 'Masonry & Finishes', material: cr(16.2), labour: cr(8.1), equipment: cr(0.9), sub: cr(2.4), total: cr(27.6) },
            { pkg: 'MEP Services', material: cr(9.4), labour: cr(2.6), equipment: cr(0.8), sub: cr(12.6), total: cr(25.4) },
            { pkg: 'External Works', material: cr(3.4), labour: cr(1.3), equipment: cr(1.3), sub: cr(4.2), total: cr(10.2) },
          ],
        },
      }),
      page('Overhead', { type: 'lineitems', tax: 0, entity: 'tenderOverhead', title: `Site & Head-office Overheads — ${HV}` }),
      page('Risk', register('tenderRisk', { views: ['table', 'board'], boardField: 'rating' })),
      page('Profit', {
        type: 'analysis',
        title: `Profit & Bid Price — ${HV}`,
        kpis: [
          { label: 'Bid price', value: '₹ 142.9 Cr', icon: 'ti-file-dollar', sub: 'Client estimate ₹ 148.0 Cr' },
          { label: 'Estimated cost', value: '₹ 129.9 Cr', icon: 'ti-sum' },
          { label: 'Profit', value: '₹ 13.0 Cr', icon: 'ti-trending-up', sub: '10.0% mark-up on cost' },
          { label: 'Margin on bid', value: '9.1%', progress: 91, icon: 'ti-percentage', sub: 'Threshold 8.0%' },
          { label: 'Bid vs client estimate', value: '-3.4%', up: false, good: true, delta: '₹ 5.1 Cr below', icon: 'ti-arrows-diff' },
        ],
        charts: [
          { title: 'Bid Price Build-up (₹ Cr)', kind: 'waterfall', categories: ['Direct cost', 'Overheads', 'Contingency', 'Profit', 'Bid price'], series: [{ name: 'Value', data: [118.0, 9.4, 2.5, 13.0, 0] }], unit: '₹Cr', span: 2 },
          { title: 'Win Probability vs Mark-up', kind: 'line', categories: ['6%', '8%', '10%', '12%', '14%'], series: [{ name: 'Win probability', data: [62, 54, 46, 35, 24] }], unit: '%' },
        ],
        table: {
          title: 'Margin on Bids in Preparation',
          columns: [
            { key: 'tender', label: 'Tender', type: 'code' },
            { key: 'name', label: 'Tender Title' },
            { key: 'estimate', label: 'Client Estimate', type: 'currency' },
            { key: 'cost', label: 'Our Cost', type: 'currency' },
            { key: 'bid', label: 'Bid Price', type: 'currency' },
            { key: 'margin', label: 'Mark-up', type: 'percent' },
            { key: 'status', label: 'Status', type: 'status' },
          ],
          rows: [
            { tender: 'TND-001', name: 'Harbour View Hospital — Phase II', estimate: cr(148), cost: cr(129.9), bid: cr(142.9), margin: 10, status: 'Bid Preparation' },
            { tender: 'TND-002', name: 'Orbit Tech Park Phase III — Tower C & D', estimate: cr(176), cost: cr(152.4), bid: cr(169.2), margin: 11, status: 'Under Review' },
            { tender: 'TND-003', name: 'Meridian Logistics Park — Blocks A–F', estimate: cr(92), cost: cr(80.6), bid: cr(88.7), margin: 10, status: 'Bid Preparation' },
            { tender: 'TND-004', name: 'Pinnacle Heights — G+22 Towers', estimate: cr(134), cost: cr(118.2), bid: cr(128.8), margin: 9, status: 'Draft' },
            { tender: 'TND-010', name: 'ABC Grand — Luxury Apartments', estimate: cr(58), cost: cr(50.4), bid: cr(56.4), margin: 12, status: 'Bid Preparation' },
            { tender: 'TND-011', name: 'XYZ Riverfront Mall — Civil & Structure', estimate: cr(124), cost: cr(108.6), bid: cr(118.4), margin: 9, status: 'Under Review' },
            { tender: 'TND-020', name: 'XYZ Affordable Housing (480 units)', estimate: cr(54), cost: cr(48.9), bid: cr(52.3), margin: 7, status: 'Draft' },
          ],
        },
      }),
    ]),
    group('Submission', 'ti-send', [
      page('Draft', statusView('tender', 'Draft')),
      page('Under Review', statusView('tender', 'Under Review')),
      page('Submitted', statusView('tender', 'Submitted')),
      page('Won', statusView('tender', 'Won')),
      page('Lost', statusView('tender', 'Lost')),
    ]),
  ],
  dashboard: {
    flow: [
      { label: 'Open Tenders', value: '6 · ₹ 394 Cr' },
      { label: 'Deadlines', value: '5 closing in 15 days' },
      { label: 'Bid Value', value: '₹ 786 Cr in preparation' },
      { label: 'Win/Loss', value: '11 won · 21 lost (FY)' },
    ],
    kpis: [
      { label: 'Open Tenders', value: '6', delta: '+2', up: true, progress: 25, icon: 'ti-file-search', sub: 'Bid / no-bid decision pending' },
      { label: 'Closing Soon (15 days)', value: '5', delta: 'Next: 3 Oct', up: true, good: false, icon: 'ti-calendar-due' },
      { label: 'Bids in Preparation', value: '7', progress: 29, icon: 'ti-file-dollar', sub: '₹ 786 Cr estimated value' },
      { label: 'Submitted — Awaiting Result', value: '3', icon: 'ti-hourglass', sub: '₹ 220 Cr' },
      { label: 'Active Tender Value', value: '₹ 1,400 Cr', delta: '+18%', up: true, progress: 64, icon: 'ti-currency-rupee' },
      { label: 'Win Rate (FY)', value: '34%', delta: '+4 pts', up: true, progress: 34, icon: 'ti-trophy', sub: '11 won of 32 decided' },
    ],
    charts: [
      { title: 'Win / Loss by Month (FY 26-27)', kind: 'stacked', categories: ['Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep'], series: [{ name: 'Won', data: [1, 2, 2, 1, 3, 2] }, { name: 'Lost', data: [3, 4, 3, 4, 4, 3] }], span: 2 },
      { title: 'Tender Status Mix', kind: 'donut', categories: ['Open', 'Under Evaluation', 'Bid Preparation', 'Draft', 'Under Review', 'Submitted', 'Won', 'Lost'], series: [{ name: 'Tenders', data: [3, 3, 3, 2, 2, 3, 3, 3] }], tones: ['blue', 'blue', 'blue', 'gray', 'yellow', 'blue', 'green', 'red'] },
      { title: 'Active Tender Value by Sector (₹ Cr)', kind: 'hbar', categories: ['Commercial', 'Residential', 'Industrial', 'Institutional', 'Hospitality', 'Infrastructure'], series: [{ name: 'Value', data: [458, 358, 250, 198, 68, 68] }], unit: '₹Cr', span: 2 },
      { title: 'Win Rate (FY)', kind: 'gauge', series: [{ name: 'Win rate', data: [34] }], unit: '%', subtitle: 'Target 38%' },
    ],
    table: { entity: 'tender', title: 'Tender Register', columns: ['title', 'client', 'type', 'deadline', 'value', 'status'], limit: 8 },
    rail: [
      {
        kind: 'dates',
        title: 'Upcoming Deadlines',
        items: [
          { date: '2026-10-03', title: 'Orbit Tech Park Phase III', sub: 'TND-002 · ₹ 176 Cr · Under Review' },
          { date: '2026-10-06', title: 'XYZ Affordable Housing', sub: 'TND-020 · ₹ 54 Cr · Draft' },
          { date: '2026-10-08', title: 'Harbour View Hospital Ph II', sub: 'TND-001 · ₹ 148 Cr · Bid Preparation' },
          { date: '2026-10-10', title: 'XYZ Riverfront Mall', sub: 'TND-011 · ₹ 124 Cr · Under Review' },
          { date: '2026-10-14', title: 'Meridian Logistics Park', sub: 'TND-003 · ₹ 92 Cr · Bid Preparation' },
        ],
      },
      { kind: 'health', title: 'Bid Pipeline', items: [{ label: 'Bid Preparation', value: 3, tone: 'blue' }, { label: 'Under Review', value: 2, tone: 'yellow' }, { label: 'Draft', value: 2, tone: 'gray' }, { label: 'Submitted', value: 3, tone: 'blue' }, { label: 'Won (FY)', value: 11, tone: 'green' }, { label: 'Lost (FY)', value: 21, tone: 'red' }] },
      {
        kind: 'list',
        title: 'Recent Tender Activity',
        items: [
          { avatar: 'Naveen P', title: 'Naveen P uploaded Addendum 3', sub: 'TND-001 Harbour View Hospital Ph II', meta: '1 hour ago' },
          { avatar: 'Kavya R', title: 'Kavya R completed rate analysis', sub: 'TND-003 Meridian Logistics Park', meta: '3 hours ago' },
          { avatar: 'Siddharth Rao', title: 'Siddharth Rao sent bid for review', sub: 'TND-011 XYZ Riverfront Mall', meta: 'Yesterday' },
          { avatar: 'Priya M', title: 'Priya M marked TND-022 as No Bid', sub: 'Meridian Cold Storage Facility', meta: '2 days ago' },
        ],
      },
    ],
  },
  entities: [
    {
      id: 'tender',
      label: 'Tender',
      plural: 'Tenders',
      app: 'tender',
      codePrefix: 'TND',
      titleField: 'title',
      form: 'wizard',
      sections: [
        { id: 'basic', title: 'Basic Details', icon: 'ti-file-description' },
        { id: 'scope', title: 'Client & Scope', icon: 'ti-building-community' },
        { id: 'dates', title: 'Dates & Value', icon: 'ti-calendar-event' },
        { id: 'decision', title: 'Bid / No-Bid', icon: 'ti-gavel' },
      ],
      fields: [
        text('title', 'Tender Title', tenderData.map((t) => t[0]), { required: true, section: 'basic', list: true }),
        text('tenderNo', 'Tender Number', tenderData.map((t) => t[1]), { required: true, section: 'basic', list: true }),
        select('type', 'Tender Type', TENDER_TYPES, { required: true, section: 'basic', list: true }),
        select('category', 'Work Category', CATEGORIES, { section: 'basic' }),
        ref('client', 'Client', 'client', { required: true, section: 'scope', list: true }),
        text('location', 'Location', undefined, { section: 'scope' }),
        area('scope', 'Scope of Work', undefined, { section: 'scope' }),
        date('issueDate', 'Issue Date', undefined, { required: true, section: 'dates' }),
        date('preBid', 'Pre-bid Meeting', undefined, { section: 'dates', list: false }),
        date('deadline', 'Submission Deadline', undefined, { required: true, section: 'dates', list: true }),
        money('value', 'Estimated Value', undefined, { required: true, section: 'dates', list: true }),
        money('emd', 'EMD Amount', undefined, { section: 'dates', list: false }),
        money('bidPrice', 'Our Bid Price', undefined, { section: 'decision', list: false }),
        select('decision', 'Bid / No-Bid', ['Bid', 'No Bid', 'Under Evaluation'], { required: true, section: 'decision', list: false }),
        ref('owner', 'Tender Manager', 'employee', { section: 'decision', list: true }),
        pct('winProb', 'Win Probability', undefined, { section: 'decision', list: false }),
        area('rationale', 'Bid / No-Bid Rationale', undefined, { section: 'decision' }),
        status(TENDER_STATUS, { section: 'basic' }),
      ],
      rows: tenderRows,
    },
    {
      id: 'tenderType',
      label: 'Tender Type',
      plural: 'Tender Types',
      app: 'tender',
      codePrefix: 'TT',
      titleField: 'name',
      count: 9,
      fields: [
        text('name', 'Tender Type', TENDER_TYPES, { required: true }),
        select('basis', 'Contract Basis', ['Item Rate', 'Lump Sum', 'EPC / Turnkey', 'Percentage Rate', 'Cost Plus'], { gen: ['Item Rate', 'Item Rate', 'Item Rate', 'Cost Plus', 'Lump Sum', 'EPC / Turnkey', 'Item Rate', 'Lump Sum', 'Percentage Rate'] }),
        select('evaluation', 'Evaluation Method', ['L1 (Lowest Price)', 'QCBS (70:30)', 'Technical then L1', 'Negotiated'], { gen: ['L1 (Lowest Price)', 'Technical then L1', 'Technical then L1', 'Negotiated', 'QCBS (70:30)', 'QCBS (70:30)', 'L1 (Lowest Price)', 'Technical then L1', 'L1 (Lowest Price)'] }),
        pct('emdPct', 'EMD %', [1, 2]),
        num('validity', 'Bid Validity', [90, 180], { unit: 'days' }),
        num('tenders', 'Tenders (FY)', [1, 9]),
        status(['Active', 'Inactive'], { gen: ['Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Inactive'] }),
      ],
    },
    {
      id: 'tenderBoq',
      label: 'BOQ Item',
      plural: 'Tender BOQ',
      app: 'tender',
      codePrefix: 'TBQ',
      titleField: 'description',
      fields: [
        text('description', 'Description', boqData.map((b) => b[1]), { required: true }),
        select('section', 'BOQ Section', ['Earthwork', 'Concrete Works', 'Reinforcement', 'Masonry', 'Finishes', 'Waterproofing']),
        text('unit', 'Unit'),
        num('qty', 'BOQ Quantity'),
        money('rate', 'Quoted Rate'),
      ],
      rows: lines('TBQ', boqData),
    },
    {
      id: 'tenderQty',
      label: 'Take-off Line',
      plural: 'Bid Quantities',
      app: 'tender',
      codePrefix: 'TQ',
      titleField: 'description',
      fields: [
        text('description', 'Description', qtyData.map((q) => q[1]), { required: true }),
        select('section', 'Package', ['Substructure', 'Superstructure', 'Masonry & Finishes', 'External Works']),
        text('unit', 'Unit'),
        num('boqQty', 'Tender BOQ Qty'),
        num('qty', 'Take-off Qty'),
        money('rate', 'Estimated Rate'),
      ],
      rows: qtyData.map(([section, description, unit, boqQty, qty, rate], i) => ({ id: `TQ-${pad(i + 1)}`, code: `TQ-${pad(i + 1)}`, section, description, unit, boqQty, qty, rate })),
    },
    {
      id: 'tenderRate',
      label: 'Rate Component',
      plural: 'Rate Build-up',
      app: 'tender',
      codePrefix: 'RA',
      titleField: 'description',
      fields: [
        text('description', 'Component', rateData.map((r) => r[1]), { required: true }),
        select('section', 'Cost Head', ['Material', 'Labour', 'Equipment', 'Overhead']),
        text('unit', 'Unit'),
        num('qty', 'Constant per cum'),
        money('rate', 'Unit Rate'),
      ],
      rows: lines('RA', rateData),
    },
    {
      id: 'tenderOverhead',
      label: 'Overhead Item',
      plural: 'Overheads',
      app: 'tender',
      codePrefix: 'OH',
      titleField: 'description',
      fields: [
        text('description', 'Overhead Item', overheadData.map((o) => o[1]), { required: true }),
        select('section', 'Overhead Group', ['Site Staff', 'Site Facilities', 'Insurance & Bonds', 'Head Office']),
        text('unit', 'Unit'),
        num('qty', 'Quantity'),
        money('rate', 'Rate'),
      ],
      rows: lines('OH', overheadData),
    },
    {
      id: 'tenderRisk',
      label: 'Bid Risk',
      plural: 'Bid Risks',
      app: 'tender',
      codePrefix: 'BR',
      titleField: 'title',
      count: 14,
      form: 'page',
      fields: [
        text('title', 'Risk', ['Steel price escalation beyond 5%', 'Rock strata deeper than soil report', 'Monsoon impact on substructure', 'Delay in drawings for MEP coordination', 'Unrealistic 20-month completion period', 'Liquidated damages uncapped', 'Payment delays — 60-day credit period', 'Specialised medical gas works', 'Dewatering in high water table', 'Labour availability in Visakhapatnam', 'No price variation clause for cement', 'Performance guarantee at 10%', 'Scope ambiguity — external works', 'Client-supplied materials delay'], { required: true }),
        ref('tender', 'Tender', 'tender', { required: true }),
        select('category', 'Category', ['Commercial', 'Technical', 'Contractual', 'Schedule', 'Site', 'Resource']),
        select('probability', 'Probability', ['Rare', 'Unlikely', 'Possible', 'Likely', 'Almost Certain']),
        select('impact', 'Impact', ['Minor', 'Moderate', 'Major', 'Severe']),
        select('rating', 'Risk Rating', ['Low', 'Medium', 'High', 'Critical'], { gen: ['High', 'High', 'Medium', 'Medium', 'Critical', 'High', 'Medium', 'Medium', 'Medium', 'Low', 'High', 'Medium', 'Low', 'Low'] }),
        money('costImpact', 'Cost Impact', [1500000, 28000000]),
        area('mitigation', 'Mitigation / Pricing Treatment', ['Priced 3% escalation; bulk booking with Shree Balaji Steel Traders.', 'Provisional quantity for rock excavation added.', 'Substructure sequenced before monsoon; rain protection priced.', 'Clarification raised in pre-bid query no. 14.', 'Qualified in bid — completion period 24 months.']),
        ref('owner', 'Risk Owner', 'employee'),
        status(['Open', 'Under Review', 'Accepted', 'Closed'], { gen: ['Open', 'Open', 'Accepted', 'Under Review', 'Open', 'Under Review', 'Accepted', 'Open', 'Accepted', 'Closed', 'Open', 'Under Review', 'Closed', 'Accepted'] }),
      ],
    },
  ],
};
