import { area, date, docs, f, fieldView, group, lineItems, money, num, page, pct, ref, register, select, status, text } from '../dsl';
import type { AppConfig, Row } from '../types';

const PROJECTS = ['Skyline Apartments', 'Riverside Villas', 'Greenfield Township', 'Metro Office Tower', 'Lakeview Residency', 'Orbit Tech Park Phase II', 'Harbour View Hospital', 'Sunrise Business Hotel'];
const TRADES = ['Mason', 'Bar Bender', 'Shuttering Carpenter', 'Helper', 'Electrician', 'Plumber', 'Welder', 'Scaffolder', 'Painter', 'Tile Layer'];

/* Salary structure — Site Engineer, Grade E2 (monthly CTC build-up) */
const salaryRows: Row[] = (
  [
    ['Basic Salary', 'Fixed Earnings', 'Month', 1, 24000],
    ['House Rent Allowance (40% of Basic)', 'Fixed Earnings', 'Month', 1, 9600],
    ['Conveyance Allowance', 'Fixed Earnings', 'Month', 1, 1600],
    ['Special Allowance', 'Fixed Earnings', 'Month', 1, 7450],
    ['Medical Allowance', 'Fixed Earnings', 'Month', 1, 1250],
    ['Leave Travel Allowance', 'Fixed Earnings', 'Month', 1, 2000],
    ['Site Allowance (outstation posting)', 'Allowances', 'Month', 1, 4500],
    ['Mobile & Internet Reimbursement', 'Allowances', 'Month', 1, 800],
    ['Night Shift Allowance (avg. 4 shifts)', 'Allowances', 'Shift', 4, 350],
    ['Performance Bonus (monthly accrual)', 'Variable Pay', 'Month', 1, 2500],
    ['Attendance Incentive', 'Variable Pay', 'Month', 1, 1000],
    ['Employer PF (12% of Basic)', 'Employer Contributions', 'Month', 1, 2880],
    ['EPF Admin Charges (0.5%)', 'Employer Contributions', 'Month', 1, 120],
    ['Gratuity Provision (4.81%)', 'Employer Contributions', 'Month', 1, 1154],
    ['Group Mediclaim Premium', 'Employer Contributions', 'Month', 1, 650],
    ['Group Personal Accident Cover', 'Employer Contributions', 'Month', 1, 180],
  ] as [string, string, string, number, number][]
).map(([description, section, unit, qty, rate], i) => ({ id: `SC-${String(i + 1).padStart(3, '0')}`, code: `SC-${String(i + 1).padStart(3, '0')}`, description, section, unit, qty, rate }));

/* Wage calculation — Skyline Apartments, 1–30 Sep 2026 (26 working days) */
const wageRows: Row[] = (
  [
    ['Masons — Tower A & B', 'Skilled', 48, 'Man-day', 1152, 1050],
    ['Bar Benders — Tower B slab gang', 'Skilled', 36, 'Man-day', 864, 1000],
    ['Shuttering Carpenters — aluminium formwork', 'Skilled', 42, 'Man-day', 1008, 1000],
    ['Tile Layers — Tower A finishes', 'Skilled', 20, 'Man-day', 480, 1000],
    ['Electricians — conduiting & wiring', 'Skilled', 14, 'Man-day', 336, 1100],
    ['Plumbers — shafts & toilets', 'Skilled', 10, 'Man-day', 240, 1050],
    ['Welders — MS works & hoist bay', 'Skilled', 6, 'Man-day', 144, 1150],
    ['Waterproofing Applicators', 'Skilled', 8, 'Man-day', 192, 950],
    ['Mason Helpers', 'Semi-skilled', 40, 'Man-day', 960, 820],
    ['Scaffolders', 'Semi-skilled', 18, 'Man-day', 432, 850],
    ['Painters — primer & putty', 'Semi-skilled', 16, 'Man-day', 384, 850],
    ['General Helpers — material shifting', 'Unskilled', 120, 'Man-day', 2880, 700],
    ['Housekeeping & Debris Removal', 'Unskilled', 12, 'Man-day', 288, 650],
    ['Watch & Ward', 'Unskilled', 8, 'Man-day', 240, 700],
    ['Overtime — slab pour cycles (double rate)', 'Overtime & Allowances', 86, 'Hour', 1120, 190],
    ['Night Shift Allowance', 'Overtime & Allowances', 42, 'Shift', 420, 100],
    ['Attendance Bonus (26/26 days)', 'Overtime & Allowances', 212, 'Worker', 212, 500],
  ] as [string, string, number, string, number, number][]
).map(([description, section, workers, unit, qty, rate], i) => ({ id: `WG-${String(i + 1).padStart(3, '0')}`, code: `WG-${String(i + 1).padStart(3, '0')}`, description, section, workers, unit, qty, rate }));

const WORKER_NAMES = ['Ramesh Kumar', 'Muthu Pandi', 'Rajkumar Yadav', 'Sunil Mahato', 'Anbu Selvan', 'Karuppasamy M', 'Bablu Kumar', 'Manikandan R', 'Suresh Oraon', 'Palani Murugan', 'Ajay Paswan', 'Kannan R', 'Dilip Mandal', 'Velu Samy', 'Raju Munda', 'Siva Kumar', 'Pintu Das', 'Arumugam P', 'Santosh Singh', 'Mariappan S', 'Ganesan K', 'Birendra Tudu', 'Selvaraj A', 'Ashok Rai'];

export const workforceApp: AppConfig = {
  id: 'workforce',
  name: 'Workforce',
  icon: 'ti-users',
  description: 'Employees, workers, allocation, attendance, shifts, leave, overtime and payroll',
  menus: [
    group('Employee Management', 'ti-id-badge-2', [
      page('Employee Master', register('employee', { views: ['table', 'board'] })),
      page('Personal Details', fieldView('employee', 'phone')),
      page('Employment Details', fieldView('employee', 'designation')),
      page('Department', register('wfDepartment')),
      page('Designation', register('wfDesignation')),
      page('Joining / Exit', register('wfJoiningExit', { tabs: { field: 'event', values: ['Joining', 'Exit'] }, views: ['table', 'calendar'], dateField: 'date' })),
      page('Skills & Qualifications', register('wfSkill', { tabs: { field: 'type', values: ['Skill', 'Certification', 'Qualification', 'Licence'] } })),
      page('Documents', docs(['Offer & Appointment Letters', 'ID Proofs (Aadhaar / PAN)', 'Educational Certificates', 'Experience & Relieving Letters', 'PF & ESI Nominations', 'Medical Fitness', 'Bank Details', 'Exit & Full-and-Final'], 'Offer & Appointment Letters', 'Employee Documents')),
    ]),
    group('Worker Management', 'ti-helmet', [
      page('Contract Workers', { type: 'status', entity: 'wfWorker', field: 'category', value: 'Contract Worker' }),
      page('Labourers', { type: 'status', entity: 'wfWorker', field: 'category', value: 'Labourer' }),
      page('Labour Contractors', register('wfLabourContractor')),
      page('Worker Registration', {
        type: 'wizard',
        title: 'Worker Registration',
        entity: 'wfWorker',
        submitLabel: 'Register Worker',
        steps: [
          {
            title: 'Worker Details',
            icon: 'ti-user',
            note: 'Capture details exactly as per Aadhaar. Workers below 18 years cannot be registered (Child Labour Act).',
            fields: [
              text('name', 'Worker Name', undefined, { required: true }),
              select('gender', 'Gender', ['Male', 'Female', 'Other']),
              date('dob', 'Date of Birth', undefined, { required: true }),
              f('phone', 'Mobile Number', 'phone'),
              text('aadhaar', 'Aadhaar Number', undefined, { placeholder: 'XXXX XXXX XXXX', required: true }),
              text('native', 'Native State', undefined, { placeholder: 'e.g. Jharkhand' }),
            ],
          },
          {
            title: 'Employment',
            icon: 'ti-briefcase',
            fields: [
              select('category', 'Worker Category', ['Contract Worker', 'Labourer'], { required: true }),
              select('trade', 'Trade', TRADES, { required: true }),
              select('skill', 'Wage Category', ['Skilled', 'Semi-skilled', 'Unskilled'], { required: true }),
              ref('contractor', 'Labour Contractor', 'wfLabourContractor'),
              ref('project', 'Project', 'project', { required: true }),
              money('wage', 'Daily Wage', undefined, { hint: 'As per TN minimum wages notification 2026' }),
            ],
          },
          {
            title: 'Statutory & Bank',
            icon: 'ti-building-bank',
            fields: [
              text('uan', 'UAN (EPF)', undefined, { placeholder: '12-digit UAN' }),
              text('esic', 'ESIC IP Number'),
              text('bocw', 'BOCW Registration No.'),
              text('bank', 'Bank Account No.'),
              text('ifsc', 'IFSC Code'),
            ],
          },
          {
            title: 'Documents & Induction',
            icon: 'ti-clipboard-check',
            upload: ['Aadhaar card', 'Passport photo', 'Bank passbook / cancelled cheque', 'Medical fitness certificate'],
            checklist: ['Safety induction completed (2 hrs)', 'PPE issued — helmet, shoes, jacket', 'Biometric enrolment done', 'Labour camp accommodation allotted', 'Emergency contact recorded'],
          },
        ],
      }),
    ]),
    group('Workforce Allocation', 'ti-arrows-exchange', [
      page('Project Assignment', register('wfProjectAssign', { views: ['table', 'board'] })),
      page('Site Assignment', register('wfSiteAssign')),
      page('Role Assignment', register('wfRoleAssign')),
      page('Transfer', {
        type: 'wizard',
        title: 'Employee Transfer',
        submitLabel: 'Submit Transfer Request',
        steps: [
          {
            title: 'Employee & Current Posting',
            icon: 'ti-user',
            fields: [
              ref('employee', 'Employee', 'employee', { required: true }),
              ref('fromProject', 'Current Project', 'project', { required: true }),
              ref('fromSite', 'Current Site', 'site'),
              text('currentRole', 'Current Role', undefined, { placeholder: 'e.g. Site Engineer — Tower A' }),
            ],
          },
          {
            title: 'New Posting',
            icon: 'ti-map-pin',
            fields: [
              ref('toProject', 'Transfer To Project', 'project', { required: true }),
              ref('toSite', 'Transfer To Site', 'site'),
              text('newRole', 'New Role'),
              date('effective', 'Effective Date', undefined, { required: true }),
              select('type', 'Transfer Type', ['Permanent', 'Temporary (deputation)', 'Project closure']),
              area('reason', 'Reason for Transfer'),
            ],
          },
          {
            title: 'Handover',
            icon: 'ti-clipboard-check',
            checklist: ['Pending work handed over to reliever', 'Site store items & tools returned', 'Petty cash settled', 'Documents & drawings handed to document controller', 'Travel & relocation allowance approved'],
          },
          {
            title: 'Approval',
            icon: 'ti-route',
            note: 'Routing: Current Project Manager → Receiving Project Manager → HR Manager (Meena Iyer).',
            fields: [ref('approver', 'Approving Manager', 'employee'), area('remarks', 'Remarks')],
          },
        ],
      }),
    ]),
    group('Attendance', 'ti-calendar-check', [
      page('Daily Attendance', {
        type: 'calendar',
        title: 'Daily Attendance — Workers (biometric)',
        mode: 'grid',
        rowsEntity: 'wfWorker',
        days: 14,
        codes: [
          { code: 'P', label: 'Present', tone: 'green' },
          { code: 'A', label: 'Absent', tone: 'red' },
          { code: 'L', label: 'Late', tone: 'yellow' },
          { code: 'H', label: 'Half Day', tone: 'yellow' },
          { code: 'WO', label: 'Weekly Off', tone: 'gray' },
          { code: 'LV', label: 'Leave', tone: 'gray' },
        ],
        weights: [88, 3, 4, 2, 0, 3],
      }),
      page('Shift', {
        type: 'calendar',
        title: 'Shift Roster — Staff',
        mode: 'grid',
        rowsEntity: 'employee',
        days: 14,
        codes: [
          { code: 'G', label: 'General (9–6)', tone: 'blue' },
          { code: 'A', label: 'First Shift (6–2)', tone: 'green' },
          { code: 'B', label: 'Second Shift (2–10)', tone: 'yellow' },
          { code: 'C', label: 'Night Shift (10–6)', tone: 'red' },
          { code: 'OFF', label: 'Weekly Off', tone: 'gray' },
        ],
        weights: [10, 4, 3, 2, 0],
      }),
      page('Overtime', register('wfOvertime', { tabs: { field: 'status', values: ['Pending', 'Approved', 'Rejected'] } })),
      page('Leave', register('wfLeave', { tabs: { field: 'status', values: ['Pending', 'Approved', 'Rejected'] }, views: ['table', 'calendar'], dateField: 'from' })),
    ]),
    group('Payroll', 'ti-cash', [
      page('Salary Structure', lineItems('wfSalaryComponent', 'Salary Structure — Site Engineer (Grade E2) · Monthly CTC', undefined, 0)),
      page('Wage Calculation', lineItems('wfWageLine', 'Wage Calculation — Skyline Apartments · September 2026', ['workers'], 0)),
      page('Payroll Run', {
        type: 'wizard',
        title: 'Payroll Run',
        submitLabel: 'Submit Payroll for Approval',
        steps: [
          {
            title: 'Period & Scope',
            icon: 'ti-calendar',
            fields: [
              select('period', 'Payroll Period', ['September 2026', 'August 2026', 'October 2026'], { required: true }),
              select('group', 'Pay Group', ['All — Staff & Workers', 'Staff — Monthly', 'Direct Workers — Monthly', 'Contract Workers — via contractors'], { required: true }),
              f('projects', 'Projects', 'multiselect', { options: PROJECTS }),
              date('payDate', 'Pay Date', undefined, { required: true }),
            ],
          },
          {
            title: 'Attendance Lock',
            icon: 'ti-lock',
            note: 'Attendance for 1–30 Sep 2026: 1,842 persons · 93.1% average · 4,860 OT hours approved.',
            checklist: ['Biometric attendance imported for 1–30 Sep', 'Leave applications approved / rejected', 'Overtime approved by site managers', 'Loss-of-pay days confirmed (38 days)', 'Attendance locked by HR — no further edits'],
          },
          {
            title: 'Calculation',
            icon: 'ti-calculator',
            lines: {
              columns: ['Pay Group', 'Headcount', 'Gross Earnings (₹)', 'Overtime (₹)', 'Total (₹)'],
              rows: [
                ['Staff — Monthly', 312, 29648000, 0, 29648000],
                ['Direct Workers', 610, 14620000, 392000, 15012000],
                ['Contract Workers', 920, 18960000, 580000, 19540000],
                ['Total', 1842, 63228000, 972000, 64200000],
              ],
            },
          },
          {
            title: 'Deductions & Contributions',
            icon: 'ti-receipt-tax',
            lines: {
              columns: ['Component', 'Basis', 'Employee (₹)', 'Employer (₹)', 'Total (₹)'],
              rows: [
                ['Provident Fund (EPF)', '12% of Basic (capped ₹15,000)', 2840000, 2840000, 5680000],
                ['ESI', '0.75% / 3.25% of gross ≤ ₹21,000', 186000, 806000, 992000],
                ['Professional Tax', 'TN half-yearly slab', 368400, 0, 368400],
                ['TDS on Salary', 'u/s 192 — staff only', 1875000, 0, 1875000],
                ['Labour Welfare Fund', 'TN LWF', 3684, 7368, 11052],
                ['Salary Advance Recovery', 'As per schedule', 412000, 0, 412000],
              ],
            },
          },
          {
            title: 'Approval',
            icon: 'ti-route',
            note: 'Net payable ₹ 5.66 Cr · variance vs August +2.8% (headcount +46, OT +640 hrs).',
            checklist: ['Variance vs previous month reviewed', 'Bank advice file generated (HDFC salary account)', 'Contractor wage register cross-checked', 'Approved by HR Manager — Meena Iyer', 'Released by Finance Manager — Gayathri S'],
          },
        ],
      }),
      page('Deductions', register('wfDeduction')),
      page('Contributions', register('wfContribution', { tabs: { field: 'scheme', values: ['EPF', 'ESI', 'Professional Tax', 'Labour Welfare Fund', 'BOCW Cess'] } })),
      page('Payslip', {
        type: 'print',
        entity: 'employee',
        docTitle: 'Payslip — September 2026',
        lines: {
          columns: ['Earnings', 'Amount (₹)', 'Deductions', 'Amount (₹)'],
          rows: [
            ['Basic Salary', 24000, 'Provident Fund (12%)', 2880],
            ['House Rent Allowance', 9600, 'Professional Tax', 208],
            ['Conveyance Allowance', 1600, 'TDS (u/s 192)', 1850],
            ['Special Allowance', 7450, 'Salary Advance Recovery', 2000],
            ['Site Allowance', 4500, 'Canteen', 600],
            ['Medical Allowance', 1250, '', ''],
            ['Leave Travel Allowance', 2000, '', ''],
            ['Night Shift Allowance (4 shifts)', 1400, '', ''],
          ],
        },
        totals: [
          { label: 'Gross Earnings', value: '₹ 51,800' },
          { label: 'Total Deductions', value: '₹ 7,538' },
          { label: 'Net Pay', value: '₹ 44,262', bold: true },
        ],
        signatures: ['Prepared by (HR)', 'Verified by (Finance)', 'Employee Signature'],
      }),
    ]),
  ],
  dashboard: {
    flow: [
      { label: 'Workforce', value: '1,842 (312 staff)' },
      { label: 'Present today', value: '1,720 · 93.4%' },
      { label: 'Overtime', value: '4,860 hrs (Sep)' },
      { label: 'Leave', value: '14 pending' },
      { label: 'Payroll', value: '₹ 6.42 Cr (Sep)' },
    ],
    kpis: [
      { label: 'Total Workforce', value: '1,842', delta: '+46', up: true, sub: '312 staff · 1,530 workers', progress: 92, icon: 'ti-users' },
      { label: 'Attendance Today', value: '93.4%', delta: '+0.8 pts', up: true, progress: 93, icon: 'ti-user-check' },
      { label: 'Overtime (Sep)', value: '4,860 hrs', delta: '+15%', up: true, good: false, progress: 61, icon: 'ti-clock' },
      { label: 'Payroll (Sep)', value: '₹ 6.42 Cr', delta: '+2.8%', up: true, good: false, progress: 70, icon: 'ti-cash' },
      { label: 'Leave Requests Pending', value: '14', sub: '6 older than 3 days', icon: 'ti-hourglass' },
    ],
    charts: [
      { title: 'Attendance Trend — Last 14 Days', kind: 'line', categories: ['16', '17', '18', '19', '20', '22', '23', '24', '25', '26', '27', '28', '29'], series: [{ name: 'Attendance %', data: [92.1, 93.0, 91.4, 92.8, 93.6, 90.8, 92.5, 93.1, 94.0, 93.8, 91.9, 92.7, 93.4] }], unit: '%', span: 2 },
      { title: 'Workforce Mix', kind: 'donut', categories: ['Staff', 'Direct Workers', 'Contract Workers'], series: [{ name: 'Headcount', data: [312, 610, 920] }], subtitle: '1,842 total' },
      { title: 'Workforce by Project', kind: 'stacked', categories: ['Skyline', 'Riverside', 'Greenfield', 'Metro Tower', 'Lakeview', 'Orbit TP', 'Harbour View', 'Sunrise'], series: [{ name: 'Staff', data: [58, 32, 44, 52, 28, 24, 26, 22] }, { name: 'Workers', data: [412, 186, 264, 338, 142, 96, 158, 121] }], span: 2 },
      { title: 'Payroll Cost (₹ Cr)', kind: 'bar', categories: ['Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep'], series: [{ name: 'Payroll', data: [5.84, 5.96, 6.08, 6.15, 6.24, 6.42] }], unit: '₹Cr' },
    ],
    table: { entity: 'employee', title: 'Employees', columns: ['name', 'designation', 'department', 'site', 'attendance', 'status'], limit: 8 },
    rail: [
      { kind: 'health', title: 'Attendance Today', items: [{ label: 'Present', value: 1720, tone: 'green' }, { label: 'Late', value: 27, tone: 'yellow' }, { label: 'Absent', value: 54, tone: 'red' }, { label: 'On Leave', value: 41, tone: 'gray' }] },
      {
        kind: 'dates',
        title: 'Statutory Due Dates',
        items: [
          { date: '2026-10-07', title: 'TDS on salary — deposit', sub: 'September 2026' },
          { date: '2026-10-15', title: 'EPF ECR & challan', sub: '₹ 56.8 L · 1,842 members' },
          { date: '2026-10-15', title: 'ESI contribution', sub: '₹ 9.9 L' },
          { date: '2026-10-31', title: 'Professional Tax — half-yearly', sub: 'Greater Chennai Corporation' },
        ],
      },
      {
        kind: 'list',
        title: 'Recent Activities',
        items: [
          { avatar: 'Meena Iyer', title: 'Meena Iyer locked September attendance', sub: 'All projects', meta: '1 hour ago' },
          { avatar: 'Aishwarya L', title: '24 workers registered', sub: 'Greenfield Township · Kaveri Labour Agency', meta: '3 hours ago' },
          { avatar: 'Senthil Kumar', title: 'OT approved — 186 hrs', sub: 'Skyline Apartments · slab pour L14', meta: 'Yesterday' },
          { avatar: 'Ganesh T', title: 'Transfer request raised', sub: 'Dinesh M → Metro Office Tower', meta: '2 days ago', status: 'Pending' },
        ],
      },
    ],
  },
  entities: [
    {
      id: 'wfDepartment',
      label: 'Department',
      plural: 'Departments',
      app: 'workforce',
      codePrefix: 'DEP',
      titleField: 'name',
      count: 16,
      fields: [
        text('name', 'Department', ['Projects', 'Execution', 'Planning', 'Contracts & QS', 'Finance', 'Human Resources', 'Procurement', 'Stores', 'Plant & Machinery', 'HSE', 'Quality', 'MEP', 'Design', 'Business Development', 'Estimation', 'Land & Legal'], { required: true }),
        select('division', 'Division', ['Operations', 'Commercial', 'Support'], { gen: ['Operations', 'Operations', 'Operations', 'Commercial', 'Support', 'Support', 'Commercial', 'Operations', 'Operations', 'Operations', 'Operations', 'Operations', 'Operations', 'Commercial', 'Commercial', 'Support'] }),
        ref('head', 'Department Head', 'employee'),
        text('costCenter', 'Cost Centre', ['CC-PRJ', 'CC-EXE', 'CC-PLN', 'CC-CQS', 'CC-FIN', 'CC-HRD', 'CC-PRC', 'CC-STR', 'CC-PNM', 'CC-HSE', 'CC-QAC', 'CC-MEP', 'CC-DES', 'CC-BDV', 'CC-EST', 'CC-LGL']),
        num('staff', 'Staff Strength', [4, 64]),
        text('location', 'Location', ['Head Office — Chennai', 'All sites', 'Head Office — Chennai', 'Head Office — Chennai', 'Head Office — Chennai', 'Head Office — Chennai', 'Head Office — Chennai', 'All sites', 'Central yard — Sriperumbudur', 'All sites', 'All sites', 'All sites', 'Head Office — Chennai', 'Head Office — Chennai', 'Head Office — Chennai', 'Head Office — Chennai']),
        status(['Active', 'Inactive'], { gen: ['Active'] }),
      ],
    },
    {
      id: 'wfDesignation',
      label: 'Designation',
      plural: 'Designations',
      app: 'workforce',
      codePrefix: 'DSG',
      titleField: 'name',
      count: 20,
      fields: [
        text('name', 'Designation', ['Project Manager', 'Site Manager', 'Site Engineer', 'Planning Engineer', 'Quantity Surveyor', 'Billing Engineer', 'Safety Officer', 'QA/QC Engineer', 'Store Keeper', 'Foreman', 'Surveyor', 'Equipment Manager', 'Crane Operator', 'Excavator Operator', 'Electrical Engineer', 'MEP Engineer', 'Accounts Executive', 'HR Executive', 'Document Controller', 'Architect'], { required: true }),
        text('department', 'Department', ['Projects', 'Execution', 'Execution', 'Planning', 'Contracts & QS', 'Contracts & QS', 'HSE', 'Quality', 'Stores', 'Execution', 'Execution', 'Plant & Machinery', 'Plant & Machinery', 'Plant & Machinery', 'MEP', 'MEP', 'Finance', 'Human Resources', 'Projects', 'Design']),
        select('grade', 'Grade', ['M3', 'M2', 'M1', 'E3', 'E2', 'E1', 'S2', 'S1'], { gen: ['M3', 'M2', 'E2', 'E2', 'E2', 'E1', 'E1', 'E2', 'S2', 'S1', 'S2', 'M1', 'S1', 'S1', 'E2', 'E2', 'E1', 'E1', 'S2', 'E3'] }),
        select('role', 'Role Type', ['Managerial', 'Engineering', 'Supervisory', 'Operator', 'Support'], { gen: ['Managerial', 'Managerial', 'Engineering', 'Engineering', 'Engineering', 'Engineering', 'Supervisory', 'Engineering', 'Support', 'Supervisory', 'Engineering', 'Managerial', 'Operator', 'Operator', 'Engineering', 'Engineering', 'Support', 'Support', 'Support', 'Engineering'] }),
        text('band', 'Salary Band (p.a.)', ['₹ 22–32 L', '₹ 14–20 L', '₹ 6–9 L', '₹ 6–9 L', '₹ 6–10 L', '₹ 4.5–7 L', '₹ 4.5–7 L', '₹ 6–9 L', '₹ 3–4.5 L', '₹ 2.8–4 L', '₹ 3.5–5 L', '₹ 10–15 L', '₹ 3–4.2 L', '₹ 2.8–4 L', '₹ 6–9 L', '₹ 6–10 L', '₹ 4–6 L', '₹ 4–6 L', '₹ 3–4.5 L', '₹ 8–12 L']),
        num('headcount', 'Headcount', [2, 42]),
        status(['Active', 'Inactive'], { gen: ['Active'] }),
      ],
    },
    {
      id: 'wfJoiningExit',
      label: 'Joining / Exit Event',
      plural: 'Joining & Exit Events',
      app: 'workforce',
      codePrefix: 'JX',
      titleField: 'name',
      count: 16,
      form: 'page',
      fields: [
        text('name', 'Employee Name', ['Harini S', 'Vikram Raj', 'Nithya Prakash', 'Abdul Rahman', 'Sowmya K', 'Pradeep V', 'Janani M', 'Rakesh Gupta', 'Mohan Das', 'Keerthi Vasan', 'Sangeetha R', 'Ashwin Kumar', 'Fathima B', 'Lokesh N', 'Revathi P', 'Tamil Selvan'], { required: true }),
        select('event', 'Event', ['Joining', 'Exit'], { gen: ['Joining', 'Joining', 'Exit', 'Joining', 'Exit', 'Joining', 'Joining', 'Exit', 'Exit', 'Joining', 'Joining', 'Exit', 'Joining', 'Joining', 'Exit', 'Joining'] }),
        text('designation', 'Designation', ['Site Engineer', 'Planning Engineer', 'Quantity Surveyor', 'Safety Officer', 'Site Engineer', 'MEP Engineer', 'HR Executive', 'Store Keeper', 'Foreman', 'Billing Engineer', 'Accounts Executive', 'Surveyor', 'Document Controller', 'QA/QC Engineer', 'Site Engineer', 'Crane Operator']),
        ref('site', 'Site', 'site'),
        date('date', 'Joining / Last Working Date', [-45, 30]),
        select('reason', 'Type / Reason', ['New hire', 'Replacement', 'Resignation', 'Retirement', 'Contract end', 'Campus hire'], { gen: ['New hire', 'Campus hire', 'Resignation', 'Replacement', 'Resignation', 'New hire', 'New hire', 'Contract end', 'Retirement', 'Campus hire', 'Replacement', 'Resignation', 'New hire', 'New hire', 'Resignation', 'Replacement'] }),
        select('clearance', 'Onboarding / Exit Clearance', ['Documents pending', 'IT & assets issued', 'No-dues in progress', 'Full & final settled']),
        area('remarks', 'Remarks', ['Offer accepted; joining kit ready.', 'Relieving letter to be issued after F&F.', 'Background verification in progress.', 'Knowledge transfer to reliever completed.']),
        status(['Pending', 'In Progress', 'Completed'], { gen: ['Completed', 'Pending', 'In Progress', 'Completed', 'Completed', 'Pending', 'In Progress', 'Completed', 'Completed', 'Pending', 'Completed', 'In Progress', 'Pending', 'Pending', 'In Progress', 'Completed'] }),
      ],
    },
    {
      id: 'wfSkill',
      label: 'Skill / Qualification',
      plural: 'Skills & Qualifications',
      app: 'workforce',
      codePrefix: 'SKL',
      titleField: 'skill',
      count: 20,
      fields: [
        text('skill', 'Skill / Qualification', ['Primavera P6 — Advanced', 'AutoCAD 2D/3D', 'Tower crane operation', 'Scaffolding inspector', 'NEBOSH IGC', 'IOSH Managing Safely', 'Total station surveying', 'Quantity take-off (CostX)', 'B.E. Civil Engineering', 'M.Tech Structural Engineering', 'Diploma in Civil Engineering', 'ITI Electrician', 'Welding — 6G certified', 'First Aid & CPR', 'Work at Height — rescue', 'Revit MEP', 'Tally Prime & GST', 'ISO 9001 Internal Auditor', 'Heavy vehicle driving licence', 'MS Project'], { required: true }),
        ref('employee', 'Employee', 'employee', { required: true }),
        select('type', 'Type', ['Skill', 'Certification', 'Qualification', 'Licence'], { gen: ['Skill', 'Skill', 'Licence', 'Certification', 'Certification', 'Certification', 'Skill', 'Skill', 'Qualification', 'Qualification', 'Qualification', 'Qualification', 'Certification', 'Certification', 'Certification', 'Skill', 'Skill', 'Certification', 'Licence', 'Skill'] }),
        select('level', 'Proficiency', ['Basic', 'Intermediate', 'Advanced', 'Expert']),
        text('issuer', 'Issued By', ['Oracle', 'Autodesk', 'DGMS / State licensing', 'CIDC', 'NEBOSH', 'IOSH', 'In-house', 'Exactal', 'Anna University', 'IIT Madras', 'DOTE Tamil Nadu', 'NCVT', 'AWS / IIW', 'St John Ambulance', 'NSC India', 'Autodesk', 'Tally Education', 'TÜV SÜD', 'RTO Chennai', 'Microsoft']),
        date('validTill', 'Valid Till', [-15, 900]),
        status(['Valid', 'Expiring Soon', 'Expired'], { gen: ['Valid', 'Valid', 'Expiring Soon', 'Valid', 'Valid', 'Expired', 'Valid', 'Valid', 'Valid', 'Valid', 'Valid', 'Valid', 'Expiring Soon', 'Valid', 'Expired', 'Valid', 'Valid', 'Valid', 'Expiring Soon', 'Valid'] }),
      ],
    },
    {
      id: 'wfLabourContractor',
      label: 'Labour Contractor',
      plural: 'Labour Contractors',
      app: 'workforce',
      codePrefix: 'LC',
      titleField: 'name',
      count: 12,
      form: 'page',
      fields: [
        text('name', 'Labour Contractor', ['Murugan Manpower Services', 'Sri Vinayaka Labour Contractors', 'Jharkhand Workforce Suppliers', 'Annai Construction Labour', 'Bihar Skilled Manpower Co', 'Kaveri Labour Agency', 'Om Sai Manpower', 'Pandian Labour Contractors', 'Ganga Infra Manpower', 'Velmurugan Gangs', 'Northeast Labour Solutions', 'Selvi Enterprises'], { required: true }),
        text('contact', 'Contact Person', ['K. Murugan', 'Vinayagam S', 'Ranjit Mahato', 'Selvi Annadurai', 'Manoj Yadav', 'Kaveri Raman', 'Sai Prasad', 'Pandian M', 'Sanjay Singh', 'Velmurugan K', 'Bikash Gogoi', 'Selvi R']),
        f('phone', 'Phone', 'phone'),
        select('trade', 'Specialisation', ['Masonry & Plaster', 'Steel Fixing', 'Shuttering', 'General Labour', 'Finishing', 'MEP Helpers']),
        num('workers', 'Workers Supplied', [40, 260]),
        text('licence', 'CLRA Licence No.', ['CLRA/TN/2025/0412', 'CLRA/TN/2024/1187', 'CLRA/TN/2025/0098', 'CLRA/TN/2023/2231', 'CLRA/KA/2025/0564', 'CLRA/TN/2025/0733', 'CLRA/TG/2024/0321', 'CLRA/TN/2024/0918', 'CLRA/KA/2024/1402', 'CLRA/TN/2025/0147', 'CLRA/AP/2025/0266', 'CLRA/TN/2024/0659']),
        date('licenceExpiry', 'Licence Valid Till', [20, 540]),
        ref('project', 'Primary Project', 'project'),
        pct('compliance', 'Wage Compliance', [82, 100]),
        status(['Active', 'Under Review', 'Inactive'], { gen: ['Active', 'Active', 'Active', 'Active', 'Under Review', 'Active', 'Active', 'Active', 'Active', 'Active', 'Under Review', 'Inactive'] }),
      ],
    },
    {
      id: 'wfWorker',
      label: 'Worker',
      plural: 'Workers',
      app: 'workforce',
      codePrefix: 'WKR',
      titleField: 'name',
      count: 24,
      import: true,
      form: 'page',
      sections: [
        { id: 'basic', title: 'Worker Details', icon: 'ti-user' },
        { id: 'work', title: 'Employment & Wages', icon: 'ti-briefcase' },
      ],
      fields: [
        text('name', 'Worker Name', WORKER_NAMES, { required: true, section: 'basic' }),
        select('category', 'Category', ['Contract Worker', 'Labourer'], { gen: ['Contract Worker', 'Labourer', 'Contract Worker', 'Contract Worker', 'Labourer', 'Labourer', 'Contract Worker', 'Labourer', 'Contract Worker', 'Labourer', 'Contract Worker', 'Labourer', 'Contract Worker', 'Labourer', 'Contract Worker', 'Labourer', 'Contract Worker', 'Labourer', 'Contract Worker', 'Labourer', 'Labourer', 'Contract Worker', 'Labourer', 'Contract Worker'], section: 'work' }),
        select('trade', 'Trade', TRADES, { section: 'work' }),
        select('skill', 'Wage Category', ['Skilled', 'Semi-skilled', 'Unskilled'], { section: 'work' }),
        ref('contractor', 'Labour Contractor', 'wfLabourContractor', { section: 'work' }),
        ref('project', 'Project', 'project', { section: 'work' }),
        money('wage', 'Daily Wage', [650, 1150], { section: 'work' }),
        text('native', 'Native State', ['Tamil Nadu', 'Tamil Nadu', 'Bihar', 'Jharkhand', 'Tamil Nadu', 'Tamil Nadu', 'Bihar', 'Tamil Nadu', 'Jharkhand', 'Tamil Nadu', 'Bihar', 'Tamil Nadu', 'West Bengal', 'Tamil Nadu', 'Jharkhand', 'Tamil Nadu', 'West Bengal', 'Tamil Nadu', 'Uttar Pradesh', 'Tamil Nadu', 'Tamil Nadu', 'Jharkhand', 'Tamil Nadu', 'Odisha'], { section: 'basic', list: false }),
        text('uan', 'UAN', ['1012 4587 3301', '1012 4587 3318', '1012 4590 1127', '1012 4590 1134'], { section: 'work', list: false }),
        status(['Active', 'Pending', 'Inactive'], { gen: ['Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Pending', 'Active', 'Active', 'Active', 'Active', 'Active', 'Inactive', 'Active', 'Active', 'Active', 'Active', 'Pending', 'Active', 'Active', 'Active', 'Active', 'Active'], section: 'work' }),
      ],
    },
    {
      id: 'wfProjectAssign',
      label: 'Project Assignment',
      plural: 'Project Assignments',
      app: 'workforce',
      codePrefix: 'PAS',
      titleField: 'employee',
      count: 20,
      fields: [
        ref('employee', 'Employee', 'employee', { required: true }),
        ref('project', 'Project', 'project', { required: true }),
        select('role', 'Project Role', ['Project Manager', 'Site Engineer', 'Planning Engineer', 'QS Engineer', 'Safety Officer', 'Store Keeper', 'MEP Coordinator', 'Foreman']),
        pct('allocation', 'Allocation', [25, 100]),
        date('from', 'From', [-320, -10]),
        date('to', 'To', [30, 420]),
        status(['Assigned', 'Planned', 'Released'], { gen: ['Assigned', 'Assigned', 'Assigned', 'Assigned', 'Planned', 'Assigned', 'Assigned', 'Released', 'Assigned', 'Assigned', 'Assigned', 'Planned', 'Assigned', 'Assigned', 'Released', 'Assigned', 'Assigned', 'Assigned', 'Assigned', 'Planned'] }),
      ],
    },
    {
      id: 'wfSiteAssign',
      label: 'Site Assignment',
      plural: 'Site Assignments',
      app: 'workforce',
      codePrefix: 'SAS',
      titleField: 'employee',
      count: 20,
      fields: [
        ref('employee', 'Employee', 'employee', { required: true }),
        ref('site', 'Site', 'site', { required: true }),
        select('shift', 'Shift', ['General', 'First', 'Second', 'Night']),
        ref('reportsTo', 'Reports To', 'employee'),
        date('from', 'Reporting Date', [-280, 5]),
        select('stay', 'Accommodation', ['Site camp', 'Company quarters', 'Own arrangement']),
        status(['Deployed', 'Planned', 'Released'], { gen: ['Deployed', 'Deployed', 'Deployed', 'Planned', 'Deployed', 'Deployed', 'Deployed', 'Released', 'Deployed', 'Deployed', 'Deployed', 'Deployed', 'Planned', 'Deployed', 'Deployed', 'Released', 'Deployed', 'Deployed', 'Deployed', 'Deployed'] }),
      ],
    },
    {
      id: 'wfRoleAssign',
      label: 'Role Assignment',
      plural: 'Role Assignments',
      app: 'workforce',
      codePrefix: 'RAS',
      titleField: 'role',
      count: 16,
      fields: [
        text('role', 'Role', ['Site-in-charge — Tower A', 'Safety Committee Member', 'First Aid Responder', 'Fire Warden', 'Quality Champion', 'Night Store In-charge', 'Concrete Pour Supervisor', 'Permit Issuer — Work at Height', 'Billing Coordinator', 'Environment Officer', 'Crane Signalman Supervisor', 'Toolbox Talk Lead', 'Subcontractor Coordinator', 'Site Document Controller', 'Night Shift In-charge', 'Emergency Response Lead'], { required: true }),
        ref('employee', 'Employee', 'employee', { required: true }),
        ref('project', 'Project', 'project'),
        select('type', 'Role Type', ['Operational', 'Statutory', 'Safety', 'Additional charge']),
        date('from', 'Effective From', [-200, 10]),
        ref('approvedBy', 'Approved By', 'employee'),
        status(['Active', 'Pending', 'Inactive'], { gen: ['Active', 'Active', 'Active', 'Active', 'Pending', 'Active', 'Active', 'Active', 'Active', 'Inactive', 'Active', 'Active', 'Pending', 'Active', 'Active', 'Active'] }),
      ],
    },
    {
      id: 'wfOvertime',
      label: 'Overtime Request',
      plural: 'Overtime Requests',
      app: 'workforce',
      codePrefix: 'OT',
      titleField: 'worker',
      count: 22,
      fields: [
        ref('worker', 'Worker', 'wfWorker', { required: true }),
        ref('project', 'Project', 'project'),
        date('date', 'OT Date', [-20, 0], { required: true }),
        num('hours', 'OT Hours', [2, 6], { unit: 'hrs', required: true }),
        money('rate', 'OT Rate / hr (2×)', [160, 290]),
        text('reason', 'Reason', ['Slab pour L14 — Tower B', 'Column casting continuation', 'Client inspection preparation', 'Shuttering de-shuttering cycle', 'Rain loss recovery', 'Raft pour — clubhouse', 'Material unloading — steel', 'Waterproofing before rain', 'Façade bracket fixing', 'Lift shaft cleaning']),
        ref('approver', 'Approver', 'employee', { list: false }),
        status(['Pending', 'Approved', 'Rejected'], { gen: ['Pending', 'Approved', 'Approved', 'Pending', 'Approved', 'Approved', 'Rejected', 'Approved', 'Pending', 'Approved', 'Approved', 'Approved', 'Pending', 'Approved', 'Approved', 'Rejected', 'Approved', 'Pending', 'Approved', 'Approved', 'Approved', 'Pending'] }),
      ],
    },
    {
      id: 'wfLeave',
      label: 'Leave Request',
      plural: 'Leave Requests',
      app: 'workforce',
      codePrefix: 'LV',
      titleField: 'employee',
      count: 22,
      fields: [
        ref('employee', 'Employee', 'employee', { required: true }),
        select('type', 'Leave Type', ['Casual Leave', 'Sick Leave', 'Earned Leave', 'Comp Off', 'Maternity Leave'], { required: true, gen: ['Casual Leave', 'Sick Leave', 'Earned Leave', 'Casual Leave', 'Comp Off', 'Earned Leave', 'Sick Leave', 'Casual Leave', 'Earned Leave', 'Comp Off', 'Casual Leave', 'Sick Leave', 'Earned Leave', 'Casual Leave', 'Maternity Leave', 'Casual Leave', 'Comp Off', 'Earned Leave', 'Sick Leave', 'Casual Leave', 'Earned Leave', 'Casual Leave'] }),
        date('from', 'From', [-20, 25], { required: true }),
        num('days', 'Days', [1, 6]),
        num('balance', 'Balance After', [2, 18], { unit: 'days' }),
        text('reason', 'Reason', ['Family function', 'Fever', 'Native visit — festival', 'Personal work', 'Worked on Sunday pour', 'Marriage in family', 'Medical check-up', 'Child school event', 'Deepavali travel', 'Comp off for night pour']),
        ref('approver', 'Approver', 'employee', { list: false }),
        status(['Pending', 'Approved', 'Rejected'], { gen: ['Pending', 'Approved', 'Approved', 'Pending', 'Approved', 'Rejected', 'Approved', 'Pending', 'Approved', 'Approved', 'Pending', 'Approved', 'Approved', 'Pending', 'Approved', 'Approved', 'Rejected', 'Pending', 'Approved', 'Approved', 'Pending', 'Approved'] }),
      ],
    },
    {
      id: 'wfSalaryComponent',
      label: 'Salary Component',
      plural: 'Salary Components',
      app: 'workforce',
      codePrefix: 'SC',
      titleField: 'description',
      fields: [
        text('description', 'Component', undefined, { required: true }),
        select('section', 'Component Group', ['Fixed Earnings', 'Allowances', 'Variable Pay', 'Employer Contributions']),
        text('unit', 'Unit'),
        num('qty', 'Qty'),
        money('rate', 'Amount / Unit'),
      ],
      rows: salaryRows,
    },
    {
      id: 'wfWageLine',
      label: 'Wage Line',
      plural: 'Wage Lines',
      app: 'workforce',
      codePrefix: 'WG',
      titleField: 'description',
      fields: [
        text('description', 'Gang / Trade', undefined, { required: true }),
        select('section', 'Wage Category', ['Skilled', 'Semi-skilled', 'Unskilled', 'Overtime & Allowances']),
        num('workers', 'Workers'),
        text('unit', 'Unit'),
        num('qty', 'Man-days / Units'),
        money('rate', 'Wage Rate'),
      ],
      rows: wageRows,
    },
    {
      id: 'wfDeduction',
      label: 'Deduction',
      plural: 'Deductions',
      app: 'workforce',
      codePrefix: 'DED',
      titleField: 'employee',
      count: 18,
      fields: [
        ref('employee', 'Employee', 'employee', { required: true }),
        select('type', 'Deduction Type', ['Salary Advance Recovery', 'Loan EMI', 'Canteen', 'PPE / Uniform', 'Loss of Pay', 'Mess & Accommodation', 'Fine (safety violation)'], { required: true }),
        select('month', 'Payroll Month', ['September 2026', 'August 2026'], { gen: ['September 2026'] }),
        money('amount', 'Amount', [300, 12000]),
        money('balance', 'Balance Outstanding', [0, 60000]),
        num('instalments', 'Instalments Left', [0, 10]),
        status(['Active', 'Completed', 'Pending'], { gen: ['Active', 'Active', 'Completed', 'Active', 'Pending', 'Active', 'Completed', 'Active', 'Active', 'Active', 'Completed', 'Pending', 'Active', 'Active', 'Completed', 'Active', 'Active', 'Active'] }),
      ],
    },
    {
      id: 'wfContribution',
      label: 'Statutory Contribution',
      plural: 'Statutory Contributions',
      app: 'workforce',
      codePrefix: 'STC',
      titleField: 'filing',
      count: 12,
      fields: [
        text('filing', 'Return / Challan', ['EPF ECR — Sep 2026', 'ESIC Challan — Sep 2026', 'EPF ECR — Aug 2026', 'ESIC Challan — Aug 2026', 'Professional Tax — H1 FY 2026-27', 'TN Labour Welfare Fund — 2026', 'BOCW Cess — Skyline Apartments (Sep)', 'BOCW Cess — Metro Office Tower (Sep)', 'EPF ECR — Jul 2026', 'ESIC Challan — Jul 2026', 'BOCW Cess — Greenfield Township (Sep)', 'BOCW Cess — Riverside Villas (Sep)'], { required: true }),
        select('scheme', 'Scheme', ['EPF', 'ESI', 'Professional Tax', 'Labour Welfare Fund', 'BOCW Cess'], { gen: ['EPF', 'ESI', 'EPF', 'ESI', 'Professional Tax', 'Labour Welfare Fund', 'BOCW Cess', 'BOCW Cess', 'EPF', 'ESI', 'BOCW Cess', 'BOCW Cess'] }),
        num('members', 'Members Covered', [180, 1842]),
        money('employee', 'Employee Share', [0, 2840000]),
        money('employer', 'Employer Share', [7000, 2840000]),
        date('due', 'Due Date', [-75, 32]),
        text('challan', 'Challan / TRRN', ['TRRN 3102609004512', 'ESIC-2609-88412', 'TRRN 3102608004377', 'ESIC-2608-87105', 'PT/GCC/H1/5521', 'LWF/TN/2026/0419', 'BOCW/TN/SKY/0926', 'BOCW/KA/MOT/0926', 'TRRN 3102607004218', 'ESIC-2607-85720', 'BOCW/TN/GFT/0926', 'BOCW/TN/RVV/0926']),
        status(['Due', 'Paid', 'Overdue', 'Pending'], { gen: ['Due', 'Due', 'Paid', 'Paid', 'Pending', 'Paid', 'Due', 'Due', 'Paid', 'Paid', 'Overdue', 'Due'] }),
      ],
    },
  ],
};
