/**
 * Appendix A of the approved plan — the exact Module → Menu → Child menu tree from the client brief.
 * A menu mapped to `[]` is a leaf menu (a page with no children).
 * The tree-fidelity test asserts the nav config matches this exactly (labels and order).
 */
export const NAV_TREE: [app: string, name: string, menus: [menu: string, children: string[]][]][] = [
  ['crm', 'CRM', [
    ['Lead Management', ['Lead Registration', 'Lead Source', 'Lead Qualification', 'Lead Conversion']],
    ['Client Management', ['Client Master', 'Client Contacts', 'Client Addresses', 'Client Documents', 'Client History']],
    ['Opportunity Management', ['Opportunity', 'Project Requirement', 'Estimated Value', 'Expected Start', 'Probability']],
    ['Communication', ['Meetings', 'Calls', 'Emails', 'Follow-ups']],
  ]],
  ['tender', 'Tender', [
    ['Tender Management', ['Tender Registration', 'Tender Details', 'Tender Type', 'Submission Deadline', 'Tender Status']],
    ['Tender Documents', ['Tender Notice', 'Specifications', 'Drawings', 'BOQ', 'Terms & Conditions']],
    ['Evaluation', ['Technical Eligibility', 'Financial Eligibility', 'Experience', 'Compliance', 'Feasibility']],
    ['Bid Preparation', ['Quantity', 'Rate Analysis', 'Cost Estimate', 'Overhead', 'Risk', 'Profit']],
    ['Submission', ['Draft', 'Under Review', 'Submitted', 'Won', 'Lost']],
  ]],
  ['land', 'Land', [
    ['Land Identification', ['Land Lead', 'Location', 'Area', 'Land Owner']],
    ['Ownership', ['Owner Details', 'Title Documents', 'Sale Deed', 'Encumbrance']],
    ['Legal Verification', ['Title Verification', 'Encumbrance Check', 'Litigation', 'Legal Opinion']],
    ['Technical Verification', ['Land Survey', 'Soil Test', 'Topographical Survey', 'Site Conditions']],
    ['Regulatory', ['Zoning', 'Land Use', 'Approvals', 'NOCs']],
    ['Acquisition', ['Negotiation', 'Agreement', 'Purchase', 'Ownership Transfer']],
  ]],
  ['estimation', 'Estimation', [
    ['Estimate Management', ['Estimate', 'Estimate Version', 'Estimate Status']],
    ['Quantity Takeoff', ['Drawings', 'Measurements', 'Quantities']],
    ['BOQ', ['BOQ Items', 'Quantity', 'Unit', 'Rate', 'Amount']],
    ['Rate Analysis', ['Material', 'Labour', 'Equipment', 'Subcontract', 'Overhead']],
    ['Cost Estimate', ['Direct Cost', 'Indirect Cost', 'Contingency', 'Profit']],
  ]],
  ['project', 'Project', [
    ['Project Master', ['Project Code', 'Project Name', 'Client', 'Site', 'Project Type', 'Status']],
    ['Project Setup', ['Start Date', 'End Date', 'Project Manager', 'Team', 'Contract']],
    ['Project Structure', ['WBS', 'Work Packages', 'Activities', 'Milestones']],
    ['Budget', ['Approved Budget', 'Cost Heads', 'Budget Allocation']],
    ['Planning & Control', ['Schedule', 'Dependencies', 'Resources', 'Issues', 'Risks', 'Delays']],
  ]],
  ['procurement', 'Procurement', [
    ['Purchase Request', ['Material Request', 'Service Request', 'Purchase Indent']],
    ['RFQ', ['Vendor Selection', 'RFQ', 'Quotation Request']],
    ['Vendor Quotations', ['Quotations', 'Rate Comparison', 'Technical Comparison']],
    ['Purchase Order', ['PO', 'PO Items', 'Delivery Schedule', 'Terms']],
    ['Procurement Tracking', ['Ordered', 'Partially Received', 'Fully Received', 'Closed']],
  ]],
  ['store', 'Store', [
    ['Store Master', ['Stores', 'Warehouses', 'Site Stores', 'Locations']],
    ['Material Receipt', ['Gate Entry', 'GRN', 'Quantity Check', 'Quality Check']],
    ['Inventory', ['Stock', 'Batch', 'Serial', 'Location']],
    ['Material Movement', ['Material Issue', 'Material Transfer', 'Material Return', 'Stock Adjustment']],
    ['Stock Control', ['Wastage', 'Stock Reconciliation']],
  ]],
  ['site', 'Site', [
    ['Site Management', ['Site Master', 'Site Setup', 'Site Mobilization']],
    ['Daily Work', ['Activities', 'Work Packages', 'Daily Tasks']],
    ['Progress', ['Quantity Completed', 'Percentage Complete', 'Progress Photos', 'Milestones']],
    ['Site Resources', ['Labour', 'Materials', 'Equipment']],
    ['Daily Reports', ['DPR', 'Site Photos', 'Site Remarks', 'Site Issues']],
  ]],
  ['subcontract', 'Subcontract', [
    ['Subcontractor Master', ['Company Details', 'Experience', 'Certifications', 'Insurance', 'Compliance']],
    ['Work Package', ['Scope', 'Quantity', 'Rate']],
    ['Contract', ['Agreement', 'Work Order', 'Terms']],
    ['Execution', ['Site Assignment', 'Measurement', 'Work Completion', 'Certification']],
    ['Settlement', ['Subcontractor Bill', 'Deductions', 'Payment']],
  ]],
  ['equipment', 'Equipment', [
    ['Equipment Master', ['Machinery', 'Vehicles', 'Equipment']],
    ['Ownership', ['Owned', 'Rented', 'Leased']],
    ['Allocation', ['Project', 'Site', 'Activity']],
    ['Usage', ['Operating Hours', 'Idle Hours', 'Production']],
    ['Fuel', ['Fuel Issue', 'Consumption', 'Efficiency']],
    ['Maintenance', ['Preventive', 'Breakdown', 'Repair']],
  ]],
  ['workforce', 'Workforce', [
    ['Employee Management', ['Employee Master', 'Personal Details', 'Employment Details', 'Department', 'Designation', 'Joining / Exit', 'Skills & Qualifications', 'Documents']],
    ['Worker Management', ['Contract Workers', 'Labourers', 'Labour Contractors', 'Worker Registration']],
    ['Workforce Allocation', ['Project Assignment', 'Site Assignment', 'Role Assignment', 'Transfer']],
    ['Attendance', ['Daily Attendance', 'Shift', 'Overtime', 'Leave']],
    ['Payroll', ['Salary Structure', 'Wage Calculation', 'Payroll Run', 'Deductions', 'Contributions', 'Payslip']],
  ]],
  ['contracts', 'Contracts', [
    ['Contract Master', []],
    ['Client Contract', ['Contract Value', 'Duration', 'Terms', 'Conditions']],
    ['Contract BOQ', ['Contract Items', 'Quantities', 'Rates']],
    ['Commercial Terms', ['Payment Terms', 'Retention', 'Advance', 'Performance Guarantee']],
    ['Milestones', []],
    ['Contract Documents', []],
  ]],
  ['billing', 'Billing', [
    ['Billing Setup', []],
    ['Measurement', ['Work Measurement', 'Quantity', 'Certification']],
    ['Progress Billing', []],
    ['RA Bill', []],
    ['Client Invoice', []],
    ['Commercial Adjustments', ['Advance Recovery', 'Retention', 'Deductions', 'Taxes']],
    ['Bill Certification', []],
  ]],
  ['finance', 'Finance', [
    ['General Ledger', ['Chart of Accounts', 'Journal', 'Accounting Entries']],
    ['Accounts Payable', ['Vendor Bills', 'Payables', 'Vendor Settlement']],
    ['Accounts Receivable', ['Client Receivables', 'Outstanding', 'Collections']],
    ['Cash', ['Petty Cash', 'Cash Transactions']],
    ['Bank', ['Bank Accounts', 'Transactions', 'Reconciliation']],
    ['Financial Reporting', ['P&L', 'Balance Sheet', 'Cash Flow', 'Project Profitability']],
  ]],
  ['quality-and-safety', 'Quality & Safety', [
    ['Quality', ['Quality Plan', 'Inspection', 'Checklist', 'Material Testing', 'NCR', 'Corrective Action']],
    ['Safety', ['Safety Plan', 'Safety Inspection', 'PPE', 'Incident', 'Accident', 'Risk Assessment', 'Safety Training']],
  ]],
  ['handover', 'Handover', [
    ['Completion', ['Work Completion', 'Completion Certificate', 'Final Inspection']],
    ['Snag Management', ['Snag', 'Assignment', 'Rectification', 'Verification']],
    ['Handover', ['Handover Documents', 'Asset Handover', 'Client Acceptance']],
    ['Warranty', ['Warranty', 'Defect Liability Period', 'Defects']],
  ]],
  ['variations', 'Variations', [
    ['Variation Request', []],
    ['Reason', ['Client Change', 'Design Change', 'Site Condition', 'Regulatory Change']],
    ['Quantity Variation', []],
    ['Rate Variation', []],
    ['New Item', []],
    ['Cost Impact', []],
    ['Schedule Impact', []],
    ['Approval', []],
    ['Contract Update', []],
  ]],
  ['claims', 'Claims', [
    ['Claim Registration', []],
    ['Claim Type', []],
    ['Claim Reason', []],
    ['Supporting Documents', []],
    ['Cost Impact', []],
    ['Time Impact', []],
    ['Evidence', []],
    ['Submission', []],
    ['Negotiation', []],
    ['Approval / Rejection', []],
    ['Settlement', []],
  ]],
  ['reporting', 'Reporting', [
    ['Executive Dashboard', ['Revenue', 'Profit', 'Active Projects', 'Cash Flow']],
    ['Project Reports', ['Project Progress', 'Project Cost', 'Budget Variance', 'Schedule']],
    ['Procurement Reports', ['Purchase', 'Vendor', 'Material Cost']],
    ['Workforce Reports', ['Attendance', 'Labour Cost', 'Productivity']],
    ['Finance Reports', ['Receivables', 'Payables', 'Cash Flow', 'Project Profitability']],
  ]],
];
