/**
 * Shared master data. Every application references these records, so
 * "PRJ-001 Skyline Apartments" is the same project in Site, Billing, Procurement, Claims …
 * Figures reconcile with the reference screenshot: 8 active projects, ₹320 Cr TCV, ₹186 Cr cost incurred.
 */
import { money, num, pct, ref, select, status, text, date } from './dsl';
import type { EntityDef, Row } from './types';

const CR = 1e7;

/* ───────── Clients ───────── */
const clientRows: Row[] = [
  ['ABC Builders Pvt Ltd', 'Developer', 'Chennai', 'Ramesh Iyer'],
  ['XYZ Developers', 'Developer', 'Coimbatore', 'Anand Krishnan'],
  ['Greenfield Infra Ltd', 'Developer', 'Hosur', 'Sanjay Mehta'],
  ['Metro Constructions', 'Corporate', 'Bengaluru', 'Kiran Rao'],
  ['Lakeview Estates', 'Developer', 'Hyderabad', 'Srinivas Reddy'],
  ['Orbit Tech Parks', 'Corporate', 'Chennai', 'Vivek Menon'],
  ['Coastal Healthcare Trust', 'Institution', 'Visakhapatnam', 'Dr. Padma Rao'],
  ['Sunrise Hospitality', 'Corporate', 'Madurai', 'Arvind Pillai'],
  ['Pinnacle Realty', 'Developer', 'Pune', 'Rohit Deshpande'],
  ['Meridian Industrial Parks', 'Corporate', 'Sriperumbudur', 'Neha Kapoor'],
].map(([name, type, city, contact], i) => ({
  id: `CL-${String(i + 1).padStart(3, '0')}`,
  code: `CL-${String(i + 1).padStart(3, '0')}`,
  name,
  type,
  city,
  contact,
  phone: `+91 98${String(40123456 + i * 7919).slice(0, 3)} ${String(10000 + i * 3571).slice(0, 5)}`,
  email: `contact@${name.toLowerCase().replace(/[^a-z]+/g, '').slice(0, 14)}.in`,
  gstin: `33AAB${'CDEFGHIJKL'[i]}${1234 + i}F1Z${i}`,
  since: `20${16 + (i % 8)}-0${(i % 9) + 1}-15`,
  status: i < 8 ? 'Active' : 'Prospect',
}));

/* ───────── Employees ───────── */
const people: [string, string, string][] = [
  ['Arun S', 'Project Manager', 'Projects'],
  ['Ravi Kumar K', 'Site Engineer', 'Execution'],
  ['Sneha P', 'Planning Engineer', 'Planning'],
  ['Divya T', 'Document Controller', 'Projects'],
  ['Karthik R', 'Project Manager', 'Projects'],
  ['Priya M', 'Quantity Surveyor', 'Contracts & QS'],
  ['Vignesh B', 'Site Engineer', 'Execution'],
  ['Lakshmi N', 'Accounts Executive', 'Finance'],
  ['Suresh Babu', 'Store Keeper', 'Stores'],
  ['Meena Iyer', 'HR Manager', 'Human Resources'],
  ['Rajesh Nair', 'Procurement Manager', 'Procurement'],
  ['Anitha G', 'Billing Engineer', 'Contracts & QS'],
  ['Mohammed Imran', 'Safety Officer', 'HSE'],
  ['Deepak Sharma', 'QA/QC Engineer', 'Quality'],
  ['Harish V', 'Planning Manager', 'Planning'],
  ['Kavya R', 'Estimation Engineer', 'Estimation'],
  ['Senthil Kumar', 'Site Manager', 'Execution'],
  ['Bala Murugan', 'Foreman', 'Execution'],
  ['Farhan Ali', 'Equipment Manager', 'Plant & Machinery'],
  ['Gayathri S', 'Finance Manager', 'Finance'],
  ['Naveen P', 'Tender Manager', 'Business Development'],
  ['Ramya K', 'CRM Executive', 'Business Development'],
  ['Prakash J', 'Surveyor', 'Execution'],
  ['Manoj Kumar', 'Electrical Engineer', 'MEP'],
  ['Sathish R', 'MEP Engineer', 'MEP'],
  ['Keerthana V', 'Architect', 'Design'],
  ['Dinesh M', 'Site Engineer', 'Execution'],
  ['Pooja Reddy', 'Legal Officer', 'Legal'],
  ['Vinoth A', 'Store Keeper', 'Stores'],
  ['Aishwarya L', 'HR Executive', 'Human Resources'],
  ['Ganesh T', 'Site Manager', 'Execution'],
  ['Siddharth Rao', 'Contracts Manager', 'Contracts & QS'],
  ['Nandhini P', 'Accounts Executive', 'Finance'],
  ['Murugan S', 'Crane Operator', 'Plant & Machinery'],
  ['Selvam K', 'Excavator Operator', 'Plant & Machinery'],
  ['Joseph D', 'Safety Steward', 'HSE'],
  ['Rahul Verma', 'Planning Engineer', 'Planning'],
  ['Swathi N', 'Quantity Surveyor', 'Contracts & QS'],
  ['Kumaravel P', 'Site Manager', 'Execution'],
  ['Arjun Menon', 'Land Acquisition Officer', 'Land & Legal'],
];
const employeeRows: Row[] = people.map(([name, designation, department], i) => ({
  id: `EMP-${String(i + 1).padStart(3, '0')}`,
  code: `EMP-${String(i + 1).padStart(3, '0')}`,
  name,
  designation,
  department,
  site: `SITE-00${(i % 8) + 1}`,
  phone: `+91 9${String(840000000 + i * 104729).slice(0, 4)} ${String(10000 + i * 7919).slice(-5)}`,
  email: `${name.toLowerCase().replace(/[^a-z]+/g, '.').replace(/\.$/, '')}@constructionerp.in`,
  joining: `20${17 + (i % 8)}-${String((i % 12) + 1).padStart(2, '0')}-0${(i % 9) + 1}`,
  type: i % 9 === 8 ? 'Contract' : 'Permanent',
  attendance: `${88 + (i % 12)}%`,
  status: i === 30 ? 'On Leave' : 'Active',
}));

/* ───────── Sites ───────── */
const siteData: [string, string, string, string, number][] = [
  ['Skyline Apartments — Sholinganallur', 'Chennai', 'Tamil Nadu', 'EMP-017', 4.2],
  ['Riverside Villas — Saravanampatti', 'Coimbatore', 'Tamil Nadu', 'EMP-031', 12.5],
  ['Greenfield Township — Bagalur Road', 'Hosur', 'Tamil Nadu', 'EMP-039', 48.0],
  ['Metro Office Tower — Whitefield', 'Bengaluru', 'Karnataka', 'EMP-017', 2.8],
  ['Lakeview Residency — Gachibowli', 'Hyderabad', 'Telangana', 'EMP-031', 6.1],
  ['Orbit Tech Park — Perungudi', 'Chennai', 'Tamil Nadu', 'EMP-039', 5.4],
  ['Harbour View Hospital — Beach Road', 'Visakhapatnam', 'Andhra Pradesh', 'EMP-017', 3.6],
  ['Sunrise Business Hotel — Bypass Road', 'Madurai', 'Tamil Nadu', 'EMP-031', 1.9],
];
const siteRows: Row[] = siteData.map(([name, city, state, manager, acres], i) => ({
  id: `SITE-00${i + 1}`,
  code: `SITE-00${i + 1}`,
  name,
  project: `PRJ-00${i + 1}`,
  city,
  state,
  manager,
  area: acres,
  labour: [412, 186, 264, 338, 142, 96, 158, 121][i],
  status: 'Active',
}));

/* ───────── Projects ───────── */
const projectData: [string, string, string, string, string, number, number, number, string, string][] = [
  ['Skyline Apartments', 'CL-001', 'Residential High-rise', '2025-06-01', '2027-06-30', 68, 85, 52, 'On Track', 'EMP-001'],
  ['Riverside Villas', 'CL-002', 'Villas', '2025-09-15', '2027-10-31', 45, 42, 22, 'On Track', 'EMP-005'],
  ['Greenfield Township', 'CL-003', 'Township', '2025-06-01', '2027-09-30', 32, 58, 24, 'Delayed', 'EMP-001'],
  ['Metro Office Tower', 'CL-004', 'Commercial', '2025-08-01', '2027-08-31', 55, 64, 40, 'On Track', 'EMP-005'],
  ['Lakeview Residency', 'CL-005', 'Residential', '2026-01-15', '2027-12-31', 28, 28, 10, 'At Risk', 'EMP-001'],
  ['Orbit Tech Park Phase II', 'CL-006', 'IT Park', '2024-06-01', '2026-11-30', 92, 18, 17, 'On Track', 'EMP-005'],
  ['Harbour View Hospital', 'CL-007', 'Institutional', '2025-01-05', '2026-12-15', 84, 15, 13, 'At Risk', 'EMP-001'],
  ['Sunrise Business Hotel', 'CL-008', 'Hospitality', '2025-05-01', '2027-02-28', 76, 10, 8, 'On Track', 'EMP-005'],
];
const projectRows: Row[] = projectData.map(([name, client, type, start, end, progress, value, cost, st, pm], i) => ({
  id: `PRJ-00${i + 1}`,
  code: `PRJ-00${i + 1}`,
  name,
  client,
  site: `SITE-00${i + 1}`,
  type,
  start,
  end,
  progress,
  value: value * CR,
  cost: cost * CR,
  budget: Math.round(value * 0.86 * CR),
  manager: pm,
  contract: `CON-00${i + 1}`,
  status: st,
}));

/* ───────── Vendors ───────── */
const vendorData: [string, string, string][] = [
  ['UltraBuild Cements', 'Cement', 'Chennai'],
  ['Shree Balaji Steel Traders', 'Steel', 'Chennai'],
  ['Chennai RMC Pvt Ltd', 'Ready Mix Concrete', 'Chennai'],
  ['Sri Murugan Aggregates', 'Aggregates & Sand', 'Kanchipuram'],
  ['Kaveri Bricks & Blocks', 'Bricks & Blocks', 'Hosur'],
  ['Apex Electricals', 'Electrical', 'Bengaluru'],
  ['FlowLine Pipes & Fittings', 'Plumbing', 'Coimbatore'],
  ['ColorCraft Paints', 'Paints', 'Chennai'],
  ['Stonecraft Tiles & Granite', 'Finishes', 'Hyderabad'],
  ['FormTech Shuttering', 'Shuttering', 'Chennai'],
  ['SafeGuard PPE Supplies', 'Safety', 'Chennai'],
  ['Deccan Hardware Mart', 'Hardware', 'Hyderabad'],
  ['Southern Glass & Aluminium', 'Glazing', 'Bengaluru'],
  ['PowerGen Rentals', 'Equipment Rental', 'Chennai'],
  ['Crane Hire India', 'Equipment Rental', 'Bengaluru'],
  ['Nilgiri Timber Depot', 'Timber', 'Coimbatore'],
  ['Coastal Fuel Services', 'Fuel', 'Chennai'],
  ['Techno Waterproofing', 'Chemicals', 'Chennai'],
  ['Bharat Lifts & Escalators', 'Vertical Transport', 'Mumbai'],
  ['GreenLeaf Landscaping', 'Landscaping', 'Madurai'],
];
const vendorRows: Row[] = vendorData.map(([name, category, city], i) => ({
  id: `VEN-${String(i + 1).padStart(3, '0')}`,
  code: `VEN-${String(i + 1).padStart(3, '0')}`,
  name,
  category,
  city,
  contact: ['Mahesh', 'Bhaskar', 'Ilango', 'Venkat', 'Sundar', 'Joseph', 'Farook', 'Raghav', 'Tarun', 'Mani'][i % 10] + ' ' + 'KRSNVMPTAG'[i % 10],
  phone: `+91 94${String(4400000 + i * 26357).slice(0, 3)} ${String(20000 + i * 2957).slice(-5)}`,
  gstin: `33AAC${'FGHJKLMNPQ'[i % 10]}${5678 + i}K1Z${i % 10}`,
  rating: [4.6, 4.2, 4.8, 3.9, 4.1, 4.4, 3.7, 4.0, 4.3, 4.5][i % 10],
  spend: [4.8, 12.6, 9.4, 3.2, 2.1, 3.8, 1.6, 1.2, 2.9, 1.8, 0.6, 0.9, 2.4, 1.1, 1.9, 0.7, 2.2, 0.8, 3.6, 0.4][i] * CR,
  status: i === 6 ? 'Under Review' : i === 19 ? 'Inactive' : 'Approved',
}));

/* ───────── Subcontractors ───────── */
const subData: [string, string][] = [
  ['Sai Ram Constructions', 'Civil & Structure'],
  ['Precision MEP Services', 'MEP'],
  ['Vertex Formwork Solutions', 'Formwork'],
  ['AquaSeal Waterproofing', 'Waterproofing'],
  ['BrightSpark Electricals', 'Electrical'],
  ['Royal Tiling Works', 'Flooring & Tiling'],
  ['Skyline Facade Systems', 'Facade'],
  ['PipeMasters Plumbing', 'Plumbing'],
  ['FireSafe Systems', 'Fire Fighting'],
  ['CoolAir HVAC Engineers', 'HVAC'],
  ['EarthMovers & Co', 'Earthwork'],
  ['FinePaint Contractors', 'Painting'],
];
const subRows: Row[] = subData.map(([name, trade], i) => ({
  id: `SUB-${String(i + 1).padStart(3, '0')}`,
  code: `SUB-${String(i + 1).padStart(3, '0')}`,
  name,
  trade,
  city: ['Chennai', 'Bengaluru', 'Hyderabad', 'Coimbatore'][i % 4],
  contact: ['Sai Prasad', 'Mukesh', 'Anbu', 'Charles', 'Ibrahim', 'Rajan'][i % 6],
  experience: 6 + ((i * 3) % 17),
  workforce: 40 + ((i * 37) % 260),
  quality: 70 + ((i * 7) % 28),
  safety: 72 + ((i * 11) % 26),
  status: i === 10 ? 'Under Review' : 'Approved',
}));

/* ───────── Items (materials) ───────── */
const itemData: [string, string, string, number][] = [
  ['Cement OPC 53 Grade', 'Cement', 'Bag', 385],
  ['Cement PPC', 'Cement', 'Bag', 360],
  ['TMT Bar Fe500D 8mm', 'Steel', 'MT', 62500],
  ['TMT Bar Fe500D 12mm', 'Steel', 'MT', 61200],
  ['TMT Bar Fe500D 16mm', 'Steel', 'MT', 60800],
  ['TMT Bar Fe500D 25mm', 'Steel', 'MT', 60400],
  ['M-Sand', 'Aggregates & Sand', 'Cum', 1850],
  ['P-Sand (Plastering)', 'Aggregates & Sand', 'Cum', 2150],
  ['Coarse Aggregate 20mm', 'Aggregates & Sand', 'Cum', 1650],
  ['Ready Mix Concrete M25', 'Ready Mix Concrete', 'Cum', 5400],
  ['Ready Mix Concrete M30', 'Ready Mix Concrete', 'Cum', 5850],
  ['AAC Block 600x200x200', 'Bricks & Blocks', 'Nos', 58],
  ['Red Brick (Wire-cut)', 'Bricks & Blocks', 'Nos', 9],
  ['Shuttering Plywood 12mm', 'Shuttering', 'Sheet', 1450],
  ['Binding Wire 18G', 'Hardware', 'Kg', 78],
  ['Admixture (Superplasticiser)', 'Chemicals', 'Ltr', 95],
  ['Waterproofing Compound', 'Chemicals', 'Kg', 140],
  ['uPVC Pipe 110mm', 'Plumbing', 'Mtr', 420],
  ['CPVC Pipe 25mm', 'Plumbing', 'Mtr', 165],
  ['FR Cable 2.5 sq.mm', 'Electrical', 'Coil', 2350],
  ['Distribution Board 12-way', 'Electrical', 'Nos', 4800],
  ['Vitrified Tile 600x600', 'Finishes', 'Sqm', 720],
  ['Granite Slab (Black Galaxy)', 'Finishes', 'Sqm', 2650],
  ['Interior Emulsion', 'Paints', 'Ltr', 310],
  ['Exterior Emulsion', 'Paints', 'Ltr', 395],
  ['Safety Helmet', 'Safety', 'Nos', 185],
  ['Safety Harness (Full Body)', 'Safety', 'Nos', 2450],
  ['HSD (Diesel)', 'Fuel', 'Ltr', 92],
  ['Aluminium Window Section', 'Glazing', 'Kg', 385],
  ['Toughened Glass 8mm', 'Glazing', 'Sqm', 1650],
];
const itemRows: Row[] = itemData.map(([name, category, unit, rate], i) => {
  const reorder = [500, 400, 20, 30, 30, 15, 120, 80, 150, 60, 60, 3000, 8000, 120, 400, 300, 250, 400, 600, 25, 10, 800, 150, 400, 400, 150, 30, 5000, 800, 120][i];
  const stock = Math.round(reorder * [2.4, 1.8, 0.7, 3.1, 2.2, 1.4, 0.9, 1.6, 2.8, 0.5, 1.2, 2.6, 1.9, 0.8, 3.4, 1.1, 2.0, 1.5, 2.7, 0.6, 1.3, 2.3, 1.7, 0.95, 2.1, 4.0, 1.2, 0.85, 1.6, 2.5][i]);
  return {
    id: `ITM-${String(i + 1).padStart(3, '0')}`,
    code: `ITM-${String(i + 1).padStart(3, '0')}`,
    name,
    category,
    unit,
    rate,
    stock,
    reserved: Math.round(stock * 0.18),
    reorder,
    minimum: Math.round(reorder * 0.6),
    status: stock < reorder * 0.6 ? 'Low Stock' : stock < reorder ? 'Reorder Level' : 'In Stock',
  };
});

/* ───────── Equipment ───────── */
const eqData: [string, string, string, string, string][] = [
  ['Tower Crane TC-5013', 'Machinery', 'Owned', 'Potain MC 125', '5 T @ 50 m'],
  ['Excavator JCB 3DX', 'Machinery', 'Owned', 'JCB 3DX Super', '0.26 cum'],
  ['Excavator Hitachi EX200', 'Machinery', 'Rented', 'Hitachi ZX200', '0.9 cum'],
  ['Transit Mixer 7 cum', 'Vehicles', 'Owned', 'Schwing Stetter AM7', '7 cum'],
  ['Concrete Boom Pump', 'Machinery', 'Leased', 'Schwing S36X', '36 m boom'],
  ['Batching Plant CP30', 'Machinery', 'Owned', 'Schwing CP30', '30 cum/hr'],
  ['DG Set 250 kVA', 'Equipment', 'Owned', 'Kirloskar KG1-250', '250 kVA'],
  ['DG Set 125 kVA', 'Equipment', 'Rented', 'Cummins C125', '125 kVA'],
  ['Tipper Tata Signa 2823', 'Vehicles', 'Owned', 'Tata Signa 2823.K', '16 cum'],
  ['Hydra Crane 14 T', 'Machinery', 'Rented', 'Escorts Hydra 14', '14 T'],
  ['Mobile Crane 50 T', 'Machinery', 'Rented', 'Liebherr LTM 1050', '50 T'],
  ['Material Hoist', 'Equipment', 'Owned', 'Alimak Scando 650', '2 T'],
  ['Vibratory Roller', 'Machinery', 'Leased', 'Case 1107EX', '11 T'],
  ['Bar Bending Machine', 'Equipment', 'Owned', 'Kiswel BB-42', '42 mm'],
  ['Bar Cutting Machine', 'Equipment', 'Owned', 'Kiswel BC-42', '42 mm'],
  ['Pickup Mahindra Bolero', 'Vehicles', 'Owned', 'Bolero Maxi Truck', '1.3 T'],
];
const equipmentRows: Row[] = eqData.map(([name, category, ownership, model, capacity], i) => ({
  id: `EQ-${String(i + 1).padStart(3, '0')}`,
  code: `EQ-${String(i + 1).padStart(3, '0')}`,
  name,
  category,
  ownership,
  model,
  serial: `SN${String(20240000 + i * 7331)}`,
  capacity,
  project: `PRJ-00${(i % 8) + 1}`,
  operator: i % 3 === 0 ? 'EMP-034' : i % 3 === 1 ? 'EMP-035' : 'EMP-018',
  hours: 620 + ((i * 97) % 900),
  utilization: 58 + ((i * 13) % 38),
  status: i === 10 ? 'Breakdown' : i === 7 ? 'Under Maintenance' : i === 15 ? 'Idle' : 'In Use',
}));

export const masterEntities: EntityDef[] = [
  {
    id: 'project',
    label: 'Project',
    plural: 'Projects',
    app: 'project',
    codePrefix: 'PRJ',
    titleField: 'name',
    form: 'wizard',
    sections: [
      { id: 'basic', title: 'Project Details', icon: 'ti-building' },
      { id: 'setup', title: 'Schedule & Team', icon: 'ti-calendar' },
      { id: 'value', title: 'Commercials', icon: 'ti-currency-rupee' },
    ],
    fields: [
      text('code', 'Project Code', undefined, { required: true, section: 'basic', hint: 'Auto-generated series PRJ-###' }),
      text('name', 'Project Name', undefined, { required: true, section: 'basic' }),
      ref('client', 'Client', 'client', { required: true, section: 'basic' }),
      ref('site', 'Site', 'site', { section: 'basic' }),
      select('type', 'Project Type', ['Residential High-rise', 'Residential', 'Villas', 'Township', 'Commercial', 'IT Park', 'Institutional', 'Hospitality', 'Infrastructure'], { section: 'basic' }),
      date('start', 'Start Date', undefined, { required: true, section: 'setup' }),
      date('end', 'End Date', undefined, { required: true, section: 'setup' }),
      ref('manager', 'Project Manager', 'employee', { section: 'setup' }),
      pct('progress', 'Progress', undefined, { section: 'setup' }),
      ref('contract', 'Contract', 'contract', { section: 'value', list: false }),
      money('value', 'Contract Value', undefined, { section: 'value' }),
      money('budget', 'Approved Budget', undefined, { section: 'value', list: false }),
      money('cost', 'Cost Incurred', undefined, { section: 'value', list: false }),
      status(['Planned', 'On Track', 'At Risk', 'Delayed', 'On Hold', 'Completed', 'Cancelled'], { section: 'basic' }),
    ],
    rows: projectRows,
  },
  {
    id: 'client',
    label: 'Client',
    plural: 'Clients',
    app: 'crm',
    codePrefix: 'CL',
    titleField: 'name',
    form: 'page',
    sections: [
      { id: 'basic', title: 'Client Details', icon: 'ti-building-community' },
      { id: 'contact', title: 'Primary Contact', icon: 'ti-address-book' },
    ],
    fields: [
      text('name', 'Client Name', undefined, { required: true, section: 'basic' }),
      select('type', 'Client Type', ['Developer', 'Corporate', 'Government', 'Institution'], { section: 'basic' }),
      text('city', 'City', undefined, { section: 'basic' }),
      text('gstin', 'GSTIN', undefined, { section: 'basic' }),
      text('contact', 'Contact Person', undefined, { section: 'contact' }),
      f_phone('phone', 'Phone'),
      f_email('email', 'Email'),
      date('since', 'Client Since', undefined, { section: 'basic', list: false }),
      status(['Prospect', 'Active', 'Inactive'], { section: 'basic' }),
    ],
    rows: clientRows,
  },
  {
    id: 'site',
    label: 'Site',
    plural: 'Sites',
    app: 'site',
    codePrefix: 'SITE',
    titleField: 'name',
    fields: [
      text('name', 'Site Name', undefined, { required: true }),
      ref('project', 'Project', 'project', { required: true }),
      text('city', 'City'),
      text('state', 'State'),
      ref('manager', 'Site Manager', 'employee'),
      num('area', 'Area', undefined, { unit: 'acres' }),
      num('labour', 'Labour Strength'),
      status(['Mobilizing', 'Active', 'Demobilized']),
    ],
    rows: siteRows,
  },
  {
    id: 'employee',
    label: 'Employee',
    plural: 'Employees',
    app: 'workforce',
    codePrefix: 'EMP',
    titleField: 'name',
    form: 'wizard',
    import: true,
    sections: [
      { id: 'personal', title: 'Personal Information', icon: 'ti-user' },
      { id: 'employment', title: 'Employment Information', icon: 'ti-briefcase' },
    ],
    fields: [
      text('code', 'Employee ID', undefined, { section: 'employment' }),
      text('name', 'Employee Name', undefined, { required: true, section: 'personal' }),
      text('department', 'Department', undefined, { section: 'employment' }),
      text('designation', 'Designation', undefined, { section: 'employment' }),
      ref('site', 'Site', 'site', { section: 'employment' }),
      f_phone('phone', 'Phone', 'personal'),
      f_email('email', 'Email', 'personal'),
      date('joining', 'Date of Joining', undefined, { section: 'employment' }),
      select('type', 'Employment Type', ['Permanent', 'Contract', 'Trainee'], { section: 'employment', list: false }),
      text('attendance', 'Attendance (Month)', undefined, { section: 'employment' }),
      status(['Active', 'On Leave', 'Notice Period', 'Exited'], { section: 'employment' }),
    ],
    rows: employeeRows,
  },
  {
    id: 'vendor',
    label: 'Vendor',
    plural: 'Vendors',
    app: 'procurement',
    codePrefix: 'VEN',
    titleField: 'name',
    fields: [
      text('name', 'Vendor Name', undefined, { required: true }),
      text('category', 'Category'),
      text('city', 'City'),
      text('contact', 'Contact Person'),
      f_phone('phone', 'Phone'),
      text('gstin', 'GSTIN', undefined, { list: false }),
      num('rating', 'Rating', undefined, { hint: 'Out of 5' }),
      money('spend', 'YTD Spend'),
      status(['Approved', 'Under Review', 'Blacklisted', 'Inactive']),
    ],
    rows: vendorRows,
  },
  {
    id: 'subcontractor',
    label: 'Subcontractor',
    plural: 'Subcontractors',
    app: 'subcontract',
    codePrefix: 'SUB',
    titleField: 'name',
    fields: [
      text('name', 'Company Name', undefined, { required: true }),
      text('trade', 'Trade'),
      text('city', 'City'),
      text('contact', 'Contact Person'),
      num('experience', 'Experience', undefined, { unit: 'yrs' }),
      num('workforce', 'Workforce'),
      num('quality', 'Quality Score', undefined, { unit: '/100' }),
      num('safety', 'Safety Score', undefined, { unit: '/100' }),
      status(['Approved', 'Under Review', 'Blacklisted']),
    ],
    rows: subRows,
  },
  {
    id: 'item',
    label: 'Item',
    plural: 'Items',
    app: 'store',
    codePrefix: 'ITM',
    titleField: 'name',
    import: true,
    fields: [
      text('name', 'Item Name', undefined, { required: true }),
      text('category', 'Category'),
      text('unit', 'Unit'),
      money('rate', 'Standard Rate'),
      num('stock', 'Current Stock'),
      num('reserved', 'Reserved'),
      num('minimum', 'Minimum Stock', undefined, { list: false }),
      num('reorder', 'Reorder Level'),
      status(['In Stock', 'Reorder Level', 'Low Stock', 'Out of Stock']),
    ],
    rows: itemRows,
  },
  {
    id: 'equipment',
    label: 'Equipment',
    plural: 'Equipment',
    app: 'equipment',
    codePrefix: 'EQ',
    titleField: 'name',
    fields: [
      text('name', 'Equipment Name', undefined, { required: true }),
      select('category', 'Category', ['Machinery', 'Vehicles', 'Equipment']),
      select('ownership', 'Ownership', ['Owned', 'Rented', 'Leased']),
      text('model', 'Model'),
      text('serial', 'Serial Number'),
      text('capacity', 'Capacity'),
      ref('project', 'Allocated Project', 'project'),
      ref('operator', 'Operator', 'employee', { list: false }),
      num('hours', 'Operating Hours', undefined, { unit: 'hrs' }),
      pct('utilization', 'Utilization', undefined, { list: false }),
      status(['In Use', 'Idle', 'Under Maintenance', 'Breakdown', 'Returned']),
    ],
    rows: equipmentRows,
  },
];

function f_phone(key: string, label: string, section = 'contact') {
  return { key, label, type: 'phone' as const, section };
}
function f_email(key: string, label: string, section = 'contact') {
  return { key, label, type: 'email' as const, section, list: false };
}
